salesforce/lwc

packages/@lwc/synthetic-shadow/src/polyfills/document-shadow/polyfill.ts
Addresses https://github.com/salesforce/lwc/issues/1304
In the synthetic shadow we patch the `activeElement` on the document. this PR patch changes this behavior patching the `activeElement` in the `Document.prototype`
=> fix: issue #1304 activeElement should be patched in the prototype

CONTRIBUTING.md, package.json
Bump Node.js dependency to `>=10.13.0` (LTS Dubnium).
https://github.com/nodejs/node/blob/b1bd9e3dd210d6b20d94c50758e12e93d9dbb3db/doc/changelogs/CHANGELOG_V10.md#nodejs-10-changelog
=> chore: bump nodejs dependency to lts dubnium

package.json, packages/@lwc/engine/types/engine.d.ts, packages/@lwc/template-compiler/src/shared/scope.ts, yarn.lock
This solves some inconsistencies between vscode and build, specifically `ShadowRoot` as interface and global variable at the same time for PR #1322
=> fix(engine): update typescript to the latest

packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts
We can remove these `@ts-ignore` comments because we upgraded to 3.x a while ago.
=> chore: remove outdated @ts-ignore comments

package.json, packages/@lwc/style-compiler/package.json, yarn.lock
Fixes the high-severity security alert WS-2019-0063
chore: conventional-changelog-cli 1.3.5 => 2.0.21
chore: cssnano 3.10.0 => 4.1.10
chore: @commitlint/cli 6.2.0 => 8.0.0
chore: husky 1.3.1 => 2.4.0
chore: lint-staged 8.1.4 => 8.2.0
chore: jest 24.0.0 => 24.8.0
chore: eslint 5.13.0 => 5.16.0
=> chore: upgrade deps to eliminate bad js-yaml sub-dep

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-negative-after-inside-click/integration/tabindex-negative-after-inside-click/tabindex-negative-after-inside-click.html, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-negative/integration/tabindex-negative/tabindex-negative.html, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/integration/child/child.html, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/integration/child/child.js, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/integration/parent/parent.html, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/integration/parent/parent.js, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/integration/tabindex-zero-internal-tabindex-negative/tabindex-zero-internal-tabindex-negative.html, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/integration/tabindex-zero-internal-tabindex-negative/tabindex-zero-internal-tabindex-negative.js, packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/test-tabindex-zero-internal-tabindex-negative.spec.js
This release aims to reduce the breadth of changes shipping to core for v1.0.0 and isolate potential issues around adding shadow semantics to sequential focus navigation.
This PR introduces breaking changes for consumers of delegatesFocus (i.e., base components), which have been addressed.
=> chore: add shadow semantics to sequential focus navigation

packages/@lwc/engine/src/framework/restrictions.ts
It doesn't make sense to restrict attribute mutation methods because authors are responsible for reflecting content attributes when they override default descriptors for global html attributes.
This PR also removes some error logging done in `setAttribute` because those errors are meant for properties.
Fixes #1257 
=> chore: remove attribute mutation restrictions

packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/patch.ts, packages/integration-karma/test/misc/cross-domain-iframe/index.spec.js, packages/integration-karma/test/misc/cross-domain-iframe/x/test/test.html
Fixes issue #1366 by exposing the `addEventHandler()` and `removeEventHandler()` methods on the iframe `contentWindow` patch layer.
This change is pending the merge of PR #1322 .
=> fix(synthetic-shadow): expose iframe contentWindow event methods

packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/patch.ts, packages/integration-karma/test/misc/cross-domain-iframe/index.spec.js, packages/integration-karma/test/misc/cross-domain-iframe/x/test/test.html
Expose `addEventHandler()` and `removeEventHandler()` methods on the iframe `contentWindow` patch layer, plus tests.
=> fix(synthetic-shadow): expose iframe contentWindow event methods (#1368)

packages/@lwc/engine/src/framework/__tests__/watcher.spec.ts
* test was not returning the promise, so it was failing in the next tick
* test is not longer relevant after changing the tests to run native shadow (fixed to match that)
=> fix(engine): test was incorrect

package.json
Some developers have reported that they cannot install this repo in NodeJS v12.
After debugging a bit, many of our dependencies (karma, webdriver-io) still rely on old versions of primitive libraries such as fibers or node-gyp. 
We need to wait until those libraries upgrade for us to do the same.
In the mean time Im restricting the version in package.json
We should do the same in all repos.
=> chore: restrict node to TLS (v10)

packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/integration-karma/test/template/properties/attrs/specialCharacter/specialCharacter.html, packages/integration-karma/test/template/properties/attrs/specialCharacter/specialCharacter.js, packages/integration-karma/test/template/properties/attrs/underscoreChild/underscoreChild.html, packages/integration-karma/test/template/properties/attrs/underscoreChild/underscoreChild.js, packages/integration-karma/test/template/properties/index.spec.js
Fixes #1369 - prevent camel-casing of the attribute names with underscore.
Rules:
- attribute name must start with alphabetic character
- attribute name must end with alpha-numeric character
- attribute name cannot contain a combination of underscore and non-alpha-numeric characters
=> fix(compiler): prevent underscore attr name camelcasing

packages/@lwc/wire-service/src/__tests__/wiring.spec.ts, packages/@lwc/wire-service/src/index.ts, packages/@lwc/wire-service/src/link-context-event.ts, packages/@lwc/wire-service/src/value-changed-event.ts, packages/@lwc/wire-service/src/wiring.ts
In preparation for Context RFC: https://github.com/salesforce/lwc-rfcs/pull/6
Note: we are keeping the old behavior around until we can remove it, more details on https://github.com/salesforce/lwc/issues/1357
=> refactor(wire-service): introducing LinkContextEvent

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/def.ts, packages/integration-karma/test/rendering/inheritance/index.spec.js, packages/integration-karma/test/rendering/inheritance/x/bar/bar.js, packages/integration-karma/test/rendering/inheritance/x/base/base.html, packages/integration-karma/test/rendering/inheritance/x/base/base.js, packages/integration-karma/test/rendering/inheritance/x/foo/foo.html, packages/integration-karma/test/rendering/inheritance/x/foo/foo.js
* subclassing `LightningElement` while relying on the implicit nature of the template file definition is broken, if a subclass doesn't have a HTML file in the bundle, and the subclass is extending something other than the common `LightningElement`, the template used for the render is not the one from the super class, but the default empty template.
This was broken for a long time and no-one notices because this is a very edge case, you must have an extension of a class other than `LigthningElement`, where the subclass doesn't have a HTML file, to exhibit this issue. We should consider this change a very low risk. …
=> fix(engine): template inheritance is broken

packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/@lwc/babel-plugin-component/src/decorators/wire/validate.js, packages/@lwc/errors/src/compiler/error-info/lwc-class.ts
Allow MemberExpression on wire adapters
Allows the following syntax on wires
```js
export default class Test {
@wire(Foo.Bar, {}) wiredProp;
}
```
=> feat: allow MemberExpression on wire adapters

packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/@lwc/babel-plugin-component/src/decorators/wire/validate.js, packages/@lwc/errors/src/compiler/error-info/lwc-class.ts
* feat: allow memberExpression on wires
* fix: test name
* fix: test correcness
* Update lwc-class.ts
* Update wire-decorator.spec.js
cherrypicks 7ee68f0de172ce4bce04f472a737c29b82e4a3c7
Allow MemberExpression on wire adapters
Allows the following syntax on wires
```js
export default class Test {
@wire(Foo.Bar, {}) wiredProp;
}
```
=> feat: [cp] allow MemberExpression on wire adapters (#1402)

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/def.ts, packages/integration-karma/test/rendering/inheritance/index.spec.js, packages/integration-karma/test/rendering/inheritance/x/bar/bar.js, packages/integration-karma/test/rendering/inheritance/x/base/base.html, packages/integration-karma/test/rendering/inheritance/x/base/base.js, packages/integration-karma/test/rendering/inheritance/x/foo/foo.html, packages/integration-karma/test/rendering/inheritance/x/foo/foo.js
* fix(engine): template inheritance was broken
* test: update test to be sync
cherrypicks 83d988159bd5b7c221aa76ca47fc2e8f374885f5
* subclassing `LightningElement` while relying on the implicit nature of the template file definition is broken, if a subclass doesn't have a HTML file in the bundle, and the subclass is extending something other than the common `LightningElement`, the template used for the render is not the one from the super class, but the default empty template.
This was broken for a long time and no-one notices because this is a very edge case, you must have an extension of a class other than `LigthningElement`, where the subclass doesn't have a HTML file, to exhibit this issue. We should consider this change a very low risk.
=> fix(engine): [cp] template inheritance is broken (#1400)

packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/rendering/disconnecting-root-vm/index.spec.js, packages/integration-karma/test/rendering/disconnecting-root-vm/x/child/child.html, packages/integration-karma/test/rendering/disconnecting-root-vm/x/child/child.js, packages/integration-karma/test/rendering/disconnecting-root-vm/x/parent/parent.html, packages/integration-karma/test/rendering/disconnecting-root-vm/x/parent/parent.js
https://playground.lwcjs.org/projects/S_7PCquA7/3/edit
When you remove a rootVM with pending rehydration(s) which results in removing custom elements by the snabbdom, an error is shown in the console: `VM2206 engine.js:356 Uncaught (in promise) Error: Assert Violation: [object:vm undefined (3)] must be inserted.`
The issue is that when the rootVM is removed, all custom elements in that hierarchy are disconnected, and when a rehydration is scheduled for a vm in that subtree that will end up removing a vm, another call by the snabbdom to disconnect the vm is done, failing with an assertion by the engine.
You can see the issue in this playground repro: https://playground.lwcjs.org/projects/S_7PCquA7/3/edit
=> fix: error from disconnecting an already disconnected vm

packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/rendering/disconnecting-root-vm/index.spec.js, packages/integration-karma/test/rendering/disconnecting-root-vm/x/child/child.html, packages/integration-karma/test/rendering/disconnecting-root-vm/x/child/child.js, packages/integration-karma/test/rendering/disconnecting-root-vm/x/parent/parent.html, packages/integration-karma/test/rendering/disconnecting-root-vm/x/parent/parent.js
cherrypick d61988dddfa86dd03f1aba4cade630ace2a18e5d
When you remove a rootVM with pending rehydration(s) which results in removing custom elements by the snabbdom, an error is shown in the console: `VM2206 engine.js:356 Uncaught (in promise) Error: Assert Violation: [object:vm undefined (3)] must be inserted.`
The issue is that when the rootVM is removed, all custom elements in that hierarchy are disconnected, and when a rehydration is scheduled for a vm in that subtree that will end up removing a vm, another call by the snabbdom to disconnect the vm is done, failing with an assertion by the engine.
You can see the issue in this playground repro: https://playground.lwcjs.org/projects/S_7PCquA7/3/edit
=> fix: [cp] error from disconnecting an already disconnected vm (#1413)

packages/@lwc/synthetic-shadow/src/polyfills/mutation-observer/polyfill.ts, packages/integration-karma/test/shadow-dom/MutationObserver/MutationObserver.spec.js
Use a WeakMap to store all nodes watched by an observer. On disconnect(), clean up references to the observer on all the nodes.
Limitation: If MutationObservers are not disconnected, this could lead to memory leak of nodes.
=> fix: mutationobserver memory leak - use weakmap for bookkeeping

packages/@lwc/synthetic-shadow/src/polyfills/mutation-observer/polyfill.ts, packages/integration-karma/test/shadow-dom/MutationObserver/MutationObserver.spec.js
Use a WeakMap to store all nodes watched by an observer. On disconnect(), clean up references to the observer on all the nodes.
Limitation: If MutationObservers are not disconnected, this could lead to memory leak of nodes.
cherry-picking #1423 
=> fix: mutationobserver memory leak - use weakmap for bookkeeping (#1423)

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/integration-tests/src/components/accessibility/test-delegates-focus-non-focusable-click-target/delegates-focus-non-focusable-click-target.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-non-focusable-click-target/integration/delegates-focus-non-focusable-click-target/delegates-focus-non-focusable-click-target.html, packages/integration-tests/src/components/accessibility/test-delegates-focus-non-focusable-click-target/integration/delegates-focus-non-focusable-click-target/delegates-focus-non-focusable-click-target.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-non-focusable-click-target/integration/input/input.html, packages/integration-tests/src/components/accessibility/test-delegates-focus-non-focusable-click-target/integration/input/input.js
This change fixes a bug that surfaces when the user clicks on a non-focusable element which results in a focus change (i.e., clicking on a form element label causes the associated form element to receive focus). The main issue was that the sequential focus navigation logic was getting executed even though we tried to skip it, due to the ordering of DOM events depending on user action:
```
Click form element   | Click form element label
==================================================
mousedown            | mousedown
FOCUSIN              | mousedown-setTimeout
mousedown-setTimeout | mouseup
mouseup              | FOCUSIN
mouseup-setTimeout   | mouseup-setTimeout
```
Specific changes:
- The delegatesFocus polyfill currently handles mouse clicks by removing the `focusin` handler (which …
=> fix: account for clicks on form element labels when delegating focus

packages/@lwc/babel-plugin-component/src/post-process/transform.js, packages/@lwc/engine/src/__tests__/dom.spec.ts, packages/@lwc/engine/src/__tests__/events.spec.ts, packages/@lwc/engine/src/framework/__tests__/api.spec.ts, packages/@lwc/engine/src/framework/__tests__/diff.spec.ts, packages/@lwc/engine/src/framework/__tests__/error-boundary.spec.ts, packages/@lwc/engine/src/framework/__tests__/events.spec.ts, packages/@lwc/engine/src/framework/__tests__/html-element.spec.ts, packages/@lwc/engine/src/framework/__tests__/patch.spec.ts, packages/@lwc/engine/src/framework/__tests__/vm.spec.ts, packages/@lwc/engine/src/framework/__tests__/watcher.spec.ts, packages/@lwc/engine/src/framework/decorators/__tests__/wire.spec.ts, packages/@lwc/engine/src/framework/decorators/register.ts, packages/@lwc/engine/src/framework/def.ts
* old metadata was based on static class properties to define the decorators.
* new metadata is defined via registerDecorators() call.
* unit tests were still using the old metadata format
* engine had a forking logic in def.ts to accommodate for missing decorator meta, and fake the call to registerDecorators when in tests.
This PR consolidates all that to only support registerDecorators() as the mechanism to define the metadata.
=> fix(engine): #1295 - removing hack to support old metadata in tests

packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/src/framework/template.ts, packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/component/LightningElement.disconnectedCallback/index.spec.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/dualTemplate.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/templateA.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/templateB.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/explicitRender/explicitRender.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/explicitRender/explicitRender.js
Cleaning up the list of child custom elements right before invoking the template function will allow that function to populate new items into that list.
Fixed issue https://github.com/salesforce/lwc/issues/1435
=> fix(engine): issue 1435 disconnect bug when switching templates

packages/@lwc/synthetic-shadow/src/3rdparty/polymer/text-content.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/integration-karma/test/polyfills/text-content/index.spec.js, packages/integration-karma/test/polyfills/text-content/x/test/test.html, packages/integration-karma/test/polyfills/text-content/x/test/test.js
From https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent:
> textContent returns the concatenation of the textContent of every child node, excluding comments and processing instructions. This is an empty string if the node has no children
This pr fixes the current implementation to match the standard.
=> fix: issue with Node.textContent returning text in comment nodes

packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/integration-karma/test/api/getComponentDef/index.spec.js
=> feat: add wire config as function

packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js
from static imports passed to the config.
=> fix: add wire test to ensure we support named imports

packages/@lwc/features/README.md, packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js
The existing test for this was failing because the `@lwc/features` test suite was not running in CI.
Added an extra restriction for flag names to be all uppercase to reduce ambiguity of which bindings are flag names vs `enableFeature`/`disableFeature`/`runtimeFlags`.
=> fix(features): flag name must match name of imported binding

packages/@lwc/features/src/__tests__/flags.spec.ts, scripts/jest/base.config.js, scripts/jest/root.config.js
POC illustrating the babel configuration issues I've been encountering. I haven't figured out a way to disable the `@babel/transform-modules-commonjs` plugin for the `@lwc/features` unit tests due to how babel merges plugin configs.
=> chore: only support jest tests from repo root

packages/@lwc/rollup-plugin/src/__tests__/index.spec.js, packages/@lwc/rollup-plugin/src/index.js
By default `@lwc/rollup-plugin` try to find the modules in the same directory of the entry. Some times this is not enough and you need to specify the root directory of the lwc modules (rootDir option)
When the rootDir is present and is a relative path, it will not work, even if is correct relative to the `process.cwd()`
This pr normalize the rootDir option by doing a `path.resolve(rootDir)`
=> fix: rollup-plugin module resolve when rootDir is a relative path

packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js
Invoking `path.skip()` in the `IfStatement` visitor seems to somehow interfere with `@babel/preset-typescript`, resulting in typescript showing up inside some if-statements in the output file. Preventing nested feature flags was never a hard requirement so it should be fine to avoid these during code reviews.
Also includes a minor refactor to use `this` instead of `state` since they are apparently the same thing.
=> fix(features): remove nested feature flags limitation

packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/integration-karma/test/shadow-dom/Node-properties/Node.cloneNode.spec.js
cloneNode() by default performs a shallow clone
=> fix: cloneNode() default behavior should match spec

packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/src/framework/template.ts, packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/component/LightningElement.disconnectedCallback/index.spec.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/dualTemplate.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/templateA.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/templateB.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/explicitRender/explicitRender.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/explicitRender/explicitRender.js
[cherrypick b0c451291a533348e534fa96847692e7aa550426]
* fix(engine): issue 1435 disconnect bug when swtiching templates
* test: tests for #1435 (#1448)
* test: tests for #1435
* test: address feedback
* fix: short circuit the call to mark children as dirty
* fix: address pr feedback
#	packages/@lwc/engine/src/framework/component.ts
=> fix(engine): issue 1435 disconnect bug when switching templates (#1443)

packages/@lwc/engine/src/framework/__tests__/vm.spec.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/def.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/modules/context.ts, packages/@lwc/engine/src/framework/modules/props.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/shared/fields.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/shared/fields.ts, packages/@lwc/synthetic-shadow/src/shared/static-html-collection.ts, packages/@lwc/synthetic-shadow/src/shared/static-node-list.ts
=> refactor: hidden fields instead of internal fields (2)

package.json
fix:  Use a more restrictive specification for Node and Yarn versions.
BREAKING CHANGE:  Developers may encounter a build failure unless they upgrade their local Node and/or Yarn versions.
UI Platform Engineering Systems is building a CI which will be running the specified versions of Node and Yarn so to be consistent this project should use the same specification.  The "patch" versions of Node and/or Yarn can float up from this spec, but not the minor or major versions.
There are two kinds of possible breaking changes:
1.  Developers may have to upgrade their local versions of node and/or yarn. The current CI may need to have its versions upgraded.
2.  The upgraded versions may reveal flaws in the previously established build assumptions that
a.  get caught by the build itself
b.  don't …
=> build: Standardize node and yarn versions

packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/integration-karma/test/api/getComponentDef/index.spec.js
Reverts #1468 and #1455 in this release of 1.1.0, due to the fact that is not in use yet.
=> fix: revert wire config as function

packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/integration-karma/test/shadow-dom/Node-properties/Node.contains.spec.js
Fixes error `TypeError: Cannot read property '$$OwnerKey$$' of null` when calling `node.contains(null)`
=> fix: containsPatched when otherNode is null or undefined

packages/@lwc/engine/src/framework/observed-fields.ts, packages/integration-karma/test/component/observed-fields/index.spec.js, packages/integration-karma/test/component/observed-fields/x/fieldForCache/fieldForCache.html, packages/integration-karma/test/component/observed-fields/x/fieldForCache/fieldForCache.js, packages/integration-karma/test/component/observed-fields/x/fieldWithSideEffect/fieldWithSideEffect.html, packages/integration-karma/test/component/observed-fields/x/fieldWithSideEffect/fieldWithSideEffect.js
This restriction was added as part of the track reform, but introduces issues with existing code. The reason why this is fine now is because memoization of field values during rendering is a valid use-case, and our magic for non-decorated fields should not effect it. Rendering is not going to be affected by lifting this since it is still in dirty mode, which means those mutations will not produce a next-tick rehydration notice.
=> fix: remove side effects assertion in non-decorated fields

packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts
This PR, stop from filtering out elements inside a shadow from the results of `element.querySelector` and `element.querySelectorAll` when `element` is not inside a shadow.
=> fix: relax dom patching for querySelector(all) on elements

packages/@lwc/engine/src/framework/observed-fields.ts, packages/integration-karma/test/component/observed-fields/index.spec.js, packages/integration-karma/test/component/observed-fields/x/fieldForCache/fieldForCache.html, packages/integration-karma/test/component/observed-fields/x/fieldForCache/fieldForCache.js, packages/integration-karma/test/component/observed-fields/x/fieldWithSideEffect/fieldWithSideEffect.html, packages/integration-karma/test/component/observed-fields/x/fieldWithSideEffect/fieldWithSideEffect.js
Cherrypicks #1491 
* fix: remove side effects assertion in observed fields
* fix: assert is valid vm during setter
#	packages/@lwc/engine/src/framework/observed-fields.ts
=> fix: [cp] remove side effects assertion in non-decorated fields (#1491)

packages/@lwc/style-compiler/package.json, yarn.lock
This PR updates the `postcss-value-parser` package to include the `calc` parsing fix. This package change magor version because they dropped support for node `8`, which is not a problem in the case of LWC.
Changelogs: https://github.com/TrySound/postcss-value-parser/releases 
=> chore: upgrade postcss-value-parser

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/integration-karma/test/shadow-dom/Event-properties/Event.target.spec.js, packages/integration-karma/test/shadow-dom/Event-properties/x/childWithOutLwcDomManual/childWithOutLwcDomManual.html, packages/integration-karma/test/shadow-dom/Event-properties/x/childWithOutLwcDomManual/childWithOutLwcDomManual.js, packages/integration-karma/test/shadow-dom/Event-properties/x/parentWithDynamicChild/parentWithDynamicChild.html, packages/integration-karma/test/shadow-dom/Event-properties/x/parentWithDynamicChild/parentWithDynamicChild.js
When event's original target is from a non-keyed node, do not retarget event when accessed asynchronously
Backport of  https://github.com/salesforce/lwc/pull/1510
=> fix: escape hatch for async event target accessor

packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/README.md, packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/patch.ts
To preserve legacy behavior, manually inserted iframe elements by third party javascript frameworks will continue to be served unwrapped.
* Have tests for the proposed changes been added? 🚨
=> fix: wrap iframe contentWindow only for iframe elements that are keyed

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/shared/utils.ts, packages/integration-karma/test/shadow-dom/Event-properties/Event.target.spec.js
No retargeting if event's original target is from a manually injected node into a non-portal parentNode and if the currentTarget is one of the following
1. target is accessed async
2. currentTarget is document
3. currentTarget is document.body
=> fix: relax condition to retarget event

packages/@lwc/engine/package.json, packages/@lwc/features/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/wire-service/package.json
Our dist files already bundle up all our dependencies.
=> fix: remove npm dependencies on private packages

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/src/framework/decorators/__tests__/wire.spec.ts, packages/@lwc/engine/src/framework/decorators/api.ts, packages/@lwc/engine/src/framework/decorators/track.ts, packages/@lwc/engine/src/framework/decorators/wire.ts, packages/@lwc/engine/src/framework/membrane.ts, packages/@lwc/engine/src/framework/mutation-tracker.ts, packages/@lwc/engine/src/framework/observed-fields.ts, packages/@lwc/engine/src/framework/wiring.ts, packages/integration-karma/test/wire/property-trap/index.spec.js, packages/integration-karma/test/wire/wiring/index.spec.js, packages/integration-tests/scripts/build.js, packages/integration-tests/src/shared/templates.js, packages/integration-tests/src/shared/todo.js
1. We were previously skipping calls to `valueMutated` when the component was already dirty, and was fine because what reacts to it, will rerender the component. Now it may happen that the component is dirty but we still need to call `valueMutated` because the wire mechanism also relies in the mutation tracker to detect changes on adapters config.
2. `register(adapterId, factory)` happens after `registerDecorators` and we were storing an adapter definition without the actual adapter (that is added after when doing register). This PR saves the adapter reference in registerDecorators, and when installing the wire adapters on the component it will try to get the `adapter` from the `adapterId`
=> fix: reactivity of wire params

packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_ts_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/js_imports_ts/src/main.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/js_imports_ts/src/utils.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_imports_js/src/main.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_imports_js/src/utils.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/main.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/utils.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/x/app/app.html, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/x/app/app.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/x/foo/foo.css, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/x/foo/foo.html, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/x/foo/foo.ts, packages/@lwc/rollup-plugin/src/__tests__/index.spec.js, packages/@lwc/rollup-plugin/src/index.js
The rollup-plugin was failing to resolve relative imports if using Typescript.  It was always assuming a `.js` file extension.  This PR fixes that bug and adds a test to ensure TS relative imports work.
=> fix(rollup-plugin): plugin now correctly resolves relative ts imports

packages/integration-tests/src/components/wired/test-wired-method-suite/wired-method-suite.spec.js
Bumping up the timeout since this test is always timing out on IE11.
```
[internet explorer 11.103 Windows 10 #0-53] [PROD_COMPAT] Component with a wired method
[internet explorer 11.103 Windows 10 #0-53] [PROD_COMPAT]   ✓ should display data correctly
[internet explorer 11.103 Windows 10 #0-53] [PROD_COMPAT]   1) should update data correctly
[internet explorer 11.103 Windows 10 #0-53] [PROD_COMPAT]
[internet explorer 11.103 Windows 10 #0-53]
[internet explorer 11.103 Windows 10 #0-53] 1 passing (20s)
[internet explorer 11.103 Windows 10 #0-53] 1 failing
[internet explorer 11.103 Windows 10 #0-53]
[internet explorer 11.103 Windows 10 #0-53] 1) Component with a wired method should update data correctly:
[internet explorer 11.103 Windows 10 #0-53] Should update todo id
[internet explorer …
```
=> test(integration-test): increase timeout for wire-service test

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/polyfills/document-body-shadow/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/document-shadow/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/node-collection-util.ts
Writing our own utils to handle NodeList and HTMLCollection. This is to not conflict with some legacy third party libraries like prototype.js that patch Array.prototype and is incapable of handling NodeList and HTMLCollection.
=> fix: custom collection util to handle nodelist and htmlcollection

packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/src/framework/decorators/api.ts, packages/@lwc/engine/src/framework/decorators/track.ts, packages/@lwc/engine/src/framework/invoker.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/@lwc/engine/src/framework/template.ts, packages/@lwc/engine/src/framework/watcher.ts, packages/integration-karma/test/component/LightningElement.disconnectedCallback/issue-1506.spec.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/disconnectedCallbackSetsTrackedValue/disconnectedCallbackSetsTrackedValue.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/disconnectedCallbackSetsTrackedValue/disconnectedCallbackSetsTrackedValue.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate1506/dualTemplate1506.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate1506/simpleTemplate.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate1506/templateWithChild.html, packages/integration-karma/test/component/LightningElement.render/index.spec.js
1. User land code is protected from making dangerous mutation during rendering phase.
2. Rendering a component is two steps, first the render() is invoked and then the returned template is evaluated.
3. The userland code was being protected using one global flag called `isRendering`. 
4.  In between these two steps, the engine is executing its own routine and does not need to be protected from dangerous mutations.
This PR separated the flag into two. One for render invocation and another for template evaluation.
Addresses issue https://github.com/salesforce/lwc/issues/1506 …
=> fix(engine): refactor boundary protection for render phase

packages/@lwc/engine/src/framework/decorators/api.ts, packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js, packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/runtime.ts
This allows us to do extra validation that identifies attempts to set feature flags that aren't defined.
=> refactor(features): default export of flags as a single object

packages/@lwc/engine/src/framework/wc.ts
The jsdoc comment that demonstrates how to use `buildCustomElementConstructor` has an error in it, this PR fixes it.
=> docs(engine): fix jsdoc example of using buildCustomElementConstructor

packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js
This will help to 1) keep flag names consistent and 2) use flags directly in the if-statement test.
=> feat(features): add support for unary negation

packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/no-patch-utils.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/integration-karma/test/synthetic-shadow/element-api/element-api.spec.js
when using collections
This PR ensures that when Patch flag is disabled for Collections (`getElementsByTagName`, `getElementsByClassName` and `getElementsByTagNameNS`) LWC root elements return unfiltered results.
Ex:
```
lwc-root-element
#shadowRoot
lwc-cmp
#shadowRoot
button
```
Before:
```js
(lwc-root-element).getElementsByTagName('button') // returned an empty collection.
(lwc-cmp).getElementsByTagName('button') // returned an empty collection.
```
With this change:
```js
(lwc-root-element).getElementsByTagName('button') // returns a collection with the button.
(lwc-cmp).getElementsByTagName('button') // returns an empty collection.
```
=> fix(synthetic-shadow): do not patch lwc root elements

packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/no-patch-utils.ts, packages/integration-karma/test/shadow-dom/Element-properties/index.spec.js
manually inserted nodes in same shadow tree
This PR makes `querySelector`, `querySelectorAll`, `getElementsBy*` to include manually inserted elements in the same shadow of the query context.
=> fix(synthetic-shadow): querySelectors not returning

packages/@lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts
is not being used.
This PR fixes:
The (add/remove)EventListenerPatched listener from https://github.com/salesforce/lwc/blob/master/packages/%40lwc/synthetic-shadow/src/faux-shadow/event-target.ts#L28 . is not being used. This is due that the event-target polyfill is adding one patched `addEventListener` to the `Node.prototype`, and `faux-shadow/event-target.ts` is adding it to the `EventTarget`.
Node inherits from EventTarget, so whenever you ask for `addEventListener` the patch defined in Node.prototype always win.
This PR fixes it by always patching EventTarget when is available
=> fix(synthetic-shadow): addEventListener for custom elements

packages/@lwc/synthetic-shadow/src/env/node.ts, packages/integration-karma/test/synthetic-shadow/element-api/element-api.spec.js
In ie11 contains is in HTMLElement.prototype, instead of Node.prototype. This commit fixes it by taking the native contains HTMLElement.prototype; is fine since HTMLElement inherits from Node.
=> fix(synthetic-shadow): fixes contains in ie11

packages/@lwc/features/src/flags.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts
Inlining these feature flags allows us to use them as compile-time flags. Usage of these feature flags was also inverted in some places to make it easier to remove them when the time comes.
Example of flag removal after these changes:
https://github.com/salesforce/lwc/commit/8bb68e12869b91b49570d2f67dc859e6ff5b13fd
Example of flag removal before these changes:
https://github.com/salesforce/lwc/compare/8d64bfcf4da9f933dae647236fdf807d165b91ba...8bb68e1
=> refactor(synthetic-shadow): inline the global patch feature flags

packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts
Previously, `isNodeShadowed` was expensive because it traverses up trying to find an owner key. This issue surfaced when calling `node.parentNode` on a node without ownerKey, it would traverse all the way up to the document.
For most of our use cases, we only need to check the presence of an ownerKey in a node. Only the `doesEventNeedsPatch` logic requires to verify if those nodes that might or might not have owner keys are in a shadow.
- `parentNode` and `parentElement` justification:
Given that `parentNode` and `parentElement` are traversal apis that look up just one level, we can make the compromise and directly check for `ownerKey` presence, if it is present we need to return the patched parentNode.
Given a node, these are the relevant scenarios:
An element,
1. Is not part of any …
=> fix(synthetic-shadow): make isNodeShadowed to only check owner key

packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/integration-karma/test/api/getComponentDef/index.spec.js
This reverts commit 81a6e484a0808b9b171dd9df733df248d25f57ab.
Revert "feat: add wire config as function (#1455)"
This reverts commit 828aacafe5aca12a5234d6c4c120926932025bfb.
This PR reverts wire config as a function. It was intended to be used by https://github.com/salesforce/lwc/pull/1459 which is on hold. This commit reverted (reverted revert) needs to be included in #1459 
This feature was "incomplete" (and was fixed as part of #1459 ) in the sense that you can put an invalid wire configuration:
`@wire(getFoo, { key1: "$prop1." })` which is valid syntax (even if it does not work) with this changes, the compiled code will result in an invalid syntax. (more info: https://github.com/salesforce/lwc/pull/1459/files#diff-ec479efc56547421ec22328c8602f1b4R595 )
* ✅ `No, it does not introduce …
=> Revert "feat: add wire config as function (#1455)"

packages/@lwc/compiler/src/options.ts
Transformation currently throws when not supplied with a name or namespace, we want to lift this restriction when transforming relative imports which currently do not have a namespace.
=> fix(compiler): make name and namespace optional

packages/@lwc/synthetic-shadow/src/faux-shadow/portal.ts
elements marked as lwc:dom=manual.
It also adds a performance optimization by not listening to the whole subtree.
=> fix(synthetic-shadow): use native mutation observer for portal elements

packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts
Patching these APIs causes major issues for Jest because it uses them internally for things like `querySelector`.
=> test(engine): avoid patching select apis during testing

packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-base-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-base-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-embed-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-embed-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-link-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-meta-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-meta-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-object-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-object-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/invalid-svg/metadata.json, packages/@lwc/template-compiler/src/parser/constants.ts
Restrict what elements can be composed inside a <math> element
Backport of https://github.com/salesforce/lwc/pull/1620
* 🚨 `Yes, it does introduce breaking changes.` 
1. If customers are using a `<link>`, `<embed>`, `<base>`, `<object>`, `<meta>` elements inside a `<math>` tag, they will encounter a compilation warning.
2. If customers use a `<embed>` or `<object>` tag in a template, the compiler will warn.
=> fix(compiler): [spring20]restrict tags that can be inside a math tag

packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-embed-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-embed-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-object-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-object-tag/metadata.json, packages/@lwc/template-compiler/src/parser/constants.ts
Easing the restriction for usage of `<embed>` and `<object>` tag in a template. It will only be prevented inside of a `<math>` tag.
=> fix: ease restriction for using object and embed in template

packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-base-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-base-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-embed-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-embed-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-link-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-meta-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-meta-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-object-tag/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/forbidden-object-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/invalid-svg/metadata.json, packages/@lwc/template-compiler/src/parser/constants.ts
Restrict what elements can be composed inside a <math> element
* 🚨 `Yes, it does introduce breaking changes.` 
If customers are using a `<link>`, `<embed>`, `<base>`, `<object>`, `<meta>` elements inside a `<math>` tag, they will encounter a compilation warning.
=> fix: restrict tags that can be inside a math tag

package.json, scripts/jest/base.config.js, yarn.lock
`jest-environment-jsdom-fifteen` is no longer needed because the latest `jest` is using `jsdom@^15.1.1`.
=> test: add resolution for jsdom@^15.2.1

packages/@lwc/synthetic-shadow/src/polyfills/HTMLSlotElement/polyfill.ts
* In aura unit tests we have some weird behavior when iframes are reloaded while all the new descriptors (expandos) added to document are set to undefined. This PR avoid doing anything on document in favor of patching the original descriptor in Document.prototype.
=> fix(synthetic-shadow): qunit has issues when document object is patched

.circleci/config.yml, CONTRIBUTING.md, package.json
One of the main issue new contributors faces when they want to pull and build the repository is that they need to have a specific version of `node` and `yarn`. Since most of the developers don't have a version manager installed it hurts external developers contribute to this repository.
* Upgrade node version to latest LTS version for the CI.
* Remove `yarn` version enforcement in `package.json`.
* Make `node` version enforcement less strict.
* Add a mention about `volta` in the `CONTRIBUTING.md`
Fixes #1593
* Have tests for the proposed changes been added? 🤷‍♂
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly …
=> build: make build requirements more friendly to new contributors

packages/@lwc/compiler/src/rollup-plugins/compat.ts, packages/@lwc/compiler/src/rollup-plugins/minify.ts, packages/@lwc/style-compiler/src/transform.ts
inline imports of cssnano and babel-compat libraries until they are required for 'compat' or 'prod' compilation.
=> feat: inline import of the compat and prod libraries

packages/@lwc/babel-plugin-component/src/__tests__/api-decorator.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/post-process/transform.js, packages/integration-karma/test/component/observed-fields/index.spec.js, packages/integration-karma/test/component/observed-fields/x/simple/simple.html, packages/integration-karma/test/component/observed-fields/x/simple/simple.js
This pr fixes: when having a decorated property named as a reserved word (ex: static) the engine will throw an error at runtime (Cannot redefine property: static)
```js
import { LightningElement, api } from 'lwc';
export default class Foo extends LightningElement {
@api static;
}
```
The problem is that the compiler is adding the decorated field `static` to both `publicProps` (correct) and `fields` (incorrect).
```js
lwc.registerDecorators(Foo, {
publicProps: {
"static": {
config: 0
}
},
fields: ["static"]
});
```
=> fix(compiler): decorated props duplicated in fields

package.json, scripts/jest/base.config.js, yarn.lock
This PR replaces the current hack to have the latest version of jsdom running into jest. Instead of hard-coding the version using yarn `resolve` machnism, this PR replaces the jest jsdom environment with a custom jest environment based on the latest version of jsdom. 
=> test: use custom jest environment instead using yarn override

packages/integration-karma/test/shadow-dom/event-in-shadow-tree/event-post-dispatch.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/event-propagation.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/event-scope.spec.js
Details
This PR enables tests that have been disabled becasue synthetic-shadow didn't used to patch `Event` not originating from an LWC component.
Fixes #1141.
=> test(synthetic-shadow): enable karma test related to #1141

packages/@lwc/engine/src/framework/def.ts
- Groups the imports in `def.ts` at the top of the module 
=> refactor(engine): fix def.ts import order

packages/@lwc/engine/src/framework/__tests__/vm.spec.ts, packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/base-bridge-element.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/src/framework/decorators/api.ts, packages/@lwc/engine/src/framework/decorators/track.ts, packages/@lwc/engine/src/framework/def.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/invoker.ts, packages/@lwc/engine/src/framework/modules/context.ts, packages/@lwc/engine/src/framework/modules/props.ts, packages/@lwc/engine/src/framework/observed-fields.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/@lwc/engine/src/framework/services.ts, packages/@lwc/engine/src/framework/stylesheet.ts, packages/@lwc/engine/src/framework/template.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/utils.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/@lwc/shared/src/fields.ts, yarn.lock
This PR refactors the View Model access and assertions in the engine:
- uniformize access to the VM in the engine: 
- make `ViewModelReflection` internal to `vm.ts`
- replace all the VM accessors with the following APIs: `associateVM`, `getAssociatedVM` and `getAssociatedVMIfPresent`
- remove all the inline VM assertions, all the assertions are now done directly in `getAssociatedVM`.
- improve `fields.ts` typing to make it more Typescript ideomatic.
- forced upgraded to `@babel/core` (directly in the `yarn.lock`) to enable support for typescript assertion functions support in jest. …
=> refactor(engine): VM access and assertions in the engine

packages/@lwc/babel-plugin-component/src/__tests__/api-decorator.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/post-process/transform.js, packages/integration-karma/test/component/observed-fields/index.spec.js, packages/integration-karma/test/component/observed-fields/x/simple/simple.html, packages/integration-karma/test/component/observed-fields/x/simple/simple.js
cherrypicks 90269c6182dfaedc4d3d34a19dc2aa7e0b42c55b (#1641)
When having a decorated property named as a reserved word (ex: static) the engine will throw an error at runtime (Cannot redefine property: static)
* fix(compiler): dont observe mutation in fields defined with bracket notation
* fix(compiler): dont observe mutations in static fields
=> fix(compiler): decorated props duplicated in fields (#1641)

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/integration-karma/test/component/LightningElement.dispatchEvent/index.spec.js
In the process of implementing SSR (#910), to start decoupling the engine from the DOM. This PR remove the `instanceof Event` check in `LigthningElement.prototype.dispatchEvent`. The same check is run by the browser when invoking the `EventTarget.prototype.dispatchEvent` method.
=> refactor(engine): remove Event instanceof check on dispatchEvent

packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/shared/src/fields.ts, packages/@lwc/shared/src/index.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/shared/static-html-collection.ts, packages/@lwc/synthetic-shadow/src/shared/static-node-list.ts
This PR makes the shared field method tree-shakeable by exporting directly the methods out of the `@lwc/shared`. This PR also makes the field methods type-safe.
```js
import { createHiddenField, setHiddenField, getHiddenField } from '@lwc/shared';
const stringField = createHiddenField<string>('string', 'namespace');
setHiddenField({}, stringField, null);
// ^ Argument of type 'null' is not assignable to parameter of type 'string'.
getHiddenField({}, stringField).toLowerCase()
// ^ Object is possibly 'undefined'.
```
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to …
=> refactor(shared): Make fields tree-shakeable

packages/integration-tests/scripts/wdio.conf.js, packages/integration-tests/scripts/wdio.local.conf.js, packages/integration-tests/scripts/wdio.sauce.conf.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-shadow-input-negative-tab-index/delegates-focus-click-shadow-input-negative-tab-index.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-false-negative-tab-index/delegates-focus-false-negative-tab-index.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-negative-tabindex-focusin-handler/delegates-focus-negative-tabindex-focusin-handler.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-tab-index-zero-no-focusable-elements-no-after-elements/delegates-focus-tab-index-zero-no-focusable-elements-no-after-elements.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-tab-index-zero-no-focusable-elements/delegates-focus-tab-index-zero-no-focusable-elements.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-tab-index-zero/delegates-focus-tab-index-zero.spec.js, packages/integration-tests/src/components/wired/test-wired-method-suite/wired-method-suite.spec.js, packages/integration-tests/src/components/wired/test-wired-prop-suite/wired-prop-suite.spec.js
This PR increases all the integration tests' timeouts to increase CI stability. This PR also removes all the hardcoded `waitFor*` timeouts to use instead the globally defined `waitforTimeout`.
**GUS work item:**  W-7093447
=> test(integration-test): Increase integration test timeout

packages/@lwc/wire-service/src/__tests__/wiring.spec.ts, packages/@lwc/wire-service/src/wiring.ts
Accept `wirecontextevent` to avoid [engine warnings about event names](https://github.com/salesforce/lwc/blob/master/packages/@lwc/engine/src/framework/restrictions.ts#L420-L427). 
`WireContextEvent` can be removed after all consumers are updated to `wirecontextevent`.
=> fix(wire): add lowercase wirecontextevent

packages/@lwc/babel-plugin-component/src/__tests__/component.spec.js, packages/@lwc/babel-plugin-component/src/component.js, packages/@lwc/babel-plugin-component/src/constants.js, packages/@lwc/engine/scripts/jest/legacy-test-exceptions.js, packages/@lwc/engine/scripts/jest/setup-test.js, packages/@lwc/engine/scripts/rollup/rollup.config.js, packages/@lwc/engine/src/framework/modules/props.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/@lwc/features/src/runtime.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/constants.ts, packages/@lwc/template-compiler/src/parser/index.ts, scripts/tasks/check-license-headers.js
Implements the WHATWG style guide for documentation:
Don't use "white" as meaning good and "black" as meaning bad; more concretely, "safelist" and "blocklist" are established precedent.
=> chore: remove usage of white/black as good/bad

packages/@lwc/features/src/__tests__/flags-prod.spec.ts, packages/@lwc/features/src/babel-plugin/index.js
- Fixes a bug where unary negation of a null feature flag was being interpreted as a boolean false flag
- Refactors the @lwc/features transform to make it clear what happens in prod/non-prod modes
- Refactors related tests for better readability
=> fix(features): unary negation of null flag interpreted as boolean false

packages/@lwc/synthetic-shadow/src/polyfills/custom-event-composed/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-composed/detect.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-composed/polyfill.ts, packages/integration-karma/test/polyfills/event-composed/index.spec.js
This PR adds support for `composed` to the `Event` constructor.
Fixes #938.
W-5983676
=> fix(synthetic-shadow): make Event constructor handle composed

packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js
Additional validation to ensure runtime flags can only be imported by compiler
W-7094575
=> feat(features): runtime flags can only be imported by compiler

package.json
With the [v10.0 release](https://github.com/okonet/lint-staged/releases/tag/v10.0.0), `lint-staged` automatically add to the staging area all the modification made to the staged files. We can remove the `git add` step to get rid of the warning message.
W-7109631
=> chore: remove git add from lint-staged

packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js
This transform is actually applied on [runtime.ts](https://github.com/salesforce/lwc/blob/master/packages/@lwc/features/src/runtime.ts) because it gets bundled with `engine` and `synthetic-shadow` and it was throwing due to an if-test against `runtimeFlags[name]` which was part of the process of setting flags during runtime.
This validation prevents evaluation of computed expressions.
W-7094575
=> feat(features): computed feature flags are not supported

packages/@lwc/engine/src/env/dom.ts, packages/@lwc/engine/src/env/node.ts, packages/@lwc/engine/src/framework/invoker.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/shared/format.ts
This PR changes the way error boundaries get resolved by internally LWC. Currently, the engine climbs the DOM tree (using `Node.prototype.parentNode` and `ShadowRoot.prototype.host`) to find a component boundary which creates a tight coupling between the DOM and the engine. With this PR, error boundaries will be resolved by climbing the `owner` property attached to the `VM`.
This PR changes the current error boundary lookup behavior. When climbing the component using `vm.owner` the error propagation would stop at the component tree root. In the current implementation, the error would stop at the document root. This means that even if 2 component trees are disconnected and if one is nested into another the outer component tree would be able to …
=> refactor(engine): lookup error boundaries using vm.owner

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/synthetic-shadow/src/3rdparty/polymer/path-composer.ts, packages/@lwc/synthetic-shadow/src/env/element.ts, packages/@lwc/synthetic-shadow/src/env/slot.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/index.ts, packages/integration-karma/test/native-shadow/Event-properties/Event.target.spec.js, packages/integration-karma/test/native-shadow/Event-properties/x/NativeChild/NativeChild.js, packages/integration-karma/test/native-shadow/Event-properties/x/NativeParent/NativeParent.js, packages/integration-karma/test/native-shadow/Event-properties/x/lwcParent/lwcParent.html, packages/integration-karma/test/native-shadow/Event-properties/x/lwcParent/lwcParent.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedElements.spec.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedNodes.spec.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/x/NativeBasic/NativeBasic.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/x/lwcParent/lwcParent.html, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/x/lwcParent/lwcParent.js
Following APIs will be updated as described:
* Element.prototype.attachShadow patch will preserve native behavior by default. When invoked with a specific flag it will return a SyntheticShadowRoot
* Element.prototype.shadowRoot will return the SyntheticShadowRoot if the element is a lwc host, return a native ShadowRoot if the element is a native custom element and null in other cases.
* Event.prototype.target will retain its native behavior if the original target is a from a native shadow tree
Work to be done:
* When an event is fired in a DOM tree which has mixed shadow mode(native/synthetic-shadow), should Event.prototype.composePath() show account for both native and synthetic shadow or should it be biased towards the current target?
* HTMLSlotElement.prototype.assignedNodes should be …
=> feat(synthetic-shadow): preserve native behavior of attachShadow

packages/@lwc/features/src/global-this.ts, packages/@lwc/features/src/runtime.ts
Packages like `@lwc/synthetic-shadow` produce build targets that don't export any bindings so it is impossible to set feature flag values for them today. This PR proposes a way for apps to set those flags through other packages that do export `setFeatureFlag`.
- No first class multi-engine support. This approach would require engine-specific flags to uniquely configure multiple engines existing in the same runtime.
- Susceptible to poisoning if `globalThis.lwcRuntimeFlags` is defined before `@lwc/features` has a chance to do so.
- Food for thought from @caridy: Do we need to protect the storage? Is that something that should be taken care of by Locker?
W-7094575
=> refactor(features): feature flag support for synthetic-shadow

packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/component/LightningElement.errorCallback/index.spec.js, packages/integration-karma/test/component/LightningElement.errorCallback/x/errorBoundary/errorBoundary.html, packages/integration-karma/test/component/LightningElement.errorCallback/x/errorBoundary/errorBoundary.js, packages/integration-karma/test/component/LightningElement.errorCallback/x/nestedBoundaryChildThrow/nestedBoundaryChildThrow.html, packages/integration-karma/test/component/LightningElement.errorCallback/x/nestedBoundaryChildThrow/nestedBoundaryChildThrow.js, packages/integration-karma/test/component/LightningElement.errorCallback/x/nestedChildThrow/nestedChildThrow.html, packages/integration-karma/test/component/LightningElement.errorCallback/x/nestedChildThrow/nestedChildThrow.js, packages/integration-karma/test/component/LightningElement.errorCallback/x/nestedGrandChildThrow/nestedGrandChildThrow.html, packages/integration-karma/test/component/LightningElement.errorCallback/x/nestedGrandChildThrow/nestedGrandChildThrow.js
This PR fixes the infinite loop that happens in `getErrorBoundaryVM` when a deeply nested component errors out.
=> fix(engine): infinite loop in getErrorBoundaryVM

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/synthetic-shadow/src/env/element.ts, packages/@lwc/synthetic-shadow/src/env/slot.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/index.ts, packages/integration-karma/test/native-shadow/Event-properties/Event.target.spec.js, packages/integration-karma/test/native-shadow/Event-properties/x/NativeChild/NativeChild.js, packages/integration-karma/test/native-shadow/Event-properties/x/NativeParent/NativeParent.js, packages/integration-karma/test/native-shadow/Event-properties/x/lwcParent/lwcParent.html, packages/integration-karma/test/native-shadow/Event-properties/x/lwcParent/lwcParent.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedElements.spec.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedNodes.spec.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/x/NativeBasic/NativeBasic.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/x/lwcParent/lwcParent.html, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/x/lwcParent/lwcParent.js
_Porting https://github.com/salesforce/lwc/pull/1693 to master_
Following APIs will be updated as described:
* Element.prototype.attachShadow patch will preserve native behavior by default. When invoked with a specific flag it will return a SyntheticShadowRoot
* Element.prototype.shadowRoot will return the SyntheticShadowRoot if the element is a lwc host, return a native ShadowRoot if the element is a native custom element and null in other cases.
* Event.prototype.target will retain its native behavior if the original target is a from a native shadow tree
* HTMLSlotElement.prototype.assignedNodes & assignedElements will check if the current context is a synthetic shadowed node, if the test is negative, native behavior will be preserved
Work to be done:
* When an event is fired in a DOM …
=> feat(synthetic-shadow): preserve native behavior of attachShadow (#1693)

packages/@lwc/wire-service/src/wiring.ts
Followup to #1679  to remove legacy `WireContextEvent`. Use `wirecontextevent` instead.
Single consumer of `WireContextEvent` has been updated to use `wirecontextevent` so no impact expected.
=> fix(wire): remove WireContextEvent (camelcase)

packages/@lwc/synthetic-shadow/src/faux-shadow/html-element.ts
The focus method supports an options object so we need to pass arguments through.
W-7109631
=> fix(synthetic-shadow): pass arguments through to original focus() method

scripts/release_npm.sh
The version footer in the dist file had the previous release number instead of the current version being released. Setting the version and executing build ensures the footer has the right information.
Fixes https://github.com/salesforce/lwc/issues/1727
W-7109631
=> chore: update release script to reflect correct footer in dist files

yarn.lock
package.json uses `beta5` but yarn.lock specifies `beta4`
=> build: resolve @best version discrepancy in yarn.lock

packages/@lwc/engine/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine/src/framework/__tests__/api.spec.ts, packages/@lwc/engine/src/framework/api.ts
This PR removes the `p` render API and related code since the compiler doesn't produce VNodes for comment. This render API might be added back once we settle on a solution (#927) to add support for comment nodes.
W-7109631
=> refactor(engine): Remove unused comment api

packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/restrictions.ts
The `$fromTemplate$` marker is an old artifact that hasn't been removed with the ab20a06 attribute restriction relaxation.
W-7109631
=> refactor(engine): remove unused $fromTemplate$ marker

packages/@lwc/engine/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/attributes.ts, packages/@lwc/engine/src/framework/base-bridge-element.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/decorators/api.ts, packages/@lwc/engine/src/framework/decorators/register.ts, packages/@lwc/engine/src/framework/decorators/track.ts, packages/@lwc/engine/src/framework/def.ts, packages/@lwc/engine/src/framework/modules/props.ts, packages/@lwc/engine/src/framework/modules/static-style-attr.ts, packages/@lwc/engine/src/framework/observed-fields.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/@lwc/engine/src/framework/stylesheet.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/@lwc/engine/tsconfig.json
Enable strict typescript check for the `@lwc/engine` package. Removed the following tsconfig overrides: `noImplicitAny`, `strictFunctionTypes` and `strictPropertyInitialization`
W-7109631
=> refactor(engine): Enforce strict typescript check 

packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/parser/html.ts, packages/@lwc/template-compiler/src/parser/utils/html-element-attributes.ts, packages/@lwc/template-compiler/src/shared/ir.ts, packages/@lwc/template-compiler/src/shared/naming.ts, packages/@lwc/template-compiler/src/shared/stack.ts, packages/@lwc/template-compiler/tsconfig.json
Enable strict typescript check for the `@lwc/template-compiler` package. Removed the following tsconfig overrides: `noImplicitAny`, `strictFunctionTypes` and `strictPropertyInitialization`
W-7109631
=> refactor(template-compiler): Enforce strict typescript check

packages/@lwc/wire-service/src/index.ts, packages/@lwc/wire-service/src/property-trap.ts, packages/@lwc/wire-service/src/wiring.ts, packages/@lwc/wire-service/tsconfig.json
Enable strict typescript check for the `@lwc/wire-service` package. Removed the following tsconfig overrides: `noImplicitAny`
W-7109631
=> refactor(wire-service): Enforce strict typescript check

.eslintrc, package.json, packages/@lwc/babel-plugin-component/src/__tests__/utils/test-transform.js, packages/@lwc/compiler/src/transformers/__tests__/transform.spec.ts, packages/@lwc/engine/src/framework/__tests__/api.spec.ts, packages/@lwc/engine/src/framework/__tests__/error-boundary.spec.ts, packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/integration-karma/test/api/createElement/index.spec.js, packages/integration-karma/test/component/LightningElement.classList/index.spec.js, packages/integration-karma/test/component/LightningElement.shadowRoot/index.spec.js, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/HTMLSlotElement.slotchange.spec.js, packages/integration-karma/test/template/directive-for-each/arrayMutation.spec.js, yarn.lock
To prevent focussed tests in the future to [sneak](https://github.com/salesforce/lwc/pull/1602#discussion_r390950818) into the codebase and to avoid other tests gotchas, this PR introduces the following jest rules:
- [`jest/no-focused-tests`](https://github.com/jest-community/eslint-plugin-jest/blob/HEAD/docs/rules/no-focused-tests.md)
- [`jest/valid-expect`](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/valid-expect.md)
- [`jest/valid-expect-in-promise`](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/valid-expect-in-promise.md)
**Misc. changes:**
- Removed eslint rules from the `.eslintrc` that were never enabled. We can add them back later if we feel the need for it.
- Remove last reference to TSLint in the repo :tada: 
* ✅ `No, …
=> build: Add linting for Jest and Jasmine

packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/def.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/utils.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/@lwc/engine/src/shared/circular-module-dependencies.ts
This PR decouples the `createElement` method from the engine internals in preparation from the server-side rendering code split. 
=> refactor(engine): Decouple createElement from engine internals

packages/@lwc/engine/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/integration-karma/test/template/directive-if/index.spec.js, packages/integration-karma/test/template/directive-if/x/multipleSlot/multipleSlot.html, packages/integration-karma/test/template/directive-if/x/multipleSlot/multipleSlot.js, packages/integration-karma/test/template/directive-if/x/multipleSlotLevel1/multipleSlotLevel1.html, packages/integration-karma/test/template/directive-if/x/multipleSlotLevel1/multipleSlotLevel1.js, packages/integration-karma/test/template/directive-if/x/multipleSlotLevel2/multipleSlotLevel2.html, packages/integration-karma/test/template/directive-if/x/multipleSlotLevel2/multipleSlotLevel2.js
after being toggled 2 times.
When passing slotted content to a custom element which is also slotted and wrapped in a `if:true={foo}` directive and toggle the if multiple times, the passed slot content stops being visible after the second toggle. You can see a repro here: https://developer.salesforce.com/docs/component-library/tools/playground/mFcLmzSYw/37/edit
The main issue is that the `vnode` for the slotted custom element is being reused, and during slot allocation the first time, `vnode.children` is being emptied. 
=> fix: slotted content of slotted custom element within if not visible

packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/integration-karma/test/shadow-dom/Node-properties/Node.contains.spec.js
- fixes #1791
Per the [spec](https://dom.spec.whatwg.org/#dom-node-contains) for Node.prototype.contains(otherNode), the return value should be true if otherNode is an inclusive descendant.
- Normalize the behavior of `contains()` for a disconnected DOM element across all browsers.
In IE11, for a disconnected DOM element which has never had child nodes, calling contains() on self will return false. For all other browsers, contains() returns true. This PR normalizes the behavior to return true across all browsers.
https://jsbin.com/cikubej/edit?html,js,console
```js
const div = document.createElement('div');
div.contains(div); // should return true
```
* Have …
=> fix(synthetic-shadow): node.contains should return true for self

package.json, packages/integration-karma/package.json, yarn.lock
https://github.com/advisories/GHSA-vh95-rmgr-6w4m
We can remove the yarn resolution for `minimist` when `karma` releases their next version which replaces the deprecated `optimist` package for `yargs` (https://github.com/karma-runner/karma/pull/3451).
Uninstalled and reinstalled the following packages to update the lock file to pull in `minimist@1.2.5`:
- @commitlint/cli
- eslint
- lerna
- cssnano-preset-default
- istanbul-api
- karma
- karma-coverage
- @wdio/mocha-framework
- @wdio/selenium-standalone-service
- @best/cli
- @best/runner-headless
- @best/runner-remote
W-7391508
=> build: address security advisory CVE-2020-7598

packages/integration-karma/test/component/LightningElement.dispatchEvent/index.spec.js
Test started failing after FF updated their error message in v45.0. Updated the test to just verify that a TypeError is thrown.
W-7391508
=> test: update test for dispatchEvent type error

packages/integration-karma/test/component/LightningElement.dispatchEvent/index.spec.js, packages/integration-karma/test/polyfills/aria-properties/index.spec.js
* Disabling ariaSelected check because Chrome currently reflect the property to the aria-sort attribute: https://bugs.chromium.org/p/chromium/issues/detail?id=914469
W-7391508
=> test: Fix failures due to Chrome 81 and Firefox 75 releases

packages/@lwc/synthetic-shadow/README.md
If you use a mutation observer, disconnect it to prevent a memory leak. 
* Have tests for the proposed changes been added? N/A
W-7138094
=> docs: add mutationobserver guidance

packages/@lwc/engine/src/framework/hooks.ts, packages/integration-karma/test/component/auraIntegration/AuraIntegration.spec.js, packages/integration-karma/test/component/auraIntegration/x/childMarkedAsCircular/childMarkedAsCircular.html, packages/integration-karma/test/component/auraIntegration/x/childMarkedAsCircular/childMarkedAsCircular.js, packages/integration-karma/test/component/auraIntegration/x/parent/parent.html, packages/integration-karma/test/component/auraIntegration/x/parent/parent.js, packages/integration-karma/test/component/lockerIntegration/x/child/child.html, packages/integration-karma/test/component/lockerIntegration/x/child/child.js, packages/integration-karma/test/component/lockerIntegration/x/lockerIntegration/lockerIntegration.html
For a component class that has been marked to have a circular reference, the engine resolves the constructor and caches it as part of the component def. During creation of elements found in a template, currently the unresolved constructor is being used. This PR uses the resolved constructor from the component definition.
This is a follow up to https://github.com/salesforce/lwc/pull/1751
W-7391508
=> fix: use resolved constructor during creating of template elements

packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts
This PR attempts to optimize the `createVM` method by removing the need to look up the component definition for each invocation. It appears that all the invokers of `createVM` already have an handle the component definition under construction. By passing the definition each of the constructors to this method it avoids an extra lookup to the def registry.
This PR also forces the `isRoot` property to be present in the config to force monomorphism at runtime. 
W-7391508
=> perf(engine): avoid multiple getComponentInternalDef lookups

packages/@lwc/engine/src/framework/decorators/wire.ts, packages/integration-karma/test/wire/wiring/index.spec.js, packages/integration-karma/test/wire/wiring/x/broadcastConsumer/broadcastConsumer.js
This PR fixes an issue in which when a wired field is modified from the component code, it does not triggers rehydration on the component.
Example
```html
<template>{wiredField}</template>
```
```js
import { LightningElement, wire, api } from 'lwc';
import { Foo } from 'bar/baz';
export default class Example extends LightningElement {
@wire(Foo) wiredField;
@api
forceRerender() {
this.wiredField = Math.random();
}
}
```
=> fix(wire-service): wired field dont triggers rehydration

packages/@lwc/engine/src/framework/def.ts, packages/integration-karma/test/component/auraIntegration/x/childMarkedAsCircular/childMarkedAsCircular.html, packages/integration-karma/test/component/auraIntegration/x/childMarkedAsCircular/childMarkedAsCircular.js, packages/integration-karma/test/component/auraIntegration/x/parent/parent.html, packages/integration-karma/test/component/lockerIntegration/x/child/child.html, packages/integration-karma/test/component/lockerIntegration/x/child/child.js
For component constructor with a circular dependency, the definition gathered is being cached with the resolved constructor as the key.
This becomes an issue when the unresolved constructor is reused the second time. The component def is recalculated unnecessarily.
Follow up to #1751 
=> fix: cache definition for constructor with circular dependency

packages/@lwc/module-resolver/README.md
Fixing module name typo in README, the module resolver accepts a module name not the associated module tag name.
=> doc(module-resolver): Fix typo in README

packages/@lwc/module-resolver/package.json, packages/@lwc/module-resolver/src/__tests__/resolve.modules.spec.ts, packages/@lwc/module-resolver/src/index.ts, packages/@lwc/module-resolver/src/shared.ts, packages/@lwc/module-resolver/src/utils.ts
With the new module-resolver, configuration passed to module-resolver and @lwc/rollup-plugin are expected to have ModuleRecords of object type. Prior configs where the ModuleRecord was a string would through an unhandled exception.
This PR checks the type of ModuleRecord and throws an error if its invalid.
W-7391508
=> fix(module-resolver): validate ModuleRecord data type

packages/@lwc/engine/src/framework/base-lightning-element.ts
Use typescript utility methods to reuse existing types.
These changes came about from the discussion in https://github.com/salesforce/lwc/pull/1847
W-7391508
=> refactor(engine): reuse existing types

packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/component/LightningElement/index.spec.js, packages/integration-karma/test/component/LightningElement/x/childThrowingBeforeSuper/childThrowingBeforeSuper.js, packages/integration-karma/test/component/LightningElement/x/parentThrowingBeforeSuper/parentThrowingBeforeSuper.html, packages/integration-karma/test/component/LightningElement/x/parentThrowingBeforeSuper/parentThrowingBeforeSuper.js
This PR fixes a bug where the engine was throwing when attempting to unmount a malformed component. It is expected from the engine that even if a component is in an invalid state it should be unmounted and recreated safely.
W-6981076
=> fix(engine): throw when unmounting malformed component

packages/@lwc/babel-plugin-component/src/__tests__/api-decorator.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/component.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/track-decorator.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/post-process/dedupe-imports.js, packages/@lwc/babel-plugin-component/src/post-process/index.js, packages/@lwc/babel-plugin-component/src/program.js, packages/@lwc/compiler/src/transformers/__tests__/transform-javascript.spec.ts, packages/@lwc/rollup-plugin/src/index.js
Each of the internal transforms on the compiler might add a named import from "lwc", which makes duplicated entries on the final output. While this ends up being tree-shaked by rollup, its just unnecessary work an problematic when dealing with raw ES6 modules.
This PR dedupes any named import from the same source specifier.
Before we output this:
```js
import { registerDecorators as _registerDecorators } from "lwc";
import { registerComponent as _registerComponent } from "lwc";
```
Now we output this:
```js
import { registerDecorators as _registerDecorators, registerComponent as _registerComponent } from "lwc";
```
Note that this is not really for user land code, since we already have linting rules, but rather to the internals of our transforms.
* ✅ `No, it does not introduce breaking …
=> fix: dedupe import statements on compilation

packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/@lwc/engine/src/framework/decorators/register.ts, packages/@lwc/engine/src/framework/wiring.ts, packages/@lwc/wire-service/src/index.ts, packages/integration-karma/test/wire/legacy-adapters/index.spec.js, packages/integration-karma/test/wire/legacy-adapters/x/dynamicWiredProps/dynamicWiredProps.js
This PR fixes an issue with legacy wire adapters in which adapters `config` is invoked when all the dynamic params of the config are `undefined`.
Before this PR, Legacy wire adapters with both, dynamic and static config values, are being called when all of the dynamic parameters are `undefined`, this behavior is different compared to the previous wire protocol (before wire-reform).
Some components are making extra server calls due this issue. Notice that this something that the adapter authors needs to handle once they fully adopt the wire-reform.
Example:
```js
class Foo extends LightningElement {
customerId;
handleSelectCustomerId(event) {
this.customerId = event.detail.customerId;
}
// on first render, it will trigger a "get orders request" without customer id (for example) …
```
=> fix(wire-service): legacy adapters initial config invoked incorrectly

packages/@lwc/wire-service/src/__tests__/index.spec.ts, packages/@lwc/wire-service/src/index.ts, packages/integration-karma/test/wire/legacy-adapters/index.spec.js, packages/integration-karma/test/wire/legacy-adapters/x/sameConfigCase/sameConfigCase.html, packages/integration-karma/test/wire/legacy-adapters/x/sameConfigCase/sameConfigCase.js
This PR addresses an issue in which legacy adapters config get called with the same config values.
This issue can occur in two scenarios:
1. Because a config dynamic param depends on multiple values, some of the dependencies change but generates the same config value.
2. An issue presented today with the @api decorator, in which whenever the api property is set, it will force the reactivity system to notify it as a mutation on the component, even if is the same value.
With the current wire protocol:
Case 1) is valid for new wire adapters and should be handled at the adapter level.
Case 2) is a loophole in the engine today, but it cannot be closed without the risk of compromising existing components. Also, the new wire adapters should handle this case.
With the previous wire protocol:
1) …
=> fix(wire-service): legacy adapters config calls with same config

packages/@lwc/babel-plugin-component/src/__tests__/dedupe-imports.spec.js, packages/@lwc/babel-plugin-component/src/post-process/dedupe-imports.js
Handle the case where all the contents of a module is imported when deduping imports.
W-7258582
=> fix(babel-component-plugin): handle importing the entire module contents

packages/integration-karma/test/integrations/locker/index.spec.js, packages/integration-karma/test/integrations/locker/x/lockerHooks/lockerHooks.html, packages/integration-karma/test/integrations/locker/x/lockerHooks/lockerHooks.js
This PR is a follow up to #1892. It adds missing tests for Locker hooks into the engine.
W-7391508
=> test(engine): Add tests for locker hooks

packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json
This is important because it improves the UX on npmjs.org with a link
back to the git repository and lwc homepage.
For example, the following screenshots compare what the npm page looks like for LWC vs React. There is no way from npm to directly find more details or log bugs with the project:
=> docs: add homepage and repository links in each package.json

packages/@lwc/engine/src/framework/restrictions.ts, packages/integration-karma/test/component/LightningElement.dispatchEvent/index.spec.js, packages/integration-karma/test/component/LightningElement.isConnected/index.spec.js
In preparation for the DOM decoupling, we will need to move the restrictions to the `engine-dom` package. The main issue with moving the current restriction outside the `engine-core` is that the restriction are heavily relying on `engine-core` internals that are unsafe to expose.
This PR removes all the restrictions leveraging engine internals. Fortunately, all the restriction leveraging internals are only there to enforce best practices and can be migrated to linting rules if necessary. The rest of the restriction should be simple enough to implement without having access to the engine internals.
* Have you …
=> refactor(engine): Remove restriction coupled with engine internal

packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/@lwc/engine/src/framework/decorators/register.ts, packages/@lwc/engine/src/framework/wiring.ts
Today the compiled code for a component using wire includes information that's not used by the engine, this is the `static` property and the source of value for dynamic parameters on the config. 
Example component:
```js
import { wire } from 'lwc';
import { getFoo } from 'data-service';
export default class Test {
@wire(getFoo, { dynamicKey: "$prop", staticKey: "fixed value" })
wiredProp;
}
```
today compiles into:
```js
// ...
_registerDecorators(Test, {
wire: {
wiredProp: {
adapter: getFoo,
static: {
staticKey: "fixed value"
},
params: {
dynamicKey: "prop"
},
config: function($cmp) {
return {
staticKey: "fixed value",
dynamicKey: $cmp.prop,
};
}
}
}
});
```
This PR transforms the output of a compiled component, reducing the size of the compiled code of a component using wire by removing …
=> fix(wire-service): reduce compiled component code

packages/@lwc/engine/dom/src/apis/create-element.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/@lwc/engine/src/shared/format.ts
This PR removes the dependency on `Element.prototype.tagName` to look up the component name. The tag name is now stored directly on the `VM`.
W-7552459
=> refactor(engine): remove dependency on Element.prototype.tagName

packages/@lwc/engine/dom/src/polyfills/aria-properties/main.ts, packages/@lwc/engine/dom/src/polyfills/aria-properties/polyfill.ts, packages/@lwc/engine/src/framework/attributes.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/html-properties.ts, packages/@lwc/shared/src/aria.ts, packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/constants.ts
This long-overdue refactor better positions ourselves for the engine-core/engine-dom split.
W-7552459
=> refactor(engine): move common aria-related code into shared package

packages/@lwc/engine/src/framework/template.ts
This PR removes the field validation logic from the template evaluation. This code is never executed because the template compiler never produced a list with all the identifiers used in it.
W-7391508
=> refactor(engine): Remove usused field validation

packages/@lwc/engine/dom/src/apis/build-custom-element-constructor.ts, packages/@lwc/engine/dom/src/apis/create-element.ts, packages/@lwc/engine/dom/src/apis/get-component-constructor.ts, packages/@lwc/engine/dom/src/apis/is-node-from-template.ts, packages/@lwc/engine/dom/src/apis/lightning-element.ts, packages/@lwc/engine/dom/src/env/dom.ts, packages/@lwc/engine/dom/src/env/shadow-dom.ts, packages/@lwc/engine/dom/src/index.ts, packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/stylesheet.ts, packages/@lwc/engine/src/framework/utils.ts, packages/@lwc/engine/src/framework/vm.ts
This PR rearranges the imports from the engine-core and engine-dom:
- All the imports from engine-dom now go through the engine-core main entry point
- The `useSyntheticShadow` value is now part of engine-dom since it is injected at runtime into engine-core.
W-7552459
=> refactor(engine): Rearrange engine-core and engine-dom boundaries 

packages/@lwc/engine/tsconfig.json, packages/@lwc/features/tsconfig.json, packages/@lwc/synthetic-shadow/tsconfig.json, packages/@lwc/wire-service/tsconfig.json, tsconfig.json
Using `es2018` as the default since we haven't completely moved off of node v10. We can bump this to `es2019` once we've fully transitioned to node v12.
https://node.green/
W-7391508
=> build: use typescript library version es2018 as default

packages/@lwc/engine-core/src/framework/context-provider.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/integration-karma/test/context/simple-context.spec.js, packages/integration-karma/test/context/x/simpleProvider/simpleProvider.js
This PR fixes 2 issues in [Context Provider for wire adapters](https://github.com/salesforce/lwc-rfcs/blob/master/text/0000-wire-reform.md#context-provider-for-wire-adapters):
1. When no context value is provided, the `consumerDisconnectedCallback` is not called during disconnecting the context consumer wire.
2. After setting multiple context values in the same provider, and disconnecting the contextual wire, `consumerDisconnectedCallback` is incorrectly called multiple times with repeated consumers.
Both issues have the same root cause, which is in how the `disconnectCallback` is provided.
This PR fixes those issues by separating the provision of a new context value, and the provision of the `disconnectedCallback`.
=> fix(wire-context): consumerDisconnectedCallback called with duplicates

packages/@lwc/engine-core/src/framework/template.ts
Fixing `Template` type by adding the missing `slots` property. This property is generated by the template if any slot is present on the template.
W-7391508
=> chore(engine-core): Add missing slots type on Template

packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts, packages/integration-karma/test/bundle/css_only/index.spec.js, packages/integration-karma/test/bundle/css_only/x/cssContainerComposition/cssContainerComposition.css, packages/integration-karma/test/bundle/css_only/x/cssContainerComposition/cssContainerComposition.html, packages/integration-karma/test/bundle/css_only/x/cssContainerComposition/cssContainerComposition.js, packages/integration-karma/test/bundle/css_only/x/onlyCssComposition/onlyCssComposition.css
This PR reworks how styles are injected in LWC components:
- **for synthetic shadow**, the stylesheets are injected via a new API on the renderer: `insertGlobalStylesheet`. This method abstracts away how stylesheets should be injected. In the case of `@lwc/engine-dom`, the stylesheets are injected at the document level while. In the case of `@lwc/engine-server`, the stylesheets can be gathered to produce the final HTML output.
- **for native shadow**, the stylesheet clone has been removed because the performance gain is almost non-existent. All the evergreen browsers, when creating a new stylesheet will reuse existing CSSOM if the string content has already been parsed. I also didn't measure any performance boost that `Node.prototype.cloneNode` could gives compared to …
=> refactor(engine-core): Rework style injection

packages/@lwc/engine-server/src/renderer.ts
This PR fixes, dynamic style property generation on SSR. For dynamic style, the engine core uses `cssText` on the StyleDeclaration to set the style property content.
W-7552550
=> fix(engine-server): Dynamic style generation

packages/@lwc/engine-core/src/framework/vm.ts, packages/integration-karma/test/rendering/slotted-text-diffing/index.spec.js, packages/integration-karma/test/rendering/slotted-text-diffing/x/child/child.html, packages/integration-karma/test/rendering/slotted-text-diffing/x/child/child.js, packages/integration-karma/test/rendering/slotted-text-diffing/x/container/container.html, packages/integration-karma/test/rendering/slotted-text-diffing/x/container/container.js
When vnodes are allocated in slots (synthetic-shadow only), the process [rewrites the vnode key](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-core/src/framework/vm.ts#L618), in the case of text vnodes (they don't have key), it will make 2 different text vnodes in the same slot, to have the same key.
Later on in [this section](https://github.com/salesforce/lwc/blob/master/packages/@lwc/engine-core/src/3rdparty/snabbdom/snabbdom.ts#L123-L145) diffing algo, [createKeyToOldIdx](https://github.com/salesforce/lwc/blob/538e6143b040880e7d3df771c863c5e5c5b91c19/packages/%40lwc/engine-core/src/3rdparty/snabbdom/snabbdom.ts#L34) will map incorrectly those 2 nodes, causing the algo to patch the incorrect vnode, which eventually triggers an error.
This PR fixes the issue by not …
=> fix(synthetic-shadow): dont add key for slotted text vnode

packages/@lwc/babel-plugin-component/src/__tests__/component.spec.js, packages/@lwc/babel-plugin-component/src/constants.js
Add new `renderComponent` API to the `@lwc/babel-plugin-component` allow list.
As a side note, I really think this should be the job of a new linting rule, should not be part of the compiler. It's maybe something we should attempt to migrate for the next release.
=> feat(babel-plugin-component): add new renderComponent API

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts
This PR disables the `renderedCallback` invocation and the reactivity when the engine is running in SSR mode.
W-7532180 / W-7532182
=> refactor(engine-core): Remove renderedCallback and reactivity for SSR

packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/@lwc/wire-service/src/index.ts
This PR adds `WireConfigValue`, `WireContextValue` and `WireAdapterSchemaValue` to the export list of `engine-core`.
The new exported types  are used with `WireAdapter` and `WireAdapterConstructor`.
Completes issue #1909 
=> fix(engine-core): export wire types used in WireAdapter

packages/@lwc/engine-server/src/polyfills.ts, packages/@lwc/features/src/runtime.ts, packages/@lwc/shared/src/global-this.ts, packages/@lwc/shared/src/index.ts
This PR replace changes the way `@lwc/engine-server` attaches `Event` and `CustomEvent` polyfills are attached to the host environment global object. Currently on those polyfills are attached to the `global` object, this object is specific to Node.js environment. With this PR, the `global` object is replaced with `globalThis` to be compatible with other environments than Node.js.
W-7552574
=> fix(engine-server): use globalThis to attach polyfills

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-server/src/__tests__/fixtures/wire/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/wire/modules/x/wire/adapter.js, packages/@lwc/engine-server/src/__tests__/fixtures/wire/modules/x/wire/wire.html, packages/@lwc/engine-server/src/__tests__/fixtures/wire/modules/x/wire/wire.js
This PR disables wire adapter execution when running in SSR mode.
W-7532187
=> feat(engine-server): Disable wire adapters in SSR

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/modules/x/attribute-style/attribute-style.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/modules/x/attribute-style/attribute-style.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/methods-noop/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/methods-noop/modules/x/methods-noop/methods-noop.js, packages/@lwc/engine-server/src/renderer.ts
- Add missing test coverage for style attribute
- Add missing test coverage for noop component method: `addEventListener`, `removeEventListener`
- Remove unused `tagName` renderer API. This API is not used since bafb31c0765a5d489dce6304a08a2d3a4972540f.
W-7552550
=> test(engine-server): Improve test coverage

packages/lwc/scripts/build.js
Includes `@lwc/engine-server` as part of the `lwc` dist package.
W-7767051
=> build(lwc): generate dist files for engine-server

packages/@lwc/engine-core/src/framework/def.ts
Update type to be of type ENUM rather than string.
Fixes #1301
W-7750710
=> refactor(engine-core): propdef type make enum

packages/@lwc/engine-server/src/__tests__/render-component.spec.ts, packages/@lwc/engine-server/src/apis/render-component.ts
This PR adds runtime checks for the `renderComponent` API and make the third parameter optional.
W-7773530
=> feat(engine-server): Add parameter check to renderComponent

packages/@lwc/engine-core/src/framework/wiring.ts
With the wire reform we started calling wired methods via `invokeComponentCallback` instead of directly. `invokeComponentCallback` executes locker hooks, which in turns changes the identity of the method arguments (the data in this case); this breaks some adapters implementation.
This PR start calling component methods without executing the hooks, to fix an issue with existing wire adapters that rely in the identity of the provided data.
=> fix(wire-service): call wired methods without calling hooks

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-dynamic-escape/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-dynamic-escape/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-dynamic-escape/modules/x/attribute-dynamic-escape/attribute-dynamic-escape.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-dynamic-escape/modules/x/attribute-dynamic-escape/attribute-dynamic-escape.js, packages/@lwc/engine-server/src/__tests__/fixtures/text-interpolation-escape/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/text-interpolation-escape/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/text-interpolation-escape/modules/x/text-interpolation-escape/text-interpolation-escape.html, packages/@lwc/engine-server/src/__tests__/fixtures/text-interpolation-escape/modules/x/text-interpolation-escape/text-interpolation-escape.js, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/engine-server/src/serializer.ts, packages/@lwc/engine-server/src/utils/html-escape.ts
This PR adds HTML escaping for dynamic text and dynamic attributes to prevent potential XSS.
W-7799963
=> fix(enginer-server): HTML escape

packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-server/src/__tests__/fixtures/getter-is-connected/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/getter-is-connected/modules/x/getter-is-connected/getter-is-connected.html, packages/@lwc/engine-server/src/__tests__/fixtures/getter-is-connected/modules/x/getter-is-connected/getter-is-connected.js, packages/@lwc/engine-server/src/apis/render-component.ts, packages/@lwc/engine-server/src/renderer.ts
When rendering on the server, `isConnected` should reflect the current vm state.
W-7532119
=> fix(engine-server): isConnected should not be `true` during construction

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/performance-timing.ts, packages/@lwc/engine-core/src/framework/profiler.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/index.ts, packages/integration-karma/test/profiler/sanity/profiler.spec.js, packages/integration-karma/test/profiler/sanity/x/container/container.html, packages/integration-karma/test/profiler/sanity/x/container/container.js, packages/integration-karma/test/profiler/sanity/x/errorChild/errorChild.html, packages/integration-karma/test/profiler/sanity/x/errorChild/errorChild.js, packages/integration-karma/test/profiler/sanity/x/item/item.html, packages/integration-karma/test/profiler/sanity/x/item/item.js
Adding experimental support for production profiling of lwc component lifecycle ui thread usage
The [performance-timing rfc](https://github.com/salesforce/lwc-rfcs/blob/master/text/0102-performance-timing.md) implementation made it easy to visualize lwc lifecycle events in chrome dev tools. Unfortunately the methodology (browser performance marks) of instrumenting these events was resource heavy, resulting in more than 30% degradation in lwc performance metrics. Thus this collection is only possible in DEV mode. 
The information collected in these lifecycle events that can be used to understand part of why a customer scenario is slow in production and to get back information on how much cpu was used by lwc lifecycle phases and what components were responsible for that. If we couple this …
=> feat: internal profiler Support

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/integration/child/child.html, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/integration/child/child.js, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/integration/nested-tabindex-negative/nested-tabindex-negative.html, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/integration/nested-tabindex-negative/nested-tabindex-negative.js, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/integration/parent/parent.html, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/integration/parent/parent.js, packages/integration-tests/src/components/delegates-focus-click/test-nested-tabindex-negative/nested-tabindex-negative.spec.js
This change fixes a bug where two clicks were required to focus on an input when the input was rendered inside two nested components with negative tabindexes.
To keep things simple for click-focusing, we currently use a global flag to bypass the first invocation of our focus navigation logic on every `mousedown`. If the flag is true, the focus navigation logic sets the flag to false and NOOPs. This system breaks down for nested components because the focus navigation logic is invoked for every component that receives the `focusin` event during the capture phase. The first `focusin` handler sets the flag to false, and as the event bubbles down to the target, other `focusin` handlers end up executing under the assumption that we need to redirect the focus that is about to enter the …
=> fix(synthetic-shadow): nested components with negative tabindex

packages/integration-karma/test/polyfills/aria-properties/index.spec.js
Chrome fixed their bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=914469#c15
Disabled in #1819
W-7971595
=> test(karma-integration): enable aria-selected integration test

packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/membrane.ts, packages/integration-karma/test/integrations/locker/index.spec.js, packages/integration-karma/test/integrations/locker/x/lockerLiveComponent/lockerLiveComponent.js, yarn.lock
~NOTE: this PR is not ready yet. We need to get a new version of observable membrane first.~
This PR enables vnext to function with LWC:
=> fix(engine): make reactive objects and component instances identifiable

packages/lwc/types.d.ts
In order to support the wire reform changes - Imports existing `WireAdapterConstructor` type, and exports type for function `createContextProvider`
W-7797740
=> fix(lwc): add wire reform type

packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-iterator/error-multi-level-expression/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-iterator/error-multi-level-expression/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression/error-computed-attribute/metadata.json, packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/@lwc/template-compiler/src/parser/expression.ts, packages/@lwc/template-compiler/src/shared/ir.ts, yarn.lock
Currently, the template compiler relies on babylon and babel-traverse to parse and validate each template expression.
This PR improves the performance of the parsing phase by:
1. Use a [acorn](https://github.com/acornjs/acorn) instead of babel to parse template expressions: this operation is pretty slow. Even simple expression `a.b.c.d.e` it can take up to 1 ms to parse a single expression.
2. Replace babel-traverse with a custom traversal to validate the template expression.
With this PR (1 + 2) the overall template parsing (compiling) phase is improved by 40% (25%)
<details>
<summary><b>Performance comparison tables</b></summary>
|       |Current	|This PR	|%	|
|---	|---	|---	|---	|
|record-layout-20-fields	|14	|8	|42.85714	|
|record-layout-60-fields	|40	|24	|40	| …
=> perf(template-compiler): optimize parse phase of the template-compiler

packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/integration-karma/test/rendering/slot/index.spec.js, packages/integration-karma/test/rendering/slot/x/child/child.html, packages/integration-karma/test/rendering/slot/x/child/child.js, packages/integration-karma/test/rendering/slot/x/container/container.html, packages/integration-karma/test/rendering/slot/x/container/container.js
In the following example:
```html
<template>
<p>{counter}</p>
<c-child>
<button />
</c-child>
</template>
````
every time the counter is updated, `<c-child>` will get rehydrated for no reason. this is due to the slotting process (in this case the `<button />` passed into `<c-child>`).
this change attempts to optimize that so it doesn't get rerendered.
=> refactor(engine): improving the diffing algo for slotted elements

package.json, yarn.lock
node-fetch GHSA-w7rc-rwvf-8q5r
yargs-parser GHSA-p9pc-299p-vxgp
`meow` dependency was pinned to ^7.1.1. This explicit pinning can be removed after @commitlint/cli releases a new version.
`node-fetch` dependency was pinned to ^2.6.1.
W-7258582
=> chore: address security vulnerabilities in dependencies

packages/@lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts
To account for listeners added prior to synthetic-shadow loading, remove both wrapped and raw listeners
W-8079168
=> fix: removeEventListener patch handle listeners created pre-engine init

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/engine-server/src/apis/render-component.ts
Clean up of core public APIs that are truly not needed anymore to be exposed.
In this case, before `createVM`, we were adjusting the `__proto__` of the element to be upgraded in ever place where we call `createVM`, instead, we can do that as part of the construction process for the component, as the first step before handling the control back to the user.
=> refactor(engine): setElementProto can be moved to the base constructor

packages/lwc/index.js, packages/lwc/scripts/build.js
This PR makes the `@lwc/engine-server` ESM artifact available throw the `lwc` package. Currently, the only artifact available is the commonjs one.   
W-8094084
=> chore(lwc): Expose engine-server ESM artifact

packages/lwc/package.json
This API is a follow up to https://github.com/salesforce/lwc/pull/2039. There is [a case in the `lwc/index.js`](https://github.com/salesforce/lwc/blob/master/packages/lwc/index.js#L67-L68) where it attempts to resolve NPM instead of the `dist/` folder. However the `@lwc/engine-server` is not pulled in as a dependency and due to this, the resolution fails.  
Adding the NPM package to `dependency` fixes the issue.
W-8094084
=> chore(lwc): Add missing depenency on @lwc/engine-server

packages/integration-karma/test/rendering/slotting/index.spec.js, packages/integration-karma/test/rendering/slotting/x/regressionContainer/regressionContainer.html, packages/integration-karma/test/rendering/slotting/x/regressionContainer/regressionContainer.js, packages/integration-karma/test/rendering/slotting/x/regressionSlot/regressionSlot.html, packages/integration-karma/test/rendering/slotting/x/regressionSlot/regressionSlot.js
This PR adds a tests for a behavior that was regressed in #1617 which eventually leaded to a revert in #2052.
With #1617, the added test throw error when updating slotted content (in `containerRegression`) triggers next tick re-render in component receiving the slotted content (`regressionSlot`).
=> test: adds regression test introduced with #1617

packages/@lwc/synthetic-shadow/src/shared/static-html-collection.ts
This PR addresses the fact that HTMLCollection types are not expected to be iterable objects, and these extra methods should be removed.
Fixes https://github.com/salesforce/lwc/issues/1665
🚨 `Yes, it does introduce breaking changes.`
This might be a breaking change if some code relies on the `HTMLCollection` interface being iterable.
W-7101579
=> refactor(syntheitc-shadow): remove iterable methods of HTMLCollection

packages/@lwc/engine-core/src/3rdparty/snabbdom/snabbdom.ts, packages/integration-karma/test/rendering/dynamic-childrens-inside-if/index.spec.js, packages/integration-karma/test/rendering/dynamic-childrens-inside-if/x/forEachCmp/forEachCmp.html, packages/integration-karma/test/rendering/dynamic-childrens-inside-if/x/forEachCmp/forEachCmp.js, packages/integration-karma/test/rendering/dynamic-childrens-inside-if/x/lwcDynamic/lwcDynamic.html, packages/integration-karma/test/rendering/dynamic-childrens-inside-if/x/lwcDynamic/lwcDynamic.js
This PR fixes an issue in the diffing algo that causes re-render issues when the `if` directive has dynamic children. 
Ex: In a component with the template like:
```html
<template>
<template if:true={sectionOpen}>
<template for:each={items} for:item="item">
<div key={item.id}>{item.name}</div>
</template>
</template>
</template>
```
the content of the iteration is not cleared out when the if block is unrendered (setting `sectionOpen` to `false`)
The compiled code for the `if` directive depends on whether it contains direct dynamic children or not. In the case of dynamic children, the code looks like `$cmp.sectionOpen ? api_iterator(.../*returns childrens*/) : []`, the problem is that the `children` from `api_iterator` are dynamic, therefore, it will go through the `updateDynamicChildren` …
=> fix(engine): fixes diffing algo when if has dynamic child

packages/lwc/types.d.ts
- querySelector
- querySelectorAll
- createElement
these methods are used and available but no typings are currently available
Adding types to the lwc package typings
* Have tests for the proposed changes been added? ❌ (N/A)
N/A
=> chore(lwc): add typings

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/html-element.ts, packages/integration-tests/src/components/delegates-focus-click/test-invoke-focus-on-click/integration/child/child.html, packages/integration-tests/src/components/delegates-focus-click/test-invoke-focus-on-click/integration/child/child.js, packages/integration-tests/src/components/delegates-focus-click/test-invoke-focus-on-click/integration/invoke-focus-on-click/invoke-focus-on-click.html, packages/integration-tests/src/components/delegates-focus-click/test-invoke-focus-on-click/integration/invoke-focus-on-click/invoke-focus-on-click.js, packages/integration-tests/src/components/delegates-focus-click/test-invoke-focus-on-click/invoke-focus-on-click.spec.js
In a nutshell, this is how we disable keyboard focus navigation when the user clicks on an element:
`mousedown`: `letBrowserHandleFocus` is set to `true`
`focusin`: short circuit the keyboard focus navigation routine if `letBrowserHandleFocus` is set to `true`
`mouseup`: `letBrowserHandleFocus` is set to `false`
The problem here is that, during a `click`,  all `focus` events are processed before `focusin` events, so if there is a focus handler that runs between the `mousedown` and `focusin` events above, and it invokes the `focus()` method on an element (which is a very strange behavior), the `letBrowserHandleFocus` flag is incorrectly set to `false` before our `focusin` handler runs, causing the "next" element to be incorrectly focused. …
=> fix(synthetic-shadow): conservatively disable focus navigation routine upon focus

scripts/release/README.md, scripts/release/version.js
Removing this option to minimize the possibility of pushing alpha tags.
W-7971595
=> chore: remove push option from version script

packages/@lwc/babel-plugin-component/src/index.js, packages/@lwc/compiler/src/__tests__/fixtures/expected-babel-compat.js, packages/@lwc/compiler/src/__tests__/fixtures/expected-babel.js, packages/@lwc/compiler/src/compiler/__tests__/result.spec.ts, packages/@lwc/compiler/src/transformers/javascript.ts
This PR ensures all the visitors in `@lwc/babel-plugin-component` runs first, which allows we can join the 2 `babel.transform` in the js transform function of the compiler.
Comparison of `transformSync` function on a component js file of 1600 lines: `152 ms` (master) vs `93 ms` (this pr)
=> perf: avoid double babel transform for js files

.circleci/config.yml
pass sauce keys as environment variables from circle ci. Forks will not be able to execute integration test suites. A LWC team member will have to help them accomplish that.
W-8276416
=> chore: remove sauce keys from circleci config

packages/@lwc/engine-core/src/framework/hot-swaps.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/flags.ts, packages/integration-karma/test/swapping/components/index.spec.js
The call for `removeActiveVMs` was in the wrong place which was causing memory leaks for non-diffed disconnected events.
To explicitly about the non-trivial memory consumption I have made a HMR_FLAG to have it disabled by default.
Note: The diff looks like a lot of changes, but I just moved things around, [this view is better](https://github.com/salesforce/lwc/pull/2103/files?w=1)
=> fix: hmr memory leak + feature flag

packages/integration-karma/test/component/LightningElement.getBoundingClientRect/index.spec.js
This PR fixes a `LightningElement.getBoundingClientRect` karma test which is flapping in ie11 with message:
```
IE 11.0 (Windows 7) component LightningElement.getBoundingClientRect should return the host element dimensions FAILED
Error: Expected 9.999998092651367 to be 10.
at <Jasmine>
at callKey1 (/home/circleci/lwc/node_modules/es5-proxy-compat/polyfills.js:1092:9)
at Anonymous function (component/LightningElement.getBoundingClientRect/test/component/LightningElement.getBoundingClientRect/index.spec.js:45:3 <- component/LightningElement.getBoundingClientRect/index.spec.js:194:5)
at <Jasmine>
```
=> test(integration-karma): fix flapper related to getBoundingClientRect() precision

packages/@lwc/engine-core/src/framework/base-bridge-element.ts, packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-dom/src/apis/build-custom-element-constructor.ts
* continue with the trend of removing unnecessary public api used by dom from core pkg
* this also makes it more generic in case we eventually go with vanilla web components
* it relies on the same principle used by public fields and accessors using the proto chain of the bridge to provide the observability of attributes when producing a custom element constructor
=> refactor(engine): removing another public api isAttributeLocked

packages/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-internal-tabindex-negative/test-tabindex-zero-internal-tabindex-negative.spec.js
Makes browser loading synchronous. This one was missed from #2116.
W-8330504
=> fix(integration-tests): make browser loading synchronous for delegates-focus-tab-navigation test

packages/@lwc/engine-core/src/framework/wiring.ts, packages/integration-karma/test/wire/legacy-adapters/index.spec.js, packages/integration-karma/test/wire/property-trap/index.spec.js, packages/integration-karma/test/wire/wiring/index.spec.js
This PR fixes a memory leak reproducible in a component having a wire adapter which config depends on a non-primitive value.
<details>
<summary>Example</summary>
<p>
```js
import { LightningElement, track, wire } from 'lwc';
import { adapter } from './adapter';
const data = {
data: {
txt: 'test value',
},
};
export default class Test extends LightningElement {
@track foo = data;
@wire(adapter, { f: '$foo.data.txt' }) txt;
}
```
</p>
</details>
When the component is disconnected, the reactive observer for the wire config is not reseted, and the reactive observer (and the component) is not collected while the value is kept alive (as part of [this WeakMap](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-core/src/libs/mutation-tracker/index.ts#L11)).
This PR fixes the …
=> fix(engine-core): leaking reactive observers for wire config

packages/@lwc/engine-core/src/framework/wiring.ts, packages/integration-karma/test/wire/wiring/index.spec.js
Follow up to #2112 
[In #2112](https://github.com/salesforce/lwc/pull/2112/files#diff-357ab2b7c6c4aa2aaece1c46d4f45152bd32f1ea4c25ed4792497e528fa4a14fL197-L207), we removed the initial `Promise.resolve()` when calculating the first config (with dynamic parameters) for a wire adapter instance. There is some wire-adapters/components on platform that does not handle well when the value of the dynamic parameter is changed during the connected or rendered callback.
This PR re-introduces the `Promise.resolve()` to compute the first config (that has dynamic parameters) for a wire adapter instance.
W-8537539
=> fix(engine-core): delay initial wire config computation until next tick

packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedElements.spec.js, packages/integration-karma/test/shadow-dom/HTMLSlotElement-properties/HTMLSlotElement-assigned.spec.js
Now that Webkit and Gecko landed `HTMLSlotElement.prototype.assignedElement`, we can finally. get rid of the condition Karma tests.
=> chore(integration-karma): Remove condition enabling assignedElement tests

packages/@lwc/synthetic-shadow/README.md
- Remove comment about restricting dispatching events on `ShadowRoot`. This landed with #2117.
- Add more context around the `slotchange` event restriction.
=> docs(synthetic-shadow): Update README content

package.json, yarn.lock
Fix resolution of systeminformation dependency. This resolved vulnerability GHSA-m57p-p67h-mq74
The usage of "systeminformation" package is as follows
perf-benchmarks > @best/cli > @best/utils > systeminformation
Issue filed for best repo https://github.com/salesforce/best/issues/263
Once @best/utils updates its version of systeminformation, the manual resolution in lwc can be reverted.
=> chore: set dependency resolution to fix security vulnerability

packages/@lwc/compiler/package.json, packages/@lwc/compiler/src/__tests__/fixtures/expected-babel-compat.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_compat_config_simple_app.js, yarn.lock
Packages that were being installed via the `http://npm.lwcjs.org` registry were updated to use yarn's default. This incorrect registry was being used by a `.yarnrc` on my system.
W-8588420
=> chore: normalize registry in yarn lockfile

packages/@lwc/module-resolver/src/__tests__/fixtures/custom-resolution/package.json, packages/@lwc/module-resolver/src/__tests__/fixtures/from-npm/package.json, packages/@lwc/module-resolver/src/__tests__/fixtures/module-entries/package.json, packages/@lwc/module-resolver/src/__tests__/fixtures/no-config/package.json
This PR avoids jest conflicting module names by removing duplicate module names.
=> test: Rename modules to avoid jest conflict

packages/@lwc/features/src/flags.ts, packages/@lwc/synthetic-shadow/src/3rdparty/inner-text.ts, packages/@lwc/synthetic-shadow/src/env/element.ts, packages/@lwc/synthetic-shadow/src/env/window.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/html-element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/integration-karma/test/synthetic-shadow/inner-outer-text/inner-outer-text.spec.js, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/container/container.css, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/container/container.html, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/container/container.js, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/grandChild/grandChild.html, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/grandChild/grandChild.js, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/slotable/slotable.html, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/slotable/slotable.js
This PR provides an `innerText` and `outerText` polyfill for synthetic-shadow, _behind a feature flag_.
The polyfill is based on the [innerText spec](https://html.spec.whatwg.org/multipage/dom.html#the-innertext-idl-attribute), though it has some known drawbacks (so far):
- for the last `table-cell` within a `table-row`, an extra `\t` will be added.
- for the last `table-row` within a `table`, an extra `\n` will be added.
- the inner text value varies from browser to browser, ex: https://codepen.io/jodarove/pen/vYGmrXj is different in chrome and safari.
Pending: innerText setter implementation.
=> feat(synthetic-shadow): innerText and outerText polyfills

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/component.ts, packages/@lwc/engine-core/src/framework/decorators/api.ts, packages/@lwc/engine-core/src/framework/decorators/register.ts, packages/@lwc/engine-core/src/framework/decorators/track.ts, packages/@lwc/engine-core/src/framework/decorators/wire.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/hot-swaps.ts, packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/engine-core/src/framework/observed-fields.ts, packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/wiring.ts
While investigating the `MacroElement` proposal I realized that the `@lwc/engine` contains competing type definition for the `LightningElement` class: `LightElement` interface and `Component` interface. This PR removes `Component` interface definition. It also fixes #1291. 
=> refactor(engine-core): Remove duplicate Component type definition

packages/@lwc/engine-core/src/framework/decorators/register.ts, packages/integration-karma/test/component/decorators/api/index.spec.js, packages/integration-karma/test/component/decorators/track/index.spec.js, packages/integration-karma/test/component/decorators/wire/index.spec.js, packages/integration-karma/test/component/decorators/wire/x/adapter/adapter.js, packages/integration-karma/test/component/observed-fields/index.spec.js
This PR improves the error message for decorator validation.
- Indicate that the decorated field is conflicting with another class member (method, accessor)
- Remove unnecessary process.env.NODE_ENV check. Invocation is already wrapped in env check
- Add tests
W-8651291
=> docs(engine-core): Improve decorator validation message

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/shared/event-target.ts, packages/integration-karma/helpers/test-utils.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/propagation.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/button/button.html, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/button/button.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/buttonGroup/buttonGroup.html, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/buttonGroup/buttonGroup.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/buttonGroupInternal/buttonGroupInternal.html, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/buttonGroupInternal/buttonGroupInternal.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/container/container.html, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/x/container/container.js
This PR applies changes to a branch based off of v1.10.1.
Fixes an event propagation regression introduced in v1.10.0. Test coverage that would have detected this regression has been added in the form of a repro.
Added tests in `propagation.spec.js` currently overlap in coverage with `event-propagation.spec.js` and will eventually replace `event-propagation.spec.js`.
W-8588420
=> fix(synthetic-shadow): fix event propagation regression

packages/@lwc/synthetic-shadow/src/polyfills/event/polyfill.ts, packages/integration-karma/test/shadow-dom/Event-properties/Event.composedPath.spec.js
The `composedPath()` polyfill should account for events whose `target` is not an instance of `Node`.
W-8735932
=> fix(synthetic-shadow): composedPath() should not throw when event.target is not an instance of Node

packages/@lwc/shared/package.json, packages/@lwc/shared/src/aria.ts, packages/@lwc/shared/src/global-this.ts, packages/@lwc/shared/src/language.ts, packages/@lwc/shared/src/symbol.ts, scripts/tasks/verify-treeshakable.js
This PR ensures that `@lwc/shared` is fully treeshakable. It's a first step in the direction of fixing #2024. While it doesn't solve the fact that `@lwc/shared` is imported multiple times by `@lwc/engine`, it adds [`/*@__PURE__*/`](https://rollupjs.org/guide/en/#treeshake) annotation to indicate to rollup that some of the code can be tree shaken safely.
A new script has been added as a `postbuild` step to the `@lwc/shared` to prevent future regression. The postbuild script check if importing the `@lwc/shared` library without consuming any import produces an empty chunk.
Fixes #2104 …
=> refactor(shared): Make @lwc/shared treeshakable

packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/integration-karma/test/shadow-dom/ShadowRoot-properties/ShadowRoot.spec.js
These two methods should not be blocked in OSS as they are stable and non-experimental.
=> fix: unblock shadow methods

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/index.ts, packages/@lwc/synthetic-shadow/src/polyfills/focus-event/README.md, packages/@lwc/synthetic-shadow/src/polyfills/focus-event/main.ts, packages/@lwc/synthetic-shadow/src/polyfills/focus-event/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/mouse-event/README.md, packages/@lwc/synthetic-shadow/src/polyfills/mouse-event/main.ts, packages/@lwc/synthetic-shadow/src/polyfills/mouse-event/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/event-target.ts, packages/@lwc/synthetic-shadow/src/shared/retarget-related-target.ts, packages/integration-karma/test/events/focus-event-related-target/index.spec.js, packages/integration-karma/test/events/focus-event-related-target/x/container/container.html, packages/integration-karma/test/events/focus-event-related-target/x/container/container.js, packages/integration-karma/test/events/focus-event-related-target/x/input/input.html, packages/integration-karma/test/events/focus-event-related-target/x/input/input.js, packages/integration-tests/src/components/events/test-retarget-related-target/integration/child/child.html, packages/integration-tests/src/components/events/test-retarget-related-target/integration/child/child.js, packages/integration-tests/src/components/events/test-retarget-related-target/integration/retarget-related-target/retarget-related-target.html, packages/integration-tests/src/components/events/test-retarget-related-target/integration/retarget-related-target/retarget-related-target.js, packages/integration-tests/src/components/events/test-retarget-related-target/retarget-related-target.spec.js
Add shadow semantics to the relatedTarget property of `FocusEvent` and `MouseEvent`.
These changes have already been reviewed in #2087 and this PR will be labeled with "nomerge" until it's decided that we're ready to move forward.
Minimal to no impact in environments where Locker is available due to the relatedTarget reference changing from the generic `document` to actual relevant event retargeting.
In environments without Locker, relatedTarget will change from the original relatedTarget to a retargeted one, as defined in the spec. …
=> refactor(synthetic-shadow): relatedTarget prototype patching for FocusEvent and MouseEvent

lerna.json, scripts/release/version.js
This PR removes the `lerna --force-publish` option. This option has long been deprecated and removed.
* 
=> chore: Remove force-publish usage

scripts/release/version.js
This reverts the changes introduced in #2223. By default, lerna publish only a subset of all the packages that have been changed since the previous release. 
While the standard behavior is the right approach, because of the way LWC is released on Salesforce, downstream consumers expect ALL the package to have the same version. We can change this behavior in the future however it would require more work on the automation pipeline.
=> chore: Add back lerna --force-publish flag

packages/@lwc/synthetic-shadow/src/3rdparty/polymer/path-composer.ts, packages/@lwc/synthetic-shadow/src/env/shadow-root.ts, packages/@lwc/synthetic-shadow/src/index.ts, packages/integration-karma/test/native-shadow/Event-methods/Event.composedPath.spec.js
`event.composedPath()` is returning incorrect values for native shadow roots due to `ShadowRoot` being defined/replaced with our `SyntheticShadowRoot` by our [ShadowRoot polyfill](https://github.com/salesforce/lwc/blob/ff6c28bc001b55cdee2a6f9442ce5e95a4f0e96a/packages/%40lwc/synthetic-shadow/src/polyfills/shadow-root/polyfill.ts).
Impact should be minimal since this bugfix only affects native web components inside LWC.
W-8538508
=> fix(synthetic-shadow): native shadow root support for pathComposer()

packages/@lwc/synthetic-shadow/src/3rdparty/polymer/path-composer.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/integration-karma/test/shadow-dom/Event-properties/Event.composedPath.spec.js, packages/integration-karma/test/shadow-dom/Event-properties/x/child/child.html, packages/integration-karma/test/shadow-dom/Event-properties/x/container/container.html
Account for instances of `EventTarget` that are neither instances of `Window` nor `Node`.
W-8588420
=> refactor(synthetic-shadow): account for event targets that are neither Window nor Node in path-composer

packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/codegen/codegen.ts, packages/@lwc/template-compiler/src/codegen/formatters/module.ts, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/config.ts, packages/@lwc/template-compiler/src/shared/types.ts, packages/@lwc/template-compiler/src/state.ts, yarn.lock
This is the first PR to remove Babel from the `@lwc/template-compiler` repo. This PR removes some dead code that was used to handle inline style generation. This code is unreachable since the parser block any usage of `<style>` in the template.
https://github.com/salesforce/lwc/blob/40d0f678436ce33119f73db5e6a755dcc5c81541/packages/%40lwc/template-compiler/src/parser/index.ts#L453-L458
W-7462545
=> refactor(template-compiler): Remove unreachable code for inline style parsing

packages/@lwc/synthetic-shadow/src/shared/event-target.ts, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/event-propagation.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/propagation.spec.js
=> fix(synthetic-shadow): properly filter non-composed events

packages/@lwc/style-compiler/src/__tests__/fixtures/unsupported-slotted-selector/actual.css, packages/@lwc/style-compiler/src/__tests__/fixtures/unsupported-slotted-selector/error.json, packages/@lwc/style-compiler/src/selector-scoping/validate.ts
Remove `::slotted` from the UNSUPPORTED_SELECTORS` list.
https://github.com/salesforce/lwc/pull/2213#pullrequestreview-579347311
=> feat(style-compiler): allow ::slotted

packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/state.ts
Before doing the actual code gen, the compiler does a full AST traversal to detect if some nodes are using the `id` attribute or prop. In order to avoid this extra AST traversal, this information is gathered while parsing the AST.
=> refactor(template-compiler): Use single traversal for scoped id generation

packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/codegen/scope.ts, packages/@lwc/template-compiler/src/index.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/scope.ts, packages/@lwc/template-compiler/src/state.ts
This PR simplifies the `@lwc/template-compiler` by removing the `ids` gathered on `State`. This property is never used. As a side effect, this PR also improves the compiler performance by removing an AST traversal for each parsed expression.
=> refactor(template-compiler): Remove unused id from internal state

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js
Currently we have wrong `this` value for shadow root and custom element listeners. With this PR listeners invoking context will be set properly.
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe the issue being fixed or feature enhanced?  ✅ 
W-8883676
=> fix(synthetic-shadow): fix invoking context for shadow root and custom element listeners

packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/codegen/scope.ts, packages/@lwc/template-compiler/src/shared/estree.ts, packages/@lwc/template-compiler/src/shared/ir.ts, yarn.lock
This PR removes the dependency on `@babel/traverse` in favor of `estree-walker`. This package is lighter and faster compared to `@babel/traverse`. The `isComponentProp` has also been optimized by replacing the recursive invocation with a simple while loop.
=> refactor(template-compiler): Replace @babel/traverse by estree-walker

packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/component.js, packages/@lwc/babel-plugin-component/src/constants.js, packages/@lwc/babel-plugin-component/src/post-process/transform.js
Move component registration transform out of post-process.
W-8630713
=> refactor(babel-plugin-component): move component registration transform out of post-process

packages/@lwc/features/src/flags.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/html-element.ts, packages/integration-karma/test/synthetic-shadow/inner-outer-text/inner-outer-text.spec.js
This PR enables the innerText and outerText shadow dom semantics by default.
=> feat(synthetic-shadow): enable innerText shadow dom semantics by default

packages/@lwc/synthetic-shadow/src/3rdparty/inner-text.ts, packages/integration-karma/test/synthetic-shadow/inner-outer-text/inner-outer-text.spec.js, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/container/container.css, packages/integration-karma/test/synthetic-shadow/inner-outer-text/x/container/container.html
This PR fixes an issue with the innerText polyfill on elements that has no selectable text.
=> fix(synthetic-shadow): innerText of elements with non-selectable text

packages/@lwc/template-compiler/src/config.ts
The "secure" option no longer does anything but we still have it as an available option name because removing it is a breaking change.
W-8988767
=> chore(template-compiler): remove unused "secure" option

packages/@lwc/synthetic-shadow/src/polyfills/event/polyfill.ts, packages/integration-karma/test/shadow-dom/Event-properties/Event.currentTarget.spec.js
Listeners on shadow roots currently receive events whose `event.currentTarget` references the shadow root's host.
W-9066543
=> fix(synthetic-shadow): correct currentTarget in shadow root listeners

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/main.ts, packages/integration-karma/test/component/LightningElement.toString/index.spec.js
Removes `BaseLightningElement` and uses `LightningElement` throughout. In preparation for creating a new `BaseLightningElement` that will be superclass of both `LightningElement` and `MacroElement` (light DOM).
W-8844567
=> refactor: simplify types

packages/@lwc/features/src/flags.ts
Revised version of https://github.com/salesforce/lwc/pull/2295. Adds a runtime flag to enable light DOM components.
W-9155929
=> feat: add runtime flag for light dom components

packages/integration-karma/test/shadow-dom/stylesheet/x/multiTemplates/a.css, packages/integration-karma/test/shadow-dom/stylesheet/x/multiTemplates/b.css
I managed to actually repro the Firefox flapper described in https://github.com/salesforce/lwc/pull/2304 . I can repro in Firefox 88 on Mac, only when using native shadow.
Apparently Firefox sometimes ends up in a dirty state where it believes that
```css
div {
margin-left: 10px;
}
```
being replaced with
```css
div {
margin-right: 10px;
}
```
means that both `margin-left` and `margin-right` are 10px.
This PR fixes it by adding an explicit 0px to both stylesheets. AFAICT this fixes the flapper.
In parallel, we can of course dive deeper and file a bug on Firefox.
=> test: fix firefox flapper in native shadow style test

.eslintrc, package.json, packages/@lwc/babel-plugin-component/src/decorators/wire/validate.js, packages/@lwc/features/src/runtime.ts, packages/@lwc/rollup-plugin/src/__tests__/index.spec.js, packages/@lwc/synthetic-shadow/src/faux-shadow/no-patch-utils.ts, packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/integration-tests/scripts/build.js, yarn.lock
Uses [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import) to ensure that imports occur in the following order:
- builtins
- external
- internal
This is [borrowed](https://github.com/airbnb/javascript/blob/1eadb93/packages/eslint-config-airbnb-base/rules/imports.js#L146-L149) from `eslint-config-airbnb-base`.
I saw this come up in a few code reviews, so I figured we should formalize this. `eslint --fix` can fix these ordering issues automatically.
=> chore: enforce import ordering with eslint

packages/integration-karma/test/events/focus-event-related-target/index.spec.js
While researching the Firefox flapper, this test was driving me a bit nuts because it seemed to be flapping too. Only later did I realize that this test only flaps if the browser content window isn't focused, and only in some browsers.
This PR adds a note to the test to hopefully save the next person from going on a wild goose chase trying to figure out why the test is flapping. 😅 
=> test: add note about test which may fail locally

packages/@lwc/engine-dom/src/renderer.ts, packages/integration-karma/README.md, packages/integration-karma/helpers/test-setup.js, packages/integration-karma/scripts/karma-configs/base.js, packages/integration-karma/test/api/CustomElementConstructor-getter/x/lifecycleChild/lifecycleChild.js, packages/integration-karma/test/api/CustomElementConstructor-getter/x/lifecycleParent/lifecycleParent.js, packages/integration-karma/test/component/aom-setter/index.spec.js, packages/integration-karma/test/component/lifecycle-callbacks/x/child/child.js, packages/integration-karma/test/component/lifecycle-callbacks/x/parent/parent.js, packages/integration-karma/test/component/lifecycle-callbacks/x/parentIf/parentIf.js, packages/integration-karma/test/component/lifecycle-callbacks/x/parentProp/parentProp.js, packages/integration-karma/test/component/lifecycle-callbacks/x/single/single.js, packages/integration-karma/test/misc/clean-dom/index.spec.js, packages/integration-karma/test/misc/cross-domain-iframe/index.spec.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedElements.spec.js, packages/integration-karma/test/native-shadow/HTMLSlotElement-properties/HTMLSlotElement.assignedNodes.spec.js, packages/integration-karma/test/polyfills/document-body-properties/index.spec.js, packages/integration-karma/test/polyfills/document-properties/index.spec.js, packages/integration-karma/test/shadow-dom/Document-properties/leak-tests.spec.js, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js, packages/integration-karma/test/shadow-dom/HTMLSlotElement-properties/HTMLSlotElement-assigned.spec.js, packages/integration-karma/test/synthetic-shadow/element-api/element-api.spec.js, packages/integration-karma/test/synthetic-shadow/inner-outer-text/inner-outer-text.spec.js, packages/integration-karma/test/template/attribute-id/aria.spec.js, packages/integration-karma/test/template/attribute-id/href.spec.js
For the `integration-karma` tests, it would be nice if the DOM were clean between each test. This matters less for things like shadow DOM, but for light DOM it starts to have an impact since elements are more likely to affect each other (e.g. styling).
This PR adds a setup script that runs between each test to clean out the `document.head` and `document.body`, as well as adding a test that would fail without this PR in place (I checked).
=> test: clean the DOM between each karma test

.circleci/config.yml
Removes the BEST performance run for now on the CI. The `perf_and_compare` step is the most expensive step on the CI build and doesn't give valuable feedback due to the result variance. This can be re-enabled in the future once we figure out how to report consistent performance comparisons.
=> ci: Disable BEST run on CircleCI

packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/integration-karma/test/light-dom/slotting/index.spec.js, packages/integration-karma/test/light-dom/slotting/x/container/container.html, packages/integration-karma/test/light-dom/slotting/x/container/container.js, packages/integration-karma/test/light-dom/slotting/x/slotted/slotted.html, packages/integration-karma/test/light-dom/slotting/x/slotted/slotted.js
With this PR, slotting content into a light DOM component throws an error in DEV mode. This restriction will be lifted once we enable support for slotting in the light DOM.
=> feat(engine-core): Prevent slotting in light DOM components

packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/compiler/src/transformers/transformer.ts
Provides a default value for `preserveHtmlComments` instead of casting `undefined` to `boolean`.
TD-0089604
=> refactor(compiler): clean up type definitions

README.md, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_compat_config_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_css_resolver.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_relative.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_ts_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/index.spec.js
In #2294 we added Jest snapshot tests, but we didn't add them for the `rollup-plugin` tests. This PR fixes that, removing the previous homegrown `fsExpected` helper function.
=> test: use Jest snapshots for rollup-plugin tests

package.json, yarn.lock
xmlhttprequest-ssl package is reported to have a vulnerability. 
**Usage:** 
Hoisted from "_project_#perf-benchmarks#@best#runner-remote#socket.io-client#engine.io-client#xmlhttprequest-ssl"
W-7258582
=> chore: address security vulnerability CVE-2020-28502

packages/@lwc/engine-core/src/framework/api.ts, packages/integration-karma/test/light-dom/ids/index.spec.js, packages/integration-karma/test/light-dom/ids/x/one/one.html, packages/integration-karma/test/light-dom/ids/x/one/one.js, packages/integration-karma/test/light-dom/ids/x/shadow/shadow.html, packages/integration-karma/test/light-dom/ids/x/shadow/shadow.js, packages/integration-karma/test/light-dom/ids/x/two/two.html, packages/integration-karma/test/light-dom/ids/x/two/two.js
When rendering to the light DOM, avoid mangling IDs/fragments, e.g. transforming `foo` into `foo-1` or `#foo` into `#foo-1`.
Note that because of https://github.com/salesforce/lwc/issues/1150 we can't actually guarantee the correct semantics for references between two components, where one is a light component and the other is a shadow component. So this means that, for light DOM elements, we essentially just never mangle any ids or fragments.
W-9224059
=> fix: preserve original ids/fragments in light DOM

packages/@lwc/features/src/flags.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/html-element.ts, packages/integration-karma/test/synthetic-shadow/inner-outer-text/inner-outer-text.spec.js, packages/integration-tests/src/components/dom/test-inner-text/inner-text.spec.js, packages/integration-tests/src/components/dom/test-inner-text/integration/inner-text/inner-text.html, packages/integration-tests/src/components/dom/test-inner-text/integration/inner-text/inner-text.js
This PR makes the innerText patch to be disabled by default.
The `innerText` patch relies on the selection API to calculate the "innerText" of text nodes. There's a bug on [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1208631) and [Safari](https://bugs.webkit.org/show_bug.cgi?id=225723), in which removing and then re-adding ranges to the selection during an input click does not restore cursor/focus in the input, making it unusable.
=> Revert "feat(synthetic-shadow): enable innerText shadow dom semantics by default (#2247)"

packages/@lwc/babel-plugin-component/src/__tests__/decorators.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/track-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/index.js
Component class transformation introduces a registerDecorators() call expression.
This expression needs to be wrapped in a statement to protect its validty incase the code is minified(which babel does when input size is more than 500kb).
Fixes #2336
W-9266461
=> fix(babel-plugin-component): fix transformation of ClassDeclarations that have an id

packages/@lwc/engine-core/src/shared/circular-module-dependencies.ts, packages/integration-karma/test/integrations/aura/index.spec.js, packages/integration-karma/test/integrations/aura/x/childModuleMarkedAsCircular/childModuleMarkedAsCircular.html, packages/integration-karma/test/integrations/aura/x/childModuleMarkedAsCircular/childModuleMarkedAsCircular.js, packages/integration-karma/test/integrations/aura/x/parent/parent.html, packages/integration-karma/test/integrations/aura/x/parent/parent.js
Fixes an existing issue when resolving circular dependencies injected by Aura. The issue is only visible for a component module (`export default class Foo extends LightningElement`) marked with `__circular__` and also having named exports.
**Note:** The issue was noticed when forcing named exports for internal components on the platform.
=> fix(engine-core): resolve circular dependencies of module

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-component-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attributes-aria/expected.html, packages/integration-karma/test/light-dom/ids/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/scoped-ids/scoped-ids.spec.js, packages/integration-karma/test/mixed-shadow-mode/scoped-ids/x/test/test.html, packages/integration-karma/test/mixed-shadow-mode/scoped-ids/x/test/test.js, packages/integration-karma/test/synthetic-shadow/scoped-id/multiple-idrefs.spec.js
Allow native shadow encapsulation to handle scoping of ids.
W-9229039
=> fix(engine-core): avoid mangling ids in native shadow mode

packages/@lwc/synthetic-shadow/src/env/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/integration-karma/test/synthetic-shadow/shadow-root-instanceof/index.spec.js, packages/integration-karma/test/synthetic-shadow/shadow-root-instanceof/x/component/component.js
Makes it so that `shadowRoot instanceof ShadowRoot` works, even in synthetic shadow mode.
~~This PR is on top of #2356 because it relies on those changes. I'm opening this PR to start running CI tests early.~~
W-9317606
=> fix: shadowRoot instanceof ShadowRoot should be true

scripts/release/publish.js
The automated release process currently publishes packages with the `next` dist tag. On a weekly cadence, we need to update the previous release dist tag to `latest`.
This process was put in place to give us time to test a release before marking it as the latest one. I don't think this extra release step is needed anymore because we are now following strict semantic versioning and because of the maturity of the CI pipeline.
=> chore: Release to latest dist tag by default

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/integration-karma/test/light-dom/basic/index.spec.js
These values should be read once and cached before construction.
No
W-9357285
=> refactor(engine-core): move preferNativeShadow and renderMode values to ComponentDef

packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/integration-karma/test/native-shadow/children/index.spec.js, packages/integration-karma/test/native-shadow/children/x/slottable/slottable.html, packages/integration-karma/test/native-shadow/children/x/slottable/slottable.js
Ensures that `HTMLSlotElement.prototype.children` behaves correctly in both native and synthetic slots.
Fixes #2135
W-8582701
=> fix: preserve HTMLSlotElement.prototype.children behavior in native slots

packages/@lwc/engine-core/src/framework/vm.ts, packages/integration-karma/test/mixed-shadow-mode/composition/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/light/light.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/light/light.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/native/native.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/native/native.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeContainer/nativeContainer.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeContainer/nativeContainer.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeLightSynthetic/nativeLightSynthetic.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeLightSynthetic/nativeLightSynthetic.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeRenderFunc/nativeRenderFunc.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeRenderFunc/one.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeRenderFunc/two.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeSlottable/nativeSlottable.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/nativeSlottable/nativeSlottable.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/synthetic/synthetic.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/synthetic/synthetic.js, packages/integration-karma/test/mixed-shadow-mode/composition/x/syntheticContainer/syntheticContainer.html, packages/integration-karma/test/mixed-shadow-mode/composition/x/syntheticContainer/syntheticContainer.js
Throws an error if synthetic shadow components are composed within native shadow components.
W-8778376
=> fix: disallow synthetic-within-native composition

packages/@lwc/errors/src/__tests__/errors.spec.ts, packages/@lwc/errors/src/compiler/error-info/index.ts
As discussed here: https://github.com/salesforce/lwc/pull/2372#discussion_r652445115
=> test: add test to confirm "next error code" comment is updated

packages/@lwc/engine-core/src/framework/restrictions.ts, packages/integration-karma/test/mixed-shadow-mode/restrictions/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/restrictions/x/component/component.html, packages/integration-karma/test/mixed-shadow-mode/restrictions/x/component/component.js, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js
Adds tests (which will run in both native and synthetic mode) to ensure that restrictions from [restrictions.ts](https://github.com/salesforce/lwc/blob/11943c7cdfc8d505827bd86e477f9b8ff7ce84d3/packages/%40lwc/engine-core/src/framework/restrictions.ts) are applied.
Here is my audit of the restrictions:
- `patchElementWithRestrictions` – this only applies to `lwc:dom="manual"` which is not needed in native mode
- `patchShadowRootWithRestrictions` – ✅  (except `addEventListener` which is already covered [here](https://github.com/salesforce/lwc/blob/4013ec09107e8393b1087de0e59197b1ee69ac86/packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js))
- `patchCustomElementWithRestrictions` – ✅ 
- `patchComponentWithRestrictions` – already covered in [an …
=> fix: ensure restrictions are applied for both synthetic and native shadow

packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/style.ts, packages/@lwc/errors/src/compiler/error-info/compiler.ts
Deprecate `outputConfig.minify` option. This option is not used anymore by the style compiler since #2252.
=> chore(compiler): Deprecate unused minify output config

packages/integration-tests/README.md
Small documentation change. I ran into this when running the integration tests – you need to specify the Sauce Labs tunnel ID, e.g. when testing IE11.
=> docs: document Sauce tunnel ID for integration tests

packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/polyfills/document-shadow/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/faux-element-from-point.ts
Follow-up to #2381. Refactors `elementFromPoint` so that the logic is shared between `document.elementFromPoint` and `ShadowRoot.elementFromPoint`.
=> refactor: move elementFromPoint into shared function

packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/apis/render-component.ts, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/engine-server/src/types.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/mixed-props-attrs/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/base/svg-with-iteration/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/base/svg/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/filter/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/foreign-object/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/linear-gradient/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/scoped-id-dynamic/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/scoped-id-static/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/simple-svg/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/valid-image/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/valid-svg/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/xlink-with-expression-value/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/xlink-with-literal-value/expected.js, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/ir.ts, packages/@lwc/template-compiler/src/shared/types.ts
This PR removes the runtime VNodes traversal when rendering SVG elements. A new optional `svg` property is added to the `data` object by the compiler, this property indicated whether the element should be created under the SVG namespace or not.
The special handling for `foreignObject` has been removed since this tag can only belong to the SVG namespace. I traced back the addition of this branch back to 2017. Back then we still used a JSX parser for the template which didn't have namespace information. Now that we are using parse5, I don't see the value of keeping this special case around.
Fix #1275, #1136. …
=> perf(engine): Remove VNodes traversal for SVG elements

packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/parser/html.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/ir.ts, packages/@lwc/template-compiler/typings/parse5.d.ts
This PR is in preparation for LWC template compiler rework. It changes the way the parse5 AST is turned into an LWC AST. 
Today the template compiler uses a visitor pattern with a stack to convert each pasrse5 AST node into the "equivalent" LWC template AST node. Using a visitor pattern to map from one AST shape to another creates more issues than it resolves: complex control flow, requires to keep a stack to track parents, etc.
In this PR, the visitor traversal is turned into a simple recursive traversal.  
=> refactor(template-compiler): Make AST traversal recursive

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/features/src/flags.ts, packages/integration-karma/test/mixed-shadow-mode/LightningElement.preferNativeShadow/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/composition/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/restrictions/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/scoped-ids/scoped-ids.spec.js
Adds a runtime flag, `ENABLE_PREFER_NATIVE_SHADOW`, which needs to be set in order to use `preferNativeShadow`. Currently it throws if the static property is set at all (regardless of the value).
W-9492763
=> fix: add flag to disable preferNativeShadow by default

packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/codegen/codegen.ts, packages/@lwc/template-compiler/src/codegen/formatters/function.ts, packages/@lwc/template-compiler/src/codegen/formatters/module.ts, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/index.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/types.ts, packages/@lwc/template-compiler/src/state.ts
This PR is a step closer to the new final AST shape without introducing any breaking change. With this PR, the `lwc:render-mode` and `lwc:preserve-comments` directives are now part of the generated LWC AST. 
As a side effect, it allows removing the `State` object from the codegen phase. That said a full AST transversal is still needed to know if the generated id attributes should be scoped or not. 
In a follow-up PR, the plan is to completely get rid of the `State` object in the parsing phase as well in favor of a proper `Parser` object. This `Parser` object would be in charge of carrying the current parsing state and handle diagnostics. This change should greatly simplify the parser logic. 
**Review note:** Since both commits are orthogonal from one another, I would recommend reviewing …
=> refactor(template-compiler): Move all LWC directives to the LWC AST

packages/@lwc/engine-core/src/libs/mutation-tracker/index.ts
This is complementary to #2416. (So I opened a separate PR to keep things simple.)
Inside of `@lwc/engine-core`, we have some helper functions that could be imported from `@lwc/shared`, but which were inlined instead.
I can't see why these couldn't just be imported from `@lwc/engine-core`, so we can avoid some duplication.
File size improvements:
| File | Before | After |
| --- | --- | --- |
| `esm/es2017/engine-dom.js` | 235,397 bytes | 235,194 bytes |
| `esm/es2017/engine-server.js` | 225,285 bytes | 225,082 bytes |
W-8054984
=> perf(engine-core): remove explicitly duplicated code

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/integration-karma/test/component/locker-live-property/index.spec.js, packages/integration-karma/test/component/locker-live-property/x/component/component.html, packages/integration-karma/test/component/locker-live-property/x/component/component.js
- [Slack thread for context](https://salesforce-internal.slack.com/archives/G0213GSKXA6/p1625604188079300)
In theory, it should make component construction faster to avoid `defineProperty()` for the `lockerLivePropertyKey` and just do an assignment directly. Also, Locker is only checking `Object.hasOwnProperty()` for this, so it doesn't matter whether we do direct assignment or `defineProperty()`.
Using Tachometer (100 min sample size, 2% horizon, 60 minute timeout), with the `dom-wc-create-10k` benchmark, the improvement is 1-2%:
Just to be safe, I re-ran with 1% horizon and 90 minute timeout, and got a similar result: …
=> perf: assign locker live property directly

packages/@lwc/engine-core/src/framework/performance-timing.ts, packages/integration-karma/test/profiler/sanity/profiler.spec.js
As noticed by @tariqrafique (https://github.com/salesforce/lwc/pull/2400#discussion_r671405601), we're not actually clearing performance measures correctly. This fixes that, and adds a test to confirm the behavior.
Technically this is a breaking change if someone is relying on `performance.getEntriesByType('measure')` and expecting to  find LWC measures in there. Hopefully nobody is doing that – they should use the unstable profiler API instead.
=> fix: clear performance marks and measures

packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/scripts/rollup.config.js, packages/@lwc/features/package.json, packages/@lwc/features/scripts/rollup/rollup.config.js
This removes duplication of code from `@lwc/shared` in `@lwc/engine-dom` and `@lwc/engine-server`. Here are the file sizes before and after:
| File | Before | After |
| --- | --- | --- |
| `esm/es2017/engine-dom.js` |232K |220K |
| `esm/es2017/engine-server.js` |224K |212K |
The downside of this change is that `@lwc/shared` is now a dependency (not devDependency) of `@lwc/engine-core` and `@lwc/features`. So this could break anyone who is depending on the `dist/` files for those packages not containing any external dependencies.
This doesn't seem like a real risk to me, as the main entry points are `@lwc/engine-dom` and `@lwc/synthetic-shadow`. (Speaking of which, this PR does _not_ fix duplication of `@lwc/shared` between those two, since they're designed to be standalone and …
=> perf: avoid duplicate @lwc/shared code

package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/scripts/rollup.config.js, packages/@lwc/engine-core/tsconfig.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-dom/scripts/rollup.config.js, packages/@lwc/engine-dom/tsconfig.json, packages/@lwc/engine-server/package.json, packages/@lwc/engine-server/scripts/rollup.config.js, packages/@lwc/engine-server/tsconfig.json, packages/@lwc/features/package.json, packages/@lwc/features/scripts/rollup/rollup.config.js, packages/@lwc/features/tsconfig.json, packages/@lwc/shared/package.json, packages/@lwc/shared/scripts/rollup/rollup.config.js, packages/@lwc/shared/tsconfig.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/@lwc/synthetic-shadow/tsconfig.json, packages/@lwc/wire-service/package.json, packages/@lwc/wire-service/scripts/rollup/rollup.config.js, packages/@lwc/wire-service/tsconfig.json, packages/lwc/scripts/utils/rollup.js, scripts/rollup/writeDistAndTypes.js, yarn.lock
Fixes #2422
`rollup-plugin-typescript` is deprecated. This PR is step 1 toward removing it in favor of `@rollup/plugin-typescript`.
I ran a diff of the `dist` files before and after to make sure they are exactly the same. They are the same, except for some whitespace in `@lwc/synthetic-shadow/dist/synthetic-shadow.js`.
W-9614477
=> chore(package): update to @rollup/plugin-typescript

package.json, packages/lwc/scripts/utils/rollup.js, yarn.lock
Related: #2422
This removes the deprecated `rollup-plugin-typescript` entirely. Instead, we use Babel to generate the ES5 builds for the `lwc` package.
I looked at the compiled output, and the `.min.js` files are slightly larger, but only by a few KBs. Nothing stands out to me that we could do to remove the extra KBs.
We _could_ use `@rollup/plugin-babel`, but it seems unnecessary to me as it's pretty straightforward to just use `@babel/core` directly. Plus, we are already doing this [elsewhere](https://github.com/salesforce/lwc/blob/9675ae066cce503e4bd50a21bb094bf727b9a11d/packages/%40lwc/compiler/src/transformers/javascript.ts#L31-L44).
=> chore(package): remove rollup-plugin-typescript entirely

packages/@lwc/synthetic-shadow/src/polyfills/event-target/polyfill.ts, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js
This is a micro-optimization for `patchedAddEventListener`. Basically it avoids cloning an Array of arguments every time `addEventListener` is called.
Running Tachometer with 1% horizon and 30 minute timeout, all tests are <1% unchanged except for:
- `dom-ss-slot-create-container` (1%-2% faster)
- `dom-ss-slot-update-slotted-content` (1% faster)
- `dom-wc-append-1k` (1% faster)
- `dom-wc-create-10k` (1%-2% faster)
- `dom-wc-create-1k` (1% faster).
<details><summary>Full results</summary>
```
┌─────────────┬─────────────────┐
│     Browser │ chrome-headless │
│             │ 91.0.4472.164   │
├─────────────┼─────────────────┤
│ Sample size │ 100             │
├─────────────┼─────────────────┤
│       Bytes │ 237.78 KiB      │
└─────────────┴─────────────────┘ …
```
=> perf(synthetic-shadow): optimize patchedAddEventListener

packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/modules/static-style-attr.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/modules/x/attribute-style/attribute-style.html, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/style/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-static/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/linear-gradient/expected.js, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/integration-karma/test/template/attribute-style-important/index.spec.js, packages/integration-karma/test/template/attribute-style-important/x/component/component.css, packages/integration-karma/test/template/attribute-style-important/x/component/component.html, packages/integration-karma/test/template/attribute-style-important/x/component/component.js
Fixes #2443
Converts `styleMap` to a `styleDecls` array containing triples of `[name, value, important?]`. E.g.:
```html
<div style="background: blue !important; color: red; opacity: 0.5 !important"></div>
```
becomes:
```js
{
/* ... */
styleDecls: [
['background', 'blue', true],
['color', 'red'],
['opacity', '0.5', true]
]
}  
```
So the compiler output has changed.
W-9682301
=> fix: fix !important in inline styles

packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/engine-core/src/framework/performance-timing.ts, packages/@lwc/engine-core/src/framework/profiler.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/@lwc/shared/src/language.ts
We had 5 different `noop` functions throughout the code. This gets us down to one, exported from `@lwc/shared`.
I won't claim this is a perf improvement, because it only reduced the minified size of `engine-dom.js` by 92 bytes. 🙂  But I figure hey, we might as well.
=> refactor: use a single noop function

packages/perf-benchmarks/README.md, packages/perf-benchmarks/scripts/build.js
I have no idea how I didn't notice this before, but there's no reason to require setting a `CIRCLE_WORKING_DIRECTORY` when running the benchmarks. We already know what the working directory is, because we can find it relative to the location of the script.
This makes the benchmark build script a lot simpler.
=> chore: simplify how benchmarks load components

packages/lwc/scripts/build.js, packages/lwc/scripts/utils/generate_targets.js
In the `lwc` package, in the `build.js` script, if any of the worker processes throws an error, currently it will just hang forever with no output. This can be confusing. 🙂 
This PR fixes it so that if any worker throws an error, the process exits with a non-zero exit code and logs the error. I confirmed that this worked by throwing a deliberate `Error` in one of the build workers and confirming that it gave useful error output.
=> chore(build): properly handle worker errors

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/decorators/register.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/performance-timing.ts, packages/@lwc/engine-core/src/framework/profiler.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/template-compiler/src/shared/types.ts
This modestly reduces the bundle size by using `const enum` instead of `enum` for client-side code ([details](https://github.com/salesforce/lwc/pull/2400#discussion_r670447568)). `engine-dom.js` drops from 223.1kB to 221.5kB (-1.6kB), and `synthetic-shadow.js` drops from 186.0kB to 185.4kB (-0.6kB).
The PR won't pass CI until #2427 is merged.
W-9611979
=> perf: use const enum over enum

packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/invalid-empty-tag/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/no-closing-tag/metadata.json, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/html.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/ir.ts, packages/@lwc/template-compiler/src/shared/parse5.ts, packages/@lwc/template-compiler/src/shared/types.ts, packages/@lwc/template-compiler/typings/parse5.d.ts, yarn.lock
* Drops the template compiler depdency on our parse5 fork in favor of the latest version of parse5.
* Clean up all the warning collection logic to use the `IRNode` instead of the original parse5 AST nodes. 
W-8283257
=> refactor(template-compiler): Upgrade `parse5` and clean up error location

packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/codegen/scope.ts, packages/@lwc/template-compiler/src/parser/expression.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/ir.ts, packages/@lwc/template-compiler/src/shared/types.ts
This PR covers the following two tasks from the [Github issue](https://github.com/salesforce/lwc/issues/2432):
- Remove parent field from IRNodes: The future AST nodes won't have parent back pointers (because it introduces circular dependencies). We can take a head start by changing the compiler code to keep track of the parent chain instead of relying on the information stored on the AST node.
W-9698817
=> refactor(template-compiler): Remove parent AST references

packages/@lwc/template-compiler/src/__tests__/fixtures/events/type-invalid/metadata.json, packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/constants.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/shared/ir.ts, packages/@lwc/template-compiler/src/shared/types.ts
This PR covers the following two tasks from the [Github issue](https://github.com/salesforce/lwc/issues/2432):
- Remove the following fields from the IRNodes: original, attrsList: Those properties won't be present in the new AST shape and are only used for internal bookkeeping. Instead of storing parse5 AST nodes on the LWC compiler AST nodes, those should be passed around in the parser.
W-9698810
=> refactor(template-compiler): Remove original and attrsList references

packages/integration-karma/test/light-dom/inheritance/index.spec.js, packages/integration-karma/test/light-dom/inheritance/x/baseLight/baseLight.html, packages/integration-karma/test/light-dom/inheritance/x/baseLight/baseLight.js, packages/integration-karma/test/light-dom/inheritance/x/baseShadow/baseShadow.html, packages/integration-karma/test/light-dom/inheritance/x/baseShadow/baseShadow.js, packages/integration-karma/test/light-dom/inheritance/x/defaultExtendsLight/defaultExtendsLight.html, packages/integration-karma/test/light-dom/inheritance/x/defaultExtendsLight/defaultExtendsLight.js, packages/integration-karma/test/light-dom/inheritance/x/defaultExtendsShadow/defaultExtendsShadow.html, packages/integration-karma/test/light-dom/inheritance/x/defaultExtendsShadow/defaultExtendsShadow.js, packages/integration-karma/test/light-dom/inheritance/x/lightExtendsShadow/lightExtendsShadow.html, packages/integration-karma/test/light-dom/inheritance/x/lightExtendsShadow/lightExtendsShadow.js, packages/integration-karma/test/light-dom/inheritance/x/shadowExtendsLight/shadowExtendsLight.html, packages/integration-karma/test/light-dom/inheritance/x/shadowExtendsLight/shadowExtendsLight.js, packages/integration-karma/test/light-dom/inheritance/x/test/test.html, packages/integration-karma/test/light-dom/inheritance/x/test/test.js
Adds a Karma test to verify that light DOM inheritance works as expected:
- shadow can override light
- light can override shadow
- undefined inherits light
- undefined inherits shadow
=> test: add more tests for light DOM inheritance

packages/@lwc/compiler/src/transformers/javascript.ts
This PR forces Babel to run with `compact` turned off. This prevents the following error to print out in the console when compiling modules larger than 500 KB:
```
[BABEL] Note: The code generator has deoptimised the styling of <filename> as it exceeds the max of 500KB.
```
=> chore(compiler): Silent Babel codegen size error

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/engine-core/src/framework/profiler.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts
This PR simplifies the LWC engine profiler logic:
- Remove the necessity to wrap profiler call in a `if (profilerEnabled) {}` block
- Unify `logOperation*` and `logGlobalOperation*` function signature
Since this PR is a complete rewrite of the `profiler.ts` I made sure to create a clean commit history with incremental changes. I would recommend reviewing this change by looking at each commit in isolation.
=> refactor(engine-core): Simplify profiler logic

packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/duplicate-default-slot/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/duplicate-default-slot/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/duplicate-default-slot/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/duplicate-named-slot/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/duplicate-named-slot/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/duplicate-named-slot/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/slot-in-iterator/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/slot-in-iterator/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/slot-in-iterator/metadata.json, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/parser/parser.ts
Fixes #1734
If a template contains multiple slots with the same name (or multiple default slots), the compiler should emit a warning. The template is invalid in that case, since there's no real reason to have duplicates.
This also fixes a discrepancy between how synthetic and native shadow DOM deal with duplicate slots (#1734, #2351).
* ✅  `No, it does not introduce breaking changes.`
Any existing template with duplicate slots, when running in synthetic shadow mode, will currently (and incorrectly) render the slotted content multiple times. After this change, those same templates will log a compile-time warning.
W-7255094
=> fix: log compiler warning on duplicate slots

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/integration-karma/test/component/LightningElement.getBoundingClientRect/index.spec.js, packages/integration-karma/test/component/dom-query/LightningElement.getElementsByClassName.spec.js, packages/integration-karma/test/component/dom-query/LightningElement.getElementsByTagName.spec.js, packages/integration-karma/test/component/dom-query/LightningElement.querySelector.spec.js, packages/integration-karma/test/component/dom-query/LightningElement.querySelectorAll.spec.js
Rather than throw an error when `querySelector`/`querySelectorAll`/etc are called in the `constructor` phase, log a warning instead. There are some valid use cases for doing this, and the browser doesn't treat it as an error, so we probably shouldn't.
**Future work**: currently we're only doing this for a few APIs, but arguably we should be consistent and do it for more APIs. (If `getElementsByTagName`, then why not `getElementsByTagNameTS`? If `getBoundingClientRect`, then why not `getClientRects`?)
W-9833099
=> fix(engine-core): just warn on qS/qSA/etc in constructor

packages/@lwc/synthetic-shadow/src/env/dom.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/polyfills/event/polyfill.ts, packages/integration-karma/test/native-shadow/Event-methods/Event.composedPath.spec.js, packages/integration-karma/test/native-shadow/Event-methods/x/synthetic/synthetic.js
Our `composedPath()` polyfill returns an incorrect path when a component is using native Shadow DOM. This is because the polyfill requires the original target to work correctly and the target we pass it has been natively retargeted.
Fixes #2379
No
W-9493000
=> fix(synthetic-shadow): invoke native composedPath() for native shadow dom

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/apis/is-node-from-template.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts
@pmdartus feedback from #2477 
No
236 Trust
=> fix: avoid synthetic shadow specific logic for light dom in native mode

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts, packages/integration-karma/test/light-dom/multiple-templates/index.spec.js, packages/integration-karma/test/rendering/elements-are-not-recycled/index.spec.js, packages/integration-karma/test/shadow-dom/multiple-templates/index.spec.js, packages/integration-karma/test/shadow-dom/multiple-templates/x/multi/a.css, packages/integration-karma/test/shadow-dom/multiple-templates/x/multi/a.html, packages/integration-karma/test/shadow-dom/multiple-templates/x/multi/b.css, packages/integration-karma/test/shadow-dom/multiple-templates/x/multi/b.html, packages/integration-karma/test/shadow-dom/multiple-templates/x/multi/multi.js, packages/perf-benchmarks-components/rollup.config.js, packages/perf-benchmarks-components/scripts/generate-styled-components.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-styled-component-create-1k-different.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-styled-component-create-1k-same.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/styled-component-create-1k-different.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/styled-component-create-1k-same.benchmark.js, packages/perf-benchmarks/src/utils/styledComponentBenchmark.js
After looking into [the synthetic-to-native shadow migration](https://salesforce.quip.com/sYZaADXA4arY), it's clear to me that we need a performant solution for including the same stylesheet in multiple components (e.g. `@import 'shared.css'`). And through manual testing, I saw that constructable stylesheets really are a significant perf improvement in Chrome.
This PR is a revised version of #2290 that aims to be less invasive to the codebase while still bringing perf improvements. I also added some new Tachometer benchmarks to verify the perf gain.
My goal is to improve native shadow performance without regressing synthetic shadow performance. To achieve this, we're only using constructable stylesheets in the per-component level, not at the global level. (See [this …
=> perf: use constructable stylesheets

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts
This PR moves the `isNativeShadowRootDefined` check from the `globalThis` to the `Renderer` interface. Both `isNativeShadowDefined` and `isSyntheticShadowDefined` flags are now present on now directly accessible via the `Renderer` interface.
=> refactor: move isNativeShadowDefined to renderer

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/@lwc/engine-server/src/__tests__/fixtures/wire/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/wire/modules/x/wire/adapter.js, packages/@lwc/features/src/flags.ts, packages/integration-karma/test/wire/wiring/index.spec.js
This PR enables the wire adapters on SSR and modifies the timing of invoking the wire adapter `update` method for a wire adapter instance configuration which depends on a component value. This PR also adds a flag to enable (disabled by default) the invocation timing, as we don't know the blast radius for the existing components today.
Currently, SSR rendering is governed by a set of principles ([SSR RFC](https://rfcs.lwc.dev/rfcs/lwc/0112-server-engine#constraints)) to make the LWC SSR predictable and performant.
(a) As of today, wire adapters are not invoked in SSR because of two main reasons:
1. The current protocol doesn't define a way today to indicate that the stream is done emitting new data.
2. In cases where a wire adapter instance configuration depends on a component value, the …
=> feat: enable wire protocol in SSR

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-server/src/__tests__/fixtures/light-dom-multiple/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/light-dom/index.js, packages/@lwc/features/src/flags.ts, packages/integration-karma/test/light-dom/basic/index.spec.js, packages/integration-karma/test/light-dom/events/index.spec.js, packages/integration-karma/test/light-dom/ids/index.spec.js, packages/integration-karma/test/light-dom/inheritance/index.spec.js, packages/integration-karma/test/light-dom/light-parent-shadow-child/index.spec.js, packages/integration-karma/test/light-dom/multiple-templates/index.spec.js, packages/integration-karma/test/light-dom/restriction/index.spec.js, packages/integration-karma/test/light-dom/shadow-getter/index.spec.js, packages/integration-karma/test/light-dom/shadow-parent-light-child/index.spec.js, packages/integration-karma/test/light-dom/slotting/index.spec.js, packages/integration-karma/test/light-dom/style-global/index.spec.js, packages/integration-karma/test/light-dom/style-multiple/index.spec.js, packages/integration-karma/test/light-dom/style-with-host/index.spec.js, packages/integration-karma/test/light-dom/style/index.spec.js, packages/integration-karma/test/light-dom/synthetic-shadow-styles/index.spec.js, packages/integration-karma/test/light-dom/synthetic-shadow/index.spec.js, packages/integration-karma/test/template/directive-lwc-render-mode/index.spec.js
This PR enables LWC light DOM by default by removing the associated feature flag.
=> feat(engine-core): Enable light DOM by default

packages/@lwc/features/src/types.ts, packages/integration-karma/test/mixed-shadow-mode/transitivity/index.spec.js
I think #2487 was supposed to remove this flag entirely, but it looks like we may have missed a few references.
=> fix: remove ENABLE_LIGHT_DOM_COMPONENTS flag entirely

packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/expression.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/parser/parser.ts
Refactor AST traversal in the parser to use new helper method findAncestor on ParserCtx and updated error handling for parseExpression, parseIdentifier and normalizeAttribute to use ParserCtx's helper methods.
W-9698836
=> refactor(template-compiler): Add AST traversal helper to ParserCtx and updated error handling

packages/perf-benchmarks-components/scripts/generate-styled-components.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/light-styled-component-create-1k-different.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/light-styled-component-create-1k-same.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-native-styled-component-create-1k-different.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-native-styled-component-create-1k-same.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-styled-component-create-1k-same.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/styled-component-create-1k-different.benchmark.js
Adds benchmarks for native-shadow-on-mixed-mode and light DOM. I'm reusing the existing "styled components" test, which includes both a "1k same component" and "1k different components" variant.
Out of curiosity, I ran the benchmarks to compare 1) native, 2) synthetic, 3) native-on-mixed, and 4) light. I used 1% horizon, 20 minute timeout, and 100 min samples. Here are [the results](https://docs.google.com/spreadsheets/d/1MNj2AnGcmwXzrvyLHvLCYau92AYUsELX1zxI7IkDC2U/edit?usp=sharing):
**1k different components**
**1k same component**
Takeaways:
- Pure-native and native-on-mixed are basically the same performance (we would hope so!)
- Light is a bit faster than native, native is a bit faster than synthetic
W-9881479
W-9726312
=> test: add benchmarks for light mode and mixed mode

packages/@lwc/compiler/src/options.ts, packages/@lwc/rollup-plugin/src/index.js
This is a follow-up to address some PR comments in #2332.
- Use Rollup `meta` data for `scoped` property (https://github.com/salesforce/lwc/pull/2332#discussion_r709142064)
- Clean up TypeScript `NormalizedTransformOptions` interface (https://github.com/salesforce/lwc/pull/2332#discussion_r703300444)
=> fix: clean up light DOM scoped styles in compiler

packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/error-dom-manual/metadata.json, packages/integration-karma/test/template/directive-lwc-render-mode/index.spec.js
Small tweaks to make light DOM error messages more friendly. Adds some more context (e.g. which component is causing the error, which DOM element is causing the error).
=> fix: improve light DOM error messages

packages/@lwc/babel-plugin-component/src/__tests__/api-decorator.spec.js, packages/@lwc/engine-core/src/framework/decorators/register.ts, packages/integration-karma/test/component/decorators/api/index.spec.js, packages/integration-karma/test/component/decorators/api/x/duplicatePropertyTemplate/duplicatePropertyTemplate.html, packages/integration-karma/test/component/decorators/api/x/duplicatePropertyTemplate/duplicatePropertyTemplate.js, packages/integration-karma/test/component/decorators/track/index.spec.js, packages/integration-karma/test/component/decorators/track/x/duplicatePropertyTemplate/duplicatePropertyTemplate.html, packages/integration-karma/test/component/decorators/track/x/duplicatePropertyTemplate/duplicatePropertyTemplate.js, packages/integration-karma/test/component/decorators/wire/index.spec.js, packages/integration-karma/test/component/decorators/wire/x/adapter/adapter.js, packages/integration-karma/test/component/decorators/wire/x/duplicatePropertyTemplate/duplicatePropertyTemplate.html, packages/integration-karma/test/component/decorators/wire/x/duplicatePropertyTemplate/duplicatePropertyTemplate.js, packages/integration-karma/test/component/observed-fields/index.spec.js, packages/integration-karma/test/component/observed-fields/x/duplicatePropertyTemplate/duplicatePropertyTemplate.html, packages/integration-karma/test/component/observed-fields/x/duplicatePropertyTemplate/duplicatePropertyTemplate.js
This is a backport of https://github.com/salesforce/lwc/pull/2501 to `winter22` branch.
W-9927596
=> fix(engine-core): Preserve old duplicate public property behavior

packages/@lwc/rollup-plugin/package.json, packages/@lwc/rollup-plugin/src/index.js
Fixes #2505
This PR updates the min semver in the `peerDependencies` Rollup version for `@lwc/rollup-plugin`, and improves the error message if the Rollup version is too old.
=> fix: throw error if Rollup version is too old

packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/error-slots-event-listeners/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/error-slots-event-listeners/metadata.json, packages/@lwc/template-compiler/src/parser/index.ts
Fixes #2507
I also added a test to confirm that `onslotchange` throws the error for a `<slot>` in light DOM mode.
W-9947075
=> fix(template-compiler): fix event listeners on light DOM slots

packages/perf-benchmarks-components/src/benchmark/trackedComponent/trackedComponent.html, packages/perf-benchmarks-components/src/benchmark/trackedComponent/trackedComponent.js, packages/perf-benchmarks-components/src/benchmark/trackedComponentRow/trackedComponentRow.html, packages/perf-benchmarks-components/src/benchmark/trackedComponentRow/trackedComponentRow.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-tracked-component/trackedcmp-create-10k.benchmark.js
As mentioned in https://github.com/salesforce/observable-membrane/pull/69, we don't currently have any benchmarks that exercise `@track`. It seems like it would be a good idea to at least have one benchmark using a component with `@track`.
This benchmark takes ~550ms to run on my machine, and I confirmed that it's exercising the `getProxy()` function in `observable-membrane`.
=> perf: add benchmark for @track

packages/@lwc/engine-core/package.json, yarn.lock
1.1.5 includes a performance improvement: https://github.com/salesforce/observable-membrane/pull/69
W-10099550
=> chore: update observable-membrane to 1.1.5

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/integration-karma/test-hydration/mismatches/type-coercion-to-string/index.spec.js, packages/integration-karma/test-hydration/mismatches/type-coercion-to-string/x/main/main.html, packages/integration-karma/test-hydration/mismatches/type-coercion-to-string/x/main/main.js
This PR fixes a validation issue while hydrating an element. The problem is visible when setting attributes/text to a non-string value.
=> fix(engine-dom): hydration errors due type mismatch

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts
#2442 introduced a small performance regression, notably in the `dom-table-create-10k` benchmark. After [tracking it down](https://gus.lightning.force.com/lightning/r/0D5EE00000KKBVG0A5/view), most of the regression can be reduced to [this simple change](https://github.com/nolanlawson/lwc-1/commit/1cedb2f30b85c610cc82493c81ba8f728d673d3d).
My hunch is that adding the `get isHydrating` changes the object shape in such a way that V8 has a harder time optimizing the other functions on the object, which are frequently called. So switching from a getter to a regular function actually gives us a decent performance win across [most of the benchmarks](https://docs.google.com/spreadsheets/d/1KZx1eE5xGQs68klGLPvDN8Lb8NZAgVJXVL8LWTgDdXk/edit#gid=0):
(The above is comparing this PR versus current …
=> perf: optimize isHydrating

packages/integration-karma/test/accessibility/LightningElement.focus/index.spec.js, packages/integration-karma/test/shadow-dom/ShadowRoot-properties/ShadowRoot.delegatesFocus.spec.js
Fixes #2565
We may have to file a bug on Firefox, but for now this should get rid of the CI test failures.
Tip: [hide whitespace changes](https://github.com/salesforce/lwc/pull/2567/files?diff=split&w=1) when looking at the diff for this PR.
=> test: fix test for Firefox 94 delegatesFocus

packages/@lwc/rollup-plugin/README.md
Adds a link to the documentation for the `modules` option for `@lwc/rollup-plugin`.
=> docs(rollup-plugin): add docs on "modules" option

package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/src/framework/membrane.ts, packages/@lwc/template-compiler/package.json, scripts/release/publish.mjs, scripts/release/version.mjs, yarn.lock
- Upgrade `dependencies` and `devDependencies`.
- Moves `publish.js` and `release.js` to modules to adopt the latest version of `execa` which doesn't ship CommonJs exports. 
W-7258582
=> chore: Upgrade depdendencies

scripts/release/version.mjs
For the new Nucleus release process, we're going to need to open a PR bumping the version numbers, rather than directly committing to `master` and then pushing the branch and the tag to git. This means that the release script should not automatically add a git tag – we will need to add it manually after the PR is merged.
W-10179839
=> chore: update release script to avoid git tags

scripts/release/publish.mjs
Fix `publish.mjs` script after the upgrade to `execa@6`. In #2581, I missed that all the `git` commands in this script were using `execa.commandSync` and not `execa.sync`. This PR rectifies this issue.
W-7258582
=> chore: fix publish script after `execa` update

.nucleus.yaml
In #2586, we enabled Nucleus for two downstream deps. This PR adds more downstreams, based on which ones were green in [a recent run](https://nucleus.data.sfdc.net/workflows/37689).
This may increase our test flappiness, so we may have to remove certain downstreams in the future if they end up being flappy.
W-10179854
=> chore: add more required downstream deps to nucleus

packages/@lwc/engine-core/src/framework/profiler.ts, packages/integration-karma/test/profiler/sanity/profiler.spec.js, packages/integration-karma/test/profiler/sanity/x/container/container.html, packages/integration-karma/test/profiler/sanity/x/light/light.html, packages/integration-karma/test/profiler/sanity/x/light/light.js
This adds observability to the profiler API for renderMode (light vs shadow) and shadowMode (synthetic vs native). It does so in a [performant](https://gus.lightning.force.com/lightning/r/0D5EE000008jsE90AI/view) and backwards-compatible way with the existing API.
Someone using the experimental profiler API can notice that the callback is being passed additional arguments.
W-9923052
=> feat: add observability for renderMode/shadowMode

packages/@lwc/engine-core/scripts/rollup.config.js, packages/@lwc/engine-dom/scripts/rollup.config.js, packages/@lwc/engine-server/scripts/rollup.config.js, packages/@lwc/features/scripts/rollup/rollup.config.js, packages/@lwc/shared/scripts/rollup/rollup.config.js, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/@lwc/synthetic-shadow/src/shared/node-ownership.ts, packages/@lwc/wire-service/scripts/rollup/rollup.config.js
Currently, if there's a TypeScript error in the code, we won't see the full error information (the filename, the line of code, etc.) in `yarn build`. That's because by default it's just a warning, and we have our own `onwarn` handler that throws its own Error:
https://github.com/salesforce/lwc/blob/9675ae066cce503e4bd50a21bb094bf727b9a11d/packages/%40lwc/engine-dom/scripts/rollup.config.js#L44-L47
This PR uses the (somewhat awkwardly-named) [`noEmitOnError`](https://github.com/rollup/plugins/tree/master/packages/typescript#noemitonerror) option to throw a proper TypeScript error message during the build.
**Before**
**After**
=> chore: show proper TypeScript error messages

packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/style-compiler/src/postcss-lwc-plugin.ts, packages/@lwc/synthetic-shadow/src/shared/node-ownership.ts
This PR removes all the unused types and code present in the repository.
This code was flagged by [`ts-prune`](https://www.npmjs.com/package/ts-prune) as exported but unused or exported but only used locally. This package is not bug-free, but I would encourage running this one in a while on our projects.
=> chore: Cleanup unused types

packages/@lwc/engine-core/src/framework/hooks.ts
This PR removes the `runWithBoundaryProtection` in `updateChildrenHook`. 
For context, the `runWithBoundaryProtection` method is used to catch and report user errors and recover from them. This method should wrap all the userland code invocation from the framework code. In the diffing algo the boundary protection is invoked in: 
- `patchShadowRoot`: root method to trigger the diffing algo.
- and `updateChildrenHook`: method used to diff children VNodes. This method is called recursively for each VNode with children. 
This is no need to `runWithBoundaryProtection` from within `updateChildrenHook` as it is always guarded by another boundary protection at `patchShadowRoot`. 
=> perf: Remove unnecessary boundary protection in children diffing

.nucleus.yaml
This downstream [has flapped](https://salesforce-internal.slack.com/archives/C02C1PTVB1N/p1638923299105500?thread_ts=1638922616.104200&cid=C02C1PTVB1N), so let's remove it for now.
=> chore(nucleus): remove LCT/lightning-container-testing

packages/integration-karma/test/rendering/table-diffing/index.spec.js
See discussion here: https://github.com/salesforce/lwc/pull/2589#discussion_r766070386
Prior to this PR, we didn't have any Jest or Karma tests to exercise the `else` block in this code path (line 133):
https://github.com/salesforce/lwc/blob/d93e2963d8d32b138ce9ed130d98e7bef84b3d74/packages/%40lwc/engine-core/src/3rdparty/snabbdom/snabbdom.ts#L127-L146
This PR adds a test that does hit this line of code:
Interestingly, the `if` block here seems completely unreachable:
https://github.com/salesforce/lwc/blob/d93e2963d8d32b138ce9ed130d98e7bef84b3d74/packages/%40lwc/engine-core/src/3rdparty/snabbdom/snabbdom.ts#L136
The only way it could be reached is if two VNodes with two different tags (e.g. `x-foo` and `x-bar`) occupy the same positions in the children array. I tried to repro this using …
=> test: add test for snabbdom mutating old children

packages/integration-karma/test/light-dom/synthetic-shadow/index.spec.js
Since we decided to maintain the existing behavior and not to drop https://github.com/salesforce/lwc/pull/2455, this PR adds a test to ensure the existing behavior does not regress.
W-9630161
=> fix(synthetic-shadow): convert getRootNode test into regression test

packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/integration-karma/helpers/test-utils.js, packages/integration-karma/test/api/createElement/index.spec.js, packages/integration-karma/test/api/createElement/x/test/test.js
Component authors have been asking for a way to detect synthetic shadow. You can do it today by inspecting the `this.template.constructor.toString()`, but it's fragile because the value may differ across Jest and the browser, or in minified vs unminified code.
This PR adds a `synthetic` boolean property to `SyntheticShadowRoot` so that developers can do:
```js
export default class extends LightningElement {
renderedCallback() {
console.log('Synthetic?', !!this.template.synthetic)
}
}
```
I'm happy to bikeshed on the name (`synthetic`? `lwcSynthetic`? `__synthetic__`?), but I seem to recall @pmdartus already suggested something like this.
The `SyntheticShadowRoot` class exposes a new boolean …
=> feat: add API to detect synthetic shadow

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
This PR is to bump the lwc version to incorporate the template compiler refactor.
I made this a minor version bump as the output of the template compiler has changed and there are downstream consumers that will be affected.
The template compiler AST shape has changed in a nonbackward compatible way.  
W-8283257
=> chore: bump lwc version

packages/@lwc/synthetic-shadow/src/env/element.ts, packages/@lwc/synthetic-shadow/src/env/text.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/integration-karma/test/light-dom/slotting/index.spec.js, packages/integration-karma/test/light-dom/synthetic-shadow/index.spec.js, packages/integration-karma/test/rendering/elements-are-not-recycled/index.spec.js, packages/integration-karma/test/shadow-dom/Element-properties/Element.assignedSlot.spec.js, packages/integration-karma/test/shadow-dom/Node-properties/Node.compareDocumentPosition.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/propagation.spec.js, packages/integration-karma/test/synthetic-shadow/element-api/element-api.spec.js
Fixes #2377 
When synthetic shadow polyfill is loaded, accessing `assignedSlot` for elements that are assigned to slots inside native shadow components will return null. The proposed fix is to call the native `assignedSlot` getter under this condition.
W-9492998
=> fix(synthetic-shadow): synthetic shadow doesn't preserve assignedSlot behavior

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
This PR bumps `lwc` and its subpackages. This is a patch version bump.
Changes: [`v2.7.0..v2.7.1`](https://github.com/salesforce/lwc/compare/v2.7.0...version-bump-2.7.1)
* ✅ Yes, it does introduce a breaking change.
The template compiler AST shape has changed in a nonbackward compatible way.  
* 🚨 No, it does not introduce an observable change.
W-8283257
=> chore: bump version to 2.7.1

packages/@lwc/synthetic-shadow/src/shared/faux-elements-from-point.ts, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/index.spec.js, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/child/child.css, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/child/child.html, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/child/child.js, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/grandparent/grandparent.css, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/grandparent/grandparent.html, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/grandparent/grandparent.js, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/parent/parent.css, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/parent/parent.html, packages/integration-karma/test/shadow-dom/ShadowRoot.elementsFromPoint/x/parent/parent.js
Fixes #2495
Here's a basic example of what's happening:
```html
<x-outer>
#shadow-root
<x-inner>
#shadow-root
<div></div>
</x-inner>
</x-outer>
```
Let's say we call `outer.shadowRoot.elementsFromPoint()`. And let's say `<x-inner>` is invisible (width and height = 0) whereas `<div>` is visible.
In _native_ shadow, we get these elements:
[<x-inner>, <x-outer>, <html>]
In synthetic shadow, the native `elementsFromPoint` returns these:
[<div>, <x-outer>, <html>]
The current (wrong) behavior returns:
[<x-outer>, <html>]
The problem is that the current code ignores the `<div>` because it's not visible in `<x-outer>`'s shadow root.
In this PR, we take the `<div>` and find an ancestor host that is accessible to `<x-outer>`'s shadow root. This host can be added to the resulting array.
* ✅ No, it …
=> fix(synthetic-shadow): elementsFromPoint returns invisible hosts

.nucleus.yaml
Remove ui-dxp-components from Nucleus because their snapshot tests will continue failing until [this](https://git.soma.salesforce.com/communities/ui-dxp-components/issues/380) is fixed.
More details: https://github.com/salesforce/lwc/pull/2549
=> chore(nucleus): disable ui-dxp-components

packages/@lwc/engine-core/src/framework/modules/attrs.ts, packages/integration-karma/test/template/attributes/index.spec.js
If the initial value of an attr is `undefined`, we don't add the attribute. But if we assign it to something else and then assign it back to undefined, we don't remove the attribute. We set it to the string `'undefined'`. This fix, removes the attribute, maintaining it consistent with the initial case.
=> fix: fix incosistent attribute behavior for undefined attrs

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/vm.ts
The diffing algo exposes multiple entry points today: `updateDynamicChildren` and `updateStaticChildren`. This PR abstracts that away and exposes a single entry point called `patchChildren`. 
This PR also moves the `allocateInSlot` function into `hooks.ts`. This method is a diffing algo internal detail and has nothing to do with the VM itself.
This PR is part of the larger refactor for [coupling the rehydration logic from the diffing logic](https://github.com/salesforce/lwc/pull/2608).
W-10409559
=> refactor(engine-core): Expose single entrypoint into the diffing algo

packages/@lwc/engine-core/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/modules/attrs.ts, packages/@lwc/engine-core/src/framework/modules/computed-class-attr.ts, packages/@lwc/engine-core/src/framework/modules/computed-style-attr.ts, packages/@lwc/engine-core/src/framework/modules/events.ts, packages/@lwc/engine-core/src/framework/modules/props.ts, packages/@lwc/engine-core/src/framework/modules/static-class-attr.ts, packages/@lwc/engine-core/src/framework/modules/static-style-attr.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-component-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-dynamic/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-static/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/if-conditional-slot/expected.html
This PR removes some of the duplicated code related to attributes and properties patching. Patching attributes and properties are now done by a single function called `patchElementPropsAndAttrs`:
- combine logic for standard elements and custom elements patching
- removes the concept of create and update hooks
This PR is part of the larger refactor for [coupling the rehydration logic from the diffing logic](https://github.com/salesforce/lwc/pull/2608).
This PR changes the order in which the props and attributes are set after the element creation.
**Before:** Static and dynamic attributes patching are interleaved.
- Event listeners (create)
- Attributes (created & update)
- Props (create & …
=> refactor(engine-core): Simplify props and attrs patching

packages/@lwc/engine-core/src/framework/modules/attrs.ts, packages/@lwc/engine-core/src/framework/modules/props.ts
This PR removes the assertions in properties and attributes patching (https://github.com/salesforce/lwc/pull/2630#discussion_r783956758). 
Those assertions were added at the time where we were still figuring out how to compile HTML to JavaScript. Those asserts will never execute as long as the VNodes originates from a template generated by the `@lwc/template-compiler`. The assertions should be safe to delete now.
This PR is part of the larger refactor for [coupling the rehydration logic from the diffing logic](https://github.com/salesforce/lwc/pull/2608).
W-10409559
=> refactor(engine-core): remove unnecessary props/attrs assertions

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
2.7.3 release. Designed to replace the botched 2.7.2 release.
=> chore: bump to 2.7.3

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/vm.ts
The VM render root is the node used as container to render a given LWC component. It can either be a `ShadowRoot` if the component is a shadow DOM component or an `HTMLElement` in the case of a Light DOM component. The diffing algo needs the render root when starting the diffing to process to know where to render the template, but also when creating a new VNode.
Looking up the render root is currently done by the intermediary of `getRenderRoot`. This value can safely be cached on the VM to avoid the function call overhead, especially when creating VNodes.
W-10409559
=> refactor(engine-core): Cache `renderRoot` on the `VM` object

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/apis/build-custom-element-constructor.ts, packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/engine-dom/src/apis/hydrate-component.ts, packages/@lwc/engine-server/src/apis/render-component.ts, packages/integration-karma/test/hydration/index.spec.js
This PR changes the way `createVM` is invoked to accept a `LightningElement` constructor as a second argument instead of a component def. This change provides multiple benefits:
- it removes the need to invoke `getComponentInternalDef` before invoking `createVM`. 
- it also allows removing the `getComponentInternalDef` from the APIs exposed from `@lwc/engine-core`. 
W-10409559
=> refactor: Make `createVM` accept a `LightningElement` constructor

packages/perf-benchmarks/README.md, packages/perf-benchmarks/scripts/build.js
This PR removes this note from [Tachometer](https://github.com/Polymer/tachometer) when running the perf tests:
```sh
$ ../../node_modules/.bin/tach --config dist/__benchmarks__/engine-dom/benchmark-table-component/tablecmp-create-1k.tachometer.json
NOTE: The "horizons" setting has been renamed to "autoSampleConditions".
Please rename it.
```
=> fix(perf-benchmarks): remove tachometer note when running perf

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/modules/attrs.ts, packages/@lwc/engine-core/src/framework/modules/computed-class-attr.ts, packages/@lwc/engine-core/src/framework/modules/computed-style-attr.ts, packages/@lwc/engine-core/src/framework/modules/events.ts, packages/@lwc/engine-core/src/framework/modules/props.ts, packages/@lwc/engine-core/src/framework/modules/static-class-attr.ts, packages/@lwc/engine-core/src/framework/modules/static-style-attr.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/shared/src/assert.ts, packages/integration-karma/test-hydration/mismatches/element-instead-of-textNode/index.spec.js, packages/integration-karma/test-hydration/mismatches/textNode-instead-of-element/index.spec.js
This PR is part of the larger refactor for [coupling the rehydration logic from the diffing logic](https://github.com/salesforce/lwc/pull/2608). 
It breaks apart the rehydration logic from the rendering logic. The new entry point for the hydration logic is now the `hydrateChildren` function. As a side effect, the rehydration logic can be completely tree-shaken if `hydrateComponent` is never imported by the application.
This PR also set the foundations for getting rid of the VNodes hooks. It adds a new `type` property that can be used to choose the appropriate diffing/hydration logic without relying on hooks.  
W-10409559
=> refactor(engine-core): Extract hydration from rendering logic

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-server/src/serializer.ts, packages/integration-karma/test-hydration/mismatches/empty-nodes/index.spec.js, packages/integration-karma/test-hydration/mismatches/empty-nodes/x/main/main.html, packages/integration-karma/test-hydration/mismatches/empty-nodes/x/main/main.js
This PR fixes an issue while hydrating an empty text expression (#2657 ).
Given a component with the following template:
```html
<template>
<p>{emptyText}</p>
</template>
```
SSR will generate an HTML like `<x-main><p></p></x-main>`, which when parsed by the browser, does not include a `TextNode` as child of `p`, however, our render mechanism will generate a `TextVNode` as child of the `p` vnode, which triggers a mismatch while hydrating.
This PR solves this issue by adding a zero-width non-joiner (ZWNJ) character on the server for empty TextNodes and taking this into account while hydrating, so we do not warn about a mismatch when hydrating the SSR content on the client.
Note: Another alternative could be to generate a `null` vnode on the client for empty text vnodes. I'm not too fond of …
=> fix(hydration): empty interpolated text mistmatch

packages/@lwc/compiler/src/transformers/__tests__/transform-javascript.spec.ts, packages/@lwc/compiler/src/transformers/javascript.ts
This reverts commit 30a8bd7f52f394995e431d60be3c936f1090bee1.
Revert the removal of object spread plugin. Temporary revert that enables the transpilation of the object spread operator until updates can be made to serve compat assets to legacy Edge browsers.
No
W-10129064
=> Revert "Remove object spread transpilation plugin (#2465)"

.nucleus.yaml
This has been failing since #2666, most likely due to the object spread change.
In their tests, you can see the failure is due to something called `_objectSpread`.
=> chore(nucleus): remove ui-interaction-explorer-components

.circleci/config.yml, .nucleus.yaml
Disables Circle CI publishing and enables Nucleus publishing. Based on my reading of the Nucleus docs (and looking at [other `.nucleus.yaml` implementations](https://github.com/search?l=YAML&q=filename%3A.nucleus.yaml+org%3Asalesforce&type=Code)), this should be correct.
Basically our workflow becomes:
- `release` branch represents the latest OSS release
- Open a PR on `master` with the version bump
- Merge it
- Open a PR to `release` from `master`
- Nucleus will auto-merge when the tests pass.
What this _doesn't_ do:
- Run code coverage in Nucleus (or publish it to Gus)
- Run Circle CI karma/integration tests in Nucleus
- Publish Slack notifications for releases
Those are all TODOs for a future PR.
* ✅ No, it does not introduce an …
=> chore(nucleus): use nucleus to publish

package.json, packages/perf-benchmarks/package.json, packages/perf-benchmarks/scripts/format-results.mjs, yarn.lock
I should have done this a while ago, but this changes `yarn test:performance` so that it outputs a nice Markdown table of the results. This is how I generate my screenshots of the perf results. (I use a markdown-to-excel converter, then I paste into a spreadsheet.)
I also fixed our eslint/prettier scripts to handle `.mjs` files since I noticed it wasn't doing that. (I'm not introducing the first `.mjs` file; there are others.)
The output looks like this (note that these results are just an example):
```
| Benchmark                                          | Before (low) | Before (high) | Before (avg) | After (low) | After (high) | After (avg) | Delta (low) | Delta (high) | Delta (avg) | Delta perc (low) | Delta perc (high) | Delta perc (avg) |
| …
```
=> chore(perf-benchmarks): print results in markdown table

packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_compat_config_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_css_resolver.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_relative.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_third_party.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_with_scoped_styles.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_ts_simple_app.js, packages/@lwc/style-compiler/src/__tests__/fixtures/grave-accents/expected.js, packages/@lwc/style-compiler/src/serialize.ts, packages/integration-karma/test/light-dom/multiple-templates/index.spec.js, packages/integration-karma/test/light-dom/multiple-templates/x/multiNoStyleInFirst/a.html, packages/integration-karma/test/light-dom/multiple-templates/x/multiNoStyleInFirst/b.html, packages/integration-karma/test/light-dom/multiple-templates/x/multiNoStyleInFirst/b.scoped.css, packages/integration-karma/test/light-dom/multiple-templates/x/multiNoStyleInFirst/multiNoStyleInFirst.js, packages/integration-karma/test/shadow-dom/multiple-templates/index.spec.js, packages/integration-karma/test/shadow-dom/multiple-templates/x/multiNoStyleInFirst/a.html, packages/integration-karma/test/shadow-dom/multiple-templates/x/multiNoStyleInFirst/b.css, packages/integration-karma/test/shadow-dom/multiple-templates/x/multiNoStyleInFirst/b.html, packages/integration-karma/test/shadow-dom/multiple-templates/x/multiNoStyleInFirst/multiNoStyleInFirst.js, packages/integration-karma/test/synthetic-shadow/dom-manual-sharing-nodes/index.spec.js, packages/integration-karma/test/synthetic-shadow/dom-manual-sharing-nodes/x/styled/styled.css, packages/integration-karma/test/synthetic-shadow/dom-manual-sharing-nodes/x/styled/styled.html, packages/integration-karma/test/synthetic-shadow/dom-manual-sharing-nodes/x/styled/styled.js, packages/integration-karma/test/synthetic-shadow/dom-manual-sharing-nodes/x/unstyled/unstyled.html, packages/integration-karma/test/synthetic-shadow/dom-manual-sharing-nodes/x/unstyled/unstyled.js
This is a small perf improvement for templates that have no stylesheet.
For such templates, we can avoid setting a `stylesheetToken` on the `tmpl` function altogether. This allows the runtime engine to avoid doing any of the normal synthetic shadow work for that component (adding the attribute, removing the attribute, setting `$shadowToken$` on the element).
The [perf benchmarks](https://docs.google.com/spreadsheets/d/19CxtGBs333jOG8sA2QHf0mGu_IEdUmxfquc7uJRdhww/edit?usp=sharing) are modestly improved:
I ran the test [twice](https://docs.google.com/spreadsheets/d/13ptIEB6ntPXtBYOjn0Ja2NcABQUo1G-Axg42PDh7128/edit?usp=sharing) and got the same results. 
To get an idea of how many templates have no stylesheets, I did an informal analysis of GUS using a conditional breakpoint:
And I found …
=> perf: only add scope token when stylesheets are present

packages/@lwc/engine-dom/src/apis/is-node-from-template.ts, packages/integration-karma/test/api/isNodeFromTemplate/index.spec.js
With the introduction of mixed shadow mode, it is now possible to have native roots exist alongside synthetic roots. The motivation for this change is that the current logic returns `false` for nodes in native roots because we look for shadow resolvers which do not exist for nodes shadowed by native roots. The proposed change adds an additional test to account for nodes shadowed by native roots.
It should be pointed out that manually inserted nodes inside a native root will now always return `true`, where it would previously return `true` when all roots were native (i.e., when `@lwc/synthetic-shadow` is not applied), and `false` when all roots were synthetic (i.e., when `@lwc/synthetic-shadow` is applied). The existing use case for manually inserted nodes within synthetic roots does not …
=> fix(engine-dom): add isNodeFromTemplate() support for native roots in mixed mode

packages/perf-benchmarks/scripts/build.js
These are basically the defaults I use whenever I'm running perf tests on my PRs; it seems silly not to just update them here.
The old defaults (especially `25%`) were based on thinking we were going to run Tachometer on every PR, so I wanted very conservative numbers so that the tests didn't spend a lot of time just to tell us there's a 0% difference. Nowadays we only use the perf tests on-demand, so it makes sense to make the defaults stricter.
=> chore(perf-benchmarks): tweak default constants

packages/@lwc/engine-core/src/framework/rendering.ts, packages/integration-karma/test/rendering/table-diffing/index.spec.js
Fixes #2680. As noted in https://github.com/salesforce/lwc/issues/2680#issuecomment-1030378111, for sorting large lists of elements, this clone operation may happen frequently, so we should probably try to limit the cloning, even if it makes the code a bit uglier.
[W-10540506](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000lFVTbYAO/view)
=> perf: only clone old children once

packages/@lwc/engine-dom/src/renderer.ts, packages/integration-karma/test/rendering/elements-are-not-recycled/index.spec.js
Chrome recently made `adoptedStyleSheets` mutable (see [this post](https://blog.chromium.org/2022/02/chrome-99-css-cascade-layers-new-picker.html) and https://github.com/WICG/construct-stylesheets/issues/45). The idea is that, instead of doing:
```js
shadowRoot.adoptedStyleSheets = [...adoptedStyleSheets, sheet]
```
...you can do:
```js
shadowRoot.adoptedStyleSheets.push(sheet)
```
In prior testing (https://github.com/WICG/construct-stylesheets/issues/94#issuecomment-832147900), I indeed found some overhead from cloning and re-assigning the array. This is actually why we don't use `adoptedStyleSheets` at the `document` level – it tends to have so many stylesheets that the perf cost of repeatedly cloning the array is too high.
Just to be sure, I wrote [a new …
=> perf(engine-dom): use adoptedStyleSheets.push

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts, packages/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/index.spec.js
Disables mixed shadow mode. Defaults to `false` as mixed shadow mode is enabled by default.
No
No
W-10699885
=> chore(features): DISABLE_MIXED_SHADOW_MODE

packages/@lwc/engine-dom/src/apis/build-custom-element-constructor.ts, packages/@lwc/engine-dom/src/apis/hydrate-component.ts, packages/integration-karma/helpers/test-hydrate.js, packages/integration-karma/scripts/karma-plugins/hydration-tests.js, packages/integration-karma/test-hydration/customElement-define/light-dom-mismatch/index.spec.js, packages/integration-karma/test-hydration/customElement-define/light-dom-mismatch/x/main/main.html, packages/integration-karma/test-hydration/customElement-define/light-dom-mismatch/x/main/main.js, packages/integration-karma/test-hydration/customElement-define/light-dom/index.spec.js, packages/integration-karma/test-hydration/customElement-define/light-dom/x/main/main.html, packages/integration-karma/test-hydration/customElement-define/light-dom/x/main/main.js, packages/integration-karma/test-hydration/customElement-define/simple/index.spec.js, packages/integration-karma/test-hydration/customElement-define/simple/x/main/main.html, packages/integration-karma/test-hydration/customElement-define/simple/x/main/main.js, packages/integration-karma/test-hydration/errors/already-hydrated-ce/index.spec.js, packages/integration-karma/test-hydration/errors/already-hydrated-ce/x/main/main.html, packages/integration-karma/test-hydration/errors/already-hydrated-ce/x/main/main.js, packages/integration-karma/test-hydration/errors/already-hydrated/index.spec.js, packages/integration-karma/test-hydration/errors/already-hydrated/x/main/main.html, packages/integration-karma/test-hydration/errors/already-hydrated/x/main/main.js
This PR implements the [`customElements.define`](https://github.com/salesforce/lwc-rfcs/blob/master/text/0117-ssr-rehydration.md#customelementsdefine) section of the [SSR Hydration RFC](https://github.com/salesforce/lwc-rfcs/blob/master/text/0117-ssr-rehydration.md).
It also changes the bailout mechanism for hydration: before this PR the bailout mechanism was to replace the element with the client rendered element (via `createElement`), in this PR, we replace the content of the element with the csr content.
=> feat(hydration): support hydration in customElements.define

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/vm.ts
This PR removes explicit usage of DOM apis within engine-core that were introduced with the hydration feature.
Note: The issue about `Node` and `Element` is still present, but we do have this issue in other places of `engine-core`.
=> refactor(hydration): remove explicit DOM api usages in engine-core

packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-key/outside-iterator/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-key/outside-iterator/metadata.json, packages/@lwc/template-compiler/src/parser/index.ts
Partially addresses #2697.
The idea is that if a template is like this:
```html
<template>
<x-foo key={myKey}></x-foo>
</template>
```
Then we should _not_ render it with `api_key`, but instead ignore the `key`.
**How we currently render it:**
```js
function tmpl($api, $cmp) {
const { k: api_key, c: api_custom_element } = $api;
return [
api_custom_element("x-foo", _xFoo, { key: api_key(0, $cmp.myKey) }),
];
}
```
**This PR:**
```js
function tmpl($api) {
const { c: api_custom_element } = $api;
return [api_custom_element("x-foo", _xFoo, { key: 0 })];
}
```
This PR also emits a warning if we find a `key` outside of an iteration.
Almost everyone using a `key` outside of an iteration is …
=> fix(template-compiler): omit api_key for key outside iteration

tsconfig.json
Currently, typescript is configured to error out whenever code contains unused bindings. While it's important to ensure we aren't shipping dead code to production, it is extremely annoying when refactoring code. It's is currently impossible to run unit and integration tests if the code contains unused locals. 
It should be safe to remove the `noUnusedLocal` flag since the eslint  [`no-unused-vars`](https://typescript-eslint.io/rules/no-unused-vars/) rule already protects us against this. 
=> chore: remove `noUnusedLocal` from `tsconfig.json`

packages/@lwc/engine-core/src/framework/secure-template.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/integration-karma/test/rendering/version-mismatch/index.spec.js
As it turns out, we cannot check for stylesheet version mismatches in `registerTemplate`, because it's called before the `tmpl.stylesheets` are set:
https://github.com/salesforce/lwc/blob/6e148383ca47ec047f5fba6d258fab7ba6865a15/packages/%40lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_simple_app_with_scoped_styles.js#L20-L24
Furthermore, a user can set stylesheets dynamically in the `render` function (https://github.com/salesforce/lwc-test/pull/147).
So the only place we can reliably check for mismatches is when the stylesheet is actually rendered. This PR does that.
Stylesheet mismatch errors will actually be logged now. (Assuming you have stylesheet mismatches, but not …
=> fix(engine-core): correctly check stylesheet mismatch

packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/renderer.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-dom/tsconfig.json, packages/@lwc/engine-dom/typings/constructableStyleSheets.d.ts
TypeScript doesn't have typings for constructed stylesheets (https://github.com/Microsoft/TypeScript/issues/30022), so I was hacking around it with `as any`. That's a code smell – let's just include the typings while we wait for TypeScript to add them.
=> refactor(engine-dom): improve typings for constructed stylesheets

packages/@lwc/engine-core/scripts/rollup.config.js, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/lwc/scripts/utils/rollup.js, scripts/rollup/lwcFeatures.js
Moves the `@lwc/features` Babel/Rollup plugin to its own file and skips running it on any unnecessary files.
This speeds up the total `yarn` build from 0m27.716s to 0m26.425s (**1.3s faster**) (median of 5 iterations).
I checked, and this doesn't really change the output `dist` files. The whitespace is a bit different because of Babel not running, but the `.min.js` files are the same so nothing really changed.
=> chore(engine-core): skip features plugin for unnecessary files

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/README.md, packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts, packages/integration-karma/test/light-dom/scoped-styles/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/scoped-ids/scoped-ids.spec.js, packages/integration-karma/test/mixed-shadow-mode/transitivity/index.spec.js
Changes the mixed shadow mode feature flag implementation to be disabled by default.
Yes, for any projects using this feature via the open source distribution since it was enabled by default in [v2.7.1](https://github.com/salesforce/lwc/releases/tag/v2.7.1). The feature must be enabled to continue using it ([documentation](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/features/README.md)).
W-10802779
=> chore: the mixed shadow mode feature flag should be disabled by default

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
This PR bumps `lwc` and its subpackages. This is a minor version bump.
Changes: [`v2.10.0..v2.11.0`](https://github.com/salesforce/lwc/compare/v2.10.0...version-bump-2.11.0)
* 🚨 Yes, it does introduce an observable change.
W-8283257
=> chore: bump to 2.11.0

packages/@lwc/engine-core/src/framework/component.ts, packages/integration-karma/test/component/default-export/index.spec.js, packages/integration-karma/test/component/default-export/x/component/component.html, packages/integration-karma/test/component/default-export/x/component/component.js, packages/integration-karma/test/component/default-export/x/component/nil.js, packages/integration-karma/test/component/default-export/x/component/string.js, packages/integration-karma/test/component/default-export/x/component/undef.js, packages/integration-karma/test/component/default-export/x/component/zero.js
Modules can export anything they want, including undefined and null. In those cases, our compiler automatically calls `registerComponent` on them.
Arguably we should not be calling `registerComponent` on those exports, but we do, so this PR fixes that case.
Export null/undefined will not throw an error now.
W-10814962
=> fix: module exports default undefined/null/etc

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
This PR bumps `lwc` and its subpackages. This is a minor version bump.
Changes: [`v2.11.0..v2.11.1`](https://github.com/salesforce/lwc/compare/v2.11.0...version-bump-2.11.1)
* 🚨 Yes, it does introduce an observable change.
W-8283257
=> chore: bump to v2.11.1

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
This PR bumps `lwc` and its subpackages. This is a patch version bump.
Changes: [`v2.11.1..v2.11.2`](https://github.com/salesforce/lwc/compare/v2.11.1...version-bump-2.11.2)
W-7258582
=> chore: bump version to v2.11.2

packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-native-styled-component-create-10k-same.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-native-styled-component-create-1k-different.benchmark.js
In #2723 we disabled mixed mode by default, but we forgot to re-enable the flag for these perf tests, which are designed to test native-shadow-in-mixed-mode. (The flag was removed from the tests in #2611.)
=> test(perf-benchmarks): set shadow mixed mode flag

.circleci/config.yml
Fixes #2742. Purely a Circle CI config change.
[W-10850221](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000sz59MYAQ/view)
=> chore: update to next-gen CircleCI image

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
This PR bumps `lwc` and its subpackages. This is a patch version bump.
Changes: [`v2.11.2..v2.11.3`](https://github.com/salesforce/lwc/compare/v2.11.2...version-bump-2.11.3)
W-7258582
=> chore: bump version to v2.11.3

package.json, yarn.lock
[iltorb](https://www.npmjs.com/package/iltorb) is a package used by [bundlesize](https://www.npmjs.com/package/bundlesize) which is a native dependency. It causes `yarn install` to be slower (due to the extra C++ build step), and is currently causing our build to fail entirely in Nucleus.
We do not actually need `iltorb`, because we are only checking the `gzip` size:
https://github.com/salesforce/lwc/blob/674f76afbca9b612ea8319e3a90522c4f326411c/scripts/bundlesize/bundlesize.config.json#L3-L17
This PR replaces `iltorb` with a no-op. It is still safe to run `bundlesize` this way.
=> chore(deps): remove iltorb

package.json, packages/lwc/scripts/utils/child_worker.js, packages/lwc/scripts/utils/generate_targets.js, packages/lwc/scripts/utils/rollup.js, yarn.lock
- Switches from [worker-farm](https://www.npmjs.com/package/worker-farm) to [workerpool](https://www.npmjs.com/package/workerpool), using Node Workers instead of processes.
- Switches from [rollup-plugin-terser](https://npmjs.com/package/rollup-plugin-terser) to vanilla [terser](https://www.npmjs.com/package/terser).
This improves the build time for the `lwc` package from 8.980s to 7.780s (1.2s improvement, median of 5 runs).
The main benefit comes from directly running `terser` rather than `rollup-plugin-terser`. The problem with `rollup-plugin-terser` is that it has [its own worker logic](https://github.com/TrySound/rollup-plugin-terser/blob/6b50b7fadbe8812d13452def82c36133f58581fd/rollup-plugin-terser.js#L22-L24) that cannot be disabled. This worker logic is unnecessary, because we are …
=> chore(build): use workerpool and vanilla terser

.gitignore, CONTRIBUTING.md, package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/scripts/rollup.config.js, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-dom/scripts/rollup.config.js, packages/@lwc/engine-server/package.json, packages/@lwc/engine-server/scripts/rollup.config.js, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/features/scripts/rollup/rollup.config.js, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/shared/scripts/rollup/rollup.config.js, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/@lwc/wire-service/scripts/rollup/rollup.config.js, packages/lwc/package.json, packages/lwc/scripts/build.js, packages/lwc/scripts/utils/child_worker.js, packages/lwc/scripts/utils/generate_targets.js, packages/lwc/scripts/utils/rollup_watch.js, scripts/rollup/typescript.js
Rather than running `yarn build` to recompile (which takes 23s on my machine), we can run `yarn dev`, which starts a watcher in every package and rebuilds incrementally when the files change.
Testing locally, I can make a change to `@lwc/shared` and the changes propagate out to `lwc` in a few seconds.
This makes local testing much more pleasant (e.g. for testing in Karma).
=> chore(build): add dev mode

scripts/jest/root.config.js
I noticed some test failures in Nucleus due to exceeding Jest's default timeout of 5000ms.
Rather than have random test failures, let's bump it up higher. 🙂 
```
FAIL rollup-plugin-lwc-compiler packages/@lwc/rollup-plugin/src/__tests__/integrations/integrations.spec.ts (25.916 s)
● integration › compat › should be compatible with compat plugin
thrown: "Exceeded timeout of 5000 ms for a test.
Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."
31 |
32 |     describe('compat', () => {
> 33 |         it('should be compatible with compat plugin', async () => {
|         ^
34 |             const bundle = await rollup({
35 |                 input: path.resolve(__dirname, 'fixtures/javascript/javascript.js'),
36 |                 plugins: [lwc(), …
```
=> test: increase jest test timeout

.git2gus/config.json
Make 249 the default build for git2gus workflow
=> chore: update git2gus default build for clco

.nucleus.yaml
Add 238/patch code line and remove 234/patch from nucleus config
=> chore: update nucleus config to add summer22 and remove winter22

package.json, yarn.lock
=> chore: remove @babel/preset-typescript dep

packages/integration-karma/scripts/karma-plugins/lwc.js
The Node event emitter listener limit is 10. We are adding 228 due to running Rollup simultaneously on 228 files here:
https://github.com/salesforce/lwc/blob/7589da0ab0608ca440f4d08b0d8e714d72574317/packages/integration-karma/scripts/karma-plugins/lwc.js#L64
Rollup adds the listener [here](https://github.com/rollup/rollup/blob/35cbfae/src/utils/hookActions.ts#L37).
This causes the warning:
(node:52671) MaxListenersExceededWarning: Possible EventEmitter memory leak detected.
11 beforeExit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
Bumping the limit is harmless, and avoids an annoying warning message when running the Karma tests.
=> test: fix Node warning about event emitters

.circleci/config.yml
This PR makes the karma and integration jobs run in parallel. The build time went down from 13m to 9m.
Observations:
**Karma Tests**
1. Running `yarn test` locally takes <15s but it runs the tests in 1 browser. `yarn sauce` typically runs in 3 browsers and takes about 45s.
1. The time to bundle the test files using rollout is about 5s locally. On circleci, this time goes up 9s. It processes 229 spec.js files.
2. Karma executes the tests simultaneously in selected browsers.
2. Sauce accounts provided to dev team has a high concurrency limit(1520).
**Integration tests** 
1. Time spent in bundling is about 2 seconds locally. It processes 58 spec.js files.
2. Total execution of this time is about 4m in non-compat, 6m in compat mode.
3. Unlike karma, wdio spins up a new sauce session per spec. …
=> chore: run karma and integration tests in parallel

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/throws-if-using-default-import-on-lwc/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/throws-if-using-default-import-on-lwc/error.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/throws-if-using-namespace-import-on-lwc/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/throws-if-using-namespace-import-on-lwc/error.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/throws-when-a-non-supported-lwc-api-is-imported/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/throws-when-a-non-supported-lwc-api-is-imported/error.json, packages/@lwc/babel-plugin-component/src/constants.js, packages/@lwc/babel-plugin-component/src/index.js, packages/@lwc/babel-plugin-component/src/utils.js, packages/@lwc/errors/src/compiler/error-info/lwc-class.ts
Fixes: https://github.com/salesforce/lwc/issues/1284
Removes `import ... from 'lwc'` validations from `@lwc/babel-plugin-component`.
This cannot be merged until https://github.com/salesforce/eslint-plugin-lwc/pull/85 is shipped and running in core.
W-10151021
=> fix(babel-plugin-component): remove import validation

packages/integration-tests/src/components/events/test-mouseover/integration/mouseover.spec.js
This test flaps a lot. (E.g. [this run](https://app.circleci.com/pipelines/github/salesforce/lwc/5858/workflows/75b0b5dc-8772-40d5-9279-a085b9f3d206/jobs/43144) and [this run](https://app.circleci.com/pipelines/github/salesforce/lwc/5858/workflows/096029e8-34c5-435f-91ff-e6e16ef0de5a/jobs/43097).)
The original goal of the test was to test `elementsFromPoints()` and how it interacts with ChromeDriver (#2495). So it's kind of pointless to run this test in IE anyway. Let's just disable it.
=> test: remove flakey IE integration test

packages/integration-karma/test/act/index.spec.js, packages/integration-karma/test/api/isNodeFromTemplate/index.spec.js, packages/integration-karma/test/api/registerTemplate/index.spec.js, packages/integration-karma/test/component/LightningElement.render/index.spec.js, packages/integration-karma/test/rendering/version-mismatch/index.spec.js, packages/integration-karma/test/services/hooks/index.spec.js, packages/integration-karma/test/swapping/components/index.spec.js, packages/integration-karma/test/swapping/styles/index.spec.js, packages/integration-karma/test/swapping/templates/index.spec.js
This PR is a follow-up of #2719. It updates all the tests to use import restricted APIs from `lwc`.
=> test: Update tests to use `lwc` restricted imports

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Upgrade LWC package versions to `2.13.1`.
=> chore: bump version to v2.13.1

.nucleus.yaml
This downstream has failed several of the recent builds. Doesn't appear to be an intermittent issue – looks like their build has a true failure in Nucleus. Let's remove it.
=> chore(nucleus): remove salesforcedevs/developer-website

packages/integration-karma/README.md, packages/integration-karma/package.json, packages/integration-karma/scripts/karma-configs/hydration/base.js, packages/integration-karma/scripts/karma-configs/test/base.js, packages/integration-karma/scripts/karma-plugins/lwc.js
- Remove Node warning in hydration tests
- Fix README to have proper instructions for hydration tests
- Use Chrome headless when running locally on the CLI (not debug mode)
The reason for Chrome headless is so it doesn't steal your mouse when you run `yarn test` or `yarn test:hydration`. When running `yarn start` or `yarn hydration:start` you will still get headful Chrome.
=> test(integration-karma): small quality-of-life improvements

packages/@lwc/engine-core/src/framework/vm.ts
to avoid mixing native and synthetic shadows, a recursion was used to find the nearest owner with a shadow attached. This PR simplifies that process by doing some extra bookkeeping on the value of shadow mode, so no recursion is needed.
=> refactor(engine): optimize computation of transitive shadow mode

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Patch release for the following changes https://github.com/salesforce/lwc/compare/v2.13.1...b75b48ff5912ba7f0d893140bcb18c1711453688
=> chore: bump version to v2.13.2

.circleci/config.yml, packages/integration-karma/test/host-element/index.spec.js
Retries Circle CI karma/integration tests until they pass.
W-10946477
=> chore: retry failed Circle CI tests

packages/@lwc/engine-core/src/framework/secure-template.ts, packages/integration-karma/test/rendering/legacy-stylesheet-api/index.spec.js, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/inspectStylesheets/inspectStylesheets.js, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/inspectStylesheets/withStylesheet.css, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/inspectStylesheets/withStylesheet.html, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/inspectStylesheets/withoutStylesheet.html, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/patchesStylesheet/patchesStylesheet.js, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/patchesStylesheet/withStylesheet.css, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/patchesStylesheet/withStylesheet.html, packages/integration-karma/test/rendering/legacy-stylesheet-api/x/patchesStylesheet/withoutStylesheet.html
Adds a shim for the old `stylesheetTokens` internal API on top of the new `stylesheetToken` API. Neither one should be used by component authors (since they are internal and undocumented), but they are used in the wild, so this unbreaks anyone who is using the old API.
Related:
- https://github.com/salesforce/lwc/pull/2332
- https://github.com/salesforce/lwc/pull/2670
If you were setting the `stylesheetTokens` on a template by copying it from one template to the other, it broke due to https://github.com/salesforce/lwc/pull/2332 and https://github.com/salesforce/lwc/pull/2670. With this PR, it works like before.
W-11093934
=> fix(engine-core): add shim for old stylesheetTokens internal API

.nucleus.yaml, lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
The summer22 branch's Nucleus configuration is messed up, so it published to `latest` instead of the `summer22` npm dist tag.
(The latest should actually be 2.13.3.)
This fixes it.
=> chore(nucleus): add summer 22 tag

packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/invalid-id/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/static-id-in-iteration/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/static-id-in-iteration/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/static-id-in-iteration/metadata.json
Backport of https://github.com/salesforce/lwc/pull/2831
=> fix: relax static id validation in iterations

packages/@lwc/compiler/README.md, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/compiler/src/transformers/transformer.ts, packages/@lwc/rollup-plugin/package.json, packages/@lwc/rollup-plugin/src/__tests__/warnings/fixtures/test/test.html, packages/@lwc/rollup-plugin/src/__tests__/warnings/fixtures/test/test.js, packages/@lwc/rollup-plugin/src/__tests__/warnings/warnings.spec.ts, packages/@lwc/rollup-plugin/src/index.ts
Fixes #2771
Propagates template compiler warnings from `@lwc/compiler` to `@lwc/rollup-plugin`, where it is logged using the [standard Rollup `this.warn()` method](https://rollupjs.org/guide/en/#thiswarn) as a [RollupWarning](https://github.com/rollup/rollup/blob/619563871dd73d64b3670c01c410ba9f882b723c/src/rollup/types.d.ts#L9-L22).
Here is what a warning looks like when running `rollup` in the console ([source](https://github.com/nolanlawson/lwc-barebone/commit/b2b7007fe5c89d28449ff61ed73554dee67bf9a3):
```
(!) Plugin rollup-plugin-lwc-compiler: @lwc/rollup-plugin: LWC1148: Invalid HTML syntax: end-tag-without-matching-open-element. This will not be supported in future versions of LWC. For more information, please visit https://html.spec.whatwg.org/multipage/parsing.html#parse-error-end- …
```
=> fix(rollup-plugin): emit warnings during compilation

packages/@lwc/engine-dom/src/styles.ts
I couldn't resist fixing some of the perf regressions introduced in #2827. This refactors the stylesheet cache to avoid making a lot of lookups, which provides some perf wins:
=> perf(engine-dom): refactor style cache to reduce lookups

packages/@lwc/engine-core/src/testFeatureFlag.ts, packages/@lwc/engine-dom/src/testFeatureFlag.ts, packages/@lwc/synthetic-shadow/src/testFeatureFlag.ts
After clicking the merge button on #2812, I realized that the new test code can be tweaked to only run in Karma. This will avoid everyday users seeing a weird `test-dummy-flag` event added to the `window`, even in dev mode.
=> test: run feature flag test code only in karma

packages/@lwc/engine-core/src/framework/rendering.ts, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/HTMLSlotElement.slotchange.spec.js, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/x/child/child.html, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/x/child/child.js
In native shadow and earlier synethic shadow, `slotchange` event fires when a slot is removed because its children are removed first and then the slot is removed. This PR reintroduces that behavior for synthetic shadow.
But it's fixing something that broke earlier.
=> fix: trigger slotchange event on removing slot

packages/integration-karma/scripts/karma-plugins/hydration-tests.js, packages/integration-karma/scripts/karma-plugins/lwc.js
Since #2833 was merged, we now have annoying warning messages in the console when we run the integration tests. This fixes that. We don't need to be notified of our own warnings.
=> test(integration-karma): silence lwc rollup plugin warnings

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
The earlier v2.13.4 had a compiler change and is not triggering downstream dependencies to update snapshots etc. Releasing a major version with those changes.
=> chore: release v2.14.0

packages/@lwc/engine-core/src/framework/rendering.ts
Follow-up to #2840.
I'm not sure if this change is really worth making, but it seems nice to call out here that `removeChildren` is only necessary for synthetic shadow. Maybe this will make it easier to remove in the future when synthetic shadow is gone? Or if we do an "LWC lite" build?
If not, I'd also be happy just to add a code comment that this is only needed for synthetic.
=> fix: only remove slot children in synthetic shadow

packages/@lwc/engine-core/src/framework/check-version-mismatch.ts
Similar to https://github.com/salesforce/lwc/commit/7e9c5d21a70867fd9a0583759259e4d9fb6ede76, if we're going to be adding globals to the `window` object for our Karma tests, we should check if we're actually in a Karma environment first.
I realized this was broken because it actually breaks `@lwc/engine-server` if you run it with `NODE_ENV=development`. 🤦  (Node doesn't have a `window` object.)
The thing that was broken is no longer broken.
=> fix: only add version mismatch test code in karma

packages/integration-karma/test/rendering/stylesheets/index.spec.js, packages/integration-karma/test/rendering/stylesheets/x/component/component.css, packages/integration-karma/test/rendering/stylesheets/x/component/component.html, packages/integration-karma/test/rendering/stylesheets/x/component/component.js, packages/integration-karma/test/rendering/stylesheets/x/identicalComponent/identicalComponent.css, packages/integration-karma/test/rendering/stylesheets/x/identicalComponent/identicalComponent.html, packages/integration-karma/test/rendering/stylesheets/x/identicalComponent/identicalComponent.js, packages/integration-karma/test/rendering/stylesheets/x/shared.css, packages/integration-karma/test/rendering/stylesheets/x/sharing1/sharing1.css, packages/integration-karma/test/rendering/stylesheets/x/sharing1/sharing1.html, packages/integration-karma/test/rendering/stylesheets/x/sharing1/sharing1.js, packages/integration-karma/test/rendering/stylesheets/x/sharing2/sharing2.css, packages/integration-karma/test/rendering/stylesheets/x/sharing2/sharing2.html, packages/integration-karma/test/rendering/stylesheets/x/sharing2/sharing2.js
To get the full perf benefit of constructable stylesheets, we should be reusing the same instance of the `CSSStyleSheet` object for identical stylesheets, rather than re-creating them. But this is easy to regress, so I realized we should probably have a test for it.
=> test(integration-karma): ensure constructable stylesheets are re-used

.nucleus.yaml
Another Nucleus downstream is [failing](https://nucleus.uipengsys-public.buildndeliver-s.aws-esvc1-useast2.aws.sfdc.cl/workflows/69603#job=207194&step=node-install-patched) for reasons outside of our control.
=> chore(nucleus): remove another downstream

packages/integration-karma/test/act/act-components/test-attrs.js, packages/integration-karma/test/act/act-components/test-body-slot.js, packages/integration-karma/test/act/act-components/test-class-attr.js, packages/integration-karma/test/act/act-components/test-conditional-false-attribute.js, packages/integration-karma/test/act/act-components/test-conditional-true-attribute.js, packages/integration-karma/test/act/act-components/test-empty-slot-element-creation.js, packages/integration-karma/test/act/act-components/test-empty-slot.js, packages/integration-karma/test/act/act-components/test-html-tags.js, packages/integration-karma/test/act/act-components/test-multiple-children-in-slot.js, packages/integration-karma/test/act/act-components/test-multiple-slots.js, packages/integration-karma/test/act/act-components/test-nested-html-tags.js, packages/integration-karma/test/act/act-components/test-property-reference.js, packages/integration-karma/test/act/act-components/test-props.js, packages/integration-karma/test/act/act-components/test-slot-adjacent-to-named-slot.js, packages/integration-karma/test/act/act-components/test-slot-element-creation-with-duplicate-slot-names.js, packages/integration-karma/test/act/act-components/test-slot-in-grandchild.js, packages/integration-karma/test/act/act-components/test-style-attr.js, packages/integration-karma/test/act/index.spec.js
This is a follow-up to #2825. It updates the ACT components in our tests to match the change made in Swarm review 36608144.
W-11013609
=> test(integration-karma): update ACT components

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: release v2.14.1

packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentAnyChildAny/grandparentAnyParentAnyChildAny.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentAnyChildAny/grandparentAnyParentAnyChildAny.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentAnyChildReset/grandparentAnyParentAnyChildReset.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentAnyChildReset/grandparentAnyParentAnyChildReset.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentResetChildAny/grandparentAnyParentResetChildAny.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentResetChildAny/grandparentAnyParentResetChildAny.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentResetChildReset/grandparentAnyParentResetChildReset.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentResetChildReset/grandparentAnyParentResetChildReset.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentAnyChildAny/grandparentResetParentAnyChildAny.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentAnyChildAny/grandparentResetParentAnyChildAny.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentAnyChildReset/grandparentResetParentAnyChildReset.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentAnyChildReset/grandparentResetParentAnyChildReset.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentResetChildAny/grandparentResetParentResetChildAny.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentResetChildAny/grandparentResetParentResetChildAny.js, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentResetChildReset/grandparentResetParentResetChildReset.html, packages/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentResetParentResetChildReset/grandparentResetParentResetChildReset.js
Follow-up to #2859. This adds more tests to ensure that transitive `shadowMode` calculation is working correctly.
I generated these tests using a small script; I did not write these by hand. 🙂 
I had previously considered adding some slot tests too, but that seemed a bit overkill, especially since the slot doesn't affect ownership; whoever is doing the slotting is the owner for the purposes of transitivity calculation.
=> test(integration-karma): more shadow transitivity tests

packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-server/src/__tests__/fixtures/light-dom-multiple/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/light-dom-scoped-styles/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/child/child.css, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/parent/parent.css, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/styles-shared/modules/x/shared.css
This is a stop-gap solution to #2851.
When we render components with shared stylesheets, the browser can optimize those stylesheets under the hood if the `<style>`s are byte-for-byte identical. (I don't have a benchmark handy, but just trust me that browsers do this. 🙂)
```css
/* component.css */
@import './shared.css';
h1 { color: red }
```
Right now we concatenate a component's styles into a single `<style>`, including any shared stylesheets. So the browser cannot optimize, because the duplicated styles are embedded inside of separate `<style>`s that are not byte-for-byte identical.
This PR optimizes the engine so that it emits separate `<style>`s instead. The ordering is maintained, so that effectively you end up with the same styles being applied.
* ✅ No, it does not introduce a …
=> perf(engine-core): render separate style tags

packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/__tests__/transform-html.spec.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/template-compiler/src/index.ts
[W-11254381](https://gus.lightning.force.com/a07EE00000ydqfmYAA)
=> feat(compiler): add compiler option to specify custom renderer config

package.json, packages/@lwc/compiler/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/style-compiler/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, yarn.lock
Our regularly-scheduled dependency version bump.
Breaking changes that don't affect us:
- [karma-jasmine v5](https://github.com/karma-runner/karma-jasmine/releases/tag/v5.0.0) – Node/karma/jasmine-core required version bumps.
- [lerna v5](https://github.com/karma-runner/karma-jasmine/releases/tag/v5.0.0) – Node version bump, some very subtle timing thing that I don't think affects us
- [lint-staged v13](https://github.com/okonet/lint-staged/releases/tag/v13.0.0) – Node version bump
Unfortunately we can't update parse5 to [v7](https://github.com/inikulin/parse5/releases/tag/v7.0.0) because it switched to ESM. We'll have to switch to ESM ourselves to update.
=> chore: update dependencies

packages/@lwc/compiler/src/transformers/template.ts, packages/integration-karma/test/shadow-dom/invalid-char-in-namespace/index.spec.js, packages/integration-karma/test/shadow-dom/invalid-char-in-namespace/x#y/component/component.css, packages/integration-karma/test/shadow-dom/invalid-char-in-namespace/x#y/component/component.html, packages/integration-karma/test/shadow-dom/invalid-char-in-namespace/x#y/component/component.js
When using LWR, the module provider expands "&#35;namespace" to the component name to be loaded. &#35; is not a valid character, which causes error as "Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': 'color-purple_purple#purple-host' is not a valid attribute name". The fix escapes &#35; with &#95;&#95;&#95;hash___. 
=> fix(compiler): escape invalid CSS character # for scope token

packages/@lwc/integration-karma/package.json, yarn.lock
This fixes a yarn warning about Jasmine:
warning Resolution field "jasmine-core@3.10.1" is incompatible with requested version "jasmine-core@^4.1.0"
As well as [a GitHub security warning](https://github.com/salesforce/lwc/security/dependabot/19) about `got`.
=> chore: fix dependency warnings

packages/@lwc/style-compiler/src/__tests__/fixtures/var-nested-with-resolver-and-color-name/actual.css, packages/@lwc/style-compiler/src/__tests__/fixtures/var-nested-with-resolver-and-color-name/config.json, packages/@lwc/style-compiler/src/__tests__/fixtures/var-nested-with-resolver-and-color-name/expected.js, packages/@lwc/style-compiler/src/__tests__/fixtures/var-nested-with-resolver/actual.css, packages/@lwc/style-compiler/src/__tests__/fixtures/var-nested-with-resolver/config.json, packages/@lwc/style-compiler/src/__tests__/fixtures/var-nested-with-resolver/expected.js, packages/@lwc/style-compiler/src/serialize.ts
Previously, when using a custom `var` resolver, `var(foo, bar) 0 0 3px` would be compiled incorrectly by omitting a `+` between the resolved value of `var(foo, bar)` and the `0 0 3px` that followed. A complete example can be found in the test fixture that's added in the PR.
Fixes W-11159171.
=> fix: text + expression concatenation in style-compiler with custom resolver

packages/@lwc/integration-karma/test/static-content/index.spec.js, packages/@lwc/integration-karma/test/static-content/x/escape/escape.html, packages/@lwc/integration-karma/test/static-content/x/escape/escape.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-escaping/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/class-attr-escaping/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/template-string-escape/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/template-string-escape/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/template-string-escape/metadata.json, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts
This PR addresses the string escaping issue when some static content uses the backtick "`" or dollar + open curly "${".
----
**Side note:** The current `serializeStaticElement` implementation is incorrect. This function returns the template string literal content as a string. This template string literal content is composed of a mix of template elements and JavaScript expressions. This string content is [then passed](https://github.com/salesforce/lwc/blob/34c08b0cd4be072cc54a10560f9d1c365cec074a/packages/@lwc/template-compiler/src/codegen/codegen.ts#L448-L460) to the `t.templateLiteral` factory function to create an AST node. This part is incorrect.
The `serializeStaticElement` should generate independent AST nodes for each part of the template literal. This happens to work today because …
=> fix(template-compiler): static content template string escaping

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts, packages/@lwc/engine-server/src/__tests__/fixtures/svgs/expected.html, packages/@lwc/engine-server/src/apis/render-component.ts, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/engine-server/src/serializer.ts, packages/@lwc/engine-server/src/types.ts, packages/@lwc/shared/src/void-elements.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/stranded-open-svg-ellipse/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/svg-within-div/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/svg-within-g/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/svg/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/filter/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/linear-gradient/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/simple-svg/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/stranded-open-path/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/valid-image/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/valid-svg/expected.js, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts, packages/@lwc/template-compiler/src/parser/constants.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/parser/utils/html-elements.ts, packages/@lwc/template-compiler/src/shared/ast.ts, packages/@lwc/template-compiler/src/shared/types.ts
This PR contains the changes I think are worth integrating into https://github.com/salesforce/lwc/pull/2898:
- Update `isVoidElement` function signature to accept a namespace. This avoids having to check if the element originates from the correct namespace.
- Update template compiler and engine serialization logic to account for void HTML elements and self-closing foreign elements.
- Remove `HTML_VOID_ELEMENTS` from `KNOWN_HTML_AND_SVG_ELEMENTS` since this set already contains all the void elements.
- Remove now unused `VOID_ELEMENT_SET`. 
> **Note**: The `KNOWN_HTML_AND_SVG_ELEMENTS` should be unnecessary because we already have `SUPPORTED_SVG_TAGS` set. Theoretically, we should revert it back to `KNOWN_HTML_ELEMENTS`, however, after experimenting with it, it might have other impacts on …
=> fix(template-compiler): Produce proper void and self closing elements

.nucleus.yaml
Can't think of a better solution for now. Need to add `lwc-platform-public` eventually instead of `lwc-platform`.
=> chore(nucleus): temporarily remove lwc-platform from downstreams

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json
Apparently I can never remember that a template compiler change should be a minor version bump. `v2.19.2` was a mistake; it should be `v2.20.0` instead.
I propose we just don't release `v2.19.2` to the `release` branch.
=> chore: release v2.20.0

packages/@lwc/perf-benchmarks/scripts/build.js
Unfortunately in https://github.com/salesforce/lwc/pull/2896 I missed this path change, so the `yarn build:performance` script broke. This unbreaks it.
=> chore(perf-benchmarks): fix build script

packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/x/withChildElms/withChildElms.html, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/x/withChildElms/withChildElms.js
This resolves [W-11233285](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00000yKKx8YAG/view).
The issue occurs when a top-level `<x-app>` tag is in the DOM before `customElements.define` is called, using that pre-existing tag as the mount point for the application. That looks something like this:
```html
<!DOCTYPE html>
<html>
<body>
<x-app></x-app>
<script src="dist/main.js"></script>
</body>
</html>
```
with entry-point JS like this:
```javascript
import App from "x/app";
customElements.define("x-app", App.CustomElementConstructor);
```
The usage here is not incorrect, but diverges from the LWC-recommended pattern of `createElement("x-app", { is: App })`. Issues arise from this in LWC due to the incorrect belief that `element.shadowRoot` would always be non-null in …
=> fix: implicit hydration with pre-existing elms in DOM

.eslintignore, .eslintrc, .github/ISSUE_TEMPLATE/Bug_report.md, .gitignore, package.json, playground/.gitignore, playground/.vscode/settings.json, playground/README.md, playground/index.html, playground/lwc.config.json, playground/package.json, playground/rollup.config.js, playground/src/main.js, playground/src/modules/x/app/app.html, playground/src/modules/x/app/app.js, playground/src/modules/x/counter/counter.html, playground/src/modules/x/counter/counter.js, scripts/tasks/check-license-headers.js, yarn.lock
Add a new `playground` project to this repo. The playground project contains a minimal LWC setup to experiment and reproduce bugs. Keeping this project within the monorepo ensures that the LWC version is always in sync with the latest version available.
This project can be previewed using Stackblitz: https://playground.lwc.dev
=> feat: Add playground in LWC repo

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Version bump to v2.20.4
Prevents component authors from overwriting internal props of HostElement in SSR. Authors should be able to now use those properties in their components as public props with no conflict.
W-11369322
=> chore: release v2.20.4 @W-11369322

.nucleus.yaml
Update Nucleus required downstreams based on an updated [flappiness analysis](https://salesforce.quip.com/RbQhA8P7ImzK).
Some of these may start flapping in the future, but we can remove them if that happens.
W-11254165
=> chore(nucleus): refresh downstreams based on flappiness

packages/@lwc/engine-core/src/framework/rendering.ts
This PR removes consolidate duplicate logic in the LWC core rendering algo:
- Remove `fallbackElmHook` which is a grab bag of unrelated code. 
- Abstract logic `patchElementWithRestrictions` to `applyElementRestrictions`.
- Consolidate style scoping logic (synthetic shadow DOM and scoped styles) inside `applyStyleScoping`. 
=> refactor(engine-core): Remove duplicated code in diffing algo

packages/@lwc/template-compiler/src/shared/types.ts
While investigating a bug related to location information endTag, it was noticed that this field is always present. Updating TS definition to reflect that.
=> fix: make ElementSourceLocation.endTag a required field

playground/jsconfig.json
Fixes this issue:
I tried `tsconfig` and workspace settings based on [this SO question](https://stackoverflow.com/questions/38271273/experimental-decorators-warning-in-typescript-compilation), but `jsconfig.json` was the only thing I found that worked.
=> chore(playground): remove decorator warning

.nucleus.yaml
See [this thread](https://salesforce-internal.slack.com/archives/G0213GSKXA6/p1659120221912479) for context. We hit a flapper, also it doesn't make much sense for this downstream to be there.
=> chore(nucleus): remove locker

packages/@lwc/engine-core/src/framework/accessor-reactive-observer.ts, packages/@lwc/engine-core/src/framework/base-bridge-element.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/component.ts, packages/@lwc/engine-core/src/framework/decorators/api.ts, packages/@lwc/engine-core/src/framework/decorators/track.ts, packages/@lwc/engine-core/src/framework/membrane.ts, packages/@lwc/engine-core/src/framework/mutation-tracker.ts, packages/@lwc/engine-core/src/framework/readonly.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/@lwc/engine-core/src/libs/mutation-tracker/index.ts, packages/@lwc/engine-dom/scripts/rollup.config.js, packages/@lwc/engine-server/scripts/rollup.config.js, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-prop/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-prop/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-prop/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-prop/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-prop/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-prop/modules/x/parent/parent.js
Removes reactivity (`observable-membrane`, `ReactiveObserver`) from `@lwc/engine-server`. Reactivity is not needed server-side.
The bundle size for `engine-server.js` drops from 246 kB to 218 kB (**27.8kB / 11.3% reduction**).
Performance in the `engine-server` Tachometer benchmarks improves **13%-18%**:
**Technically** this would be a breaking change if any consumer were directly using `@lwc/engine-core`. They would need to know to transform `process.env.IS_BROWSER`. But I'm certain we don't have any consumers who are doing that.
=> perf(engine-server): disable reactivity in SSR

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/export-engine-star/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/export-engine-star/expected.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/import-engine-default-and-named/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/import-engine-default-and-named/expected.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/import-engine-default/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/import-engine-default/expected.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/import-engine-star/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/import-engine-star/expected.js, packages/@lwc/babel-plugin-component/src/utils.js
Currently the Babel plugin will throw an error at this line if the code it's processing tries to import the default or `*` from the `"lwc"` package:
https://github.com/salesforce/lwc/blob/03491dcf775021f3ba42cc49431238947f6504a7/packages/%40lwc/babel-plugin-component/src/utils.js#L60
The reason is that `specifier.get('imported').node` is undefined.
This PR fixes that. It doesn't attempt to surface any errors for `import lwc from 'lwc'` or `import * as lwc from 'lwc'` since that's already handled by `eslint-plugin-lwc`. The goal is just to avoid an unhandled exception.
=> fix(babel-plugin-component): default/star imports should not throw

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/apis/hydrate-component.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts
Rebased and slightly-tweaked version of #2806. I only wrote it because I forgot that that PR existed.
Based on what I've seen with pivots (#2724), we don't need `isHydrating` anymore, and in fact it breaks some tests in that PR if I don't remove it.
=> refactor(engine): remove isHydrating global flag

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts
Now that we have `process.env.IS_BROWSER` (via #2961), we can use that instead of `renderer.ssr`. It's strictly better, because it will cause SSR-only/browser-only code to get tree-shaken when building `engine-dom`/`engine-server`. Also Locker does not need to intercept `renderer.ssr`.
=> refactor(engine): remove ssr global flag

packages/@lwc/integration-karma/test/component/observed-attributes/index.spec.js, packages/@lwc/integration-karma/test/component/observed-attributes/x/observes/observes.js
Adds a karma test to confirm the behavior described in https://github.com/salesforce/lwc/issues/2972.
=> test: add test to confirm observedAttributes behavior

packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-extra-class-from-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-extra-class-from-client/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-extra-class-from-client/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-extra-class-from-server/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-extra-class-from-server/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-extra-class-from-server/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-same-different-order/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-same-different-order/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/static-unoptimized-same-different-order/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-different-priority/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-different-priority/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-different-priority/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-extra-from-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-extra-from-client/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-extra-from-client/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-extra-from-server/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-extra-from-server/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-extra-from-server/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same-different-order/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same-different-order/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same-different-order/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same-priority/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same-priority/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same-priority/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static-unoptimized-same/x/main/main.js
Partially addresses #2817. Improves test coverage from 84.88% to 85.49% (lines).
This PR just adds some more tests for class/style hydration mismatches, modifying existing tests to _not_ use the static content optimization.
I also found #2962 in the process, but I did not attempt to fix it.
=> test(integration-karma): improve test coverage

packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/elseif.spec.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/parser/parser.ts, packages/@lwc/template-compiler/src/shared/ast.ts, packages/@lwc/template-compiler/src/shared/types.ts
=> feat: lwc:if, lwc:elseif, and lwc:else directives

packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/elseif.spec.ts, packages/@lwc/template-compiler/src/parser/index.ts, packages/@lwc/template-compiler/src/parser/parser.ts, packages/@lwc/template-compiler/src/shared/ast.ts
This PR enhances the template compiler's parser to track slot names from various if-block contexts.
**From the RFC:**
A developer may want to use if/else-if/else chains to render a `<slot>`:
```html
<template>
<template lwc:if={foo}>
<slot></slot>
</template>
<template lwc:else>
<slot></slot>
</template>
</template>
```
In this case, the template compiler should _not_ warn about duplicate slots with the same name. This is a perfectly valid use case, and the template compiler knows for certain that the `<slot>` will not be rendered twice.
What this means is that for each new set of if/elseif/else chains, we need to keep track of and avoid using the names found in the other branches of the same chain when checking for duplicate slot names.
This PR accomplishes this by doing the following:
- …
=> feat: refactor parser context to support new behavior for slot name tracking

packages/@lwc/features/src/__tests__/flags-prod.spec.ts, packages/@lwc/features/src/__tests__/flags.spec.ts, packages/@lwc/features/src/babel-plugin/index.js, packages/@lwc/features/src/flags.ts
In our build artifacts for `engine-dom` and `engine-server`, I would like to be able to replace runtime flags with `true` and `false` for tree-shaking purposes. (I.e. a consumer can tree-shake out any runtime features they are not using.)
This is possible today with e.g. `@rollup/plugin-replace`, but currently our build artifacts contain things like:
```js
if (runtimeFlags.ENABLE_REACTIVE_SETTER) {
```
... which would require:
```js
replace({
'runtimeFlags.ENABLE_REACTIVE_SETTER': 'false',
preventAssignment: true
})
```
I propose renaming `runtimeFlags` to the more explicit `lwcRuntimeFlags`, because:
1. It makes it more obvious that you're replacing an LWC runtime flag.
2. It matches the name of the global anyway.
3. It completely eliminates the possibility of collision with some other …
=> refactor(features): rename runtimeFlags to lwcRuntimeFlags

packages/@lwc/aria-reflection-polyfill/package.json
@lwc/shared version in @lwc/aria-reflection-polyfill is 2.22.0 because when it was created lwc version was 2.22.0. But by the time the PR was merged, lwc version had moved to 2.23.0.
=> chore: fix @lwc/shared version in new package

.circleci/config.yml
Avoid repeating parameters in karma suite command
=> chore: avoid repeating parameter values by providing defaults

packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/component/unknown-properties/index.spec.js, packages/@lwc/integration-karma/test/component/unknown-properties/x/child/child.html, packages/@lwc/integration-karma/test/component/unknown-properties/x/child/child.js, packages/@lwc/integration-karma/test/component/unknown-properties/x/component/component.html, packages/@lwc/integration-karma/test/component/unknown-properties/x/component/component.js
This partially mitigates #1297.
We have gotten many reports of people's tests failing in Jest or IE11 because of missing properties on `Element` or `HTMLElement`. Rather than make this a dev-only error, let's make it a dev-only warning.
In dev mode, unknown element properties will now be a warning, not an error.
=> fix(engine-dom): make unknown props a warning, not error

packages/@lwc/perf-benchmarks/package.json, yarn.lock
Tachometer 0.6.0 released a breaking change that caused our benchmark tests to no longer work. This PR downgrades us to the latest working version.
We could change our tests to accommodate Tachometer, which would require (AFAICT) to change all imports like:
```js
import { renderComponent } from '@lwc/engine-server';
```
...to:
```js
import { renderComponent } from '../../relative/path/to/node_modules/@lwc/engine-server';
```
The reason is that Tachometer does not seem to handle package imports very well (see also https://github.com/Polymer/tachometer/issues/215).
I didn't have time to make this change or test it, so let's just downgrade for now.
=> chore: downgrade tachometer for now

lerna.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
This contains one `feat`, but in retrospect it was probably more of a `fix:`. No compiler changes.
=> chore: release v2.23.2

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/integration-karma/test/template/html-comments/index.spec.js, packages/@lwc/integration-karma/test/template/html-comments/x/confusedWithText/confusedWithText.html, packages/@lwc/integration-karma/test/template/html-comments/x/confusedWithText/confusedWithText.js
=> fix(engine): comment node patched with text node

packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/light-dom/root/index.spec.js, packages/@lwc/integration-karma/test/light-dom/root/x/light/light.html, packages/@lwc/integration-karma/test/light-dom/root/x/light/light.js, packages/@lwc/integration-karma/test/light-dom/root/x/list/list.html, packages/@lwc/integration-karma/test/light-dom/root/x/list/list.js, packages/@lwc/integration-karma/test/light-dom/synthetic-shadow/index.spec.js, packages/@lwc/synthetic-shadow/src/shared/node-ownership.ts
We were using native `parentNode` while navigating up to find the nearest root node.
This made sense when the element was inserted via `lwc:dom="manual"`.
It breaks down when an element is slotted into a Shadow DOM element, because the
native `parentNode` doesn't give us the right parent node (it gives us the slot).
=> fix: `getRootNode` for elements slotted into synthetic shadow from root light DOM components

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Weekly release v2.23.5
W-11466097
=> chore: v2.23.5

package.json, yarn.lock
This PR removed Lerna as a dependency on the root `package.json`.  Lerna is no longer needed as #2965 replaces it with Nx.  The dependency should have been removed in #2965 but it looks like it was missed as part of that PR.
=> chore: remove lerna from root package.json

.prettierignore
If you run `yarn format`, it will check files in `.rollup-cache` which is unnecessary. This fixes that.
=> chore: tell prettier to ignore rollup cache

packages/@lwc/integration-karma/test/light-dom/root/index.spec.js, packages/@lwc/integration-karma/test/light-dom/root/x/light/light.html, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts
Related to #2455 
In the following case
```html
<body>
<x-light>
<x-shadow>
<button></button>
</x-shadow>
</x-light>
</body>
```
```
const shadow = document.querySelector('x-shadow');
shadow.querySelector('button'); // returns `null` incorrectly before fix.
```
`button` is within the light DOM of `x-shadow` and should therefore be queryable.
=> fix: querySelector etc. for root light DOM

packages/@lwc/perf-benchmarks/package.json
When running `yarn:performance`, there are certain environmental variables that affect the output. NX [needs to be told about these](https://nx.dev/concepts/how-caching-works#runtime-hash-inputs), or else it won't bust the cache properly.
I tested manually and the NX cache appears to be working correctly. It also still considers source files to be part of the cache key.
=> chore(perf-benchmarks): bust NX cache based on env vars

packages/@lwc/integration-karma/test/light-dom/scoped-styles/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-styles/x/pseudoChild/pseudoChild.html, packages/@lwc/integration-karma/test/light-dom/scoped-styles/x/pseudoChild/pseudoChild.js, packages/@lwc/integration-karma/test/light-dom/scoped-styles/x/pseudoParent/pseudoParent.html, packages/@lwc/integration-karma/test/light-dom/scoped-styles/x/pseudoParent/pseudoParent.js, packages/@lwc/integration-karma/test/light-dom/scoped-styles/x/pseudoParent/pseudoParent.scoped.css, packages/@lwc/style-compiler/src/__tests__/fixtures/pseudo-element/actual.css, packages/@lwc/style-compiler/src/__tests__/fixtures/pseudo-element/expected.js, packages/@lwc/style-compiler/src/selector-scoping/transform.ts
Fixes #3051
It looks like the problem was just with bare pseudo-elements like `::before` and `::after`.
The behavior before was broken. In the odd case where someone was relying on the broken behavior, the non-broken behavior will be observable. (E.g. with the old behavior, you could use `.unused, ::before {}` as a hack to target any `::before`s in your descendant tree, even if they didn't belong to your component.)
Hopefully this is not a a big deal in practice, and in any case, we need this fix to preserve encapsulation.
W-11785692
=> fix(style-compiler): fix whitespace before pseudo-elements

packages/@lwc/integration-karma/scripts/karma-configs/hydration/sauce.js, packages/@lwc/integration-karma/scripts/karma-configs/test/sauce.js, packages/@lwc/integration-karma/scripts/karma-configs/utils.js
Addresses #3083 switching to W3C format for saucelab capabilities config, pin firefox version to 105 and `geckodriverVersion` to 0.30.0.
See the Saucelabs article for [details](https://saucelabs.com/blog/update-firefox-tests-before-oct-4-2022).
=> chore: update geckodriver version for firefox

packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts
Since the main content of `containsDynamicChildren` was removed in https://github.com/salesforce/lwc/commit/17a129e95b21cfd093045e021809053022e98ec5#diff-375bb5567638caba6505ed89abae4d4bc1744f27a71fd1e2a650422f7f6f3b59L67, I don't see how this function will ever return anything other than `false`. If I'm not missing anything, we can save on traversal time and confusion by removing this function.
=> chore: remove unnecessary containsDynamicChildren

packages/@lwc/engine-core/src/framework/hot-swaps.ts, packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/swapping/components/index.spec.js
This flag is no longer necessary. LWR is already using it, and on platform, we already block access to these APIs and tree-shake them out. (If you don't use these APIs, they are tree-shaken.)
This is the only flag LWR is using, so we can simplify their usage of LWC by just enabling HMR by default.
Not detectable on platform.
=> fix(engine-core): remove ENABLE_HMR flag

packages/@lwc/integration-karma/test/template/directive-if-elseif-else/index.spec.js, packages/@lwc/integration-karma/test/template/directive-if-elseif-else/x/childWithNamedSlots/childWithNamedSlots.html, packages/@lwc/integration-karma/test/template/directive-if-elseif-else/x/childWithNamedSlots/childWithNamedSlots.js, packages/@lwc/integration-karma/test/template/directive-if-elseif-else/x/parentWithNamedSlot/parentWithNamedSlot.html, packages/@lwc/integration-karma/test/template/directive-if-elseif-else/x/parentWithNamedSlot/parentWithNamedSlot.js
Adds a test case for named slots and slot content wrapped in a lwc:if directive
W-11838547
=> test: add test for named slots and lwc:if directive

.nucleus.yaml
These two downstreams seem to be failing for spurious reasons. (Snapshots, some kind of WebDriver error.)
=> chore(nucleus): remove failing downstreams

packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/index.spec.js, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/anotherChild/anotherChild.html, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/anotherChild/anotherChild.js, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/child/child.html, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/child/child.js, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/grandparent/grandparent.css, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/grandparent/grandparent.html, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/grandparent/grandparent.js, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/parent/parent.html, packages/@lwc/integration-karma/test/shadow-dom/part-and-exportparts/x/parent/parent.js, packages/@lwc/template-compiler/src/parser/attribute.ts
Fixes #3005
Adds support for the [`exportparts`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/exportparts) attribute.
You can use `exportparts` now without it throwing an error.
W-11605544
=> fix(template-compiler): support exportparts attribute

packages/@lwc/engine-core/src/framework/rendering.ts
This fix is cherry-picked from the ephemeral 2.26.1 release branch. It resolves the issue seen in Salesforce platform relating to registration of tag-names that are not lowercased.
This is bug fix for behavior that has not yet landed on platform. As such, it represents a nominal observable change.
W-11609119
=> fix(engine-core): tagNames generated by Java compiler than need to be lowercased

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/only-present-in-ssr/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/only-present-in-ssr/x/child/child.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/only-present-in-ssr/x/child/child.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/only-present-in-ssr/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/only-present-in-ssr/x/main/main.js
This PR addresses an issue that was discovered while digging into other SSR/hydration logic bugs. We found cases where SSR generated a classname that was not present in the corresponding client-side VDOM.
For example, this showed up when `classMap` was mutated in `connectedCallback`. However, based on recent discussion, this is not a pattern that we will allow in SSR in the future. As such, there are no known indelible cases where this the validation failure condition is reached.
However, it is still prudent to fill the gap in validation, which is done in this PR.
Fixes #3007.
The observable change is nominal.
W-11609056
=> chore: check for addl invalid hydration condition

packages/@lwc/engine-server/src/__tests__/fixtures/for-static-content/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-static-content/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/for-static-content/modules/x/container/container.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-static-content/modules/x/container/container.js, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/engine-server/src/types.ts
This fixes an issue in SSR for static content not appearing in the rendered HTML when it's within an iteration or there's multiple component instances on the same page.
=> fix(engine-server): missing static elements within foreach

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/@lwc/engine-dom/jest.config.js, packages/@lwc/engine-dom/src/formatters/__tests__/component.spec.ts, packages/@lwc/engine-dom/src/formatters/component.ts, packages/@lwc/engine-dom/src/formatters/index.ts, packages/@lwc/engine-dom/src/index.ts, packages/@lwc/shared/src/language.ts
This PR solves #1902 by adding debug information for wired properties and methods on a component, exposing it via [Custom Object Formatters in Chrome DevTools](https://docs.google.com/document/d/1FTascZXT9cxfetuPRT2eXPQKXui4nWFivUnS_335T3U/preview#).
The information about each wired property/method has the following shape:
- `data`: the last value emitted by the wire adapter.
- `config`: the last config reported to the wire adapter.
- `context`: for context wire adapters use only.
- `isDataProvisionedForConfig`: `bool`: whether or not the data provisioned by the wire adapter correspond to the config. Note: the wire protocol does not know this for certain, it is `true` if the adapter emits data after a config was reported.
This information is exposed via Custom Object Formatters. The only …
=> feat(engine-dom): add wire debug info and devtool formatters

packages/@lwc/integration-karma/test/template/directive-external/custom-elements/ce-with-children.js, packages/@lwc/integration-karma/test/template/directive-external/custom-elements/ce-with-event.js, packages/@lwc/integration-karma/test/template/directive-external/custom-elements/ce-without-children.js, packages/@lwc/integration-karma/test/template/directive-external/index.spec.js, packages/@lwc/integration-karma/test/template/directive-external/x/withChildren/withChildren.html, packages/@lwc/integration-karma/test/template/directive-external/x/withChildren/withChildren.js, packages/@lwc/integration-karma/test/template/directive-external/x/withDeclarativeEvent/withDeclarativeEvent.html, packages/@lwc/integration-karma/test/template/directive-external/x/withDeclarativeEvent/withDeclarativeEvent.js, packages/@lwc/integration-karma/test/template/directive-external/x/withDifferentViews/withDifferentViews.html, packages/@lwc/integration-karma/test/template/directive-external/x/withDifferentViews/withDifferentViews.js, packages/@lwc/integration-karma/test/template/directive-external/x/withImperativeEvent/withImperativeEvent.html, packages/@lwc/integration-karma/test/template/directive-external/x/withImperativeEvent/withImperativeEvent.js, packages/@lwc/integration-karma/test/template/directive-external/x/withUnregisteredWC/withUnregisteredWC.html, packages/@lwc/integration-karma/test/template/directive-external/x/withUnregisteredWC/withUnregisteredWC.js, packages/@lwc/integration-karma/test/template/directive-external/x/withoutChildren/withoutChildren.html, packages/@lwc/integration-karma/test/template/directive-external/x/withoutChildren/withoutChildren.js
Add basic integration tests for `lwc:external` directive.
Tests on data passing between LWC and custom elements will be added later.
[W-11912243](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000018peSSYAY/view)
=> test(integration-karma): add basic test cases for lwc:external directive

packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/engine-dom/src/custom-elements/create-custom-element-scoped.ts, packages/@lwc/engine-dom/src/custom-elements/create-custom-element-vanilla.ts, packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts
As it turns out, #2724 introduced perf overhead by adding `connectedCallback`s and `disconnectedCallback`s to every LWC Element prototype.
I toyed around with it, and the overhead is there even if the callback is a (nearly-empty) function:
This is driven by `ENABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE`. Since this is an experimental feature, we can disable the `connectedCallback`/`disconnectedCallback` entirely if it is `false`. (This is basically what we were doing before #2724.)
This improves the perf by 14-17%:
[W-12028575](https://gus.lightning.force.com/lightning/r/a07EE00001BsZ0hYAF/view)
=> perf(engine-dom): optimize connected/disconnected callbacks

packages/@lwc/engine-core/src/framework/api.ts
It turns out that https://github.com/salesforce/lwc/commit/2ada663f3858ea97065907835c1df8930b1b9870 and https://github.com/salesforce/lwc/commit/e983223755ed18060cdeff3059dc9f58ac041eca  [introduced](https://gus.lightning.force.com/lightning/r/0D5EE000012dtb90AA/view) a perf regression. The `dom-ss-slot-update-slotted-content-5k` benchmark regressed 16% comparing `master` to 240. The culprit is this `reduce` function:
https://github.com/salesforce/lwc/blob/63760138ee3f16ae5d8a339b89d26f742366cf5b/packages/@lwc/engine-core/src/framework/api.ts#L192
This PR improves the benchmark by 11-12% (comparing this PR to `master`):
Improvements:
- use a for-loop instead of `Array.prototype.reduce`
- use `ArrayPush` instead of `ArrayConcat` (`ArrayConcat` creates a [brand-new copy of the …
=> perf(engine-core): optimize slot iteration

packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/detect.ts
Fixes #1513
Non-IE11 browsers will no longer get this iframe polyfill.
W-12067861
=> fix(synthetic-shadow): apply iframe-content-window polyfill only in IE11

packages/@lwc/engine-dom/src/custom-elements/create-custom-element-scoped.ts
This is a follow-up to https://github.com/salesforce/lwc/pull/3162#issuecomment-1315413494.
This code did not need to be changed, so I refactored it back to the (simpler) way it was before. I also added a comment to explain.
Just as a sanity check, I ran the benchmark comparing this PR to `master` to ensure there is no difference (pivots are not tested by our benchmark at all, but even if it were, it shouldn't matter):
FYI @caridy
=> fix(pivots): refactor connected/disconnectedCallback code

packages/@lwc/integration-karma/test/custom-elements/index.spec.js
Just adds a test to ensure we are doing this correctly.
=> test(pivots): add test for attributeChangedCallback during upgrade

.git2gus/config.json, .nucleus.yaml
[W-11466097](https://gus.lightning.force.com/a07EE000011woQMYAY)
=> chore: update git2gus release and nucleus for 244 clco

packages/@lwc/integration-karma/test/template/directive-external/index.spec.js
The tests in #3144 emit a console warning when running `yarn test`:
```
Unknown public property "tokyo" of element <ce-with-property>. [...]
```
By adding `toLogWarningDev`, these don't get logged to the console, and as a bonus, we add a test to ensure that the warning is logged.
=> test(integration-karma): add tests for dev warning

packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-slot-ss/ss-slot-create-container-5k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-slot-ss/ss-slot-update-slotted-content-5k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/light-styled-component-create-10k-same.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/light-styled-component-create-1k-different.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-styled-component-create-10k-same.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-styled-component-create-1k-different.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/styled-component-create-10k-same.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/styled-component-create-1k-different.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-table-component/tablecmp-append-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-table-component/tablecmp-create-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-table-component/tablecmp-create-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-table/table-create-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-tracked-component/trackedcmp-create-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-hydrate/table-hydrate-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-hydrate/tablecmp-hydrate-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-server/table-render-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-server/tablecmp-render-10k.benchmark.js
Renames the benchmarks so that they are easier to read in the Best UI.
Fixes:
- Some benchmarks have duplicate names (Whoops 🤦‍♂️)
- Can't tell which ones are `server` vs `dom`
- It's not obvious that `ss` means "synthetic shadow"
- Names are inconsistent
Names before:
```
benchmark-slot-ss/synthetic-shadow-create/5k
benchmark-slot-ss/synthetic-shadow-slot-update-slotted-content/5k
benchmark-styled-component/create/10k/same
benchmark-styled-component/create/10k/same
benchmark-styled-component/create/1k/different
benchmark-styled-component/create/1k/different
benchmark-table-component/append/1k
benchmark-table-component/create/10k
benchmark-table-component/create/1k
benchmark-table-component/hydrate/1k
benchmark-table-component/render/10k
benchmark-table/create/10k …
```
=> chore(perf-benchmarks): improve benchmark names

packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/metadata.json, packages/@lwc/template-compiler/src/parser/attribute.ts
The [`normalizeAttributeValue`](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/template-compiler/src/parser/attribute.ts#L83-L163) function does not account for a '=' character in the attribute value when validating against [escaped](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/template-compiler/src/parser/attribute.ts#L46-L49) and [quoted](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/template-compiler/src/parser/attribute.ts#L41-L44) attributes.
Currently, the logic to split the attribute name and value is the following:
```
const [, value] = rawAttribute.split('=');
```
When the attribute's value contains an '=' the `rawAttribute` will be split multiple times. 
In this case, the validation logic does not execute on the full attribute …
=> fix: update attribute parsing to account for '=' in attribute value

packages/@lwc/perf-benchmarks/best.config.js
We got the okay from Best infra folks to bump the # of iterations from 30 to 60. The tests will take ~20 minutes instead of ~10 minutes, but we should have lower variance.
=> chore(perf-benchmarks): increase best iterations

packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/integration-karma/test/shadow-dom/Element-properties/Element.innerHTML.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Node-properties/Node.textContent.spec.js, packages/@lwc/integration-karma/test/template/directive-lwc-dom-manual/index.spec.js
Fixes #3117
In dev mode, when using native shadow, there is no longer a console.error in certain cases. This is mildly observable and unlikely to break anything.
=> fix(engine-dom): remove portal warnings for native shadow

packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/attribute-with-equal/metadata.json, packages/@lwc/template-compiler/src/parser/attribute.ts
This is a backport of #3185 to Spring23.
See the description in #3185 
W-12107374
=> fix: update attribute parsing to account for '=' in attribute value (backport)

packages/@lwc/aria-reflection/src/polyfill.ts, packages/@lwc/engine-core/src/framework/base-bridge-element.ts
These are small follow-up fixes for #3197 based on PR review comments from @ravijayaramappa.
=> fix(aria-reflection): small fixes for #3197

packages/@lwc/engine-core/src/framework/attributes.ts, packages/@lwc/integration-karma/test/component/html-properties/index.spec.js, packages/@lwc/integration-karma/test/component/html-properties/x/component/component.html, packages/@lwc/integration-karma/test/component/html-properties/x/component/component.js
In addition to ARIA reflection, we also support some HTML `Element` properties on `LightningElement` like `id`, `title`, and `spellcheck`. Some of these reflect to attributes (e.g. `id`), some of them don't, and some of them don't actually do anything if you call the setter. Some also log a warning.
Since these are on `LightningElement`, they're relevant for cases where the component author is calling e.g. `this.title = "foo"` from within their component.
I couldn't find any tests for this behavior, so I wrote some tests. This should ensure that, if we change the code in the future, we're at least sure about whether or not we're making a backwards-compatible change.
=> test: add tests for LightningElement property reflection

packages/@lwc/engine-core/src/shared/logger.ts, packages/@lwc/engine-dom/src/styles.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts
In general, I think we should strive to avoid any reference to a `process.env.NODE_ENV` value other than `"production"`. The other possible values (`"development"`, `"test"`, etc.) are unreliable in my experience.
There are only three places we're doing this. The `"test"` usage is undoubtedly [just to target Jest](https://jestjs.io/docs/environment-variables#node_env).
=> fix: clean up usage of process.env.NODE_ENV

packages/@lwc/integration-karma/test/light-dom/host-pseudo/index.spec.js, packages/@lwc/integration-karma/test/light-dom/host-pseudo/x/component/component.html, packages/@lwc/integration-karma/test/light-dom/host-pseudo/x/component/component.js, packages/@lwc/integration-karma/test/light-dom/host-pseudo/x/component/component.scoped.css, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/index.spec.js, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/invalid/invalid.css, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/invalid/invalid.html, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/invalid/invalid.js, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/invalid/invalid.scoped.css, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/valid/valid.css, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/valid/valid.html, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/valid/valid.js, packages/@lwc/integration-karma/test/synthetic-shadow/host-pseudo/x/valid/valid.scoped.css
This adds test to verify the existing behavior described here: https://github.com/salesforce/lwc/issues/3225
I also added some `TODO`s to change this behavior. But note that it would be a backwards-incompatible change.
=> test(integration-karma): add tests for :host() pseudo

packages/@lwc/compiler/src/transformers/__tests__/transform-html.spec.ts, packages/@lwc/compiler/src/transformers/template.ts
Fixes missing semicolons in tmpl.stylesheets and stylesheetToken assignments
W-12242450
=> fix: missing semicolon in stylesheetToken assignment

packages/@lwc/engine-core/src/framework/attributes.ts, packages/@lwc/engine-core/src/framework/restrictions.ts
This reduces the `engine-dom` bundle size slightly, by removing some code that is only needed in dev mode. The size is reduced from 64609 to 63098 bytes when minified (1511 bytes or **1.5kb saved**).
We emit several console warning when calling accessors for certain `HTMLElement` props like `title` and `className`. The object describing these warnings is [quite large](https://github.com/salesforce/lwc/blob/e2d97e567c16d7460ccddb34a0cfb6717b9af36e/packages/@lwc/engine-core/src/framework/attributes.ts#L32-L124), not to mention the code to generate the log messages.
Because of how we were constructing this object, Terser was not able to tree-shake it, even in prod mode. This fixes that.
Note that the tests in #3215 confirm the existing behavior (although our Karma tests only run in dev mode …
=> perf: remove HTMLElement accessor warning map in prod

packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js
Fixes sourcemaps in our karma tests, in particular when running `yarn start` and debugging in the Karma debug mode.
Before (note how the little "tag" icons are messed up and inserted in the middle of words):
After:
=> test(integration-karma): fix sourcemaps

.nucleus.yaml
This downstream is borked right now. No sense blocking all of our PRs on it.
=> chore(nucleus): remove lwc-platform for now

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts
Found some unused code while doing a coverage audit.
=> fix(engine-core): remove unused refs code
