.circleci/config.yml, package.json, yarn.lock
=> chore: upgrade lerna, remove unneded ci

packages/@lwc/wire-service/README.md
Fixes #1333
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe issue being fixed or feature enhanced? ✅
=> docs(wire-service): Update README.md links

packages/@lwc/engine/scripts/jest/test-whitelist.js, packages/@lwc/engine/src/framework/__tests__/html-element.spec.ts, packages/@lwc/engine/src/framework/restrictions.ts
=> fix: disable attribute reflection restriction for tests

packages/@lwc/engine/src/framework/attributes.ts, packages/@lwc/engine/src/framework/restrictions.ts
It's a little noisy because I moved things around but I commented on the relevant changes in this PR. Looking at individual commits should also clarify the changes.
=> chore(engine): global html properties cleanup

packages/@lwc/engine/src/framework/wc.ts
=> chore: remove todo for default shadow mode

.github/PULL_REQUEST_TEMPLATE.md
Adding a missing "the" to fix #1372.
* Have tests for the proposed changes been added? ✅ - N/A
* Have you followed [these instructions](../CONTRIBUTING.md#-commit-message-conventions) to clearly describe _the_ issue being fixed or feature enhanced? ✅
=> docs(pr-template): fix grammar error in the PR template

packages/@lwc/style-compiler/src/__tests__/fixtures/nester-vars-compounded/actual.css, packages/@lwc/style-compiler/src/__tests__/fixtures/nester-vars-compounded/config.json, packages/@lwc/style-compiler/src/__tests__/fixtures/nester-vars-compounded/expected.js, packages/@lwc/style-compiler/src/serialize.ts
Fixes https://github.com/salesforce/lwc/issues/1376
=> fix: nested style fix

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/delegates-focus-click-target-natively-non-focusable.spec.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/child/child.html, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/child/child.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/delegates-focus-click-target-natively-non-focusable/delegates-focus-click-target-natively-non-focusable.html, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/delegates-focus-click-target-natively-non-focusable/delegates-focus-click-target-natively-non-focusable.js, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/parent/parent.css, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/parent/parent.html, packages/integration-tests/src/components/accessibility/test-delegates-focus-click-target-natively-non-focusable/integration/parent/parent.js
=> fix(synthetic): consider ancestors when determining click-focusability

.gitignore, CONTRIBUTING.md, package.json, packages/@lwc/engine/package.json, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/tsconfig.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/tsconfig.json, packages/@lwc/wire-service/.gitignore, packages/@lwc/wire-service/package.json, packages/@lwc/wire-service/src/engine.ts, packages/@lwc/wire-service/src/index.ts, packages/@lwc/wire-service/src/property-trap.ts, packages/@lwc/wire-service/src/wiring.ts, packages/@lwc/wire-service/tsconfig.json, packages/lwc/package.json, packages/lwc/types.d.ts
* refactoring the types, each pkg has its own types generated by typescript
* lwc/types.d.ts has its own manually defined types for platform
=> fix(engine): types

packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/wire-service/src/__tests__/wiring.spec.ts, packages/@lwc/wire-service/src/index.ts, packages/@lwc/wire-service/src/link-context-event.ts, packages/@lwc/wire-service/src/value-changed-event.ts, packages/@lwc/wire-service/src/wiring.ts
* refactor(wire-service): introducing LinkContextEvent
#	packages/@lwc/wire-service/src/wiring.ts
cherrypicks #1358
=> refactor(wire-service): [cp] introducing LinkContextEvent (#1358)

yarn.lock
Upgrading js-yaml to latest.
We still have one other usage which needs a major upgrade of [cssnano](https://github.com/cssnano/cssnano) dependency.
=> chore: update js-yaml version to latest

packages/@lwc/wire-service/README.md
README: Correct code sample on the LWC wire service event types
=> docs(wire-service): correct event types in readme sample code

packages/@lwc/module-resolver/src/index.ts
Remove a very annoying `console.log` statement in the module resolver
* Have tests for the proposed changes been added? 🤔
=> chore: remove moduleresolver console log

.circleci/config.yml, scripts/release_canary_npm.js
Allow multiple paths for canary generation
=> feat: add N paths to generate packages

package.json, yarn.lock
Upgrade @commitlint/cli and @commitlint/config-conventional to v8.1.0
=> chore: address security vulnerability CVE-2019-10744

.circleci/config.yml, package.json, packages/perf-benchmarks/best.headless.config.js, packages/perf-benchmarks/package.json, yarn.lock
Upgrades our Best installation to Best v4. We need to set the `process.env.BEST_HUB_CLIENT_TOKEN` on circle ci for this to work properly.
=> feat: move to best v4

.circleci/config.yml
Rename CircleCI step in `perf_and_compare` to more accurately reflect what it does.
=> chore: rename circleci step

.circleci/config.yml, packages/perf-benchmarks/best.headless.config.js
Move to the new Best Hub which is set by environment variable inside Circle CI. Also enable running our benchmarks in batch.
=> chore: move to new best hub

.git2gus/config.json
=> feat: hide gus urls

packages/@lwc/engine/src/framework/vm.ts, packages/integration-karma/test/component/LightningElement.disconnectedCallback/index.spec.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/dualTemplate.js, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/templateA.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/dualTemplate/templateB.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/explicitRender/explicitRender.html, packages/integration-karma/test/component/LightningElement.disconnectedCallback/x/explicitRender/explicitRender.js
tests for #1435 
Supporting https://github.com/salesforce/lwc/pull/1443
=> test: tests for #1435

packages/@lwc/engine/src/3rdparty/snabbdom/types.ts, packages/@lwc/engine/src/env/dom.ts, packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/component.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/stylesheet.ts, packages/@lwc/engine/src/framework/template.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/@lwc/engine/src/shared/language.ts
=> fix(engine): removing the remaining pieces of manual reactions

packages/lwc/index.js
`## Does this PR introduce breaking changes?
=> fix: lwc module not resolving prod mode

package.json, packages/@lwc/engine/scripts/rollup/rollup.config.js, packages/@lwc/features/scripts/rollup/rollup.config.js, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/@lwc/wire-service/scripts/rollup/rollup.config.js, yarn.lock
Node module resolution whitelist.
=> build: node module resolution whitelist

packages/integration-karma/test/shadow-dom/event-in-shadow-tree/event-propagation.spec.js
issue #1132
https://github.com/salesforce/lwc/issues/1132
=> test: enabled tests for #1132

package.json, yarn.lock
https://nvd.nist.gov/vuln/detail/CVE-2019-10746
https://nvd.nist.gov/vuln/detail/CVE-2019-10747
=> chore: address security vulnerabilities

.circleci/config.yml, packages/integration-karma/README.md, packages/integration-karma/scripts/karma-configs/base.js, packages/integration-karma/scripts/karma-plugins/env.js
Avoid testing with production artifacts. This will allow us to test features that are behind feature flags.
=> test(integration-karma): avoid testing with production artifacts

packages/@lwc/template-compiler/package.json
=> fix: missing shared dependency

packages/lwc/index.js, packages/lwc/scripts/build.js, packages/lwc/scripts/utils/helpers.js, packages/lwc/scripts/utils/rollup.js
Add debug mode to lwc artifacts
=> fix: add debug mode to facade

packages/@lwc/engine/package.json
lerna did not update the features package since its private.
=> fix: missing dep

packages/@lwc/features/package.json
=> fix(features): make @lwc/features a public package

packages/@lwc/synthetic-shadow/package.json, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/lwc/package.json, packages/lwc/scripts/utils/rollup.js
and `@lwc/synthetic-shadow` modules
=> fix(feature-flags): Enable feature flags in lwc distribution

packages/lwc/package.json
The "module" entry in package.json for `lwc` has an incorrect path.  This PR fixes the path for all us esm lovers out there ❤️ 
=> fix(lwc): fix incorrect module path in package.json for lwc package

packages/@lwc/module-resolver/src/__tests__/fixtures/module-entries/ns/tsEntry/tsEntry.ts, packages/@lwc/module-resolver/src/__tests__/fixtures/module-entries/ns/tsEntry/util.ts, packages/@lwc/module-resolver/src/__tests__/resolve.modules.spec.ts, packages/@lwc/module-resolver/src/utils.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/expected_default_config_ts_simple_app.js, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/main.ts, packages/@lwc/rollup-plugin/src/__tests__/fixtures/ts_simple_app/src/x/app/app.ts
When working on typescript, bundles where not resolved properly in rollup
=> fix(module-resolver): typescript module resolution bug

scripts/release_npm.sh
=> chore: allow a registry to be specified for release:ci:npm target

scripts/release_npm.sh
=> fix: update release_npm script

scripts/release_npm.sh
=> chore: revert #1580 and #1581 related to release script update

packages/integration-karma/test/shadow-dom/Element-properties/index.spec.js, packages/integration-karma/test/synthetic-shadow/element-api/element-api.spec.js
=> test: ignore console errors about manual dom insertion

packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/portal.ts, packages/integration-karma/test/dom-manual/moving-node-to-document/index.spec.js, packages/integration-karma/test/dom-manual/moving-node-to-document/x/container/container.html, packages/integration-karma/test/dom-manual/moving-node-to-document/x/container/container.js
elements
Fixes https://github.com/salesforce/lwc/issues/1588
=> fix(synthetic-shadow): remove ownerKeys of migrated dom:manual

.circleci/config.yml
=> fix(ci): set node version to 10.16.3 until

docs/architecture/web-components.md
=> fixed few typos

.git2gus/config.json
Update the git2gus release to `226`.
=> chore: Update git2gus release

packages/@lwc/shared/src/language.ts, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/synthetic-shadow/src/3rdparty/polymer/outer-html.ts, packages/@lwc/synthetic-shadow/src/3rdparty/polymer/retarget.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/portal.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-token.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/@lwc/synthetic-shadow/src/polyfills/click-event-composed/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/mutation-observer/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/static-html-collection.ts, packages/@lwc/synthetic-shadow/src/shared/static-node-list.ts, packages/@lwc/synthetic-shadow/src/shared/utils.ts, packages/@lwc/synthetic-shadow/tsconfig.json
* Add `tsc` as part of the `@lwc/synthetic-shadow` build step.
* Enable strict mode.
* Fix type declarations.
Fixes #1649
=> refactor(synthetic-shadow): Add tsc to the build task

.circleci/config.yml
Pass sauce config as environment variables.
W-7089198
=> chore: pass sauce config as environment variable

packages/integration-karma/test/polyfills/click-event-composed/index.spec.js, packages/integration-karma/test/shadow-dom/Event-properties/Event.target.spec.js
=> test: enable tests that depend on latest safari

packages/@lwc/synthetic-shadow/src/faux-shadow/event-target.ts
Came across some dead code in event-target modules of synthetic-shadow.
=> chore: remove dead code

package.json, packages/integration-tests/package.json, yarn.lock
Weekly dev dependencies upgrade.
W-7109631
=> chore: Weekly dev dependencies update

package.json, yarn.lock
* Upgrade Node to `12.15.0`
* Upgrade Yarn to `1.22.0`
* Upgrade all the dev dependencies
W-7109631
=> chore: upgrade Node, Yarn and dev dependencies

packages/@lwc/engine/src/framework/context.ts, packages/@lwc/engine/src/framework/invoker.ts
=> fix: remove unused currentContext

.github/PULL_REQUEST_TEMPLATE.md
Update PR template to include GUS work item
W-7109631
=> chore: update pr template to include gus info

.circleci/config.yml
* Pin node version to 12, to avoid upgrade until next LTS release
* Upgrade `sauceconnect` to the latest version.
W-7109631
=> build: upgrade build dependencies

package.json, packages/perf-benchmarks/best.headless.config.js, packages/perf-benchmarks/best.ie11.config.js, packages/perf-benchmarks/package.json, yarn.lock
=> feat: upgrade best

scripts/release_npm.sh
=> chore: update release script to reflect correct footer in dist files

packages/@lwc/module-resolver/src/utils.ts, packages/@lwc/module-resolver/tsconfig.json
Enable strict typescript check for the `@lwc/module-resolver` package.
W-7109631
=> refactor(module-resolver): Enforce strict typescript check

packages/@lwc/rollup-plugin/src/__tests__/index.spec.js
Forgot `only` modifier in tests
=> fix: only tests

packages/integration-karma/scripts/merge-coverage.js
Increase coverage numbers to the current levels
W-7109631
=> test: bump coverage threshold to current values

.github/ISSUE_TEMPLATE/Bug_report.md, CONTRIBUTING.md, docs/element.md, packages/@lwc/babel-plugin-component/README.md, packages/@lwc/compiler/README.md, packages/@lwc/engine/README.md, packages/@lwc/engine/src/polyfills/proxy-concat/README.md, packages/@lwc/errors/README.md, packages/@lwc/synthetic-shadow/src/polyfills/HTMLSlotElement/README.md
=> fix: typos

packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/decorators/api.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/local-registry.ts, packages/@lwc/engine/src/framework/stylesheet.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/integration-karma/test/component/lifecycle-callbacks/index.spec.js
just adding more changes to the clean up PR
=> more changes on top of PR #1798

packages/@lwc/babel-plugin-component/src/__tests__/implicit-explicit.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/observed-fields.spec.js, packages/@lwc/babel-plugin-component/src/__tests__/wire-decorator.spec.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.js, packages/integration-karma/test/api/getComponentDef/index.spec.js, packages/integration-karma/test/api/getComponentDef/x/publicPropertiesInheritance/base.js, packages/integration-karma/test/api/getComponentDef/x/wireAdapter/wireAdapter.js, packages/integration-karma/test/api/getComponentDef/x/wireMethods/wireMethods.js, packages/integration-karma/test/api/getComponentDef/x/wireMethodsInheritance/base.js, packages/integration-karma/test/api/getComponentDef/x/wireMethodsInheritance/wireMethodsInheritance.js, packages/integration-karma/test/api/getComponentDef/x/wireProperties/wireProperties.js, packages/integration-karma/test/api/getComponentDef/x/wirePropertiesInheritance/base.js, packages/integration-karma/test/api/getComponentDef/x/wirePropertiesInheritance/wirePropertiesInheritance.js
=> feat(compiler): add wire config as function

packages/@lwc/engine/src/framework/api.ts, packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/@lwc/engine/src/framework/def.ts, packages/@lwc/engine/src/framework/hooks.ts, packages/@lwc/engine/src/framework/restrictions.ts, packages/@lwc/engine/src/framework/upgrade.ts, packages/@lwc/engine/src/framework/utils.ts, packages/@lwc/engine/src/framework/vm.ts, packages/@lwc/engine/src/framework/wc.ts, packages/@lwc/engine/src/shared/circular-module-dependencies.ts, packages/integration-karma/test/component/auraIntegration/AuraIntegration.spec.js, packages/integration-karma/test/component/auraIntegration/x/childMarkedAsCircular/childMarkedAsCircular.html, packages/integration-karma/test/component/auraIntegration/x/childMarkedAsCircular/childMarkedAsCircular.js, packages/integration-karma/test/component/auraIntegration/x/parent/parent.html, packages/integration-karma/test/component/auraIntegration/x/parent/parent.js, packages/integration-karma/test/component/lockerIntegration/x/child/child.html, packages/integration-karma/test/component/lockerIntegration/x/child/child.js, packages/integration-karma/test/component/lockerIntegration/x/lockerIntegration/lockerIntegration.html
(cherry picked from commit 1ea1d60b379f48eb6870c9fdfd01ee5d03d1ce57)
=> refactor(engine): decouple createElement from engine internals

packages/lwc/README.md
Created a README for the lwc package so we can publish it to https://www.npmjs.com/package/lwc
* Have tests for the proposed changes been added? N/A
W-7408095
=> docs: create README for lwc package

packages/@lwc/engine/src/framework/base-lightning-element.ts, packages/integration-karma/test/component/LightningElement.hasAttribute/index.spec.js, packages/integration-karma/test/component/LightningElement.hasAttribute/x/test/test.js, packages/integration-karma/test/component/LightningElement.hasAttributeNS/index.spec.js, packages/integration-karma/test/component/LightningElement.hasAttributeNS/x/test/test.js, packages/integration-karma/test/component/LightningElement.removeAttribute/index.spec.js, packages/integration-karma/test/component/LightningElement.removeAttributeNS/index.spec.js, packages/integration-karma/test/component/LightningElement.setAttribute/index.spec.js, packages/integration-karma/test/component/LightningElement.setAttributeNS/index.spec.js
=> feat(engine): hasAttribute() on LightningElement

packages/integration-tests/package.json, yarn.lock
=> chore: lwc-integration dependencies update

package.json, packages/@lwc/compiler/package.json, packages/@lwc/rollup-plugin/src/__tests__/index.spec.js, yarn.lock
=> chore: update to rollup 2.7.3

package.json, packages/lwc/package.json
Adding missing module resolution. Renaming root monorepo to avoid conflicts.
=> chore: minor package rename

.circleci/config.yml
This PR simplifies the CircleCI configuration leveraging the new 2.1 manifest capabilities:
W-7391508
=> build: Simplify CircleCI config

packages/integration-karma/scripts/karma-plugins/lwc.js
Currently, when modifying any file used in the Karma test suite, it forces Karma to recompile all the tests. This PR fixes this issue by invalidating only the dependant tests. With PR, the time it takes for the runner to take into account went from 20 seconds down to 500 ms.
Note: I will open a PR on the Karma repo, to open the right APIs to accommodate this. 
W-7391508
=> test(karma): Karma fast watch mode

package.json, yarn.lock
=> chore: update es5-proxy-compat to v0.22.1

packages/@lwc/shared/jest.config.js
This PR adds a missing `jest.config.js` file to `@lwc/shared` package.
W-7391508
=> test(shared): Add missing jest.config

packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/wiring.ts, packages/@lwc/wire-service/package.json, packages/@lwc/wire-service/src/index.ts
=> feat(wire-service): export wire-reform types

.circleci/config.yml
allow integration test suites for PRs from forked repo
W-7717458
=> chore: allow integration test suites for PRs from forked repo

packages/integration-karma/test/wire/legacy-adapters/index.spec.js, packages/integration-karma/test/wire/legacy-adapters/x/sameAdapterDifferentConfig/constants.js, packages/integration-karma/test/wire/legacy-adapters/x/sameAdapterDifferentConfig/sameAdapterDifferentConfig.html, packages/integration-karma/test/wire/legacy-adapters/x/sameAdapterDifferentConfig/sameAdapterDifferentConfig.js
Adding a karma test to capture the issue describe in #1815 
=> test(wire): karma test for multiple same wires with different configs

packages/@lwc/engine-core/src/framework/context-provider.ts
=> fix(wire-context): memory leak in ContextProvider

packages/@lwc/engine-core/src/framework/restrictions.ts
Follow up to the discussion:  https://github.com/salesforce/lwc/pull/1922#discussion_r439403894.
This PR removes the need to check if the content `Node` is an instance of `Element` by moving the portal related restriction directly to the `patchElementWithRestrictions` method. This way, there is no ambiguity regarding the type of node.
W-7532176
=> refactor(engine-core): Remove Element check from restrictions

packages/@lwc/engine-server/src/__tests__/fixtures/for-each-child-nested/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-child-nested/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-child-nested/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-child-nested/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-child-nested/modules/x/for-each-child-nested/for-each-child-nested.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-child-nested/modules/x/for-each-child-nested/for-each-child-nested.js, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-nested/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-nested/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-nested/modules/x/for-each-nested/for-each-nested.html, packages/@lwc/engine-server/src/__tests__/fixtures/for-each-nested/modules/x/for-each-nested/for-each-nested.js, packages/@lwc/engine-server/src/__tests__/fixtures/iterator-block/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/iterator-block/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/iterator-block/modules/x/iterator-block/iterator-block.html, packages/@lwc/engine-server/src/__tests__/fixtures/iterator-block/modules/x/iterator-block/iterator-block.js
Follow up on https://github.com/salesforce/lwc/pull/1953
This PR includes tests for for:each and iterator
W-7552627
=> test: basic tests for for:each and iterator

packages/@lwc/engine-core/src/framework/component.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/integration-karma/test/component/LightningElement.render/index.spec.js, packages/integration-karma/test/component/LightningElement.toString/index.spec.js, packages/integration-karma/test/template/directive-for-each/index.spec.js
Fixes #1033 by implementing the proposed fix in #1496.
W-7111501
=> fix(engine-core): use class name when invoking toString() on component

packages/@lwc/engine-server/src/__tests__/fixtures/lifecycle-hooks/modules/x/lifecycle-hooks/lifecycle-hooks.js, packages/@lwc/engine-server/src/__tests__/fixtures/slotchange/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slotchange/modules/x/receiver/receiver.html, packages/@lwc/engine-server/src/__tests__/fixtures/slotchange/modules/x/receiver/receiver.js, packages/@lwc/engine-server/src/__tests__/fixtures/slotchange/modules/x/slotchange/slotchange.html, packages/@lwc/engine-server/src/__tests__/fixtures/slotchange/modules/x/slotchange/slotchange.js, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/modules/x/slots-nested/slots-nested.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-nested/modules/x/slots-nested/slots-nested.js, packages/@lwc/engine-server/src/__tests__/fixtures/slots-unknown/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-unknown/modules/x/receiver/receiver.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-unknown/modules/x/receiver/receiver.js, packages/@lwc/engine-server/src/__tests__/fixtures/slots-unknown/modules/x/slots-unknown/slots-unknown.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-unknown/modules/x/slots-unknown/slots-unknown.js
More tests for slots.
W-7552627
=> test(engine-server): add slots coverage

packages/lwc/tsconfig.json
The `lwc` dist package has a type definition file which requires DOM types.
W-7391508
=> chore(lwc): specify dom lib for types.d.ts

.git2gus/config.json
git2gus config now points to 230
W-7805790
=> chore: update git2gus settings for 230

packages/lwc/types.d.ts
Currently, `create-lwc-app` [generates the following code inside `src/index.ts`][1] when using typescript:
```typescript
import { createElement } from 'lwc';
import MyApp from 'my/app';
// ... redacted for brevity
createElement('my-app', { is: MyApp });
```
However, since there is no type for `createElement`, developers will see errors in their editors from Typescript indicating that the `'lwc'` package does not export a `createElement` function. Someone [previously tried to add types for `createElement` in a pull request][2], but from reading the PR's comments, this is a [feature, not a bug][3]. `createElement` is a privileged function that only framework internals/special consumers should be calling.
`create-lwc-app` should be updated to generate the following code (suggested by …
=> fix(lwc): add missing `LightningElement.CustomElementConstructor` type

packages/@lwc/engine-dom/src/renderer.ts
Rely on custom element registration and instantiation to detect compat mode.
W-5103036
=> fix: update compat mode detection logic

.circleci/config.yml
https://wiki.saucelabs.com/display/DOCS/2020/08/04/Action+Required%3A+Sauce+Connect+Proxy+and+TLS+Deprecation+Notice%2C+October+5%2C+2020#:~:text=In%20line%20with%20security%20best,as%20of%20October%205%2C%202020
W-7258582
=> chore: update sauce connect proxy

packages/@lwc/template-compiler/src/index.ts
=> feat: Export helpful types from lwc/template-compiler

packages/@lwc/wire-service/README.md
Update the `@lwc/wire-service` README to reflect wire reform changes. Doc now provides a summary and points to lwc.dev.
Fixes #2085
* Have tests for the proposed changes been added? ✅  N/A
W-8379699
=> docs(wire-service): update readme to reflect wire reform

packages/@lwc/synthetic-shadow/src/3rdparty/polymer/text-content.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/portal.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/patch.ts, packages/@lwc/synthetic-shadow/src/shared/utils.ts
This PR removes some of the TypeScript guards from `@lwc/synthetic-shadow`.
=> refactor(synthetic-shadow): Minor TypeScript improvement

packages/@lwc/shared/src/fields.ts, packages/@lwc/shared/src/index.ts, packages/@lwc/shared/src/symbol.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/no-patch-utils.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/@lwc/synthetic-shadow/src/polyfills/document-shadow/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/iframe-content-window/patch.ts, packages/@lwc/synthetic-shadow/src/polyfills/mutation-observer/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/node-ownership.ts
This refactor is being done in this PR to reduce noise in an upcoming PR. These changes do not result in any change in behavior.
W-7258582
=> refactor(synthetic-shadow): move node ownership logic into own module

packages/@lwc/compiler/package.json, packages/@lwc/compiler/src/bundler/__tests__/bundler.spec.ts, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/style-compiler/src/dir-pseudo-class/transform.ts, packages/@lwc/style-compiler/src/postcss-lwc-plugin.ts, packages/@lwc/style-compiler/src/selector-scoping/transform.ts, packages/@lwc/style-compiler/src/selector-scoping/validate.ts, yarn.lock
This PR upgrades the LWC project dependencies.
=> chore: Upgrade dependencies

packages/integration-karma/test/accessibility/LightningElement.focus/index.spec.js, packages/integration-karma/test/shadow-dom/ShadowRoot-properties/ShadowRoot.delegatesFocus.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/event-scope.spec.js
Fixes #1327, fixes #1329, fixes #1139
W-7258582
=> test(integration-karma): enable tests for fixed issues

packages/@lwc/engine-dom/src/env/dom.ts, packages/@lwc/synthetic-shadow/src/env/dom.ts, packages/@lwc/synthetic-shadow/src/env/element.ts, packages/@lwc/synthetic-shadow/src/env/event-target.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/event-target.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/polyfills/click-event-composed/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-listener/polyfill.ts
This clean up occurred in a different PR but giving it its own PR to reduce noise.
* ✅ `No, it does not introduce breaking changes.`]
W-8384275
=> refactor(synthetic-shadow): consolidate EventTarget prototype methods

packages/@lwc/engine-core/src/framework/api.ts
This PR fixes an issue where the `$shadowResolver$` resolver property is added on all the nodes regardless if the engine is running in native or in synthetic shadow. This avoids issues, where multiple versions of the LWC engine are loaded on the same document and one version of LWC, is using native shadow and the other one is using synthetic shadow.
=> fix(engine): add check of $shadowResolver$ in native shadow

packages/@lwc/synthetic-shadow/src/polyfills/event-target/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/window-event-target/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/event-target.ts
Pass arguments down intact where possible to facilitate native validation.
=> refactor: pass arguments through to native methods

packages/lwc/types.d.ts
=> fix: invalid wire decorator type definition post wire reform

.circleci/config.yml
Enabling integration test for forked repos using context to avoid exposing sauce lab secrets.
* ✅ `No, it does not introduce breaking changes.
W-8434068
=> build: enable integration tests for forked repos

.eslintrc, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-target/polyfill.ts, packages/@lwc/synthetic-shadow/src/polyfills/window-event-target/polyfill.ts, packages/@lwc/synthetic-shadow/src/shared/event-target.ts, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.dispatchEvent.spec.js, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.removeEventListener.spec.js, packages/integration-karma/test/shadow-dom/EventTarget-methods/x/container/container.html, packages/integration-karma/test/shadow-dom/EventTarget-methods/x/container/container.js
add integration tests for EventTarget addEventListener, removeEventListener, dispatchEvent
Co-Authored-By: Sumit Jaiswal <sumit.s.j.jaiswal@gmail.com>
W-8597107
fix #2134
=> test(integration-karma): add integration tests for EventTarget

packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/index.ts
Refactoring a code path that had some redundant logic. No specific reason to fix this now. Noticed the room for improvement and fix it.
=> fix(template-compiler): refactor logic to simplifiy attribute name handling

packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/integration-karma/test/shadow-dom/ShadowRoot-properties/ShadowRoot.spec.js
=> refactor(synthetic-shadow): Move ShadowRoot method restrictions to synthetic-shadow

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/shared/event-target.ts
Reusable utility method `shouldInvokeListener()`.
=> refactor(synthetic-shadow): reusable utility method shouldInvokeListener()

packages/@lwc/features/src/flags.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/@lwc/synthetic-shadow/src/shared/event-target.ts
guard non-composed event propagation fix with feature flag. By default fix will be enabled.
=> fix(synthetic-shadow): guard non-composed event propagation fix with feature flag

babel.config.js
Dropped all the unused plugins from root `babel.config.js`.
=> chore: Simplify root Babel config

packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js
Automation for https://github.com/salesforce/lwc/issues/2253
@W-8928394
=> test: assert that multiple identical listeners on same target are discarded

packages/@lwc/compiler/src/__tests__/fixtures/expected-dynamic-component.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-dynamic/flatten-child/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-dynamic/only-child/expected.js, packages/@lwc/template-compiler/src/__tests__/parser.spec.ts, packages/@lwc/template-compiler/src/codegen/formatters/module.ts, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/config.ts, packages/@lwc/template-compiler/src/index.ts, packages/@lwc/template-compiler/src/shared/ir.ts
- Group all the IR related methods in a single file
- Remove unused types
- Group helpers in a logic fashion
=> refactor(template-compiler): Misc. restructuring

.git2gus/config.json
Updates git2gus default build to 234(Winter22)
W-9048049
=> chore: update git2gus for 234 branch

packages/@lwc/synthetic-shadow/src/faux-shadow/events.ts, packages/integration-karma/test/shadow-dom/EventTarget-methods/EventTarget.addEventListener.spec.js
Fixes #2253 
Supersedes #2261
This bug fix introduces an observable change in behavior.
W-8928394
=> fix(synthetic-shadow): discard duplicate listeners on shadow roots and host elements

packages/integration-karma/test/shadow-dom/stylesheet/x/multiTemplates/a.css, packages/integration-karma/test/shadow-dom/stylesheet/x/multiTemplates/b.css
cherrypicks d673b48d4ab8aee835da533be78db4f7f372fbcb
=> test: fix firefox flapper in native shadow style test (#2305)

packages/integration-tests/src/components/dom/test-inner-text/integration/inner-text/inner-text.js
Addresses this [comment](https://github.com/salesforce/lwc/pull/2330/files/84bda2e4b003fecb63b11df6587251447ffc1566#r632847303) from a previous review. 
=> test(integration-test): fixes incorrect inner-text test

packages/integration-karma/test/light-dom/multiple-templates/x/multi/multi.js
=> test: move component to new syntax for Light DOM

packages/@lwc/engine-dom/src/env/dom.ts
=> chore(engine-dom): remove unused env/dom module

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/hooks.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/apis/is-node-from-template.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/shared/src/keys.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-token.ts
=> refactor: RenderMode and ShadowMode instead of isLightRenderModeVM and syntheticShadow

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/integration-karma/test/light-dom/events/index.spec.js, packages/integration-karma/test/light-dom/events/x/lightChild/lightChild.html, packages/integration-karma/test/light-dom/events/x/lightChild/lightChild.js, packages/integration-karma/test/light-dom/events/x/lightContainer/lightContainer.html, packages/integration-karma/test/light-dom/events/x/lightContainer/lightContainer.js, packages/integration-karma/test/light-dom/events/x/shadowChild/shadowChild.html, packages/integration-karma/test/light-dom/events/x/shadowChild/shadowChild.js, packages/integration-karma/test/light-dom/events/x/shadowContainer/shadowContainer.html, packages/integration-karma/test/light-dom/events/x/shadowContainer/shadowContainer.js
Add tests for events in Light DOM.
=> test: add tests for Light DOM events

yarn.lock
Merged #2370 immediately after resolving merge conflicts in package.json, causing me to miss these yarn.lock updates.
No
W-7258582
=> fix: yarn.lock missed updates

packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts
Replace complex `Array.prototype.reduce` logic with `Array.prototype.filter` logic.
=> refactor(synthetic-shadow): Simplify array reduce with array filter

packages/@lwc/template-compiler/src/parser/index.ts
We were filtering the slots logic earlier because we wanted to include `style` and `class` attributes as well. Now, since we are not doing any special handling of `style` and `class` attributes, we can move this to `applySlot`.
=> refactor: move renderMode slot logic to applySlot

packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-iterator/error-for-each-mix/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-iterator/error-for-each-mix/metadata.json, packages/@lwc/template-compiler/src/parser/index.ts
=> fix: Prevent usage of `for:each` and `iterator:*` directives on the same element

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/engine-core/src/framework/vm.ts
Replace `invokeComponentRenderedCallback` with `invokeComponentCallback`
=> refactor(engine-core): Remove duplicate code in `invoker.ts`

packages/@lwc/template-compiler/src/index.ts, packages/@lwc/template-compiler/src/shared/types.ts
Minor changes to make lwc-platform happy.
W-9698817
=> chore(template-compiler): update exports for use in lwc-platform

packages/@lwc/synthetic-shadow/src/env/dom.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/polyfills/event/polyfill.ts, packages/integration-karma/test/native-shadow/Event-methods/Event.composedPath.spec.js, packages/integration-karma/test/native-shadow/Event-methods/x/synthetic/synthetic.js
Cherry-pick of #2480
Fixes #2379
No
W-9493000
=> fix(synthetic-shadow): invoke native composedPath() for native shadow dom

packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts
Update the type for FeatureFlagMap
No
=> fix(features): add ENABLE_WIRE_SYNC_EMIT to FeatureFlagMap interface

.circleci/config.yml, packages/integration-karma/scripts/karma-plugins/env.js, packages/integration-karma/scripts/shared/options.js, packages/integration-karma/test/api/isNodeFromTemplate/index.spec.js, packages/integration-karma/test/light-dom/synthetic-shadow/index.spec.js, packages/integration-karma/test/rendering/elements-are-not-recycled/index.spec.js, packages/integration-karma/test/shadow-dom/Element-properties/Element.assignedSlot.spec.js, packages/integration-karma/test/shadow-dom/MutationObserver/MutationObserver.spec.js, packages/integration-karma/test/shadow-dom/Node-properties/Node.compareDocumentPosition.spec.js, packages/integration-karma/test/shadow-dom/event-in-shadow-tree/propagation.spec.js
Add another CI run specifically for mixed shadow mode.
W-9726385
=> chore: enable mixed shadow mode ci run

packages/@lwc/engine-core/package.json, yarn.lock
Updates `observable-membrane` to `1.1.3`.
Previous PR: #2490 
There are [numerous changes between 1.0.1 and 1.1.3](https://github.com/salesforce/observable-membrane/compare/v1.0.1...v1.1.3), but the only one that seems observable to me is this change to improve error messages: https://github.com/salesforce/observable-membrane/commit/415b2bdebaabd735502fada3bb9fb36583ce755d
=> chore: update observable-membrane

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Release branch for `2.6.0`. 
W-7258582
=> release: 2.6.0

.nucleus.yaml
Enables Nucleus for all PRs.
W-10179854
=> chore: enable Nucleus for all PRs

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts, packages/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/restrictions/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/scoped-ids/scoped-ids.spec.js, packages/integration-karma/test/mixed-shadow-mode/slotting/index.spec.js, packages/integration-karma/test/mixed-shadow-mode/transitivity/index.spec.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-native-styled-component-create-10k-same.benchmark.js, packages/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-styled-component/ss-native-styled-component-create-1k-different.benchmark.js
Enable mixed shadow mode by default.
No
No
W-10256357
=> refactor(features): enable mixed shadow mode by default

packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/shared/node-ownership.ts, packages/integration-karma/test/light-dom/slotting/index.spec.js, packages/integration-karma/test/light-dom/synthetic-shadow/index.spec.js, packages/integration-karma/test/light-dom/synthetic-shadow/x/consumer/consumer.html, packages/integration-karma/test/light-dom/synthetic-shadow/x/lightContainerDeepShadow/lightContainerDeepShadow.html, packages/integration-karma/test/light-dom/synthetic-shadow/x/lightContainerDeepShadow/lightContainerDeepShadow.js, packages/integration-karma/test/light-dom/synthetic-shadow/x/lightContainerDeeperShadow/lightContainerDeeperShadow.html, packages/integration-karma/test/light-dom/synthetic-shadow/x/lightContainerDeeperShadow/lightContainerDeeperShadow.js, packages/integration-karma/test/synthetic-shadow/element-api/element-api.spec.js
Related: #2502 #2540
This reverts commit 0de7ef2685fd26f0ba7d56987c8562a880922fe8.
Fixes #2425
The observable changes have been described elsewhere.
W-10059718
=> fix(synthetic-shadow): fix light DOM serialization

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: bump to 2.7.2

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Release commit for 2.5.12
W-10459160
=> chore: bump to 2.5.12

packages/@lwc/compiler/src/transformers/__tests__/transform-javascript.spec.ts, packages/@lwc/compiler/src/transformers/javascript.ts
This reverts commit 30a8bd7f52f394995e431d60be3c936f1090bee1.
W-10129064
=> revert(compiler): revert removal of object spread plugin

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: v2.9.0

packages/@lwc/template-compiler/src/__tests__/fixtures/svg/stranded-open-path/expected.js
Accidentally broke a snapshot test in #2684 because we didn't update to master before merging the PR. (My bad.)
=> test: update snapshot test

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: v2.10.0

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/src/framework/component.ts, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-karma/test/component/default-export/index.spec.js, packages/integration-karma/test/component/default-export/x/component/component.html, packages/integration-karma/test/component/default-export/x/component/component.js, packages/integration-karma/test/component/default-export/x/component/nil.js, packages/integration-karma/test/component/default-export/x/component/string.js, packages/integration-karma/test/component/default-export/x/component/undef.js, packages/integration-karma/test/component/default-export/x/component/zero.js, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: release v2.11.1 @W-7258582

.nucleus.yaml
This downstream has flapped twice recently. I've filed bugs on the team. Let's remove it for now.
=> chore(nucleus): remove flapping downstreams

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Create a new minor version for CLCO
=> chore: bump version to v2.12.0

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: bump version to v2.12.1

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Upgrade LWC package versions to `2.13.0`.
=> chore: Bump version to v2.13.0

package.json, yarn.lock
Weekly `devDependencies` upgrade.
=> chore: `devDependencies` upgrade

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: bump version to v2.13.3

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/__tests__/fixtures/parsing-errors/invalid-id/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/static-id-in-iteration/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/static-id-in-iteration/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/regression/static-id-in-iteration/metadata.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
Backport of https://github.com/salesforce/lwc/pull/2830
=> fix: relax static id validation in iterations @W-11130708

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: release v2.14.0 (#2846) @W-7258582

packages/@lwc/template-compiler/README.md
- fix typo in template compiler readme
=> docs: fix typo in template compiler readme

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/HTMLSlotElement.slotchange.spec.js, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/x/child/child.html, packages/integration-karma/test/shadow-dom/HTMLSlotElement-events/x/child/child.js, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> fix: fire slotchange when slot is removed. @W-11170043

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json, yarn.lock
Address minimist security vulnerability by updating it to 1.2.6
=> chore: update minimist to v1.2.6 @W-11164696

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
[W-7258582](https://gus.lightning.force.com/a07B00000087ImNIAU)
=> chore: release v2.15.0

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
=> chore: release v2.16.0

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/integration-karma/package.json, packages/integration-tests/package.json, packages/lwc/package.json, packages/perf-benchmarks-components/package.json, packages/perf-benchmarks/package.json
[W-11254381](https://gus.lightning.force.com/a07EE00000ydqfmYAA)
=> chore: release v2.17.0

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json
Release version 2.19.0. Contains a compiler change.
=> chore: release v2.19.0

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json
Cut a new release for `2.19.1`.
=> chore: Release 2.19.1

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json
=> chore: release v2.20.2

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json
=> chore: release v2.20.3

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Minor version bump for 242 CLCO
W-11476649
=> chore: minor version bump for 242 CLCO

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
PR for nucleus to release
W-11476649
=> chore: minor version bump for 242 CLCO (#2943)

.git2gus/config.json, .nucleus.yaml
=> chore: update git2gus and nucleus for 242 clco

yarn.lock
Upgrades:
- @types/node
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- lerna
- rollup
Also recalculated `@babel` dependencies to trim the tree.
=> chore: weekly upgrade

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.22.0

.nucleus.yaml
=> chore(nucleus): remove experience-container-validate

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.23.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Weekly release
See #3037 
W-11466097
=> chore: release v2.23.3

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.23.4

.nucleus.yaml
Some downstreams were recently renamed or removed.
=> chore(nucleus): update removed/renamed downstreams

packages/@lwc/engine-dom/src/renderer-factory.ts
=> docs: improve docs for renderer-factory

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Weekly release v2.23.6
See #2977
W-11466097
=> chore: release v2.23.6

packages/@lwc/integration-karma/scripts/karma-configs/hydration/sauce.js, packages/@lwc/integration-karma/scripts/karma-configs/test/sauce.js
=> chore(integration-karma): disable firefox for now (winter23)

.nucleus.yaml
This PR updates the .`nucleus.yaml` file to include the winter23 dist tag.
=> chore: add winter23 dist tag to npm-publish-release

lerna.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Version bump for v2.20.6 to be backported.
See #3080 
W-11824865
=> chore: release v2.20.6 @W-11824865@

packages/@lwc/integration-karma/scripts/karma-configs/hydration/sauce.js, packages/@lwc/integration-karma/scripts/karma-configs/test/sauce.js, packages/@lwc/integration-karma/scripts/karma-configs/utils.js
=> chore: update geckodriver version for firefox (#3089) (winter23)

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.25.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.25.1

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Includes https://github.com/salesforce/lwc/compare/v2.25.1...master
W-11466097
=> chore: release v2.26.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
create a new minor version for scope slots feature
W-11469044
=> chore: release v2.27.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.28.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.28.1

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.29.0

.nucleus.yaml
=> chore(nucleus): remove failing downstreams

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.30.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.30.1

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
(chore: release v2.30.2)
[W-11466097](https://gus.lightning.force.com/a07EE000011woQMYAY)
=> chore: release v2.30.2

packages/@lwc/engine-core/src/framework/modules/attr-unless-prop.ts
=> chore(engine-core): setProperty() instead of direct assignment

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.30.3

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.31.0

.git2gus/config.json, .nucleus.yaml, package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: update Nucleus and git2gus for 244 clco

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.32.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.32.1

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Backport release 
* ✅ No, it does not introduce a observable change.
W-12107374
=> chore: release v2.31.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Weekly lwc release.
W-11466097
=> chore: release v2.33.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.34.0 @W-11466097

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.35.0

.nucleus.yaml
This reverts commit 142cbe04796f9100c4f373c69b10e4c9ddd506f1.
lwc-platform should be working now.
=> chore: revert "chore(nucleus): remove lwc-platform for now"

packages/@lwc/engine-core/src/framework/hot-swaps.ts, packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/utils.ts
Slight improvement on our code coverage.
=> refactor: refactor prod assertions to improve coverage

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.35.1

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.31.3

yarn.lock
Security vulnerability updates.
=> chore: update json5 to address vuln

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release v2.31.4
No
No
W-12246411
=> chore: release v2.31.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.36.0

yarn.lock
=> chore: update yarn.lock (backport)

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.31.6

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.37.3 @W-12246411@

packages/@lwc/aria-reflection/scripts/rollup.config.js, packages/@lwc/aria-reflection/tsconfig.json, packages/@lwc/engine-core/scripts/rollup.config.js, packages/@lwc/engine-core/tsconfig.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-dom/scripts/rollup.config.js, packages/@lwc/engine-dom/tsconfig.json, packages/@lwc/engine-server/scripts/rollup.config.js, packages/@lwc/engine-server/tsconfig.json, packages/@lwc/features/scripts/rollup/rollup.config.js, packages/@lwc/features/tsconfig.json, packages/@lwc/shared/scripts/rollup/rollup.config.js, packages/@lwc/shared/tsconfig.json, packages/@lwc/synthetic-shadow/scripts/rollup/rollup.config.js, packages/@lwc/synthetic-shadow/tsconfig.json, packages/@lwc/wire-service/scripts/rollup/rollup.config.js, packages/@lwc/wire-service/tsconfig.json, packages/lwc/scripts/utils/rollup.js
=> feat: enable sourcemaps generation

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.38.0

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.31.7

.nucleus.yaml
Some of the repos changed names. Also added lightning-components back.
=> chore(nucleus): update required downstreams

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Dynamic components release.
See #3381
=> chore: release v2.39.0

packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/rollup-plugin/src/index.ts, packages/@lwc/template-compiler/src/__tests__/config.spec.ts, packages/@lwc/template-compiler/src/config.ts
Adding a flag for template expressions, separate from #3376.
W-12177613
=> chore: add feature flag for template expressions

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release experimental template expressions flag.
W-12177613
=> chore: release v2.39.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Create a new minor release to allow usage of scoped slots without requiring any flags to be set.
W-12134716
=> chore: release v2.40.0 @ W-12134716

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.40.1

package.json, packages/@lwc/aria-reflection-polyfill/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.31.8 (backport)

.nucleus.yaml
=> chore(nucleus): remove lds-lightning-platform

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.41.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.41.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.43.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.44.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.45.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release following #3480.
W-13044995
=> chore: release v2.45.2

.nucleus.yaml
=> chore(nucleus): remove talon-template-byo

.nucleus.yaml
=> chore(nucleus): add webruntime to required downstreams

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v2.45.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
New patch version with a bug fix related to scoped slots
W-13206150
=> chore: release v2.45.5

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
New patch release with the scoped slots fix backport.
W-13461672
=> chore: release v2.41.4 @W-13461672

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.46.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.47.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.48.0

package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/template-compiler/package.json, playground/package.json, yarn.lock
=> chore: update non-breaking deps

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.49.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.49.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v2.50.0

.nucleus.yaml
See [thread](https://salesforce-internal.slack.com/archives/C5W3E40TC/p1687454794968449?thread_ts=1686240532.763579&cid=C5W3E40TC)
=> chore(nucleus): remove ui-omniscript-components

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
New patch version to include security vulnerability fixes
W-13699580
=> chore: v3.0.1

packages/lwc/index.d.ts
Type safe template references. Fixes #3597
No
No
W-13756322
=> chore: type safe template references

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v3.0.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Minor version bump for 248 CLCO
W-13772683
=> chore: release v3.1.0 for CLCO

yarn.lock
=> chore: weekly dependency update

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v3.1.1

packages/@lwc/engine-core/src/framework/stylesheet.ts
[Context](https://salesforce-internal.slack.com/archives/G0210EW0V2R/p1690913377442249?thread_ts=1690901239.213789&cid=G0210EW0V2R)
=> fix: improve warning for unscoped light DOM styles

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v3.1.2

packages/@lwc/perf-benchmarks/best.config.js, packages/@lwc/perf-benchmarks/package.json, yarn.lock
Updates Best. [Context](https://salesforce-internal.slack.com/archives/C023KEX1F6G/p1690991076062589)
=> chore: update best

.circleci/config.yml, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-tests/scripts/build.js, packages/@lwc/integration-tests/scripts/wdio.local.conf.js, yarn.lock
Updates WebDriverIO. Due to [some changes](https://webdriver.io/blog/2023/07/31/driver-management/) to how it handles browser drivers, we needed to change our config to make it work.
=> chore: update webdriverio

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v3.1.3

packages/@lwc/compiler/package.json, yarn.lock
Title says it. 
* ✅ No, it does not introduce a breaking change. 
=> chore: upgrade Locker Version v0.19.9 

nx.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, playground/package.json, scripts/tasks/check-and-rewrite-package-json.js
Supersedes #3677 as these changes don't contain whitespace modifications. I considered making changes on top of #3677 but it was much easier to start with the original file.
W-13980320
=> chore: nx repair

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v3.2.0

.nucleus.yaml
=> chore(nucleus): test removing image override

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v3.3.0 @W-14106783

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json, yarn.lock
=> chore: v3.3.2 @W-14106783

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v3.3.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v3.4.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v3.0.3

packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/integration-karma/test/act/act-components/README.md
This PR removes references to internal-facing documents, see W-14172884 for more details.
W-14172884
=> chore: remove references to internal docs

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Weekly version bump.
#3698 changes errors to warnings in certain scenarios. 
W-14174850
=> chore: release v3.5.0

packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/integration-karma/test/act/act-components/README.md
=> chore: remove references to internal docs (#3743) (winter24)

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v3.6.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release v3.7.0 with observable changes.
Some observable changes due to parse5 upgrade. However, they are non-breaking and generally more permissive than the preexisting behavior.
W-14260063
=> chore: release v3.7.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release v3.7.1 with a bug fix.
* ⚠️ Yes, it does introduce a breaking change.
This is a bug fix and technically breaking. But this shouldn't be disruptive for anyone consuming the effected APIs, only helpful.
See above.
W-14260063
=> chore: release v3.7.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v3.7.2

packages/@lwc/engine-server/src/__tests__/fixtures/face-callback/modules/face/container/container.html
=> test: fix spurious console error

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Contains several breaking changes, which will be documented in the [GitHub releases page](https://github.com/salesforce/lwc/releases).
=> chore: release v4.0.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v4.0.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Major version bump, to accommodate `VFragment` implementation.
See details in #3846.
See details in #3846.
W-14408593
=> chore: release v5.0.0

.github/workflows/karma.yml
=> chore(ci): parallelize karma tests

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v5.0.2

README.md
This PR replaces the circleci badge with github actions badges on the `readme.md`.
=> chore: add github action badges

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
A new patch release(v5.2.0)
W-14646095
=> chore: v5.2.0 @W-14646095

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/if-block/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/runtime-checks/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slot-fowarding/slots/forwarding/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slot-fowarding/slots/reactivity/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slot-fowarding/slots/reactivity/x/lightLeaf/lightLeaf.js, packages/@lwc/integration-karma/test/light-dom/slot-fowarding/slots/reactivity/x/shadowLeaf/shadowLeaf.js, packages/@lwc/integration-karma/test/light-dom/slotting/index.spec.js, packages/@lwc/shared/src/api-version.ts
This PR adds api versioning to #3883
W-14356488
=> refactor: add api versioning to light dom slot forwarding

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v5.2.1

packages/@lwc/engine-server/README.md
After the change #3594 changes, We can't import renderComponent from LWC. So updating the Doc to reflect the same. 
NA
=> docs(lwc-engine): update README example

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v5.0.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Minor version bump due to compiler change.
=> chore: release v5.3.0

.eslintrc, scripts/rollup/rollup.config.js
=> chore(copyright): update rollup config to use correct copyright

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.1.0

packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/index.spec.js, packages/@lwc/integration-karma/test/component/face-callbacks/index.spec.js, packages/@lwc/integration-karma/test/custom-elements/index.spec.js
Backport of #3984
See #3984
W-14983600
=> refactor: disable `formAssociated` on custom element constructor `spring24`

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Backport release for #3985
See #3985
=> chore: release v5.0.8

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/any/any.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/native/native.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/none/none.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/reset/reset.js
Backport of https://github.com/salesforce/lwc/pull/3980
=> feat: add reporting for shadowSupportMode (#3980)

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Contains signal implementation and some bug fixes hence, a minor version bump to `v6.2.0`
=> chore: release v6.2.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.2.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release to enable `ElementInternals` and face.
W-15001648
=> chore: release v6.3.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v6.3.2

packages/@lwc/engine-server/src/__tests__/html-serialization.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/rootDir/rootDir.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/warnings/warnings.spec.ts, yarn.lock
Basically the same as #4062 but will actually pass CI
=> chore: bump transitive deps

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.3.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v5.0.10

.nucleus.yaml
=> ci: update configs for spring24

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Weekly release.
See the following:
- #4103
- #4098
- #4094
- #4084
- #4071
- #4102
W-15276750
=> chore: release v6.4.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.4.1

.git2gus/config.json, .nucleus.yaml, package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
`summer24` CLCO tasks:
1. Bump `git2gus` version.
2. Bump `.nucleus.yaml` release branches.
3. Minor version bump for LWC.
W-15276750
=> chore: summer24 CLCO

.nucleus.yaml
Update the `summer24` branch dist tag.
W-15276750
=> chore: add summer24 git tag to nucleus.yaml

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.5.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release containing some type-checking fixes and HMR APIs in `engine-server`
W-15369047
=> chore: release v6.5.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v6.5.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v6.6.0

packages/@lwc/integration-karma/test/synthetic-shadow/shadow-token/index.spec.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-table-ss/ss-table-create-10k.benchmark.js
Extracted the test and benchmark from #4185 because I'm not confident in the perf optimization anymore, but I do like having the extra tests.
I also went ahead and moved the unit test from Jest to Karma, so that I didn't need to muck with our Jest coverage settings.
=> test(synthetic-shadow): add more tests/benchmarks

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.6.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.6.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.6.3

.nucleus.yaml
`Skilling-and-Enablement/ui-ses-experience-cloud` is the same as `Skilling-and-Enablement/ui-external-enablement`, the project was just renamed at some point.
=> chore(nucleus): remove duplicate downstream

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.6.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release PR for #4222 
W-15822925
=> chore: release v6.4.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.4.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.6.5

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.4.4

.nucleus.yaml
As discussed in dev sync, let's be sure to test webruntime (CLWR).
=> chore(nucleus): enable communities/webruntime

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/util.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicForwardedSlottable/dynamicForwardedSlottable.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicForwardedSlottable/dynamicForwardedSlottable.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicSlotForwarding/dynamicSlotForwarding.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicSlotForwarding/dynamicSlotForwarding.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/forwardedSlottable/forwardedSlottable.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/forwardedSlottable/forwardedSlottable.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotForwarding/slotForwarding.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotForwarding/slotForwarding.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotee/slotee.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotee/slotee.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slottable/slottable.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slottable/slottable.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/standardSlotting/standardSlotting.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/standardSlotting/standardSlotting.js
=> fix: prevent prematurely cloning light dom slot vnodes (summer24)

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release PR for #4258
W-15870024
=> chore: release v6.6.6

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release PR for #4262
W-15941045
=> chore: release v6.4.5

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release for #4278 and #4271
W-15963098
=> chore: release v6.7.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.7.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release `v6.7.2`

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json, yarn.lock
Yes, this will be documented. See [prerelease notes](https://github.com/salesforce/lwc/releases/tag/v7.0.0-prerelease)
=> chore: release v7.0.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.0.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.0.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.0.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.0.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.0.5

.github/workflows/karma.yml
This just seems like a good thing to test. In the near future, some envs may have native lifecycle and others may have synthetic lifecycle.
=> test(ci): test hydration with synthetic lifecycle

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.1.0

.vscode/settings.json
Makes the eslint extension for vs code pick up our flat config, so that we get all the usual goodness.
=> chore: configure vscode to use flat config

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.1.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.1.2

.husky/pre-push
As of Husky v9.1.1 it is automatically changing this file to remove the shebang (maybe due to https://github.com/typicode/husky/commit/b9f5889511712846f0e6178124e6dc6334adc758?). In any case, it keeps trying to update it, so let's commit it so we can move on with our lives.
=> chore: update husky config file

packages/@lwc/engine-core/src/framework/stylesheet.ts
This is a micro-optimization for sure, but it does have a small impact. It reduces the number of unnecessary arrays we create in `getStylesheetsContent` by optimizing for the common case where a template has no stylesheets. (Occurs for roughly 50% of components in core.)
Just to get an idea, here are the numbers from our Karma tests (measured by code coverage):
- No stylesheets: 7958
- `tmpl.stylesheets` only: 375
- `static stylesheets` only: 18
- Both: 22
I had a hard time measuring the impact because it's (admittedly) small, but Firefox shows a <1% improvement in `dom-tablecmp-create-10k`, which renders 10k components without stylesheets:
=> perf(engine-core): optimize `getStylesheetsContent`

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.2.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.2.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.2.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.2.5

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.2.6

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v7.1.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.0.0 @W-16645496@

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.1.0

packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/modules/x/stylish/dazzling.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/modules/x/stylish/dazzling.html, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/modules/x/stylish/dazzling.scoped.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/modules/x/stylish/glamorous.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/modules/x/stylish/snazzy.scoped.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets-dynamic-render/modules/x/stylish/stylish.js, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/modules/x/stylish/glamorous.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/modules/x/stylish/snazzy.scoped.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/modules/x/stylish/stylish.html, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/modules/x/stylish/stylish.js
The point of this is to just add some more tests that the `@lwc/ssr-compiler` is known to fail.
=> test(ssr): add `static stylesheets` fixtures

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.1.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.1.2

packages/@lwc/ssr-compiler/src/compile-template/ir-to-es.ts
[W-16872176](https://gus.lightning.force.com/a07EE000022ItdlYAC)
=> fix(ssr-compiler): define IR to ES map for lwc:external nodes

packages/@lwc/ssr-compiler/src/compile-js/stylesheet-scope-token.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/index.ts, packages/@lwc/ssr-compiler/src/shared.ts
[W-16872186](https://gus.lightning.force.com/a07EE000022IuwZYAS)
=> fix(ssr-compiler): generate scope tokens using component name and namespace

packages/@lwc/ssr-runtime/src/index.ts
Fixes implementation based on previous incorrect assumptions.
=> fix(ssr-compiler): setAttribute and getAttribute

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.1.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v7.1.5 @W-16948407

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.2.0

packages/@lwc/integration-karma/scripts/karma-plugins/hydration-tests.js
Fixes #4577
I finally got annoyed enough by these warning messages that I fixed it. 😛 
=> test(hydration): ignore expected console warnings

packages/@lwc/ssr-compiler/src/__tests__/allowed-lwc-imports.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/lightning-element.ts
Builds on https://github.com/salesforce/lwc/pull/4670 so that one should be merged first.
[W-14977927](https://gus.lightning.force.com/a07EE00001jYSpNYAW)
=> fix(ssr-compiler): hide private implementations

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release `v8.3.0`

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.4.0

.github/workflows/integration.yml, .github/workflows/unit.yml, packages/@lwc/integration-tests/src/components/accessibility/test-tab-navigation-tabindex-negative/tab-navigation-tabindex-negative.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-focusable-coverage/focusable-coverage.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-issue-1031/issue-1031.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-negative-after-inside-click/tabindex-negative-after-inside-click.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-negative/tabindex-negative.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-toggle/tabindex-toggle.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero-after-inside-click/tabindex-zero-after-inside-click.spec.js, packages/@lwc/integration-tests/src/components/delegates-focus-tab-navigation/test-tabindex-zero/tabindex-zero.spec.js
Bumps WDIO and benchmark smoke tests to use Chrome ~v130~ v129.
=> chore(ci): update chrome

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.5.0

packages/@lwc/ssr-compiler/src/__tests__/estemplate.spec.ts, packages/@lwc/ssr-compiler/src/estemplate.ts
Also makes it more clear what was the expected type and what was the actual type.
=> fix(ssr-compiler): update estemplate spec

packages/@lwc/ssr-runtime/src/__tests__/stubs.spec.ts
`master` is broken due to two commits going in that are incompatible with each other.
=> chore: fix test broken due to merge

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: v8.6.0

packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/error.txt, packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/modules/x/component/component.js
Remove test scenarios that throw exceptions
[W-17150202](https://gus.lightning.force.com/lightning/r/a07EE000024xRezYAE/view)
Co-authored-by: Nolan Lawson <nlawson@salesforce.com>
Co-authored-by: James Tu <jmsjtu@gmail.com>
=> test(ssr-compiler): remove test scenarios that throw exceptions

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts
Partially addresses #4793.
This is step 1: in our tests, we need to make sure that all our Rollup warnings are present and accounted for. Any unknown warnings should result in an `Error` rather than being ignored.
=> test(ssr): account for all Rollup warnings

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.7.0

packages/@lwc/ssr-compiler/package.json, yarn.lock
I should stop hitting the auto-merge button. Addresses [this comment](https://github.com/salesforce/lwc/pull/4807#discussion_r1837234511).
=> chore: remove unused utility dependency

packages/@lwc/engine-server/src/__tests__/fixtures/superclass/basic/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/basic/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/basic/modules/x/component/component.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/basic/modules/x/fancyElement/fancyElement.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/basic/modules/x/fancyElement/fancyElement.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/mixin/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/mixin/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/mixin/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/mixin/modules/x/component/component.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/mixin/modules/x/fancyMixin/fancyMixin.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/override/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/override/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/override/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/override/modules/x/component/component.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/override/modules/x/fancyElement/fancyElement.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/override/modules/x/fancyElement/fancyElement.js
Add tests to help with https://github.com/salesforce/lwc/issues/4818
There were previously no tests for this in `engine-server`.
=> test(ssr): basic tests for superclasses and mixins

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.8.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.9.0

packages/@lwc/engine-dom/package.json
- Surfaced while working on #4897 
- Explanation: [Creating a non-flat node_modules directory](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory)
File:
https://github.com/salesforce/lwc/blob/0b0f97bf14fb2bf7004ed0468db55b4f564a1db6/packages/%40lwc/engine-dom/src/index.ts#L9
=> fix(engine-dom): missing @lwc/features dependency

packages/@lwc/engine-server/package.json
- Surfaced while working on #4897 
- Explanation: [Creating a non-flat node_modules directory](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory)
File:
https://github.com/salesforce/lwc/blob/4a21fa86c9c901638b3046cb3bb35a515d5e623a/packages/%40lwc/engine-server/src/index.ts#L8
=> fix(engine-server): missing @lwc/features dependency

.nucleus.yaml
See [relevant CLCO instructions](https://salesforce.quip.com/4fB6A3Cb7PGp#LGYACA5rjk3).
=> chore(nucleus): update branches for CLCO

.nucleus.yaml
See relevant CLCO instructions [here](https://salesforce.quip.com/4fB6A3Cb7PGp#LGYACA5rjk3).
=> chore(nucleus): set npm tag for `spring25`

packages/@lwc/engine-core/src/framework/hydration.ts
=> fix(perf): avoid creating unnecessary sets @W-17361878

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.12.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.12.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.12.2 @W-17485572

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.12.3

LICENSE-CORE.md, LICENSE.md, packages/@lwc/aria-reflection/LICENSE.md, packages/@lwc/babel-plugin-component/LICENSE.md, packages/@lwc/compiler/LICENSE.md, packages/@lwc/engine-core/LICENSE.md, packages/@lwc/engine-dom/LICENSE.md, packages/@lwc/engine-server/LICENSE.md, packages/@lwc/errors/LICENSE.md, packages/@lwc/features/LICENSE.md, packages/@lwc/integration-karma/LICENSE.md, packages/@lwc/integration-tests/LICENSE.md, packages/@lwc/integration-types/LICENSE.md, packages/@lwc/module-resolver/LICENSE.md, packages/@lwc/perf-benchmarks-components/LICENSE.md, packages/@lwc/perf-benchmarks/LICENSE.md, packages/@lwc/rollup-plugin/LICENSE.md, packages/@lwc/shared/LICENSE.md, packages/@lwc/signals/LICENSE.md, packages/@lwc/ssr-compiler/LICENSE.md, packages/@lwc/ssr-runtime/LICENSE.md, packages/@lwc/style-compiler/LICENSE.md, packages/@lwc/synthetic-shadow/LICENSE.md, packages/@lwc/template-compiler/LICENSE.md, packages/@lwc/types/LICENSE.md, packages/@lwc/wire-service/LICENSE.md, packages/lwc/LICENSE.md
To quote @nolanlawson, "yolo".
=> chore: 2025

ARCHITECTURE.md, CONTRIBUTING.md
Adds a high-level `ARCHITECTURE.md` doc, as [many other OSS projects](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html) have done.
=> docs: add ARCHITECTURE.md

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.12.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.10.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.10.3

packages/@lwc/babel-plugin-component/src/decorators/wire/validate.ts
Addresses one of the items in #3444 (https://github.com/salesforce/lwc/pull/3373#discussion_r1158243741).
Tests were added in #5147 and #5148 to make sure the behavior stays the same.
=> chore: improve member expression computed typechecking

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: prepare release v8.12.6 @W-17528745

packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-dynamic-value/modules/x/component/component.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
=> fix: obscure dynamic value test case triggering v2 failure

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
[W-17720448](https://gus.lightning.force.com/a07EE000028sra1YAA)
=> chore: release v8.12.7

.git2gus/config.json
=> chore: it's the fuuutuuuure

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> @W-17769475 chore: bump to v8.13.1 for release

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.13.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.13.3

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/integration-karma/test/component/LightningElement/index.spec.js
=> chore: revert revert of locker flag

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.14.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: bump version to 8.15.0

.gitignore, package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.16.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v8.16.2

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release 8.16.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release 8.16.4

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
[W-18174268](https://gus.lightning.force.com/a07EE00002C20XEYAZ)
=> chore: bump version to 8.18.1

.nucleus.yaml
=> chore: add summer25 def to nucleus.yaml

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Bump version to 8.16.5 (256 patch)
[W-18328598](https://gus.lightning.force.com/a07EE00002DAb1vYAD)
=> @W-18328598 chore: release 8.16.5 (256 patch / summer25)

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-not-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: bump version to 8.20.1

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-not-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: bump version to 8.20.3

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-not-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: bump version to 8.21.0

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-not-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
- 
[W-19292529](https://gus.lightning.force.com/a07EE00002JqS03YAF)
=> chore: bump version to 8.21.1

.nucleus.yaml
=> chore: add `winter26` dist tag to nucleus

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-not-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: bump version to 8.21.2

packages/@lwc/perf-benchmarks-components/src/benchmark/expression/expression.html
=> fix: broken perf test
