salesforce/lwc

packages/@lwc/engine-core/src/framework/queue-microtask.ts, packages/@lwc/engine-core/src/framework/utils.ts, packages/@lwc/engine-core/src/framework/vm.ts
We have a function, `addCallbackToNextTick`, which is basically doing the same thing as [`queueMicrotask`](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask), which is supported in modern browsers. This refactors the code so that we prefer the native implementation and fall back to the polyfill.
=> fix: use queueMicrotask in supported browsers

packages/@lwc/shared/src/global-this.ts
Trims the code in this polyfill. I don't think most of it is necessary.
If you're running LWC in a legacy browser, it's probably on the main thread. So `window` will work fine.
I'm not aware of anyone running LWC in a web worker.
As for Node, `globalThis` is supported [since Node 12.0.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis#browser_compatibility).
=> fix(shared): simplify globalThis polyfill

packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/missing-css/missing-css.js, packages/@lwc/rollup-plugin/src/__tests__/resolver/resolver.spec.ts, packages/@lwc/rollup-plugin/src/index.ts
This PR updates `rollup-plugin` on stylesheet imports so that if a component imports an non-existing CSS file it will ~~throw an error~~ log a warning message, while keep the current behavior treating any non-existing CSS file as empty string (compiled to `export default undefined`). 
The previous behavior can be problematic because the new [CSS extensibility feature (a.k.a. programmatic style injection)](https://github.com/salesforce/lwc/pull/3123) allows users to override a component's style by programmatically importing a stylesheet module from JavaScript using an import statement. ~~We should enforce that the imported CSS file must exist and if not the compilation should fail instead of treating it as an empty string so that developers can be informed the issue during build time.~~ We …
=> feat(rollup-plugin): warn stylesheet import for CSS extensibility

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/rendering/programmatic-stylesheets/index.spec.js, packages/@lwc/integration-karma/test/rendering/programmatic-stylesheets/x/stylesheetsMutation/stylesheet.css, packages/@lwc/integration-karma/test/rendering/programmatic-stylesheets/x/stylesheetsMutation/stylesheetsMutation.html, packages/@lwc/integration-karma/test/rendering/programmatic-stylesheets/x/stylesheetsMutation/stylesheetsMutation.js
Adds a warning if developer tries to mutate `static stylesheets` on `LightningElement`.
A developer can mutate `static stylesheets`, but this will have no effect because LWC only registers them once on the VM. As a DX improvement, we add a warning in dev mode if this happens.
[W-12369133](https://gus.lightning.force.com/a07EE00001JD8b9YAD)
=> feat(engine-core): warn if developer mutates static stylesheets

packages/@lwc/engine-core/src/framework/check-version-mismatch.ts, packages/@lwc/engine-core/src/framework/component.ts, packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/rendering/version-mismatch/index.spec.js
This adds reporting for compiler/runtime version mismatches.
Unfortunately, because compiler version stamps were implemented as JS comments, this can only work in dev mode. (In prod mode, the minifier strips out comments.) But I think even reporting in dev mode is better than nothing.
W-12253834
=> feat: add reporting for version mismatches

packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/engine-core/src/index.ts, packages/@lwc/engine-core/src/patches/detect-non-standard-aria.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/index.spec.js, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/x/light/light.html, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/x/light/light.js, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/x/shadow/shadow.html, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/x/shadow/shadow.js, packages/@lwc/integration-karma/test/accessibility/synthetic-cross-root-aria/index.spec.js, packages/@lwc/integration-karma/test/polyfills/aria-properties/index.spec.js
This is part 2 of the new reporting APIs. (Part 1 is #3287.)
This one covers non-standard ARIA properties. It includes new detection logic to understand when people are using these APIs.
See [related docs PR](https://github.com/salesforce-experience-platform/lwc-docs/pull/251).
W-12253834
=> feat: add reporting for non-standard ARIA reflection

packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/api/freezeTemplate/index.spec.js, packages/@lwc/integration-karma/test/rendering/legacy-stylesheet-api/index.spec.js, packages/@lwc/integration-karma/test/static-content/index.spec.js
This is part 3 of the new reporting APIs. (Part 1 is #3287 and part 2 is #3288)
This adds reporting for frozen template (and frozen stylesheet) violations. So if anybody mutates these, we get a report.
[Related docs PR](https://github.com/salesforce-experience-platform/lwc-docs/pull/252)
W-12253834
=> feat: add reporting for frozen template

packages/@lwc/integration-karma/test/light-dom/slotting/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slotting/x/forwardedSlot/forwardedSlot.html, packages/@lwc/integration-karma/test/light-dom/slotting/x/forwardedSlot/forwardedSlot.js, packages/@lwc/integration-karma/test/light-dom/slotting/x/forwardedSlotConsumer/forwardedSlotConsumer.html, packages/@lwc/integration-karma/test/light-dom/slotting/x/forwardedSlotConsumer/forwardedSlotConsumer.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/error-slots-attributes/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/template/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/template/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-render-mode/template/expected.js, packages/@lwc/template-compiler/src/parser/index.ts
As part of restricting attributes on light DOM slots (since they are not rendered), we also disallowed the `slot` attribute. This prevents forwarding slots from parent component to child component. We remove that restriction in this PR.
W-11308178
=> fix: allow  attribute on light DOM slots

packages/@lwc/engine-core/src/framework/utils.ts
Tiny fix. Found a couple cases where we weren't pulling in these functions from `@lwc/shared`.
=> fix: use shared Object/Array functions

packages/@lwc/integration-karma/test/polyfills/aria-properties/index.spec.js
See #3284
Our polyfill aligns with the spec, but WebKit/Chromium do not. We can't change it right now because of backwards compat. This test just confirms the existing behavior.
=> test(aria-reflection): test existing setter behavior

packages/@lwc/engine-core/src/framework/check-version-mismatch.ts, packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/engine-core/src/patches/detect-non-standard-aria.ts, packages/@lwc/engine-core/src/patches/detect-synthetic-cross-root-aria.ts, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/index.spec.js, packages/@lwc/integration-karma/test/accessibility/synthetic-cross-root-aria/index.spec.js, packages/@lwc/integration-karma/test/api/freezeTemplate/index.spec.js, packages/@lwc/integration-karma/test/rendering/version-mismatch/index.spec.js
As discussed [here](https://github.com/salesforce/lwc/pull/3287#discussion_r1069876017), we should provide more detail in our deprecation reporting. This PR adds a new Payload type that is unique per type of deprecation report.
Technically this is a breaking change for anyone using `__unstable__ReportingControl` since the API signature changed. But since it should only be used by us, and anyway it's called "unstable," and also we just released it, I think we're fine.
See above.
W-12390195
=> fix(engine): provide more details in deprecation reports

.circleci/config.yml, .github/workflows/benchmark.yml
Our builds keep failing because Puppeteer fails to download Chromium. We only need this for local `@best/runner-headless` testing, which is not used in any of our CI scripts (even our Best scripts, which use the remote runner).
This disables the download, using the `PUPPETEER_SKIP_DOWNLOAD` [env var](https://pptr.dev/api/puppeteer.configuration/#properties).
=> chore: use PUPPETEER_SKIP_DOWNLOAD in CI

packages/@lwc/perf-benchmarks/package.json, yarn.lock
As mentioned here, we can't upgrade Tachometer just yet:
https://github.com/salesforce/lwc/blob/0ca36ebc33df393031e9ec98c90432a512984d5e/packages/@lwc/perf-benchmarks/package.json#L15
This isn't really sustainable because we don't have any CI tests to catch this failure. (We run Tachometer manually.) We might need to submit a patch to Tachometer or something.
=> chore: downgrade tachometer

packages/@lwc/engine-server/src/__tests__/create-element.spec.ts, packages/@lwc/engine-server/src/apis/create-element.ts, packages/@lwc/engine-server/src/index.ts
This is to support isomorphic code that uses `createElement` on the client. Importing the function throws currently; with this PR, you can at least import it. However, it will throw an error if you try to run it.
=> fix(engine-server): expose createElement API

packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts
=> chore: fix out-of-date code comment

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/flags.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/rendering/programmatic-stylesheets/index.spec.js
Remove feature flag for programmatic stylesheets.
[W-12394260](https://gus.lightning.force.com/a07EE00001JYs7SYAT)
=> fix(engine-core): remove feature flag for programmatic stylesheets

packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/template-transform.ts, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-custom-element/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-custom-element/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-custom-element/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-custom-element/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-standard-element/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-standard-element/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-standard-element/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/inline-both-standard-element/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/template-both/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/template-both/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/template-both/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/template-both/metadata.json, packages/@lwc/template-compiler/src/parser/attribute.ts, packages/@lwc/template-compiler/src/parser/index.ts
Fixes https://github.com/salesforce/lwc/issues/3277.
=> fix: warn on using if:true and if:false on same node

packages/@lwc/features/src/__tests__/features.spec.ts, packages/@lwc/features/src/__tests__/lwcRuntimeFlags.spec.ts, packages/@lwc/features/src/__tests__/setFeatureFlag.spec.ts
There is logic in `@lwc/features` to test for scenarios like setting a non-boolean, or trying to set a flag that's undefined, but we don't have tests for this behavior (in either Jest or Karma). This adds Jest tests for this behavior.
=> test(features): add tests for setFeatureFlag

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
A new patch version for this week's release.
W-12246411
=> chore: v2.37.1 @ W-12246411

packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/index.spec.js, packages/@lwc/integration-karma/test/accessibility/synthetic-cross-root-aria/index.spec.js, packages/@lwc/integration-karma/test/api/freezeTemplate/index.spec.js, packages/@lwc/integration-karma/test/polyfills/aria-properties/index.spec.js, packages/@lwc/integration-karma/test/rendering/version-mismatch/index.spec.js
As discussed, we're switching from int enums to string enums for the reporting API.
This is an unstable API used only by us; we can do what we want.
W-12505852
=> fix(reporting): report string enums

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
v2.37.2
Changes to the payload structure of runtime reporting events. Only used by our team and there's no chance of breakage.
=> chore: release v2.37.2 @W-12246411

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/integration-karma/test-hydration/attributes/falsy-mismatch/index.spec.js, packages/@lwc/integration-karma/test-hydration/attributes/falsy-mismatch/x/main/main.html, packages/@lwc/integration-karma/test-hydration/attributes/falsy-mismatch/x/main/main.js, packages/@lwc/integration-karma/test-hydration/attributes/falsy/index.spec.js, packages/@lwc/integration-karma/test-hydration/attributes/falsy/x/main/main.html, packages/@lwc/integration-karma/test-hydration/attributes/falsy/x/main/main.js
The attribute values `undefined` and `null` (i.e. nullish values) are special cases. When used on the server side, they become `null` on the client side (i.e. the attribute does not exist).
This fixes it so that we don't have hydration mismatches in this special case. 
W-12477772
=> fix(hydration): properly handle nullish attribute values

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/renderer/index.ts, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/integration-karma/test/component/owner-document/index.spec.js, packages/@lwc/integration-karma/test/component/owner-document/x/shadow-dom/shadow-dom.html, packages/@lwc/integration-karma/test/component/owner-document/x/shadow-dom/shadow-dom.js, packages/@lwc/integration-karma/test/component/properties/index.spec.js
`this.ownerDocument` in `LightningElement` didn't return the ownerDocument because it was not forwarded to the underlying host element. We fix that in this PR.
=> feat: forward `ownerDocument` in `LightningElement`

packages/@lwc/engine-core/src/patches/detect-synthetic-cross-root-aria.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts
It occurred to me that we do not want people to take a dependency on these global `getElementById`/`querySelectorAll` bypass functions added to the `window`. They're defined in `synthetic-shadow`, so `engine-dom` can delete them as soon as it grabs them.
This is not really a breaking change, because we only shipped this change this release (#3214), and most likely nobody has taken a dependency on it yet. (And if they did, they really should not.)
Also note that only non-Lockerized components can even possibly take a dependency on this.
See above.
=> fix: delete global shadow DOM bypass functions

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/index.spec.js, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/x/customRender/customRender.js, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/x/customRender/template.html, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/x/customRender/template2.html, scripts/bundlesize/bundlesize.config.json
VFragments are not cleaned up properly when resetting component root because their .elm points to the end delimiter text node, not the root element.
=> fix: @W-12593632 clean up VFragments when resetting component root

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js, packages/@lwc/integration-karma/test/rendering/callback-invocation-order/x/multiTemplateConditionals/multiTemplateConditionals.js, packages/@lwc/integration-karma/test/rendering/callback-invocation-order/x/multiTemplateConditionals/template.html, packages/@lwc/integration-karma/test/rendering/callback-invocation-order/x/multiTemplateConditionals/template2.html, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/index.spec.js, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/x/customRender/customRender.js, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/x/customRender/template.html, packages/@lwc/integration-karma/test/rendering/if-inside-custom-render/x/customRender/template2.html
VFragments are not cleaned up properly when resetting component root because their `.elm` points to the end delimiter text node, not the root element.
Backport of https://github.com/salesforce/lwc/pull/3363.
=> fix: clean up VFragments when resetting component root

.nucleus.yaml
=> chore(nucleus): remove lightning-components

packages/@lwc/integration-tests/src/components/memory-leaks/test-lifecycle-leak/test-lifecycle-leak.spec.js
Temporary workaround for #3393
It breaks my heart because I _just_ wrote this test, but Circle CI is no bueno with CDP anymore, so let's disable this test for now.
=> chore: disable mem leak test for now

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/integration-karma/test/rendering/issue-3377/index.spec.js, packages/@lwc/integration-karma/test/rendering/issue-3377/x/test/test.html, packages/@lwc/integration-karma/test/rendering/issue-3377/x/test/test.js, packages/@lwc/integration-karma/test/rendering/issue-3396/index.spec.js, packages/@lwc/integration-karma/test/rendering/issue-3396/x/test/test.html, packages/@lwc/integration-karma/test/rendering/issue-3396/x/test/test.js, packages/@lwc/integration-karma/test/rendering/sequential-reordering/index.spec.js, packages/@lwc/integration-karma/test/rendering/sequential-reordering/x/test/test.html, packages/@lwc/integration-karma/test/rendering/sequential-reordering/x/test/test.js
Implements an abstraction for moving vfragment-based nodes around and fixes both reported issues around insertion when the vfragment-based nodes are the reference node. Note that we already had logic for mounting/patching/removing.
Fixes #3396
Fixes #3377
No
Yes
W-12630370
=> fix(engine-core): add abstraction for moving vfragments

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Includes a patch fix for ordering of content during rendering of `lwc:if` blocks.
W-12246411
=> chore: v2.41.2

.nucleus.yaml
Add `summer23` to the release branch definition in nucleus config
W-12778686
=> chore: add summer23 to nucleus config @ W-12778686

.nucleus.yaml, package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
New minor version for work on the 246 codeline
W-12778686
=> chore: new minor version to track 246 codeline

.nucleus.yaml, package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
New minor version for the 246 codeline
W-12778686
=> chore: new minor version to track 246 codeline @ W-12778686

packages/@lwc/integration-karma/test/light-dom/synthetic-shadow/index.spec.js
There was one reference we missed in #3426 @abdulsattar. This removes it.
=> test: remove references to ENABLE_LIGHT_GET_ROOT_NODE_PATCH

packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/integration-karma/test/component/dynamic-imports/index.spec.js, packages/@lwc/integration-karma/test/rendering/slotting/index.spec.js, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotLight/unknownSlotLight.html, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotLight/unknownSlotLight.js, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotLightChild/unknownSlotLightChild.html, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotLightChild/unknownSlotLightChild.js, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotShadow/unknownSlotShadow.html, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotShadow/unknownSlotShadow.js, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotShadowChild/unknownSlotShadowChild.html, packages/@lwc/integration-karma/test/rendering/slotting/x/unknownSlotShadowChild/unknownSlotShadowChild.js
Fixes #3403
Removes all warnings for when a slot name doesn't exist, in both synthetic shadow and light DOM.
I considered _adding_ a warning to native shadow, but I'm not sure this is something we can easily override, nor does it seem particularly valuable to me.
W-12703461
=> fix(engine-core): do not warn on missing slot names

packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/component/decorators/api/index.spec.js, packages/@lwc/integration-karma/test/component/decorators/api/x/getterSetterAndProp/getterSetterAndProp.js
(Related to #3245)
We have a bunch of code that checks the accessors on `@api`s and tries to throw an error if the `this` is incorrect. However, we have no tests for it. This PR adds tests.
Unfortunately, our current behavior is inconsistent between prod mode and dev mode, and between different types of accessors, but I think it's better to have tests for the existing behavior than no tests at all.
=> test: test `this` check on accessor in `@api`

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-empty-in-ssr-null-string-in-client/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-null-string-in-ssr-empty-in-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-null-string-in-ssr-empty-in-client/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/dynamic-null-string-in-ssr-empty-in-client/x/main/main.js, packages/@lwc/integration-karma/test-hydration/svg/basic/index.spec.js, packages/@lwc/integration-karma/test-hydration/svg/basic/x/main/main.html, packages/@lwc/integration-karma/test-hydration/svg/basic/x/main/main.js, packages/@lwc/integration-karma/test-hydration/svg/with-class/index.spec.js, packages/@lwc/integration-karma/test-hydration/svg/with-class/x/main/main.html, packages/@lwc/integration-karma/test-hydration/svg/with-class/x/main/main.js, packages/@lwc/integration-karma/test-hydration/svg/with-empty-class/index.spec.js, packages/@lwc/integration-karma/test-hydration/svg/with-empty-class/x/main/main.html, packages/@lwc/integration-karma/test-hydration/svg/with-empty-class/x/main/main.js
=> fix(hydration): fix hydrating SVG classes

packages/@lwc/babel-plugin-component/README.md
=> docs: fix typo in README

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/camel-to-kebab-component-name/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/camel-to-kebab-component-name/config.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/component/camel-to-kebab-component-name/expected.js, packages/@lwc/babel-plugin-component/src/component.ts
This PR fixes an issue where the `sel` in `registerComponent` does not convert a camel-cased name to kebab case.
This is needed for dynamic components so that the tag will contain the properly formatted name, ex:
A component with name `fancyButton` will be rendered as `x-fancybutton` rather than `x-fancy-button`.
This only affects dynamic components, which is still in pilot.
The tag name for a dynamic component will now be properly converted to kebab case.  Dynamic components is still in pilot so this should be a safe change to make.
=> fix: convert camel cased names to kebab case in registerComponent selector

packages/@lwc/engine-server/src/utils/validate-style-text-contents.ts
Something about Best's build process [does not like](https://github.com/salesforce/lwc/actions/runs/4661685489/jobs/8317449243#step:6:25) how we import from `parse5`, introduced in #3442 :
```
Error: 'parseFragment' is not exported by ../../../node_modules/parse5/lib/index.js
```
Using `import *` works fine though.
=> fix(benchmarks): fix best import error

packages/@lwc/engine-core/src/framework/decorators/api.ts, packages/@lwc/engine-core/src/framework/decorators/register.ts, packages/@lwc/engine-core/src/framework/readonly.ts, packages/@lwc/integration-karma/test/api/readonly/index.spec.js, packages/@lwc/integration-karma/test/component/decorators/api/index.spec.js, packages/@lwc/integration-karma/test/component/decorators/track/index.spec.js, packages/@lwc/integration-karma/test/component/decorators/wire/index.spec.js, packages/@lwc/integration-karma/test/component/observed-fields/index.spec.js
Partially addresses #3245
Anytime we throw an error in dev mode but not in prod mode, that's a bug. This PR gets us one step closer to fixing that, by making decorator validation errors _log_ rather than throw.
=> fix(engine-core): remove dev-only errors for decorators

packages/@lwc/perf-benchmarks/best.config.js, packages/@lwc/perf-benchmarks/package.json, yarn.lock
Fixes #3463. I tested locally and Best works now.
=> fix(perf-benchmarks): use correct Rollup plugins for Best

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Minor version bump after the revert in #3472.
This will require a follow-up PR internally to accommodate the API changes in this revert. See #3443 for what is being rolled back.
=> chore: release v2.45.0

packages/@lwc/engine-core/src/framework/decorators/api.ts, packages/@lwc/integration-karma/test/component/decorators/api/index.spec.js, packages/@lwc/integration-karma/test/component/decorators/api/x/noSetter/noSetter.js, packages/@lwc/integration-karma/test/rendering/side-effects/index.spec.js, packages/@lwc/integration-karma/test/rendering/side-effects/x/childWithApiGetterSetter/childWithApiGetterSetter.html, packages/@lwc/integration-karma/test/rendering/side-effects/x/childWithApiGetterSetter/childWithApiGetterSetter.js, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringRender/sideEffectDuringRender.html, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringRender/sideEffectDuringRender.js, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringRenderExternal/sideEffectDuringRenderExternal.html, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringRenderExternal/sideEffectDuringRenderExternal.js, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringTemplate/sideEffectDuringTemplate.html, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringTemplate/sideEffectDuringTemplate.js, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringTemplateExternal/sideEffectDuringTemplateExternal.html, packages/@lwc/integration-karma/test/rendering/side-effects/x/sideEffectDuringTemplateExternal/sideEffectDuringTemplateExternal.js
As it turns out, I missed some dev-only errors in the other 3 PRs:
- #3409 
- #3412 
- #3413 
The reason I missed them is that we didn't have any tests for them. 😅 So I added some tests, and then changed the errors to be `console.error`s instead.
=> fix(engine-core): clean up some untested dev-only errors

packages/@lwc/babel-plugin-component/package.json
Forgot to tell NX to cache the `types` directory in `@babel/plugin-component`. Amazingly this has been broken since #3373 but was probably flappy because it depended on whether we loaded the cache or not.
=> fix(babel-plugin-component): ensure nx caches types

packages/@lwc/wire-service/README.md
https://github.com/salesforce/lwc/pull/3469
=> fix: providBookWithId method name typo in wire-service docs

packages/@lwc/integration-karma/test/synthetic-shadow/active-element/index.spec.js, packages/@lwc/integration-karma/test/synthetic-shadow/active-element/x/source/source.html, packages/@lwc/integration-karma/test/synthetic-shadow/active-element/x/source/source.js, packages/@lwc/integration-karma/test/synthetic-shadow/active-element/x/target/target.html, packages/@lwc/integration-karma/test/synthetic-shadow/active-element/x/target/target.js, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts
Partially addresses #3413
Makes some more dev-only errors into logs.
[TD-0142487](https://gus.lightning.force.com/lightning/r/a0nEE000000Dhf3YAC/view)
=> fix(synthetic-shadow): convert dev-only errors to logs

packages/@lwc/integration-karma/helpers/test-setup.js
Unfortunately in #3489 I broke the Karma local tests (`yarn start`), because Karma itself calls `console.log`, resulting in:
```
An error was thrown in afterAll
Error: Expected console not to be called, but was called 2133 time(s)
at throwIfConsoleCalled (/Users/nlawson/workspace/lwc/packages/@lwc/integration-karma/helpers/test-setup.js:72:15)
at UserContext.<anonymous> (/Users/nlawson/workspace/lwc/packages/@lwc/integration-karma/helpers/test-setup.js:116:5)
at <Jasmine>
```
This PR scopes it to just error/warn, which is mostly what we want to catch in LWC anyway. It's the simplest solution I could think of.
=> fix(integration-karma): only fail on console warn/error

.circleci/config.yml, package.json, packages/@lwc/engine-server/package.json, packages/@lwc/perf-benchmarks/README.md, packages/@lwc/perf-benchmarks/best.config.js, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/perf-benchmarks/scripts/build.js, scripts/rollup/rollup.config.js, yarn.lock
FIxes #3498
Also adds a CI test so we can stop breaking our benchmarks all the time.
The solution I used was to bundle `parse5` into `@lwc/engine-server` since Tachometer can't handle CommonJS. We'll have to do this anyway once we fix #3451, since we can't ship ESM directly to consumers without breaking a bunch of people.
[W-13219245](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001RaHltYAF/view)
=> fix(perf-benchmarks): fix server/hydrate benchmarks

.circleci/config.yml
I accidentally removed this test: https://github.com/salesforce/lwc/pull/3456/files#r1195609517
This PR adds it back in as a CI test.
=> test: add treeshakable test back in

packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/x/attrChanged/attrChanged.js, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/x/reflectCamel/reflectCamel.js
Adds tests to assert the existing behavior described here: https://github.com/salesforce/lwc/issues/2972#issuecomment-1550367388
=> test(integration-karma): test CustomElementConstructor attributes

packages/@lwc/engine-core/src/framework/attributes.ts, packages/@lwc/engine-core/src/framework/base-bridge-element.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/modules/attrs.ts
The goal of "attribute locking" is to avoid reflecting `setAttribute` to a property setter when manipulated by the framework.
I tested, though, and this only occurs for `CustomElementConstructor`, e.g. when [reflecting a set attribute to an `@api` prop](https://stackblitz.com/edit/salesforce-lwc-zk6nww?file=src/main.js).
This case is not actually tested in any of our tests, nor in any of our downstream tests. And AFAICT, with the introduction of `lwc:external`, it's not even possible for this case to arise, because we sniff to set a property rather than an attribute:
https://github.com/salesforce/lwc/blob/acc19c692f57ed8405a10a09b77f174ea015e440/packages/%40lwc/engine-core/src/framework/modules/attr-unless-prop.ts#L44-L46
So it seems to me that this code can just be removed.
* ✅ No, it …
=> fix(engine-core): remove attribute locking

scripts/rollup/rollup.config.js
This accidentally got removed in #3456, but we need it on platform.
W-13402515
=> fix: add proxy-compat comment back to dist files

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json, scripts/rollup/rollup.config.js
Release v2.45.4 to npm
W-13206150
=> chore: release v2.45.4 @W-13206150

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/integration-karma/test/light-dom/scoped-slot/reactivity/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/reactivity/x/childSlotTagWithKey/childSlotTagWithKey.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/x/child/child.html, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/x/child/child.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/x/parent/parent.html, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/x/parent/parent.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/x/slotted/slotted.html, packages/@lwc/integration-karma/test/light-dom/scoped-slot/rehydration-issue-w-12965122/x/slotted/slotted.js
The PR fixes a bug where the scopes slot fragment was executing in the receiving component's template reactive observer(tro) and led to memory leaks.
Executing the scoped slot fragment in the child component's tro would result in the child component being registered as the observer for values that are observed in the scoped slot fragment(which come from the parent's template). If the scoped slot fragment happens to have bindings from the parent's component class and the bindings change, then child component would be added to the rehydration queue thus causing a memory leak.
Example template for better understanding.
```xml
<template>
<x-child>
<template lwc:slot-data={item}>
<x-slotted label={item.label} attr={attr}></x-slotted>
</template>
</x-child>
<template>
```
Note: The above …
=> fix(engine-core): execute scoped slot fragment in the slot owner's reactive observer

.nucleus.yaml
This ensures that Nucleus applies the `latest` npm dist-tag when publishing to npm.
=> chore(nucleus): set "latest" dist-tag when publishing

package.json
When this script itself changes, it should re-run during the precommit hook.
Missed in #3456 
=> chore: run package.json updater when script changed

packages/@lwc/errors/src/compiler/instrumentation.ts
Removes `const` so this enum is not erased during compilation.
=> fix: metrics enum should not be const

packages/@lwc/compiler/README.md, packages/@lwc/compiler/src/transformers/__tests__/transform-html.spec.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/compiler/src/transformers/transformer.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts
This adds an explicit `cssScopeTokens` return value for `transformSync` in `@lwc/compiler`. This would be a cleaner way for `lwc-test` to know which scope tokens are being generated by the template compiler.
E.g. if you look at https://github.com/salesforce/lwc-test/pull/184, you can see that I have to do [a regex-search](https://github.com/salesforce/lwc-test/pull/184/files#r1218686881) on the code returned by `@lwc/compiler` to detect and replace the scope tokens. This is ugly; we should just have the compiler return the scope tokens explicitly.
W-12425100
=> feat(compiler): return cssScopeTokens

packages/@lwc/integration-karma/test/template/attribute-class/index.spec.js
While working on patch flags, I realized we were missing some tests for updating dynamic `class` attributes with null/undefined/empty string. This borrows some of the same tests from `integration-karma/test/template/attribute-style/index.spec.js` to accomplish this.
=> test(integration-karma): add tests for updating class attribute

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js
Wraps all error/warn logs in `hydration.ts` in a `process.env.NODE_ENV !== 'production'` check. Prompted by https://github.com/salesforce/lwc/issues/2939#issuecomment-1560209569
Note we don't really have a test for this yet, because we only run the hydration tests in dev mode (#3253).
=> fix(hydration): log errors/warnings only in dev mode

package.json, packages/@lwc/compiler/src/transformers/javascript.ts, packages/@lwc/compiler/src/typings/@babel-plugin-proposal-async-generator-functions.d.ts, packages/@lwc/compiler/src/typings/@babel-plugin-transform-async-to-generator.d.ts, yarn.lock
=> chore: update babel deps

nx.json, package.json, yarn.lock
There don't seem to be any breaking changes for us in [Nx v16](https://blog.nrwl.io/nx-16-is-here-69584ec87053), and [the migration process](https://nx.dev/core-features/automate-updating-dependencies) didn't make any substantial changes.
To at least test that the cache is working, I did `yarn test && rm -fr packages/@lwc/*/dist && yarn test` to confirm that NX restores the `dist` files.
=> chore: update nx to v16

package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, scripts/jest/utils/index.ts, yarn.lock
Updates our remaining Babel deps. Follow-up to #3573 
=> chore: update more babel deps

packages/@lwc/integration-tests/package.json, packages/@lwc/integration-tests/scripts/commands/focus.js, packages/@lwc/integration-tests/scripts/wdio.conf.js, yarn.lock
Updates WebDriverio to [v8](https://github.com/webdriverio/webdriverio/releases/tag/v8.0.0), and fixes some minor breaking changes in our tests.
=> chore: update webdriverio to v8

packages/@lwc/compiler/README.md, packages/@lwc/rollup-plugin/README.md, packages/@lwc/rollup-plugin/src/__tests__/compilerConfig/compilerConfig.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/compilerConfig/fixtures/lightningWebSecurityTransforms/lightningWebSecurityTransforms.html, packages/@lwc/rollup-plugin/src/__tests__/compilerConfig/fixtures/lightningWebSecurityTransforms/lightningWebSecurityTransforms.js, packages/@lwc/rollup-plugin/src/index.ts
=> feat: add enableLightningWebSecurityTransforms to rollup-plugin

scripts/rollup/rollup.config.js
Fixes #3445. Removes legacy `dist/` files from the npm package.
The following will no longer work:
```js
require('@lwc/compiler/dist/commonjs/transformers/transformer.js')
require('@lwc/engine-dom/dist/engine-dom.js')
require('@lwc/synthetic-shadow/dist/synthetic-shadow.js')
```
Instead of a deep `require()`, do this:
```js
require('@lwc/compiler')
require('@lwc/engine-dom')
require('@lwc/synthetic-shadow')
```
=> chore: remove legacy dist files (BREAKING CHANGE)

packages/@lwc/engine-core/src/libs/mutation-tracker/index.ts, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-tracked-component/trackedcmp-update-10k.benchmark.js
This is a micro-optimization that applies when updating tracked components. I noticed it while looking at LWC running in the `js-framework-benchmark`.
I also added a new benchmark. The improvement here is 1-3%:
=> perf(engine-core): optimize ReactiveObserver.reset()

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/runtime-instrumentation.ts
This allows for future browser extensions to track & instrument component definitions & instances. If the browser extension is loaded on the page, a global function (provided by the extension) is invoked whenever a component definition is created or a component is instantiated. If the browser extension is not loaded, the function calls are no-ops and would be optimized away by the JavaScript engine (no perf impact).
I'd like to get this in the current code line, so that development of the browser extension can be done without modifying network calls to inject the instrumentation.
The change here is negligible. Technically, if someone could modify the global scope prior to execution of …
=> chore: add injection points for devtools instrumentation

packages/@lwc/compiler/src/options.ts
To prevent tons of warning log lines for downstream consumers, the warning about still using the deprecated LWC compiler option `enableLwcSpread` is now only logged once.
=> fix: warn only once about deprecated compiler option `enableLwcSpread`

.nucleus.yaml
This PR adds the `winter24` branch to the nucleus configs and removes `winter23`.
This is needed for nucleus to detect releases on the `winter24` branch once it's created.
W-13733617
=> chore: add winter24 branch

.git2gus/config.json
Update git2gus for 248
W-13733617
=> chore: update git2gus to 248 codeline for CLCO

packages/@lwc/features/src/__tests__/setFeatureFlag.spec.ts, packages/@lwc/features/src/index.ts
This warning message keeps getting raised when users run into unrelated issues and start grasping at straws. 
No
No
W-13775648
=> chore: relax the logged message when attempting to set unknown feature flag

.circleci/config.yml
Bump to the latest version of `circleci/browser-tools` which fixes a problem [installing chromedriver](https://github.com/CircleCI-Public/browser-tools-orb/issues/75).  
The latest release fixes a problem where the endpoint CircleCi uses for downloading chrome driver changed for all versions >= 115.
W-13798590
=> chore: bump circleci browser-tools version (master)

.circleci/config.yml
Bump to the latest version of `circleci/browser-tools` which fixes a problem [installing chromedriver](https://github.com/CircleCI-Public/browser-tools-orb/issues/75).  
The latest release fixes a problem where the endpoint CircleCi uses for downloading chrome driver changed for all versions >= 115.
W-13798590
=> chore: bump circle ci broswer-tools version (summer23)

.circleci/config.yml
Bump to the latest version of `circleci/browser-tools` which fixes a problem [installing chromedriver](https://github.com/CircleCI-Public/browser-tools-orb/issues/75).  
The latest release fixes a problem where the endpoint CircleCi uses for downloading chrome driver changed for all versions >= 115.
W-13798590
=> chore: bump circle ci broswer-tools version (winter24)

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/renderer/index.ts, packages/@lwc/engine-server/src/__tests__/fixtures/tag-name/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/tag-name/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/tag-name/modules/x/tag-name/tag-name.html, packages/@lwc/engine-server/src/__tests__/fixtures/tag-name/modules/x/tag-name/tag-name.js, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/integration-karma/test/component/LightningElement.tagName/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.tagName/x/override/override.js, packages/@lwc/integration-karma/test/component/properties/index.spec.js
Fixes #3633
No
`tagName` can still be defined by the component.
Yes
`tagName` is no longer `undefined`.
W-13784946
=> feat(engine): tagName property

.nucleus.yaml
The `milestone-*` branches should run Nucleus tests when PRs are opened on them.
=> chore(nucleus): add test workflow for milestone- branches

packages/@lwc/engine-dom/src/styles.ts, packages/@lwc/integration-karma/test/shadow-dom/multiple-templates/index.spec.js
Fixes #2828 by dropping support for old Chrome. Adds support for constructable stylesheets in Safari 16.6.
=> fix(engine-dom): fix constructable stylesheets in Safari

.nucleus.yaml
Remove it. It's broken for unrelated reasons.
=> chore(nucleus): remove Guardrails/analyzer-framework

.circleci/config.yml
Looks like ChromeDriver is borked in Circle CI again. This might fix it.
=> chore: update circle ci image

packages/@lwc/engine-core/src/framework/modules/props.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/integration-karma/test/spread/index.spec.js, packages/@lwc/integration-karma/test/spread/x/test/test.html, packages/@lwc/integration-karma/test/spread/x/test/test.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-spread/dynamic-components/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-spread/no-renderer-hook/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-spread/valid/expected.js, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/shared/estree.ts
`lwc:spread` was not reactive when used with @track decorator. The properties within the object were being accessed when patching the element, which is outside of the template reactive observer. This PR moves it to within the render method, which is invoked during template reactive observer. It also makes the code much simpler.
=> fix: spread not being reactive

.nucleus.yaml
NX caching in Nucleus has caused us nothing but headaches, and it only saves us like 20 seconds max. Let's just remove the NX cache from Nucleus.
We can still keep it for Circle CI and local dev, because it's caused fewer problems there, and we have more control over those environments.
=> chore(nucleus): remove NX cache

packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-mutation-observer-ss/ss-mutation-observer-10k.benchmark.js, packages/@lwc/synthetic-shadow/src/polyfills/mutation-observer/polyfill.ts
A small micro-optimization for our `MutationObserver` polyfill.
Also adds a benchmark, which is improved by 2%-6%:
I have other ideas for improvements, but I'm keeping this PR simple to make it easier to review.
=> perf(synthetic-shadow): micro-optimize MutationObserver

.nucleus.yaml
=> chore(nucleus): remove broken downstreams

packages/@lwc/features/src/__tests__/features.spec.ts, packages/@lwc/features/src/__tests__/lwcRuntimeFlags.spec.ts, packages/@lwc/features/src/__tests__/setFeatureFlag.spec.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts
This PR replaces the `DUMMY_TEST_FLAG` with `PLACEHOLDER_TEST_FLAG` to provide more inclusive language in our feature flags.
W-14136687
=> chore: use inclusive language for feature flags

packages/@lwc/compiler/src/transformers/__tests__/transform-html.spec.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/index.spec.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.css, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.html, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.scoped.css, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.css, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.html, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.scoped.css, packages/@lwc/shared/src/keys.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/legacy-shadow-token.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/portal.ts
Adds a runtime flag that, when enabled, renders the legacy CSS attributes/classes _in addition_ to the new ones.
The reason for rendering both is that we still want the SVG static perf optimization, but some folks need the flag enabled to support legacy global stylesheets.
The reason for a runtime flag is because we can't vary the output of the compiler on the flag, so the check must be done entirely at runtime. To accomplish this, we output the compiled template with both tokens, e.g.:
```js
tmpl.stylesheetToken = "lwc-2idtulmc17f";
tmpl.legacyStylesheetToken = "x-shadow_shadow";
```
W-14181175
=> feat: add flag to render legacy CSS scope tokens

packages/@lwc/compiler/src/transformers/__tests__/transform-html.spec.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/index.spec.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.css, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.html, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/light/light.scoped.css, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.css, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.html, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/x/shadow/shadow.scoped.css, packages/@lwc/shared/src/keys.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/legacy-shadow-token.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/portal.ts
Same as #3734 but backporting to winter24.
W-14181183
=> feat: add flag to render legacy CSS scope tokens (backport)

packages/@lwc/integration-karma/helpers/test-setup.js
Safari seems to have decided to get _really_ slow in Circle CI.
=> chore(karma): further increase test timeout

.circleci/config.yml, packages/@lwc/integration-tests/scripts/wdio.sauce.conf.js
Bump saucelabs tunnel version from 4.6.2 (deprecated) > 4.9.1.
Also pin the platform version per browser for saucelabs tests.
=> chore: bump saucelabs tunnel version and pin platform

.husky/pre-commit, package.json
enables developers to run tests from @lwc/integration-karma using `yarn test:karma` from the root dir.
N/A
=> feat: add shortcut for running karma tests

.circleci/config.yml, packages/@lwc/integration-tests/scripts/wdio.sauce.conf.js
Backport of #3752 for `winter24`.
=> chore: backport saucelabs fix (winter24)

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/x/native/native.js
Introduces renderMode = native for semantic rendering of native only components
W-14092474
=> feat: adding native shadow mode support

packages/@lwc/integration-karma/package.json, packages/@lwc/integration-karma/scripts/karma-configs/shared/browsers.js, packages/@lwc/integration-karma/scripts/karma-configs/utils.js, yarn.lock
Fixes #3083
Fixes #3773
Using a [forked version](https://github.com/nolanlawson/karma-sauce-launcher/tree/update-webdriverio) of `karma-sauce-launcher` to work around a bug with Firefox. Not sure if `karma-sauce-launcher` is under active maintenance.
This also moves us to (finally) test latest Firefox again.
=> chore(saucelabs): use latest firefox

packages/@lwc/engine-core/src/framework/base-bridge-element.ts, packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/integration-karma/test/component/api-with-superclasses/index.spec.js, packages/@lwc/integration-karma/test/component/api-with-superclasses/x/subClass/subClass.js, packages/@lwc/integration-karma/test/component/api-with-superclasses/x/superClass/superClass.js, packages/@lwc/integration-karma/test/component/api-with-superclasses/x/superSuperClass/superSuperClass.js
Fixes #3758
For now I am just disabling the helpful dev warnings if a component does not directly extend from `LightningElement`. I opened some other issues to track follow-up work:
- #3761
- #3762
W-14208047
=> fix(engine-core): fix subclass not inheriting `@api` in dev mode

package.json, yarn.lock
Bumps transitive dependencies and locks `jsonwebtoken` to the latest version. I confirmed that this does not break `tachometer`, which is relying on an older version.
=> chore: update deps to fix security audits

packages/@lwc/template-compiler/package.json
As part of [the upgrade to v7](https://github.com/salesforce/lwc/pull/3602), the parse5 dependency should be moved to `devDependencies` so that it is properly inlined into the dist/ bundles.
https://github.com/salesforce/lwc/blob/1c1687e0afaa715287b119064237803f9df1cf5d/scripts/rollup/rollup.config.js#L133-L138
=> fix: move parse5 to devDeps

packages/@lwc/integration-karma/test/component/html-properties/index.spec.js, packages/@lwc/integration-karma/test/polyfills/aria-properties/index.spec.js
Firefox 119 ([scheduled](https://wiki.mozilla.org/index.php?title=Release_Management/Calendar&redirect=no) to be released on October 24th) will potentially contain [a bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1853209) that will break a bunch of our ARIA reflection tests. Rather than wait to be broken, let's proactively make these tests resilient to Firefox 119.
Note that I didn't bother to add Firefox Nightly to our test matrix, because I don't think it's worth it to run in CI every time. So you'll have to believe me that these new tests pass. 🙃 
=> test: fix aria tests in Firefox Nightly

packages/lwc/index.d.ts
Add generic types for wires so that wire adapter authors can specify the types of a wire adapter and this can enable type checking for wire adapters. Setting all the default types to `any` so that it should be backward compatible. 
For example, a wire adapter author can have the following
```
export const getRecord: WireAdapterConstructor<GetRecordConfig, GetRecordPayload>;
```
so that users of `getRecord` can have type checking for the config object type `GetRecordConfig` and potentially the payload object `GetRecordPayload`.
=> feat: add generic types for wires

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/sanity/index.spec.js, packages/lwc/index.d.ts
Fixes #3782 
Updated `ElementInternals` proxy to an allow listed set of APIs.
W-14260034
=> refactor(engine-core): allow list `ElementInternals` APIs and update type definitions

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/modules/static-parts.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/component/refs/index.spec.js, packages/@lwc/integration-karma/test/component/refs/x/rerenderElementStaticRef/rerenderElementStaticRef.html, packages/@lwc/integration-karma/test/component/refs/x/rerenderElementStaticRef/rerenderElementStaticRef.js, packages/@lwc/integration-karma/test/static-content/index.spec.js, packages/@lwc/integration-karma/test/static-content/x/listenerStaticWithUpdates/listenerStaticWithUpdates.html, packages/@lwc/integration-karma/test/static-content/x/listenerStaticWithUpdates/listenerStaticWithUpdates.js
Fixes #3796
This is an alternative to #3797 – it's a fix-forward rather than a revert.
I also added in the same tests.
I guess I'm waiting to see if both PRs pass CI, and then we can decide if we want to fix-forward or revert.
[W-14294276](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001cOeCwYAK/view)
=> fix(engine-core): fix timing of ref resets

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/apis/hydrate-component.ts, packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts, packages/@lwc/engine-dom/src/renderer-factory.ts, packages/@lwc/engine-dom/src/renderer.ts, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/integration-karma/test-hydration/simple/index.spec.js, packages/@lwc/integration-karma/test-hydration/simple/x/child/child.html, packages/@lwc/integration-karma/test-hydration/simple/x/child/child.js, packages/@lwc/integration-karma/test-hydration/simple/x/main/main.html, packages/@lwc/integration-karma/test/hydration/index.spec.js
We just register an `UpgradableConstructor` (without an `upgradeCallback`). There's no support for FACE because we didn't have them earlier to this PR as well. Also, there's no support for native callback lifecycle because, again, we didn't have support for this prior to this PR.
=> fix: register custom element during hydration

packages/@lwc/integration-karma/test/static-content/index.spec.js, packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.html, packages/@lwc/integration-karma/test/static-content/x/deepListener/deepListener.js, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/mixed-props-attrs/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-dynamic/only-child/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-dynamic/sibbling/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-for-each/template-outside-scope-reference/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-if/template-expression/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-key/iterator-key-member-expression/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/if-else/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/if-elseif-else-nested/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/if-elseif-else/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/if-elseif-multiple/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/if-elseif/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/if/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic-components/inline/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic/if-else/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic/if-elseif-else-nested/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic/if-elseif-else/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic/if-elseif-multiple/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic/if-elseif/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-lwc-if-else/dynamic/if/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/dynamic-components/valid/siblings/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression/attribute-deep/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression/attribute-multiple/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression/computed/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression/parenthesis/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/metadata/used-attrs/ast.json, packages/@lwc/template-compiler/src/codegen/codegen.ts
=> fix(template-compiler): fix static listeners with deep paths

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Minor version bump due to compiler change.
=> chore: release v3.8.0

packages/lwc/index.d.ts
This can break existing unsupported usage of types. We will be officially supporting types soon, but we're taking the opportunity to make these changes for the major version bump.
W-13823857
=> chore: generics for better typing (BREAKING CHANGE)

packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.isConnected/index.spec.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/index.spec.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/x/child/child.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/x/component/component.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/x/parent/parent.html, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/x/parent/parent.js, packages/@lwc/integration-karma/test/misc/lifecycle-remove-disconnected/lifecycle-remove-disconnected.spec.js, packages/@lwc/integration-karma/test/native-shadow/Event-methods/Event.composedPath.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Node-properties/Node.getRootNode.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Node-properties/Node.isConnected.spec.js, packages/@lwc/integration-karma/test/shadow-dom/event-in-shadow-tree/propagation.spec.js
Fixes #3764
This is a less ambitious version of https://github.com/salesforce/lwc/pull/3815. Rather than trying to report _all_ differences between synthetic and native lifecycle, we only report a `connectedCallback` firing when the element is disconnected from the DOM.
This has a few advantages:
1. It's much easier to detect
2. It's the most common cause of a true functional breakage we've seen with native vs synthetic lifecycle
3. It's something the component author can actually fix themselves (usually)
The risk of this PR is that a component author will be confused if they see the warning and don't understand how to resolve it. Even at the risk of such false positives, though, this PR is probably still worth it.
* ✅ No, it does not …
=> feat(reporting): report disconnected connectedCallback

package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-tests/scripts/wdio.local.conf.js, packages/@lwc/perf-benchmarks/package.json, yarn.lock
Pins 2 dependencies and removes one we are not using.
This fixes ~3/4 of our security alerts – the remaining one would need to be fixed by Best~ all of our security alerts.
=> chore: bump deps to resolve security alerts

packages/@lwc/integration-karma/package.json, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js
This one has bugged me for a while.
If you run `yarn start` in the Karma tests, and your test file has a syntax error, then the whole Karma process (and the browser) crashes. This PR makes it so that the syntax error is temporarily ignored, but only when running in "watch" mode (i.e. `karma start` or `karma hydration:start`).
=> test: syntax errors should not crash karma

.github/workflows/unit.yml
Disable perf smoke test that runs as part of unit test suite. Note: This does not affect perf tests that are run on best.
=> chore: disable perf smoke tests until image with chrome 119 is published

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/basic/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/for-each/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/named-slot/expected.html, packages/@lwc/integration-karma/helpers/test-hydrate.js, packages/@lwc/integration-karma/scripts/shared/options.js, packages/@lwc/integration-karma/test-hydration/adjacent-text-nodes/index.spec.js, packages/@lwc/integration-karma/test-hydration/adjacent-text-nodes/x/main/main.html, packages/@lwc/integration-karma/test-hydration/adjacent-text-nodes/x/main/main.js, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/index.spec.js, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/x/child/child.html, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/x/child/child.js, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/x/main/main.html, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/x/main/main.js, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/x/scoped/scoped.html, packages/@lwc/integration-karma/test-hydration/light-dom/slots/nested-and-scoped/x/scoped/scoped.js, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/if-block/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/runtime-checks/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slotting/index.spec.js, packages/@lwc/shared/src/api-version.ts
Prior to this PR, empty text nodes were placed at each end of a VFragment. This allows for efficient insertion and removal of elements relative to the fragment, which may have sibling nodes not belonging to the fragment. These text nodes are essential bookends for fragments like those found in scoped slots or `lwc:if`.
When rendered on the server, these empty text nodes are rendered using a zero-width space character. This ensures that a text node is actually present after HTML is parsed by the browser. For example,`<div /><div/>` will be parsed by the browser (post-SSR, pre-hydration) as two `<div>`s, even if an empty text node was present in between those `<div>`s in the VDOM.
This introduces two problems:
1.  **Zero-width space characters are layout-impacting.** During hydration, we …
=> chore: use comment nodes for VFragment bookends

.github/workflows/unit.yml, packages/@lwc/perf-benchmarks/scripts/build.js
https://github.com/google/tachometer/blob/main/README.md#on-demand-dependencies
=> chore: pin chromedriver version for github action

packages/@lwc/style-compiler/package.json, packages/@lwc/style-compiler/src/serialize.ts, yarn.lock
`String.prototype.matchall` is available in [Node v12+](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll#browser_compatibility). It should be safe to remove this polyfill.
Technically this is a breaking change, but historically we have not made any guarantees about Node compatibility, nor do we test in any version of Node other than the latest LTS. I suspect Node v10 is already broken anyway, and in any case, nobody should be using it.
This does not merit a major version bump IMO.
See above.
=> fix: remove string.prototype.matchAll polyfill

.github/workflows/integration.yml, .github/workflows/karma.yml, packages/@lwc/integration-karma/scripts/karma-configs/utils.js, packages/@lwc/integration-karma/scripts/shared/options.js, packages/@lwc/integration-tests/scripts/wdio.sauce.conf.js
Guess we were still using some Circle CI env vars. These should have been removed in #3783.
=> chore: remove all Circle CI env vars

.nucleus.yaml
=> chore: add spring24 branch spec to nucleus and remove old branch specs

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Bumps the minor version to differentiate from the newly created `spring24` branch.
=> chore: release v5.1.0

.github/workflows/karma.yml, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js, packages/@lwc/integration-karma/scripts/karma-plugins/transform-framework.js
This fixes sourcemaps in the Karma tests. I confirmed that you can actually set breakpoints in `engine-dom` using `karma start`, and that the Istanbul coverage HTML reports actually work now:
=> chore(integration-karma): fix sourcemaps

packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/accessibility/non-standard-aria-props/index.spec.js, packages/@lwc/integration-karma/test/accessibility/synthetic-cross-root-aria/index.spec.js, packages/@lwc/integration-karma/test/api/freezeTemplate/index.spec.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/component/component.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/component/component.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/light/light.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/light/light.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/native/native.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/native/native.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/parent/parent.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/reporting/x/parent/parent.js, packages/@lwc/integration-karma/test/polyfills/aria-properties/index.spec.js, packages/@lwc/integration-karma/test/rendering/version-mismatch/index.spec.js
Adds telemetry for shadow mode usage (synthetic vs native).
Due to the volume of logs this is going to generate (easily TBs), we'll want to report this as a metric rather than as logs. This will require updating our API to distinguish between logs and metrics (e.g. `incrementCounter`, `log()`). We may also want to refactor the existing `report` API into `log`.
This aligns the runtime reporting with our compiler instrumentation:
https://github.com/salesforce/lwc/blob/6e75634e16a21c500d5e3f45400d1db3da3f5346/packages/%40lwc/errors/src/compiler/instrumentation.ts
Alternatively, we can make this decision in the consuming app container. (e.g. `if (reportName === 'ShadowModeUsage') { ... }`). However, that would require each consuming app to know which reporting events require special handling. …
=> feat: log shadow mode through engine reporting API

.github/workflows/unit.yml
Fixes #3852
Pins chromedriver to the same version of Chrome we are currently using in the Tachometer benchmark smoke tests.
=> chore(ci): pin chromedriver version

.github/workflows/karma.yml, packages/@lwc/shared/src/api-version.ts
This is a _non-breaking_ change to prepare for API version 61 (aka 250, aka Summer '24). All this does it bump the latest API version and add tests for the n-1 version.
=> feat(api-versioning): bump latest to 61

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/transforms-computed-properties/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/transforms-computed-properties/expected.js, packages/@lwc/babel-plugin-component/src/decorators/wire/transform.ts
=> fix(compiler): handle symbol properties for dynamic values

packages/@lwc/babel-plugin-component/src/__tests__/index.spec.ts
If an error is thrown within the Babel plugin itself (e.g. caused by #3910), you get a very unhelpful error because `err.filename` is undefined below, and so it fails when you try to `path.basename` it.
The resulting error is still not very helpful (and we should address #3910 to resolve that), but this PR makes it so you at least don't get a totally unrelated error message.
I do not believe it's worth adding tests for this, because any error thrown by the plugin is a bug that should be fixed eventually, so any test we write will quickly become stale.
=> fix(babel-plugin-component): improve error reporting

.github/workflows/unit.yml
Backport of #3897 so that CI can pass
=> chore(ci): pin chromedriver version [backport]

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/integration-karma/test/component/LightningElement.dispatchEvent/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/restrictions/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/restrictions/x/component/component.js
This is not really a restriction as nothing is actually prevented. The intention was likely to help developers identify potential typos, or maybe to nudge them into using declarative event binding in their template. While it is preferred to use declarative event binding over imperative event binding, we don't prevent the former, so it doesn't make sense to log an error for it. It doesn't make sense to make this a warning for the same reason--this should have been implemented as a lint rule to begin with.
=> chore: remove event name/type restriction

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/light-dom/scoped-styles/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/x/valid/valid.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/restrictions/x/component/component.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/scoped-ids/scoped-ids.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/scoped-ids/x/test/test.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/slotting/x/child/child.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentAnyChildAny/grandparentAnyParentAnyChildAny.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentAnyChildReset/grandparentAnyParentAnyChildReset.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentResetChildAny/grandparentAnyParentResetChildAny.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/grandparentAnyParentResetChildReset/grandparentAnyParentResetChildReset.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/leafAny/leafAny.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/parentAnyChildAny/parentAnyChildAny.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/synthetic-behavior/x/parentAnyChildReset/parentAnyChildReset.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/transitivity/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/transitivity/x/native/native.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/transitivity/x/nativeContainer/nativeContainer.js, packages/@lwc/integration-karma/test/static-content/index.spec.js, packages/@lwc/integration-karma/test/static-content/x/native/native.js
This PR removes the `shadowSupportMode = 'any'` option.
`shadowSupportMode = 'any'` was gated behind a feature flag and should not break existing customers.
W-14832125
=> refactor: remove `shadowSupportMode = 'any'`

packages/@lwc/integration-karma/test/component/decorators/api/index.spec.js
Firefox tests are newly failing due to:
```
Firefox 121.0 (Windows 10) component decorators api non-LightningElement `this` when calling accessor getterSetter setter - external FAILED
Expected function to throw TypeError with a message matching /(undefined is not an object|Right side of assignment cannot be destructured|vm is undefined|undefined is not a VM|Cannot destructure property '(getHook|setHook)'|Cannot read properties of undefined)/, but it threw TypeError with message 'undefined has no properties'.
```
This fixes that.
=> chore: fix broken test due to Firefox update

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/x/any/any.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/LightningElement.shadowSupportMode/x/any2/any2.js
This avoids making the removal of `shadowSupportMode="any"` a breaking change.
W-14974451
=> chore: warn on shadowSupportMode 'any'

.github/workflows/karma.yml, packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/check-version-mismatch.ts, packages/@lwc/engine-core/src/framework/utils.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/helpers/test-setup.js, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-karma/scripts/karma-configs/test/tags.js, packages/@lwc/integration-karma/scripts/karma-plugins/env.js, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js, packages/@lwc/integration-karma/scripts/shared/options.js, packages/@lwc/integration-karma/test/light-dom/slotting/index.spec.js, packages/@lwc/integration-karma/test/rendering/version-mismatch/index.spec.js, scripts/bundlesize/bundlesize.config.json, yarn.lock
In #3883 we changed the format of the compiled components to use the `slotAssignment` key rather than `attrs.slot`.
Unfortunately this breaks anyone who uses the LWC v5 compiler in combination with the v6 engine.
Version mismatches between the compiler and the engine have never been supported, but as a temporary measure, this PR proposes that we support v5-compiler-plus-v6-engine.
[W-14974789](https://gus.lightning.force.com/a07EE00001jWYzpYAG)
=> fix(engine-dom): support LWC v5 compiler slot format

packages/@lwc/engine-core/src/framework/def.ts, packages/@lwc/engine-core/src/framework/reporting.ts, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/any/any.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/native/native.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/none/none.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/shadowSupportModeReporting/x/reset/reset.js
Adds logging for shadowSupportMode 'any' and 'native'.
=> feat: add reporting for shadowSupportMode

packages/@lwc/integration-karma/scripts/karma-configs/shared/browsers.js, packages/@lwc/integration-tests/scripts/wdio.sauce.conf.js
=> fix: pin chrome version to bypass shadowRoot issues with chrome 121

packages/@lwc/aria-reflection/tsconfig.json, packages/@lwc/babel-plugin-component/tsconfig.json, packages/@lwc/engine-core/tsconfig.json, packages/@lwc/engine-dom/tsconfig.json, packages/@lwc/engine-server/tsconfig.json, packages/@lwc/features/tsconfig.json, packages/@lwc/signals/tsconfig.json, packages/@lwc/synthetic-shadow/tsconfig.json, packages/@lwc/wire-service/tsconfig.json, scripts/rollup/rollup.config.js, tsconfig.json
Fixes #3366 
@jamestu, @jye-sf, @wjhsf, and I determined the ES version to upgrade using the [compat table](https://compat-table.github.io/compat-table/es2016plus/) while considering Safari v16 as the lowest common denominator. It shows that Safari does not seem to have complete support for `Function.prototype.toString` which is an ES2019 feature, but we found it to be working when testing it in Safari v17.3:
```js
> const sum = new Function('a', 'b', 'return a + b');
> sum.toString();
> "function anonymous(a, b) {
return a + b
}" = $1
```
https://compat-table.github.io/compat-table/es2016plus/
To be safe, we might consider adding a lint rule to make sure we don't use this anywhere, but that wouldn't guarantee that our transpilation target wouldn't use it.
If lack of support for …
=> chore: Update target to es2021

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release additional logging around shadowSupportMode.
Exposed through `__unstable__ReportingControl` which should not be used by downstream consumers.
=> chore: release v5.0.9

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/modules/static-parts.ts, packages/@lwc/engine-core/src/framework/rendering.ts
Fixes #3800
This PR fixes the issue of calling `traverseAndSetElement` on every render by only traversing the parts instead of the entire subtree of the static node.
I wrote a small perf benchmark to demonstrate the gains with deeply nested static parts, [here](https://github.com/salesforce/lwc/commit/cd318b9d196f9916832d4534d5569577364ba05b). 
The benchmark shows a roughly 17% perf improvement in this scenario.
The benchmark is not included in this PR as it is specific to this fix and I plan to include more benchmarks as part of the work in #3624.
W-15044923
=> refactor: avoid calling traverseAndSetElement on every rerender

packages/lwc/__tests__/default-exports.spec.ts, packages/lwc/__tests__/package-exports.spec.ts, packages/lwc/babel-plugin-component.d.ts, packages/lwc/babel-plugin-component.js, packages/lwc/features.d.ts, packages/lwc/features.js, packages/lwc/jest.config.cjs, packages/lwc/rollup-plugin.d.ts, packages/lwc/rollup-plugin.js, packages/lwc/template-compiler.d.ts, packages/lwc/template-compiler.js, packages/lwc/tsconfig.json, scripts/jest/root.config.js
Some of our packages have default exports, but `export * from 'some-package'` does not include the default export. In order to use a default export from an `lwc` re-export, the default export must be handled explicitly.
```ts
import LwcRollupPlugin from '@lwc/rollup-plugin' // has always worked
import LwcRollupPlugin from 'lwc/rollup-plugin' // didn't work, now it does
```
W-13710298
=> fix: add default exports to `lwc` @W-13710298

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/shared/src/language.ts
Currently, `isObject` claims that it narrows a type to simply `object`, but it only checks `typeof obj === 'object'` and does not check for `null`. The following code passes type validation, but fails at runtime.
```ts
const obj: object | null = null
if (isObject(obj)) obj.toString()
```
The options to fix this are either to preserve the type guard and change the runtime behavior, or change the type guard and preserve the runtime behavior. Tests in our repo pass either way, but I opted for the former because preserving runtime behavior seems less likely to subtly break downstream users.
I also changed `any` to `unknown` where it is safe to do so, because that's Best Practices™ ✨.
=> fix: isObject doesn't actually narrow down to just an object

.github/workflows/unit.yml
The chromedriver v119 endpoints are throwing a 500 error for some reason, but 121 is not. We just need a pinned version; either 121 or 119 should work fine.
=> chore: pin CI tests to chrome 121

packages/@lwc/integration-karma/test/component/lifecycle-callbacks/index.spec.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/foo/foo.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/fooInternal/fooInternal.js
While documenting [timing differences in lifecycle callbacks in LWC v6](https://github.com/salesforce/lwc/releases/tag/v6.0.0#new-timing), I realized we didn't have corresponding tests for the ordering of `disconnectedCallback`, in addition to `connectedCallback`/`renderedCallback`. This adds those tests.
=> test(integration-karma): improve lifecycle timing tests

packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/nativeChild/nativeChild.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/nativeChild/nativeChild.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/syntheticParent/syntheticParent.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/syntheticParent/syntheticParent.js, packages/@lwc/synthetic-shadow/src/3rdparty/polymer/retarget.ts
Fixes #3958
Yes, but only as a bug fix for events dispatched on elements that were slotted into a native shadow.
Yes, but only as a bug fix for events dispatched on elements that were slotted into a native shadow.
W-15120294
=> fix(synthetic-shadow): retargeting does not correctly account for native shadow roots

packages/@lwc/integration-karma/test/component/lifecycle-callbacks/index.spec.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/foo/foo.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/lightContainer/lightContainer.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/lightContainer/lightContainer.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/lightFoo/lightFoo.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/lightFoo/lightFoo.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/lightFooInternal/lightFooInternal.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/invocationorder/lightFooInternal/lightFooInternal.js
Follow-up to #4009 to add tests for light DOM.
Interestingly, this test shows the same behavior between light DOM and synthetic shadow, so I may need to do some extra tests to figure out why #4013 is showing bizarre behavior for `renderedCallback` only in light DOM.
=> test: add tests for invocation order in light DOM

packages/@lwc/integration-karma/test/component/default-export/index.spec.js, packages/@lwc/integration-karma/test/component/default-export/x/exportAsDefault/exportAsDefault.html, packages/@lwc/integration-karma/test/component/default-export/x/exportAsDefault/exportAsDefault.js, packages/@lwc/integration-karma/test/component/default-export/x/exportAsDefaultWithOtherExports/exportAsDefaultWithOtherExports.html, packages/@lwc/integration-karma/test/component/default-export/x/exportAsDefaultWithOtherExports/exportAsDefaultWithOtherExports.js, packages/@lwc/integration-karma/test/component/default-export/x/exportDefaultClassWithOtherExports/exportDefaultClassWithOtherExports.html, packages/@lwc/integration-karma/test/component/default-export/x/exportDefaultClassWithOtherExports/exportDefaultClassWithOtherExports.js
This just adds skipped tests for #4020 as well as confirming that we aren't currently breaking non-default exports mixed with a default export, as long as the default export uses the `export default class extends LightningElement` syntax.
=> test: add test to confirm export behavior

packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/index.spec.js
This moves some logic that we only need for Karma tests into Karma-only code. There's no reason for us to have code that affects prod if it's only used in our own tests.
=> refactor: move fragment cache-busting to Karma-only

.eslintrc, packages/@lwc/compiler/src/index.ts, packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/javascript.ts, packages/@lwc/compiler/src/transformers/style.ts, packages/@lwc/compiler/src/transformers/template.ts, packages/@lwc/compiler/src/transformers/transformer.ts, packages/@lwc/engine-dom/src/apis/build-custom-element-constructor.ts, packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/engine-dom/src/apis/hydrate-component.ts, packages/@lwc/engine-dom/src/apis/is-node-from-template.ts, packages/@lwc/engine-dom/src/renderer-factory.ts, packages/@lwc/engine-dom/src/renderer/context.ts, packages/@lwc/engine-server/src/apis/create-element.ts, packages/@lwc/engine-server/src/apis/render-component.ts, packages/@lwc/engine-server/src/serializer.ts, packages/@lwc/engine-server/src/utils/classes.ts, packages/@lwc/engine-server/src/utils/validate-style-text-contents.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/wire-service/src/index.ts, packages/@lwc/wire-service/src/value-changed-event.ts, packages/lwc/__tests__/default-exports.spec.ts, packages/lwc/index.d.ts
Like it says on the tin.
W-13278716
=> docs: add more JSDoc for top-level exports @W-13278716

.eslintrc, packages/@lwc/engine-core/src/framework/base-bridge-element.ts, packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/check-version-mismatch.ts, packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/engine-core/src/framework/restrictions.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/wiring/wiring.ts, packages/@lwc/engine-core/src/patches/detect-non-standard-aria.ts, packages/@lwc/engine-core/src/shared/logger.ts, packages/@lwc/engine-dom/src/styles.ts, packages/@lwc/features/src/__tests__/features.spec.ts, packages/@lwc/features/src/__tests__/lwcRuntimeFlags.spec.ts, packages/@lwc/features/src/__tests__/setFeatureFlag.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/apiVersion/apiVersion.spec.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/focus.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/html-element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-root.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/slot.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/@lwc/synthetic-shadow/src/polyfills/event-target/polyfill.ts, packages/@lwc/template-compiler/src/__tests__/index.spec.ts, packages/@lwc/template-compiler/src/parser/expression-complex/html.ts, packages/lwc/index.d.ts
In #3995 I claimed to leverage the full power of `@typescript-eslint`. That was a lie! I focused on the rules that were auto-fixable or minimal manual fixes, and disabled the ones requiring manual fixes. In #4025, a new `@ts-ignore` was introduced, so I decided that it seemed like a good time to re-enable the rule saying "hey, don't do that!"
=> chore: avoid @ts-ignore

packages/@lwc/integration-karma/test/shadow-dom/event-in-shadow-tree/event-post-dispatch.spec.js
Safari fixed their bug a while back so these tests should pass for native shadow now:
https://bugs.webkit.org/show_bug.cgi?id=206374
=> test: enable test for native shadow

packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/text-node-adjacency/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/text-node-adjacency/expected.js, packages/@lwc/template-compiler/src/parser/index.ts
The logic used to discard unnecessary HTML whitespace was being applied to text content whitespace due to a change in the timing that the text content whitespace is being parsed. Detailed comment added for posterity when we need to integrate the complex expression changes.
[W-14631165](https://gus.lightning.force.com/a07EE00001g6aQOYAY)
=> fix(template-compiler): avoid discarding text content whitespace for complex expressions

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/transforms-computed-properties-const-from-obj/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/transforms-computed-properties-const-from-obj/expected.js
This adds a test to confirm that you can do the following:
```js
import * as importee from 'some/importee'
const obj = { baz: 'baz', quux: 'quux' }
const { foo } = importee;
const bar = importee.bar;
const { baz } = obj
const quux = obj.quux
export default class Test extends LightningElement {
@wire(getFoo, {
[foo]: '$foo',
[bar]: '$bar',
[baz]: '$baz',
[quux]: '$quux'
})
yolo
```
In #3956 we are questioning how much we want to lock this down, and if maybe the current behavior is too permissive, but this test at least documents the existing behavior.
=> test: add test for wired properties from consts

packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/api/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/sanity/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.errorCallback/index.spec.js, packages/@lwc/integration-karma/test/component/face-callbacks/index.spec.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/index.spec.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/if-block/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/index.spec.js, packages/@lwc/integration-karma/test/light-dom/scoped-slot/runtime-checks/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slot-fowarding/slots/forwarding/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slot-fowarding/slots/reactivity/index.spec.js, packages/@lwc/integration-karma/test/light-dom/slotting/index.spec.js, packages/@lwc/integration-karma/test/light-dom/synthetic-shadow-styles/index.spec.js, packages/@lwc/integration-karma/test/misc/lifecycle-remove-disconnected/lifecycle-remove-disconnected.spec.js, packages/@lwc/integration-karma/test/misc/object-rest-spread/index.spec.js, packages/@lwc/integration-karma/test/misc/performance-timing/index.spec.js, packages/@lwc/integration-karma/test/native-shadow/Event-methods/Event.composedPath.spec.js, packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js, packages/@lwc/integration-karma/test/rendering/dynamic-slots/index.spec.js, packages/@lwc/integration-karma/test/rendering/legacy-scope-tokens/index.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Node-properties/Node.getRootNode.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Node-properties/Node.isConnected.spec.js, packages/@lwc/integration-karma/test/shadow-dom/event-in-shadow-tree/propagation.spec.js, packages/@lwc/integration-karma/test/static-content/index.spec.js, packages/@lwc/shared/src/api-version.ts
This is just a refactor of the test code to organize how we test API versioning.
I find it easier to think about when the Karma tests explicitly say `if (someApiVersionFeature)` rather than `if (process.env.API_VERSION >= 59)`.
=> refactor: organize API versioning tests

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/engine-core/src/framework/utils.ts, packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/engine-dom/src/apis/hydrate-component.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/api/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/index.spec.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/x/formAssociated/formAssociated.html, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/x/formAssociatedFalse/formAssociatedFalse.html, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/x/formAssociatedFalseNoAttachInternals/formAssociatedFalseNoAttachInternals.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/x/formAssociatedNoAttachInternals/formAssociatedNoAttachInternals.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/x/notFormAssociated/notFormAssociated.html, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/formAssociated/x/notFormAssociatedNoAttachInternals/notFormAssociatedNoAttachInternals.js, packages/@lwc/integration-karma/test/component/LightningElement.attachInternals/elementInternals/sanity/index.spec.js, packages/@lwc/integration-karma/test/component/face-callbacks/index.spec.js, packages/@lwc/shared/src/api-version.ts
Fixes #3929
Logs a warning when using synthetic custom element lifecycle and attempting to use `static formAssociated = true`. Also, ensures `formAssociated` is always false when the API version is <61.
Technically someone could have been trying to use an older API version and setting formAssociated to true, but the FACE callbacks wouldn't have worked and older API versions are not used in OSS so I really doubt anyone took a dependency on this.
=> fix: disable form association entirely on older API versions

.github/PULL_REQUEST_TEMPLATE.md
I don't like "✅ No". Also, it's slightly inconvenient that ⚠️ displays in text-mode in the editor but emoji-mode in the actual post.
=> chore: new year, new emoji 🚀

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/class/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/class/error.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/is/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/is/error.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/slot/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/slot/error.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/style/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/disallowed-props/style/error.json, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/throws-error-if-property-name-conflicts-with-disallowed-global-html-attribute-name/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/api-decorator/throws-error-if-property-name-is-is/actual.js
This is extracted out of #4044 since it's not strictly related to that PR.
This just adds tests to confirm the behavior of disallowed `@api` properties defined here:
https://github.com/salesforce/lwc/blob/ccd0253991b6e5b806369d4e021833ab14c505e5/packages/%40lwc/babel-plugin-component/src/constants.ts#L23-L26
Previously, only some of these props were tested. Now, they are all tested.
=> test: consistent fixture tests for disallowed `@api` props

packages/@lwc/integration-karma/test/component/lifecycle-callbacks/index.spec.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/item/item.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/item/item.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/itemLight/itemLight.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/itemLight/itemLight.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/itemWrapper/itemWrapper.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/itemWrapper/itemWrapper.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/itemWrapperLight/itemWrapperLight.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/itemWrapperLight/itemWrapperLight.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/list/list.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/list/list.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/listLight/listLight.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/reordering/listLight/listLight.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/child/child.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/child/child.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/childLight/childLight.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/childLight/childLight.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/parent/parent.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/parent/parent.js, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/parentLight/parentLight.html, packages/@lwc/integration-karma/test/component/lifecycle-callbacks/timing/parentLight/parentLight.js
This reproduces the issue described in #4057 and merely asserts the current behavior.
We should probably fix it, but first I wanted to at least have a repro of the issue itself. I added `TODO` comments where applicable.
=> test: reproduce timing issue with renderedCallback

packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/nativeChild/nativeChild.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/nativeChild/nativeChild.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/syntheticChild/syntheticChild.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/syntheticChild/syntheticChild.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/syntheticParent/syntheticParent.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/retargeting/x/syntheticParent/syntheticParent.js, packages/@lwc/synthetic-shadow/src/3rdparty/polymer/path-composer.ts, packages/@lwc/synthetic-shadow/src/3rdparty/polymer/retarget.ts, packages/@lwc/synthetic-shadow/src/shared/utils.ts
Fixes https://github.com/salesforce/lwc/issues/3958
Bringing back #4018 with the following consideration:
Account for the case where the event target is not shadowed, in addition to the case where the retargeting candidate is shadowed by a native shadow root.
Yes, but only as a bug fix for events dispatched on elements that were slotted into a native shadow.
W-15120294
=> fix(synthetic-shadow): account for both non-shadowed targets and targets shadowed by native shadow roots

packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/computed-property/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/computed-property/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/computed-property/config.json, packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/computed-property/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/expression-complex/valid/computed-property/metadata.json, packages/@lwc/template-compiler/src/codegen/expression.ts
`arr[baz]` and `arr.baz` are both considered member expressions, with the difference being whether the property is computed or not. 
W-14631155
=> fix(template-compiler): add complex template expression binding support for computed properties

packages/@lwc/perf-benchmarks-components/src/benchmark/jsFrameworkBenchmarkTable/jsFrameworkBenchmarkTable.html, packages/@lwc/perf-benchmarks-components/src/benchmark/jsFrameworkBenchmarkTable/jsFrameworkBenchmarkTable.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/append-rows-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/clear-rows-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/create-rows-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/create-rows-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/partial-update-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/remove-row-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/replace-rows-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/select-row-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/swap-rows-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/utils/runJsFrameworkBenchmark.js
As we track our progress with fine-grained reactivity (#3624), I think it would be helpful to have the actual `js-framework-benchmark` benchmarks in our local benchmarks. Otherwise, it's kind of a pain to set up `js-framework-benchmark` itself, link it to LWC, and run it to see the results.
This PR is my attempt to replicate as closely as possible what `js-framework-benchmark` is doing. A few limitations:
- There is some overlap here with existing benchmarks, which were clearly also inspired by `js-framework-benchmark` but are slightly different.
- Some of the benchmarks execute quite quickly (<5ms), which is not great for Tachometer since it tends to lead to lots of variance. _(**Update**: opened #4070 to resolve this.)_
Despite these limitations, I still think this is worth doing, at …
=> perf: add js-framework-benchmark tests

packages/@lwc/perf-benchmarks/README.md, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/perf-benchmarks/scripts/build.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-expression/expression.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/clear-rows-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/partial-update-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/remove-row-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/select-row-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/js-framework-benchmark/swap-rows-1k.benchmark.js
(This PR is on top of #4069 to avoid bitrotting myself.)
The `js-framework-benchmark` actually throttles some of its benchmarks in its [reported results](https://krausest.github.io/js-framework-benchmark/2024/table_chrome_122.0.6261.69.html). We should mimic this behavior to try to approximate what they're doing.
Plus, some of our existing benchmarks also execute fairly quickly, so throttling them could help reduce variance.
This adds CPU throttling to certain benchmarks (matching the `js-framework-benchmark` behavior), as well as adding a global `BENCHMARK_CPU_THROTTLING_RATE` that can be set on the command line and which overrides the per-benchmark defaults.
Note that this only affects Tachometer, not Best. Best has no CPU throttling currently.
-   😮‍💨 No, it does not introduce a …
=> perf: add throttling to tachometer benchmarks

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts
In #3381 the `@lwc/engine-server` fixture test warnings were suppressed.
The intention here was to only supress the warnings generated for `lwc:dynamic` [usage](https://github.com/salesforce/lwc/tree/jtu/enable-engine-server-warnings/packages/%40lwc/engine-server/src/__tests__/fixtures/lwc-dynamic).
Supressing all warnings in `@lwc/engine-server` hid an issue with the fixture tests in #4055.
Filtering the warnings to specifically look for `lwc:dynamic` warning messages.
=> chore: filter `@lwc/engine-server` fixture test warnings for `lwc:dynamic` only

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
First weekly release.
From https://github.com/salesforce/lwc/pull/4059:
> This is technically a breaking change, but it's only a breaking change for npm package users who have mismatched LWC versions. These users should use something like [Yarn resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) if necessary to force all their lwc and @lwc/* dependencies to the same version.
=> chore: release v6.3.4

packages/@lwc/integration-karma/test/mixed-shadow-mode/composed-path/index.spec.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/composed-path/x/test/component.js, packages/@lwc/integration-karma/test/mixed-shadow-mode/composed-path/x/test/test.html, packages/@lwc/integration-karma/test/mixed-shadow-mode/composed-path/x/test/test.js, packages/@lwc/synthetic-shadow/src/polyfills/event-target/polyfill.ts
Backport for #4012 
W-15126229
=> fix: event listener not being invoked for native web components

packages/@lwc/engine-core/src/framework/rendering.ts, packages/@lwc/integration-karma/test/static-content/index.spec.js, packages/@lwc/integration-karma/test/static-content/x/iframeOnload/iframeOnload.html, packages/@lwc/integration-karma/test/static-content/x/iframeOnload/iframeOnload.js
Fixes #4081
This is just a matter of inserting the static nodes after applying their event listeners, as originally discovered by @jmsjtu.
Well unless you consider the fact that `iframe` `onload` works correctly now. 😅
=> fix: fix iframe onload with static content optimization

packages/@lwc/engine-core/src/framework/modules/events.ts
Removes an unnecessary `?.` (nullisch coalescing). This object is always defined and non-null.
=> fix: remove unnecessary nullish coalescing

packages/@lwc/synthetic-shadow/src/env/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/shadow-token.ts
Optimizes the `recursivelySetShadowResolver` function to avoid calling `childNodes` and to use `firstChild`/`nextSibling` instead.
Browsers represent the DOM as a [linked list](https://viethung.space/blog/2020/09/01/Browser-from-Scratch-DOM-API/#Choosing-DOM-tree-data-structure) under the hood, so this is faster.
This improves the `dom-ss-slot-create-container-5k-this-change` benchmark by 4-9%, and possibly some other synthetic-shadow benchmarks as well.
The reason this is important is because we set `KEY__SHADOW_STATIC` on the top level of a static fragment, which then causes us to recurse through the entire DOM structure to set the `KEY__SHADOW_RESOLVER`. (This is used for the legacy `isNodeShadowed`/`isNodeFromTemplate` as well as for the patched `MutationObserver`.) If we have a lot …
=> perf(synthetic-shadow): optimize recursivelySetShadowResolver

packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts
This optimizes `createUpgradableConstructor` and thus improves the `dom-light-styled-component-create-1k-different` benchmark by 6-7%:
The main optimization is to avoid creating the same `class` with the same methods/constructor over and over, and to instead just `extend` a base class.
=> perf: optimize `createUpgradableConstructor`

packages/@lwc/template-compiler/src/__tests__/fixtures/directive-for-each/static-content-optimization/expected.js
Unfortunately #4092 and #4071 are not compatible with each other, and were merged separately. One of the new snapshots introduced by one was modified by the other. This PR fixes the snapshot.
=> chore: update jest snapshot

packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-dom/src/apis/build-custom-element-constructor.ts, packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts, packages/@lwc/integration-karma/test/component/face-callbacks/face/formAssociated/formAssociated.js, packages/@lwc/integration-karma/test/component/face-callbacks/face/lightDomFormAssociated/lightDomFormAssociated.js, packages/@lwc/integration-karma/test/component/face-callbacks/index.spec.js, packages/lwc/index.d.ts
Fixes #4093. Adds support for arguments in Form Associated Custom Element callbacks.
The params for these callbacks work now. 🙂
=> fix: support arguments for FACE callbacks

packages/@lwc/engine-core/src/framework/modules/computed-class-attr.ts
This optimizes `patchClassAttribute`, specifically the case where the old class name is `undefined` and the new one is `""` (the empty string). This is exercised by the `js-framework-benchmark` component here:
https://github.com/salesforce/lwc/blob/3665f31e94ee8b990036c7caaa4be4d4496d77ca/packages/%40lwc/perf-benchmarks-components/src/benchmark/jsFrameworkBenchmarkTable/jsFrameworkBenchmarkTable.js#L134-L136
Here is the perf improvement (relative to #4099):
=> perf(engine-core): optimize `patchClassAttribute`

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-server/src/__tests__/fixtures/lifecycle-hooks/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/lifecycle-hooks/modules/x/lifecycle-hooks/lifecycle-hooks.html, packages/@lwc/integration-karma/test/template/directive-for-each/index.spec.js
There's an edge case not covered in our existing tests with the fix introduced in #4097.
On the server, it looks like [`VStatic.fragment` does not have a `tagName`](https://github.com/salesforce/lwc/blob/master/packages/%40lwc/engine-server/src/renderer.ts#L98-L104).
This PR fixes the issue but defaulting to the VM's tag name since there is no better alternative on the server.
=> fix: error accessing tagName on fragment

packages/@lwc/integration-karma/test/light-dom/root/index.spec.js, packages/@lwc/synthetic-shadow/src/faux-shadow/element.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/node.ts, packages/@lwc/synthetic-shadow/src/faux-shadow/traverse.ts, packages/@lwc/synthetic-shadow/src/shared/node-ownership.ts
Fixes #4076
Light DOM nodes aren't owned by any shadow root. We change `isNodeOwedBy` to account for `owner` being null.
=> fix: children and childNodes not returning top-level slotted children

packages/@lwc/engine-core/package.json, packages/@lwc/engine-core/src/libs/signal-tracker/index.ts, packages/lwc/package.json
Not sure why this hasn't broken sooner but the `@lwc/signals` package is causing breakages in our nucleus down streams.
The reason is because the the `SignalTracker` imports the `Signal` type from `@lwc/signals` and because it hasn't been added as a dependency it causes breakages.
W-15276750
=> fix: add signals as dependency

packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts
The optimization introduced in #4092 to hoist the `UpgradableConstructor` seems to be causing issues without downstream teams.
The current suspicion is that the `BaseUpgradableConstructor` falls out of scope and causes an `Illegal Constructor` failure.
Can't do a straight revert because #4094 builds on top of #4092 so I'm creating a new PR to move it back into `createUpgradableConstructor`.
W-15276750
=> fix: move `UpgradableConstructor` back into `createUpgradableConstructor`

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.4.1

.nucleus.yaml
I noticed that some of our `yarn lint` jobs are causing Nucleus to crash with an OOM since ESLint is apparently a hungry boy. I stole this Nucleus config from [LBC here](https://github.com/salesforce-experience-platform-emu/lightning-components/blob/f809bde3a8dc9400126710246b211a2b1705fdfe/.nucleus.yaml#L13-L22) and it should bump us up to 16GB on these instances.
=> chore(nucleus): bump memory limit

packages/@lwc/integration-karma/scripts/karma-configs/shared/browsers.js
Resolves https://github.com/salesforce/lwc/issues/3987 to use latest chrome version in saucelabs.
W-15377039
=> fix: use latest chrome version in saucelabs

packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts
This brings back the perf optimization from #4092 which was removed in #4110. This does so safely in a way that doesn't break due to W-15361244 (which I verified manually).
Interestingly, the perf improvement is no longer quite as big – only in the 1-2% range:
It turns out the reason is that the bulk of the original improvement came not from the superclass, but instead from avoiding the for-loop to set all the props on the prototype (https://github.com/nolanlawson/lwc-1/commit/58e45c33c30b4708333bac45388c8f81632db4f1):
Either way, this PR is still a perf improvement, and we can do it safely now.
=> perf(engine-dom): bring back BaseUpgradableConstructor

.github/dependabot.yml
Run once per week, grouping non-major version changes into a single PR, as they are theoretically non-breaking changes.
W-15450855
=> chore: configure dependabot @W-15450855

packages/@lwc/engine-core/src/libs/mutation-tracker/index.ts, packages/@lwc/perf-benchmarks-components/src/benchmark/tree/tree.html, packages/@lwc/perf-benchmarks-components/src/benchmark/tree/tree.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-tree/tree-create-3k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-tree/tree-remove-3k.benchmark.js
Instead of doing an expensive `Array#splice` in this perf-sensitive mutation tracking code, we can
1) swap the target item with the last item
2) call `Array#pop` instead
I couldn't find an existing benchmark to repro the improvement in Chrome, so I wrote a new one. This new test builds a tree structure with recursive components. The reason it repros the improvement is that it has lots of component instances that are tracking mutations on a single getter (which is probably something that happens in the real world fairly frequently).
The improvement is 20-24%:
Here it is in a manual test to show the improvement to the `reset()` function:
FWIW I got this idea from Svelte [here](https://github.com/sveltejs/svelte/blob/3bb231197e7787b785cb463560f1b176323c119a/packages/svelte/src/internal/client …
=> perf(engine-core): avoid `Array#splice` in mutation tracking

packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/typings/acorn.d.ts, yarn.lock
Acorn shipped a breaking change in its types: https://github.com/acornjs/acorn/issues/1260
This is a workaround based on Svelte's solution: https://github.com/sveltejs/svelte/pull/10301
=> chore(template-compiler): update acorn and fix its types

.github/dependabot.yml, packages/@lwc/perf-benchmarks/package.json
We can't update `tachometer` due to a breaking change that hasn't been resolved yet.
For now we need to tell Dependabot not to try to update this dependency.
=> chore(dependabot): pin tachometer version

packages/@lwc/engine-server/src/apis/hot-swaps.ts, packages/@lwc/engine-server/src/index.ts
This exposes stubs for HMR APIs from `@lwc/engine-server`, so that the modules with HMR hooks are valid but these APIs are a no-op.
W-15369047
=> feat: exports HMR stubs from engine-server

packages/@lwc/compiler/src/transformers/__tests__/transform-javascript.spec.ts, packages/@lwc/compiler/src/transformers/transformer.ts
Fix: LWC compiler errors on .jsx/.tsx files #4122. 
(Treating .jsx/.tsx  file extensions the same as .js & .ts.) 
=> Fix: lwc compiler errors on .jsx/.tsx files

.nucleus.yaml
See [docs](https://confluence.internal.salesforce.com/display/UIPENGSYS/Jobs) and [release failure](https://nucleus.uipengsys-public.buildndeliver-s.aws-esvc1-useast2.aws.sfdc.cl/workflows/221455#job=997848&step=node-conformance). `yarn lint` is running up against memory limits, preventing a release.
=> chore(nucleus): bump memory for release job

packages/@lwc/engine-core/src/framework/modules/static-parts.ts, packages/@lwc/engine-core/src/framework/renderer.ts, packages/@lwc/engine-dom/src/renderer/index.ts, packages/@lwc/engine-server/src/renderer.ts
This improves the `js-framework-benchmark`'s `create-10k` test by 8-10% in Chrome/Firefox and 4-9% in Safari. It does so by avoiding either recursion or a stack (array) by using a loop with `firstChild`/`nextSibling`/`parentNode`.
<details><summary>Click to see benchmark results</summary>
</details>
I was kind of concerned that adding `parentNode` would cause a perf regression in synthetic shadow (due to patches), but I tested manually in synthetic shadow (https://github.com/nolanlawson/lwc-1/commit/4536c23ffeed0bb2a08de47217ef07eb7755504b), and it's faster there as well:
<details><summary>Click to see</summary>
</details>
I also tried using a `TreeWalker` (https://github.com/nolanlawson/lwc-1/commit/303e7b7a796437a1ba42aa2499ba47ab8d2ed610), since [this is what Lit …
=> perf: avoid using a stack in `traverseAndSetElements`

.github/workflows/unit.yml, package.json, scripts/tasks/generate-license-files.js
https://github.com/salesforce/lwc/blob/cab5e419494975657246f0543005f4ed521cc139/package.json#L15
The current root build script uses `nx` to run `build` in all the packages, and then generates license files. This prevents me from running `yarn build -p <project>`, which is lame. Also, we don't need to regenerate licenses every time we make code changes, only when we update our dependencies!
This PR removes the license generation from the build script and enforces it via lint-staged and CI.
=> chore(scripts): separate license generation from build script

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts
Fix `@lwc/engine-server` circular dependency warning
=> test: fix `@lwc/engine-server` circular dependency warning

package.json
Follow up to #4191 because I forgot to delete a word. Per the [`nx` docs](https://nx.dev/nx-api/nx/documents/run-many#all), specifying `--all` is no longer required. The command is the same without the flag, and removing it allows us to use `--project` to build only specific projects.
=> chore(scripts): remove `--all` from build script to enable using `--project`

.nucleus.yaml
Refreshes our required Nucleus downstreams based on
1. Low flakiness
2. Tests not taking too long
3. Team ownership, no individual repos
[Spreadsheet with analysis based on last 10 runs](https://docs.google.com/spreadsheets/d/1xP4oMFUxZYMQ6D2mkcGaBYZXM7pMuqQqSeBn0BGZSv8/edit?usp=sharing)
=> chore(nucleus): refresh required downstreams

.nucleus.yaml
Backport of #4120 to fix nucleus jobs
=> chore(nucleus): bump memory limit summer24

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/integration-karma/test/regression/invalid-key/index.spec.js, packages/@lwc/integration-karma/test/regression/invalid-key/x/conditionalList/conditionalList.html, packages/@lwc/integration-karma/test/regression/invalid-key/x/conditionalList/conditionalList.js
By expanding static content optimization to more nodes we've revealed a bug with the existing diffing algo.
In special circumstances when a text vnode is compared against a static vnode they will be considered the same vnode because we use the `sel` and `key` to determine vnode equality.
Since both text and static vnodes have an `undefined` `key` and `sel` values they are incorrectly evaluated.
This PR updates the values of `sel` to distinguish these vnodes and prevent future false positives.
=> fix: add selector type to all vnodes

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/engine-core/src/framework/vnodes.ts, packages/@lwc/integration-karma/test/regression/invalid-key/index.spec.js, packages/@lwc/integration-karma/test/regression/invalid-key/x/conditionalList/conditionalList.html, packages/@lwc/integration-karma/test/regression/invalid-key/x/conditionalList/conditionalList.js
=> fix: add selector type to all vnodes (#4234)

packages/@lwc/aria-reflection/README.md
Updates the README to explicitly spell out which ARIA reflections we support, via the polyfill or otherwise.
The polyfill README feels like a good place to document this.
=> docs: flesh out list of ARIA reflections

packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js, packages/@lwc/integration-karma/test/mixed-api-version/index.spec.js, packages/@lwc/integration-karma/test/mixed-api-version/x/container/container.html, packages/@lwc/integration-karma/test/mixed-api-version/x/container/container.js, packages/@lwc/integration-karma/test/mixed-api-version/x/useApiVersion60/useApiVersion60.html, packages/@lwc/integration-karma/test/mixed-api-version/x/useApiVersion60/useApiVersion60.js
Fixes #4242.
In dev mode, synthetic lifecycle will actually work for lazy components inside of non-portals now.
W-15812405
=> fix: fix synthetic lifecycle for mixed API versions and non-portals

packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js, packages/@lwc/integration-karma/test/mixed-api-version/index.spec.js, packages/@lwc/integration-karma/test/mixed-api-version/x/container/container.html, packages/@lwc/integration-karma/test/mixed-api-version/x/container/container.js, packages/@lwc/integration-karma/test/mixed-api-version/x/useApiVersion60/useApiVersion60.html, packages/@lwc/integration-karma/test/mixed-api-version/x/useApiVersion60/useApiVersion60.js
=> fix: fix synthetic lifecycle for mixed API versions and non-portals (backport)

packages/@lwc/integration-karma/test/regression/lifecycle/index.spec.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/nativeSloterNativeSlotee/nativeSloterNativeSlotee.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/nativeSloterNativeSlotee/nativeSloterNativeSlotee.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/nativeSloterSyntheticSlotee/nativeSloterSyntheticSlotee.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/nativeSloterSyntheticSlotee/nativeSloterSyntheticSlotee.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/syntheticSloterSyntheticSlotee/syntheticSloterSyntheticSlotee.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/syntheticSloterSyntheticSlotee/syntheticSloterSyntheticSlotee.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion60Slotee/useApiVersion60Slotee.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion60Slotee/useApiVersion60Slotee.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion60Sloter/useApiVersion60Sloter.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion60Sloter/useApiVersion60Sloter.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion61Slotee/useApiVersion61Slotee.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion61Slotee/useApiVersion61Slotee.js, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion61Sloter/useApiVersion61Sloter.html, packages/@lwc/integration-karma/test/regression/lifecycle/x/useApiVersion61Sloter/useApiVersion61Sloter.js
With the introduction of native lifecycle, we're observing new behavior when an element is moved inside the DOM.
This PR adds some tests to verify the current behavior.
=> test: add tests for new behavior with native lifecycle invocations

packages/@lwc/engine-core/src/framework/hot-swaps.ts, packages/@lwc/integration-karma/test/swapping/styles/index.spec.js
swapStyle() can be called on stylesheets that are yet to be rendered. This is valid especially in the case of salesforce platform where component definitions are (pre-)loaded and can be instantiated in the future, for example dynamic components.
W-15890472
=> fix(engine-core): handle stylesheets not rendered yet

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/util.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicForwardedSlottable/dynamicForwardedSlottable.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicForwardedSlottable/dynamicForwardedSlottable.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicSlotForwarding/dynamicSlotForwarding.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/dynamicSlotForwarding/dynamicSlotForwarding.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/forwardedSlottable/forwardedSlottable.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/forwardedSlottable/forwardedSlottable.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotForwarding/slotForwarding.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotForwarding/slotForwarding.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotee/slotee.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slotee/slotee.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slottable/slottable.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/slottable/slottable.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/standardSlotting/standardSlotting.html, packages/@lwc/integration-karma/test/light-dom/lifecycle/x/standardSlotting/standardSlotting.js
The fix introduced in #3883 resulted in a regression where slotted elements inside a light dom slot were not invoking `disconnectedCallback`.
For example:
```html
<template lwc:render-mode='light'>
<x-light-named-slot lwc:if={show}>
<x-child slot="namedSlot"></x-child>
</x-light-named-slot>
</template>
```
```html
<template lwc:render-mode='light'>
<slot name="namedSlot"></slot>
</template>
```
When `<x-light-named-slot>` is removed from the DOM, `<x-child>`'s `disconnectedCallback` is never invoked.
The issue is caused by prematurely cloning light dom slot vnodes when the `vnode.elm` is `undefined`.
The reason cloning at this point is premature is that cloning is only necessary during slot forwarding, when the `slot` attribute is dynamic.
The reason it is safe to clone the node at this …
=> fix: prevent prematurely cloning light dom slot vnodes

packages/@lwc/compiler/src/transformers/transformer.ts, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/lwc.config.json, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/package.json, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/javascript.js, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/modules/x/base/base.html, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/modules/x/base/base.js, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/modules/x/ext-js/ext-js.js, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/modules/x/ext-ts/ext-ts.ts, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/typescript.ts, packages/@lwc/rollup-plugin/src/__tests__/resolver/resolver.spec.ts, packages/@lwc/rollup-plugin/src/index.ts
To detect whether a component is using an implicit HTML import, we check that it's a `.js` file. But that's not the only kind of script file that can be used! This PR adds support for all flavors of JS/TS/JSX that we might expect to encounter.
Fixes #4233.
W-15941938
=> fix(rollup-plugin): allow any implicit HTML import from any kind of script file @W-15941938

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
=> chore: release v6.6.7

packages/@lwc/integration-karma/test/custom-elements-registry/index.spec.js
This fixes an annoying Chrome warning when running the tests:
Apparently if you use `sandbox="allow-same-origin allow-scripts"` then you may as well not have `sandbox` at all.
=> chore(integration-karma): fix iframe sandbox warning

.eslintrc, .github/workflows/karma.yml, packages/@lwc/engine-dom/src/custom-elements/create-custom-element.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/scripts/karma-plugins/env.js, packages/@lwc/integration-karma/scripts/shared/options.js, packages/@lwc/integration-karma/test/component/face-callbacks/index.spec.js, packages/@lwc/integration-karma/test/custom-elements-registry/index.spec.js, packages/@lwc/integration-karma/test/light-dom/lifecycle/index.spec.js, packages/@lwc/integration-karma/test/regression/lifecycle/index.spec.js
Fixes #4251. Allows components to use FACE (Form Associated Custom Element) callbacks even when running in synthetic lifecycle mode.
This also adds tests for the `DISABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE` flag just to make sure everything works correctly even when that flag is enabled.
=> fix(engine-dom): allow FACE in synthetic lifecycle

.github/workflows/integration.yml, packages/@lwc/integration-tests/scripts/wdio.local.conf.js, packages/@lwc/integration-tests/scripts/wdio.sauce.conf.js
SauceLabs is throwing 503 errors suddenly, so let's switch to local Chrome instead.
=> test: run webdriverio CI tests in local chrome

.husky/pre-push, .prettierignore
It's annoying when I push and go do something else while I wait for CI to run, then I come back later and CI failed after 30 seconds because of something trivial.
This PR adds a git hook to run CI checks locally that are quick and not covered by the pre-commit hook.
W-15999315
=> chore(git): run CI checks on push @W-15999315@

packages/@lwc/engine-core/src/framework/base-lightning-element.ts, packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/component/LightningElement.hostElement/index.spec.js, packages/@lwc/shared/src/api-version.ts
It occurred to me that it's kind of strange for the release notes to say "`this.style` is only available in API version 62 due to possible breaking changes, but `this.hostElement` is available regardless." It's more consistent to just put both of them behind API versioning.
Plus, this way we don't have to worry about potential breaking changes on the off-change that someone has already squatted `this.hostElement`.
Related: #4259 
No, we haven't released `this.hostElement` yet.
=> fix: put `this.hostElement` behind API version 62

.github/workflows/karma.yml
Rebalances the Karma tests from 3 groups into 4, and splits the groups so that each has 6-7 individual tests.
=> chore(ci): rebalance karma tests

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/integration-karma/test/template/attribute-class/object-values.spec.js
We currently iterate over _all_ enumerable properties on an object, not just _own_ enumerable properties. This breaks anything using LBC's `classSet` utility, because that has enumerable props on the prototype. Anything using that helper will see `add invert toString` added to their class. Oops!
Technically, but it's a bug fix!
W-16109991
=> fix(class): avoid enumerable prototype for class object binding @W-16109991@

packages/@lwc/integration-karma/test/rendering/style-specificity-important/index.spec.js, packages/@lwc/integration-karma/test/rendering/style-specificity-important/x/component/component.css, packages/@lwc/integration-karma/test/rendering/style-specificity-important/x/component/component.html, packages/@lwc/integration-karma/test/rendering/style-specificity-important/x/component/component.js, packages/@lwc/template-compiler/src/codegen/helpers.ts
If DISABLE_STATIC_CONTENT_OPTIMIZATION=1 "! important" will now be parsed correctly.
This approach uses Regex to find the !important tag at the end of the string, it is generous in that it allows for abitrary amounts of  white space.
Happy to update to only look for the one scenario outlined in the original issue.
=> fix: inline style parsing for "! important"

packages/@lwc/integration-karma/test/template/attribute-class/object-values.spec.js
I committed and pushed and merged #4337. But I hadn't staged the file I had wanted to commit! So now we have a second PR to add one dinky little test. 🤦 
=> test(ncls): test own non-enumerable props @W-16109991@

packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/index.spec.js, packages/@lwc/integration-karma/test/component/native-vs-synthetic-lifecycle/x/logsWhenConnected/logsWhenConnected.js
In some environments, the `lwcRuntimeFlags.DISABLE_NATIVE_CUSTOM_ELEMENT_LIFECYCLE` flag is _lazily_ set to `true`, after the engine has initialized but before a component has rendered. This worked okay in LWC v6 through LWC v7.0.0, but broke in LWC v7.0.1 due to #4316, which caused all DOM monkey-patching to only occur at initialization time. 
So lazily-setting the flag effectively puts you in a broken state, where the component is trying to run in synthetic lifecycle mode, but `connectedCallback`/`disconnectedCallback` never fires because the monkey-patching is never put in place.
This PR restores the previous behavior, where the monkey-patching can occur dynamically at the time the component is rendered.
-   🔬 Yes, it does include an …
=> fix: allow lazy-disabling native lifecycle

packages/@lwc/integration-karma/test/api/CustomElementConstructor-getter/index.spec.js
Fixes a trivial lint issue I forgot to handle in #4338.
=> chore: run `yarn lint --fix`

packages/@lwc/integration-karma/README.md, packages/@lwc/integration-karma/scripts/karma-plugins/hydration-tests.js
Adds support for the `.only` convention we use in our Jest tests to the hydration tests. This makes it a lot easier to test individual hydration tests.
=> test(hydration): add `.only` support

.github/workflows/unit.yml, packages/@lwc/integration-karma/helpers/test-hydrate.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-hydrate/table-hydrate-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-hydrate/tablecmp-hydrate-1k.benchmark.js
Chrome is giving us a warning about using `includeShadowRoot`s in our tests:
We can switch over to the new [`parseHTMLUnsafe`](https://developer.mozilla.org/en-US/docs/Web/API/Document/parseHTMLUnsafe_static) API instead. Although nothing is ever easy, so we have to polyfill for Firefox.
=> test(ssr): use `Document.parseHTMLUnsafe`

.eslintrc, package.json
I noticed that `yarn format` was formatting `.eslinrc`, but not on `git commit`. This fixes that.
=> chore(prettier): format `.eslintrc` on commit

packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-hydrate/table-hydrate-1k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-hydrate/tablecmp-hydrate-1k.benchmark.js
Apparently Best is running Chrome v123, because it's failing with
```
Document.parseHTMLUnsafe is not a function
```
which was caused by #4357.
This introduces a polyfill to temporarily fix it. Not we only care about Chrome for Best tests.
=> fix(perf-benchmarks): add `parseHTMLUnsafe` polyfill

packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/integration-karma/test/swapping/styles/index.spec.js, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheets/identicalStylesheets.css, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheets/identicalStylesheets.html, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheets/identicalStylesheets.js, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheets/newStyle.css, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheets/newTemplate.html, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheets/style.css, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheetsContainer/identicalStylesheetsContainer.html, packages/@lwc/integration-karma/test/swapping/styles/shadow/identicalStylesheetsContainer/identicalStylesheetsContainer.js
The main root cause of the issue is that AbortController look up is based on the stylesheet content(a string) rather than the stylesheet function. There is a possibility that two stylesheets produce the same exact stylesheet content and when they both need to be unrendered at the same time, the AbortController look up will fail for the second stylesheet.
The scenario where the abort controller has a conflict is the following:
1. A component has been rendered
2. Modify a css files for that component and we only call swapStyle() to swap the style sheet.
- Note that the new style module is associated with the vm instance and will have a callback registered for style hmr
3. Now modify the js files and we call swapComponent() to swap the component. Note that for js file changes we bundle the …
=> fix: do not error if abort controller for stylesheet does not exist @W-16189944

packages/@lwc/engine-core/src/framework/api.ts
From looking at our Best benchmarks, I realized we had actually regressed recently in `dom-table-hydrate-1k` due to https://github.com/salesforce/lwc/pull/3950:
Tachometer confirmed it (comparing current master to the 250 release, i.e. [v6.4.5](https://github.com/salesforce/lwc/releases/v6.4.5)):
The reason is actually unrelated to hydration – it's because the components used in this benchmark set a `class` to `row.className` which is actually undefined:
https://github.com/salesforce/lwc/blob/c1f4a2bce0883d3d8bd9c1dce0cedd6295b36335/packages/%40lwc/perf-benchmarks-components/src/benchmark/table/table.html#L11
After https://github.com/salesforce/lwc/pull/3950, the `ncls` utility is converting `undefined` into an empty string:
https://github.com/salesforce/lwc/blob/c1f4a2bce0883d3d8bd9c1dce0 …
=> perf: optimize initial render for nullish class

.github/dependabot.yml, .prettierrc, packages/@lwc/template-compiler/src/__tests__/fixtures.spec.ts, scripts/tasks/generate-license-files.js
We can't update to prettier v3 (see #4386), so we should tell dependabot to stop trying. I also added notes for the changes that we'll need to make when we do the upgrade, and I explicitly set `trailingComma` in the prettier config because the default value changes in v3 (not a big deal, but keeping the v2 value means a smaller diff in the upgrade).
=> chore(dependabot): ignore prettier v3

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-and-class-modify/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-and-class-modify/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-and-class-modify/modules/x/cmp/cmp.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-and-class-modify/modules/x/cmp/cmp.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-aria-modify/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-modify-uppercase/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-modify-uppercase/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-modify-uppercase/modules/x/cmp/cmp.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-modify-uppercase/modules/x/cmp/cmp.js, packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/method-remove-attribute/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/method-set-attribute/expected.html, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/engine-server/src/utils/mutation-tracking.ts, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/attr-mutated-class-mismatch/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/attr-mutated-class-mismatch/x/child/child.html, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/attr-mutated-class-mismatch/x/child/child.js, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/attr-mutated-class-mismatch/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/attr-mutated-class-mismatch/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/class-mutated-attr-mismatch/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/class-mutated-attr-mismatch/x/child/child.html, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/class-mutated-attr-mismatch/x/child/child.js, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/class-mutated-attr-mismatch/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/host-mutation-in-connected-callback/class-mutated-attr-mismatch/x/main/main.js
A flaw with #4358 is that it ignores _all_ hydration mismatches whenever _any_ attribute is mutated server-side in a `connectedCallback`. This PR fixes that, by encoding the mutated attributes in the `data-lwc-host-mutated` attribute and processing those on the client side during hydration.
This ensures that we are maximally strict about hydration validation, while still ignoring any attributes mutated in `connectedCallback`.
Kinda? But this feature hasn't really shipped yet, so it should be safe to change.
=> fix(hydration): only ignore mutated host attributes

.nucleus.yaml, package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
chore: update .nucleus.yaml and release v7.2.0 for CLCO (bump minor version number)
=> chore: update .nucleus.yaml and release v7.2.0 for CLCO

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, scripts/jest/root.config.js
This does two things:
1. Ensure that `error.txt` and `expected.html` files are _always_ written, even as empty files. This ensures that when you run `yarn test` on `ssr-compiler`, it will not unexpectedly create some additional files, e.g. if it expects no error but gets an error. This creates some additional noise on the filesystem, but makes it much easier to test `ssr-compiler` and `engine-server` in parallel.
2. Add an env var, `TEST_SSR_COMPILER`, that allows for testing the `ssr-compiler` without having to change the Jest config file.
=> test(ssr-compiler): harmonize fixture format

packages/@lwc/engine-core/src/framework/api.ts, packages/@lwc/integration-karma/test/template/directive-for-each/index.spec.js
I noticed that this bit of code in the `i` (iterator) function was not being tested. This adds tests, and also improves the error message a bit by making it the same as the one below it.
=> fix: improve error for null/undefined iter values

packages/@lwc/rollup-plugin/package.json
Somehow, we managed to miss the fact that `@lwc/rollup-plugin` has an implicit dep on `@lwc/shared`:
https://github.com/salesforce/lwc/blob/58ac746ec5cb8052acca84c0f3f04972c92d39cf/packages/%40lwc/rollup-plugin/src/index.ts#L15
This fixes that.
=> fix(rollup-plugin): add `@lwc/shared` dep

packages/@lwc/babel-plugin-component/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/types/package.json, yarn.lock
* `@lwc/types` does not use `@lwc/template-compiler`
* `@lwc/engine-server` does not use `@parse5/tools`
* `@lwc/babel-plugin-component` uses `@babel/traverse` and `@babel/types`
* https://github.com/salesforce/lwc/blob/4333670fc7e39dc9fdb7d625048ce558db9d7316/packages/%40lwc/babel-plugin-component/src/component.ts#L8-L10
* `@lwc/ssr-compiler` uses `@lwc/shared`
* https://github.com/salesforce/lwc/blob/4333670fc7e39dc9fdb7d625048ce558db9d7316/packages/%40lwc/ssr-compiler/src/compile-template/element.ts#L9
=> chore(deps): add missing and remove unused deps

packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/synthetic-shadow/disable-synthetic-shadow/index.spec.js, packages/@lwc/integration-karma/test/synthetic-shadow/disable-synthetic-shadow/x/component/component.js, scripts/rollup/rollup.config.js
Today, you can simply not import `@lwc/synthetic-shadow` and you'll run in pure-native-shadow mode. However, if `@lwc/synthetic-shadow` is loaded, then there's no way to switch back to a pure-native-shadow mode.
In some environments though (notably core), it would be convenient to have a runtime flag that can toggle this behavior on-demand, regardless of whether `@lwc/synthetic-shadow` was previously loaded or not. This PR accomplishes that via a new `lwcRuntimeFlags` prop.
=> feat: add flag to disable synthetic shadow

vitest.config.mjs
Enables the HTML reporter. This allows coverage to be reported when running `yarn test --ui --coverage`:
=> test: add html coverage reporter

nx.json
Ran `nx repair` to auto fix our nx config. Looks like it simplifies a few options.
=> chore: nx repair

package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/perf-benchmarks/scripts/build.js, packages/@lwc/perf-benchmarks/scripts/fix-deps.sh, yarn.lock
I realized I can upgrade Tachometer since I had just missed that we need the `"root"` property to make bare npm imports work properly: https://github.com/google/tachometer/issues/244#issuecomment-2267191898
=> chore: upgrade tachometer

package.json
This comment is no longer needed as of https://github.com/salesforce/lwc/pull/4435, since we are now on Prettier v3.
=> chore: remove obsolete comment

packages/@lwc/integration-karma/helpers/test-utils.js, packages/@lwc/integration-karma/test/component/LightningElement.errorCallback/index.spec.js, packages/@lwc/integration-karma/test/rendering/callback-invocation-order/index.spec.js
The current tests for #4451 and #3827 are somewhat janky – they occasionally log to the DevTools console which is very distracting.
Luckily I already had some code to capture unhandled rejections/errors, so I just extracted this into a general-purpose utility so that we can improve this test.
This is spun off from #4452 to avoid bloating that PR.
=> test: improve tests for unhandled rejections

packages/@lwc/errors/src/__tests__/errors.spec.ts, scripts/rollup/rollup.config.js, tsconfig.json
This makes sure vscode picks up vitest/globals.
=> chore: fix type errors in test files during dev

.github/dependabot.yml
Deps that are similar like Best and WebdriverIO should be updated together. Also Tachometer and Prettier don't need to be pinned anymore.
=> chore(dependabot): add groups, remove outdated

.github/dependabot.yml
Missed this in #4466. `webdriverio` in particular needs to be included with `@wdio/*`.
=> chore(dependabot): add bare package names, nx

package.json, scripts/release/README.md, scripts/release/version.js
Unfortunately, it turns out that #4445 regressed the `release:version` script. It no longer updates the version in the root (monorepo) `package.json`, and more importantly, doesn't bump the versions in private packages like `@lwc/integration-tests`. I opened a discussion on NX about this: https://github.com/nrwl/nx/discussions/27566
In the meantime, we should revert to the old `release:version` script. Otherwise our tests will be running against old versions pulled from npm rather than the local versions of the code!
=> chore: restore `release:version` script

packages/@lwc/engine-server/src/__tests__/unsupported-apis.spec.ts
Improves our test coverage on `@lwc/engine-server`.
=> test(engine-server): assert HMR not supported

packages/@lwc/integration-karma/package.json, yarn.lock
I noticed there was no autocompletion or hover information for jasmine's expect, spyOn, etc, which makes it harder for someone unfamiliar with jasmine like myself.
This PR just adds the @type/jasmine dev dependency to @lwc/integration-karma. It doesn't seem to affect tests in other packages, but I recommend giving it a try before merging.
I understand karma is to be replaced at some point, but in the meanwhile it's nice to have this.
=> chore(integration-karma): add @types/jasmine

packages/@lwc/integration-karma/test/events/memoization/index.spec.js, packages/@lwc/integration-karma/test/events/memoization/x/deep/deep.html, packages/@lwc/integration-karma/test/events/memoization/x/deep/deep.js, packages/@lwc/integration-karma/test/events/memoization/x/list/list.html, packages/@lwc/integration-karma/test/events/memoization/x/list/list.js
This adds Karma tests for event listener memoization, which came up when I was reviewing #4468.
This behavior is a little subtle, and previously we were only really testing it in the template-compiler snapshot tests here:
https://github.com/salesforce/lwc/blob/39af4df1fd18d2d4835fcc532795b9b65e1ba23b/packages/%40lwc/template-compiler/src/__tests__/fixtures/regression/handler-memoization/actual.html#L4-L9
Adding the test ensures we don't regress the current functionality.
=> test(integration-karma): add listener memoization tests

packages/@lwc/integration-karma/scripts/karma-plugins/env.js, packages/@lwc/integration-karma/test/template/escape-tag-name/index.spec.js, packages/@lwc/integration-karma/test/template/escape-tag-name/x/component/component.html, packages/@lwc/integration-karma/test/template/escape-tag-name/x/component/component.js, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/non-optimized/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/non-optimized/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/non-optimized/config.json, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/non-optimized/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/non-optimized/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/optimized/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/optimized/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/optimized/config.json, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/optimized/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/html-tags/backslash-in-tag-name/optimized/metadata.json, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts
Fixes an issue in the static content optimization where tag names are not properly escaped so may render invalid characters.
Only observable for odd characters like backslashes which are uncommonly (if ever) used.
=> fix(template-compiler): escape tag names

packages/@lwc/integration-karma/scripts/karma-plugins/env.js, packages/@lwc/integration-karma/test/template/escape-attr-name/index.spec.js, packages/@lwc/integration-karma/test/template/escape-attr-name/x/booleanValue/booleanValue.html, packages/@lwc/integration-karma/test/template/escape-attr-name/x/booleanValue/booleanValue.js, packages/@lwc/integration-karma/test/template/escape-attr-name/x/stringValue/stringValue.html, packages/@lwc/integration-karma/test/template/escape-attr-name/x/stringValue/stringValue.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/non-optimized/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/non-optimized/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/non-optimized/config.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/non-optimized/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/non-optimized/metadata.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/optimized/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/optimized/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/optimized/config.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/optimized/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/attr-name-escape/optimized/metadata.json, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts
Similar to #4498, but for attribute names. We were not properly escaping these, so some invalid characters may be rendered.
Like the other PR, this only applies to extremely odd characters that are rarely if ever used in attribute names.
=> fix(template-compiler): escape attribute names

packages/@lwc/perf-benchmarks/scripts/build.js
At some point our Tachometer scripts got messed up, and when it tries to compare against a remote branch (e.g. `master`) it fails because NX thinks that the `@lwc/perf-benchmarks-components` project doesn't exist.
$ yarn build:performance:components
NX   Cannot find project '@lwc/perf-benchmarks-components'
This seems to be something subtle with how we were copying directory around (maybe NX is using symlinks under the hood or something)? Doing `yarn install` after copying these files, and copying only the necessary source files, seems to fix the issue.
=> chore(tachometer): fix remote branches

.github/dependabot.yml
In #4466 / #4473, we added dedicated groups for packages that should be kept in sync, like babel, because they break if you update just one at a time. We already have a `theoretically-non-breaking` group that bundles all patch/minor version bumps into one PR, but it turns out that the new groups we created take precedence, so we end up with multiple PRs for non-breaking changes. This PR updated our config so that our groups only apply to major versions, meaning we get the needed groups for breaking changes, but all non-breaking changes remain bundled in the single PR.
=> chore(dependabot): only use groups for major bumps

packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/integration-karma/test/rendering/sanitize-stylesheet-token/index.spec.js, packages/@lwc/integration-karma/test/rendering/sanitize-stylesheet-token/x/component/component.css, packages/@lwc/integration-karma/test/rendering/sanitize-stylesheet-token/x/component/component.html, packages/@lwc/integration-karma/test/rendering/sanitize-stylesheet-token/x/component/component.js
Fixes validation of attribute names / static content HTML for dynamically-set stylesheet tokens.
Setting `template.stylesheetToken` now requires a string value.
W-16614556
=> fix(engine): avoid non-string scope tokens

scripts/release/version.js
I don't like this:
```sh
$ yarn release:version                                                                   
yarn run v1.22.22
$ node ./scripts/release/version.js
Enter a new LWC version: x.y.z
```
I do like this:
```
$ yarn release:version x.y.z
```
This PR makes both possible.
(Hopefully this will be obsolete soon, anyway.)
=> chore(release): allow providing release version directly

.nucleus.yaml
Otherwise this branch publishes to `latest` which we don't want.
=> chore(nucleus): use `winter25` dist-tag

packages/@lwc/rollup-plugin/src/__tests__/apiVersion/apiVersion.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/compilerConfig/compilerConfig.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/enableStaticContentOptimization/enableStaticContentOptimization.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/integrations/integrations.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/resolver/resolver.spec.ts, packages/@lwc/rollup-plugin/src/__tests__/warnings/warnings.spec.ts
This PR makes a few tweaks to tests in `@lwc/rollup-plugin`.
It improve overall execution time from ~3.78s to ~1.44s (-62%) in my local environment.
It also reduces memory usage significantly in some tests.
This makes development while running tests in watch mode a bit more pleasant.
```sh
✓ resolver  (13 tests) 2843ms 530 MB heap used
✓ compilerConfig  (6 tests) 1920ms 102 MB heap used
✓ apiVersion  (5 tests) 1669ms 261 MB heap used
✓ enableStaticContentOptimization  (4 tests) 1266ms 205 MB heap used
✓ warnings  (1 test) 497ms 97 MB heap used
✓ integrations  (1 test) 466ms 98 MB heap used
✓ rootDir  (2 tests) 19ms 34 MB heap used
Test Files  7 passed (7)
Tests  32 passed (32)
Start at  05:29:27
Duration  3.78s (transform 422ms, setup 0ms, collect 4.45s, tests 8.68s, environment 1ms, …
```
=> chore(rollup-plugin): speed up and reduce memory usage in tests

packages/@lwc/engine-core/src/framework/profiler.ts, packages/@lwc/engine-core/src/framework/vm.ts
Closes #4511 
In production there should be no observable changes. In development, using a browser that supports [Chrome DevTools's Performance Panel Extensions](https://docs.google.com/document/d/1Fp4LLvq2VAv9ksgcxDGLf472Rbi9vz_Tqs74DdcT0hw/edit?resourcekey=0-STF_hF7kXMMK_yHz9ANbJw), measurements will appear under a custom track.
=> feat(engine): enhance performance timings

packages/@lwc/engine-core/src/framework/profiler.ts
This is a small follow-up to #4511: it adds tooltips that are visible when hovering over the custom timings in DevTools.
It seems to me that the main benefit of these tooltips is to merely recapitulate the same name as the slice (this is what a lot of the other tooltips in the DevTools UI do). I personally find it annoying to have to zoom in to read the full text, so it's nice to be able to see it without zooming.
These tooltips are pretty minimal because I didn't want to clutter the UI – they mostly just repeat the slice names while adding a hint of context.
The next PR would be to add mutation tracking so that we can report _why_ a component re-rendered (#4542), but I think this may be a bit trickier so I am holding off for now.
-   🔬 …
=> feat(engine): add tooltips for performance timings

packages/@lwc/engine-core/src/framework/component.ts, packages/@lwc/engine-core/src/framework/decorators/track.ts, packages/@lwc/engine-core/src/framework/mutation-logger.ts, packages/@lwc/engine-core/src/framework/mutation-tracker.ts, packages/@lwc/engine-core/src/framework/profiler.ts, packages/@lwc/engine-core/src/framework/vm.ts, packages/@lwc/engine-core/src/framework/wiring/wiring.ts, packages/@lwc/engine-core/src/libs/mutation-tracker/index.ts, packages/@lwc/integration-karma/test/profiler/mutation-logging/index.spec.js, packages/@lwc/integration-karma/test/profiler/mutation-logging/x/child/child.html, packages/@lwc/integration-karma/test/profiler/mutation-logging/x/child/child.js, packages/@lwc/integration-karma/test/profiler/mutation-logging/x/parent/parent.html, packages/@lwc/integration-karma/test/profiler/mutation-logging/x/parent/parent.js, packages/@lwc/shared/src/language.ts
Fixes #4542 
Adds mutation tracking to the existing DevTools extensions (https://github.com/salesforce/lwc/pull/4535, #4541), so component authors can figure out why a component was re-rendered.
For all `lwc-rehydrate` events, there is a list of which components were mutated, and which properties on those components were mutated.
Only in dev mode, and only if you're looking at perf timings.
The overhead of these new APIs should also be minimal – I counted the following times when running our full Karma test suite:
- `getMutationProperties` - 12.5ms
- `trackTargetForMutationLogging` – 0.3ms
- `flushMutationLogsForVM` – 0.9ms
=> feat: add mutation logging to DevTools profiler

packages/@lwc/ssr-compiler/package.json, yarn.lock
This reverts commit 485b715ba3d765d550319493adea057ac1983749.
We need Node v16 support for just a tad longer.
=> fix: revert "build(deps): bump meriyah from 5.0.0 to 6.0.0 (#4550)"

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-class-whitespace/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-class-whitespace/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/style-class-whitespace/modules/x/foo/foo.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-class-whitespace/modules/x/foo/foo.js, packages/@lwc/engine-server/src/__tests__/fixtures/svgs/expected.html, packages/@lwc/integration-karma/test/rendering/style-class-whitespace/index.spec.js, packages/@lwc/integration-karma/test/rendering/style-class-whitespace/x/component/component.html, packages/@lwc/integration-karma/test/rendering/style-class-whitespace/x/component/component.js, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/class/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/base/class/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-important/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-important/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-important/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-static/actual.html, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-static/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/base/style-static/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/directive-for-each/static-content-optimization/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/svg/linear-gradient/expected.js, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts
=> chore(template-compiler): normalize class and style attribute values

packages/@lwc/ssr-compiler/src/compile-js/stylesheets.ts
The experimental SSR compiler currently doesn't support capital letters in component names. This fixes that.
This gets the new SSR tests down from 59 failures to 56 failures.
Related: #4555 
=> fix(ssr): allow capital letters in component names

.github/workflows/karma.yml
We missed this in #4543 – now that we have API version 63, we need to test version 62 in CI.
=> test(karma): test API version 62 in CI

CONTRIBUTING.md, package.json
To avoid issues with Volta only respecting the current working directory's `package.json`, add a top-level Karma "start" script.
=> test: add top-level karma watch script

packages/@lwc/integration-karma/test/rendering/noframes/index.spec.js, packages/@lwc/integration-karma/test/rendering/noframes/x/component/component.html, packages/@lwc/integration-karma/test/rendering/noframes/x/component/component.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/no-escaping-tags/expected.js, packages/@lwc/template-compiler/src/codegen/static-element.ts
See [context](https://gus.lightning.force.com/lightning/r/0D5EE00001uU05Y0AS/view).
W-16784305
=> fix(compiler): fix noframes rendering

packages/@lwc/integration-karma/test/regression/style-newline/index.spec.js, packages/@lwc/integration-karma/test/regression/style-newline/x/component/component.html, packages/@lwc/integration-karma/test/regression/style-newline/x/component/component.js, packages/@lwc/template-compiler/src/codegen/helpers.ts
Fixes #4579
Pretty straightforward fix, just required using [Regex dotAll](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/dotAll) (available in Node v8+).
Technically yes, but it also fixes a recent regression (#4579). Also I suspect this use case is extremely uncommon (newlines separating style declarations), and it probably didn't work in the past with non-static-optimized elements anyway due to the style normalization previously only being applied to non-static-optimized elements.
=> fix(template-compiler): styles containing newlines

packages/@lwc/engine-server/src/__tests__/fixtures/no-template/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/no-template/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/no-template/modules/x/test/test.js, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts
Fixes rendering the non-existent host scope token class when a component doesn't have a template.
=> fix(ssr): avoid undefined appended to tag name

packages/@lwc/ssr-runtime/src/index.ts
This adds `setAttribute` and `removeAttribute` to the SSR implementation of `LightningElement`. It also adds stubs for methods that we may want to add in the future, so that we can more easily keep track of the gaps.
=> fix(ssr): add missing methods from LightningElement @W-16614337

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/engine-core/src/framework/utils.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-component-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-style/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-newline/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-newline/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/style-newline/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-newline/modules/x/component/component.js, packages/@lwc/engine-server/src/renderer.ts, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static/unoptimized-different-priority/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static/unoptimized-extra-from-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/static/unoptimized-extra-from-server/index.spec.js, packages/@lwc/shared/src/index.ts, packages/@lwc/shared/src/style.ts, packages/@lwc/ssr-compiler/src/compile-template/component.ts, packages/@lwc/ssr-compiler/src/compile-template/element.ts, packages/@lwc/ssr-compiler/src/compile-template/shared.ts, packages/@lwc/template-compiler/src/codegen/helpers.ts, packages/@lwc/template-compiler/src/codegen/index.ts, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts, packages/@lwc/template-compiler/src/index.ts
Fixes normalization of `style` attributes in the `@lwc/ssr-compiler`.
=> fix(ssr): use style normalizer from template compiler

packages/@lwc/ssr-compiler/src/compile-template/element.ts
=> fix(ssr): normalize class names @W-16869035

packages/@lwc/ssr-runtime/src/index.ts
Made the following changes to `@lwc/ssr-runtime` to better match `@lwc/engine-server`:
* Adds `addEventListener` and `removeEventListener` as no-ops
* Adds `hasAttribute` because we missed that last time
* Changes the "not implemented" error for some methods to "not available"
* Methods that don't use that specific message in `@lwc/engine-server` are left as-is
* Changes some props to "not available" getters
W-16867451
=> fix(ssr): add more LightningElement methods @W-16867451

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts
=> fix(ssr): improve error message when test succeeds but formatting fails

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-null/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-null/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-null/modules/x/test/test.js, packages/@lwc/engine-server/src/renderer.ts
setAttribute should gracefully handle non-string values
[W-16871277](https://gus.lightning.force.com/a07EE000022ISyQYAW)
=> fix(engine-server): setAttribute should gracefully handle non-string values

packages/@lwc/babel-plugin-component/src/__tests__/index.spec.ts, packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/style-compiler/src/__tests__/index.spec.ts, packages/@lwc/template-compiler/src/__tests__/fixtures.spec.ts, scripts/test-utils/matchers.ts, scripts/test-utils/test-fixture-dir.ts
Using the filename as the test description severely limits how useful the test descriptions are. This PR adds the ability to include a description in each fixture's `config.json`. It does not add any descriptions because there are 241 fixtures, and ain't nobody got time for that.
=> test(fixtures): add option to have human-friendly description

packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-runtime/src/__tests__/validate-style-text-contents.spec.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/validate-style-text-contents.ts, packages/@lwc/ssr-runtime/vitest.config.mjs
Matches the behavior of `@lwc/engine-server`.
W-16882876
=> fix(ssr): disallow </style> in CSS files @W-16882876

packages/@lwc/engine-server/src/__tests__/fixtures/import-lwc-from-helper/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/import-lwc-from-helper/imports.js, packages/@lwc/engine-server/src/__tests__/fixtures/import-lwc-from-helper/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/import-lwc-from-helper/modules/x/cmp/cmp.html, packages/@lwc/engine-server/src/__tests__/fixtures/import-lwc-from-helper/modules/x/cmp/cmp.js, packages/@lwc/engine-server/src/__tests__/fixtures/import-lwc-from-helper/wire-adapter.js
The SSR compiler transforms imports from `lwc` into imports from `@lwc/ssr-runtime`, but it only does so in component files, not helper files. This PR adds a test for imports from helper files that works for `@lwc/engine-server`, but not `@lwc/ssr-compiler`.
The test fails for `@lwc/ssr-compiler` because it allows imports from `lwc`, which in turn imports from `@lwc/engine-dom`, which gets compiled with `process.env.IS_BROWSER` set to `true`, leading to unguarded use of `Element`, which is not defined.
https://github.com/salesforce/lwc/blob/643a65ca8b94b19584db4c2b326e870b3f728764/packages/%40lwc/engine-core/src/patches/detect-non-standard-aria.ts#L123-L124
https://github.com/salesforce/lwc/blob/643a65ca8b94b19584db4c2b326e870b3f728764/packages/%40lwc/engine-core/src/patches/detect-non-sta …
=> test(imports): add fixture for LWC imports from helper file @W-16872166

packages/@lwc/ssr-runtime/src/index.ts
must exactly match @lwc/engine-core
=> chore: remove quotes from error message

packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-dom/src/index.ts, packages/@lwc/wire-service/src/index.ts
This PR adds the `DataCallback` as a type definition export in `lwc`.
This type is needed when authoring wire adapters and it would be nice to have as part of the `lwc` package since the other adapter types are in there too.
=> chore: add `DataCallback` as type export in `lwc`

packages/@lwc/ssr-compiler/src/compile-template/component.ts, packages/@lwc/ssr-runtime/src/index.ts
Boolean attributes have a value of `true` in the AST but the attribute value should be an empty string during runtime.
=> fix(ssr-compiler): boolean attribute value as empty string

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-runtime/src/index.ts
Define setters for reflected attributes. Needed to add a private `#setAttribute()` method that can set `null` without turning it into a string so that `removeAttribute()` works as expected.
Also `for-of` was also changed to `for-in` in `renderAttrs` so that we can iterate over non-string (accessor) enumerable entries.
This implementation is now more correct than `engine-server` as it seems the latter may not be handing `setAttribute(null)` correctly for standard reflected attributes:
```
FAIL  |lwc-ssr-compiler| src/__tests__/fixtures.spec.ts > fixtures > attribute-null/index.js
Error: Received content for "/Users/ekashida/Repos/lwc/packages/@lwc/engine-server/src/__tests__/fixtures/attribute-null/expected.html" doesn't match expected content.
Difference:
- Expected
+ Received
- <x-test …
```
=> fix(ssr-compiler): define setters for reflected attributes

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-runtime/package.json, packages/@lwc/ssr-runtime/src/index.ts
Track mutated attributes and render results on the host element.
[W-16871307](https://gus.lightning.force.com/a07EE000022IEfKYAW)
=> feat(ssr-compiler): track mutated attributes

eslint.config.mjs, packages/@lwc/engine-core/src/framework/sanitized-html-content.ts, packages/@lwc/ssr-compiler/src/compile-js/stylesheet-scope-token.ts, scripts/shared/packages.mjs
When doing the refactor in #4618, I noticed that the `header/header` rule was not being enforced. Turns out we removed it in #4378, because of https://github.com/Stuk/eslint-plugin-header/issues/57. However, there's a simple workaround, so this PR restores the rule.
=> chore(eslint): restore header rule

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, scripts/test-utils/test-fixture-dir.ts
There are cases where `engine-server` and SSR necessarily must have divergent output (e.g. an error message containing a reference to an `engine-server` VM cannot be reproduced by SSR). This PR adds the ability to configure separate output files for use by SSR. It adds a new field, `ssrFiles` to the existing `config.json` pattern. If the `error.txt` or `expected.html` generated by `engine-server` is not the expected SSR output, an `error` or `expected` key can be used to provide an alternative file.
```jsonc
// config.json
{
"ssrFiles": {
"error": "error-ssr.txt",
"expected": "expected-ssr.html"
}
}
```
-   🔬 Yes, it does include an …
=> test(ssr): add ability to diverge from engine-server

vitest.shared.mjs
This just detects if a debugger is attached by checking `inspector.url()`. If we're debugging, then avoid timing out!
=> chore(test): avoid timeout when debugging

.github/dependabot.yml, package.json, yarn.lock
As a library, if we generate type definitions using a newer version of TypeScript than our downstream users have installed, then they will not be able to use those types. Therefore, to avoid inadvertently breaking users, we should pin our version of TypeScript. This PR prevents dependabot from upgrading our version of TypeScript, and it reverts the version we use to our [officially supported version](https://developer.salesforce.com/docs/platform/lwc/guide/ts.html#:~:text=type%20definitions%20with-,TypeScript%20v5.4.5,-to%20develop%20Lightning). There are only very minor differences in the type definitions between v5.4.5 and v5.6.2, so the downgrade should be safe to do.
-   🤞 No, it does …
=> chore(deps): pin typescript version

packages/@lwc/engine-server/package.json, packages/@lwc/integration-karma/test/rendering/noframes/index.spec.js, packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/no-escaping-tags/ast.json, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/no-escaping-tags/expected.js, packages/@lwc/template-compiler/src/codegen/static-element.ts, packages/@lwc/template-compiler/src/parser/expression-complex/html.ts, yarn.lock
The `<noframes>` parsing issue was fixed in https://github.com/inikulin/parse5/pull/1277 so we can remove the special-casing now.
=> fix: bump parse5, remove `<noframes>` special case

packages/@lwc/ssr-runtime/src/__tests__/server-side-render-component-alias.spec.ts, packages/@lwc/ssr-runtime/src/index.ts
This aligns with the naming convention in `@lwc/engine-server` without breaking backwards compat, by making `renderComponent` an alias of `serverSideRenderComponent`.
=> feat(ssr-runtime): export `renderComponent` alias

packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-connected-callback/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-connected-callback/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-connected-callback/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-connected-callback/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-render/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-render/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-render/modules/x/test/template.html, packages/@lwc/engine-server/src/__tests__/fixtures/host-mutate-in-render/modules/x/test/test.js
Adds a test for mutating the host attribute in `render()` vs `connectedCallback()`.
=> test(ssr): add test for mutate in `render()`

packages/@lwc/ssr-compiler/src/compile-template/component.ts, packages/@lwc/ssr-compiler/src/compile-template/element.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/compile-template/ir-to-es.ts
Implements native shadow slots for SSR!
=> feat(ssr): implement native slots @W-14631061

packages/@lwc/engine-server/src/__tests__/fixtures/lwc-inner-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/lwc-inner-html/modules/x/lwc-inner-html/lwc-inner-html.html, packages/@lwc/ssr-compiler/src/compile-template/element.ts
This PR implements `lwc:inner-html` in `@lwc/ssr-compiler`. It does not currently do any input sanitization on the HTML content.
W-16872197
=> feat(ssr): implement lwc:inner-html @W-16872197

eslint.config.mjs, packages/@lwc/integration-karma/test/component/LightningElement.errorCallback/index.spec.js, packages/@lwc/integration-karma/test/native-shadow/Event-methods/Event.composedPath.spec.js, packages/@lwc/integration-karma/test/polyfills/event-composed/index.spec.js, packages/@lwc/integration-karma/test/rendering/slotting/index.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Event-methods/index.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Event-properties/Event.currentTarget.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Event-properties/Event.defaultPrevented.spec.js, packages/@lwc/integration-karma/test/shadow-dom/Event-properties/Event.target.spec.js, packages/@lwc/integration-karma/test/shadow-dom/MutationObserver/MutationObserver.spec.js, packages/@lwc/integration-karma/test/template/directive-lwc-inner-html/index.spec.js, packages/@lwc/integration-karma/test/wire/legacy-adapters/index.spec.js, packages/@lwc/integration-karma/test/wire/reactive-params.spec.js, packages/@lwc/integration-karma/test/wire/wiring/index.spec.js
This PR enables the `vitest/no-done-callback` lint for karma tests and replaces all usages of it with async / await.
This rule is [recommended by jest](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-done-callback.md), and in [vitest the support for done was removed](https://vitest.dev/guide/migration.html#done-callback) years ago in favor of [test context](https://vitest.dev/guide/test-context.html#built-in-test-context).
The [jasmine docs also recommend using async/await](https://vitest.dev/guide/test-context.html#built-in-test-context) over the done callback.
I also noticed most of the tests which use the callback were written ~5 years ago.
This should make debugging easier, as well as transitioning to a different framework if needed.
This PR does not touch …
=> chore(integration-karma): replace done callback with async/await

packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-light-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-light-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-light-component/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-light-component/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-shadow-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-shadow-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-shadow-component/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/default-template-shadow-component/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-default-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-default-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-default-component/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-default-component/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-shadow-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-shadow-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-shadow-component/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/light-template-shadow-component/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-default-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-default-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-default-component/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-default-component/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-light-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-light-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-light-component/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/render-mode-mismatch/shadow-template-light-component/modules/x/test/test.js
This merely asserts the behavior described in #4663.
Most of these cases _should_ throw an error rather than just logging an error. But we should at least assert on what we're currently doing.
Note that you can already tell whether a component/template renders as shadow or light DOM due to the presence of the `<template shadowrootmode=open>`.
=> test(engine-server): add render mode mismatch test

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/light/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/light/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/light/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/light/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/light/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/light/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/shadow/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/shadow/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/shadow/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/shadow/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/shadow/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/duplicate-slots-in-template/shadow/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/light/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/light/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/light/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/light/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/light/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/light/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/shadow/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/shadow/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/shadow/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/shadow/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/shadow/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/reordered-duplicate-nonexistent-slots/shadow/modules/x/outer/outer.js
We don't have enough tests for slots. This adds tests for:
- duplicate slots (both in the template and in the consumer)
- slot reordering (between the template and the consumer)
- nonexistent slot names (not defined in the template)
We should probably add a test for light DOM slot forwarding as well at some point.
=> test(engine-server): more slot tests

packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/leaf/leaf.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/leaf/leaf.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/lightContainer/lightContainer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/lightContainer/lightContainer.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/scopedSlotChild/scopedSlotChild.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/scopedSlotChild/scopedSlotChild.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/scopedSlotParent/scopedSlotParent.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-forwarding/scoped-slots/modules/x/scopedSlotParent/scopedSlotParent.js
This is merely copied from the Karma tests.
Unlike normal light DOM slots, which throw an error (#4668), scoped light DOM slots do not throw an error when forwarded. So we can just add a test here and increase our test coverage in `engine-server`.
=> test(engine-server): test scoped slot forwarding

packages/@lwc/integration-karma/test/rendering/iframe/index.spec.js, packages/@lwc/integration-karma/test/rendering/iframe/x/component/component.html, packages/@lwc/integration-karma/test/rendering/iframe/x/component/component.js, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/attribute-allow/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/static-content/no-escaping-tags/expected.js, packages/@lwc/template-compiler/src/codegen/static-element.ts
See [W-17015807](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000023cou6YAA/view) for details.
=> fix(template-compiler): disable static content optimization for iframes

packages/@lwc/ssr-compiler/src/__tests__/compilation.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts
=> fix(ssr): use relative imports for implicit templates @W-16975723

packages/@lwc/engine-core/src/framework/mutation-logger.ts, packages/@lwc/integration-karma/test/profiler/mutation-logging/index.spec.js, packages/@lwc/integration-karma/test/profiler/mutation-logging/x/getterThrows/getterThrows.html, packages/@lwc/integration-karma/test/profiler/mutation-logging/x/getterThrows/getterThrows.js
#4544 introduced a bug. If an `@track`ed object has any getters that throw, and if those errors are not normally encountered during component rendering (e.g. because the template only checks `deep.foo` and not `deep.bar`, and `deep.bar` throws), then we will actually start throwing errors in dev mode because `trackTargetForMutationLogging` will invoke the getter. This PR fixes that.
W-16911163
=> fix(engine): fix mutation tracking when getter throws

packages/@lwc/integration-karma/scripts/karma-plugins/hydration-tests.js
I was having trouble debugging the ssr code generated in hydration tests. With this change, it shows up in stack traces and the code is highlighted. In VSCode it also persists break points between sessions.
=> chore(integration-karma): provide filename for ssr code in hydration tests

packages/@lwc/integration-karma/test/profiler/mutation-logging/index.spec.js
=> test(integration-karma): fix flaky `PerformanceObserver` test

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts
Small but easy improvement observed locally ~1.65s to ~1.25s.
This is still the longest-running test file (in subsequent runs), so this might help uncover other ways to improve.
=> chore(engine-server): run test fixtures concurrently

packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/transformer.ts, packages/@lwc/rollup-plugin/src/index.ts, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/index.ts, packages/@lwc/ssr-compiler/src/shared.ts, packages/@lwc/ssr-compiler/src/transmogrify.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/render.ts
This PR adds a final step to component compilation when targeting SSR. This final step optionally transforms the async-generator variety of generated code into one of two other varieties: async or sync (without generators).
These two alternate modes are provided primarily for performance reasons; the synchronous SSR compilation mode is at least an order of magnitude faster than generated code that relies on async generators.
A few additional notes:
- There are two helper functions in `@lwc/ssr-runtime` that are paradigm-dependent and (prior to this PR) were implemented as generator functions.
- Alternatives to these helper functions are provided, and are used if either the `sync` or `async` compilation mode is selected.
- Both the compiler _and_ the runtime have to know what mode they're …
=> feat(ssr): add SSR compilation mode

packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string-on-client-nonempty-on-server/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string-on-client-nonempty-on-server/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string-on-client-nonempty-on-server/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string-on-server-nonempty-on-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string-on-server-nonempty-on-client/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string-on-server-nonempty-on-client/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/empty-string/empty-on-client-nonempty-on-server/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/empty-string/empty-on-client-nonempty-on-server/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/empty-string/empty-on-client-nonempty-on-server/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/empty-string/empty-on-server-nonempty-on-client/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/empty-string/empty-on-server-nonempty-on-client/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/style-attr/empty-string/empty-on-server-nonempty-on-client/x/main/main.js
Add tests for hydration mismatches where style/class has the empty string in one case (client/server) and a nonempty string in another. This would have caught this issue: https://github.com/salesforce/lwc/pull/4684/files#r1815784007
=> test(hydration): add tests for empty string mismatch

packages/@lwc/ssr-compiler/src/__tests__/compilation.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts
See https://github.com/salesforce/lwc/pull/4681#issuecomment-2436286589
=> fix(ssr): support `.ts` files

packages/@lwc/engine-core/src/framework/hydration.ts, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/empty-string/x/main/main.js
Hopefully this is right, but if not there should be some test that fails.
Closes #4661
No hydration mismatch on dynamic class with empty string 😄
=> fix(engine-core): dynamic class with empty string results in hydration mismatch

packages/@lwc/compiler/src/options.ts, packages/@lwc/rollup-plugin/README.md, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/transmogrify.spec.ts, packages/@lwc/ssr-runtime/src/render.ts
#4685 got merged automatically with a few comments still pending. However, only very minor changes were remaining. Those comments are addressed here.
W-17029474
=> chore: resolve minor feedback from #4685

packages/@lwc/engine-server/src/__tests__/fixtures/very-deeply-nested-each/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/very-deeply-nested-each/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/very-deeply-nested-each/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/very-deeply-nested-each/modules/x/component/component.js, packages/@lwc/rollup-plugin/src/index.ts, packages/@lwc/ssr-compiler/src/compile-template/shared.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/for-each.ts, packages/@lwc/ssr-runtime/package.json, packages/@lwc/ssr-runtime/src/index.ts
Fixes attribute value expression rendering inside of loops (e.g. `for:each`). Also fixes some other minor unrelated stuff.
=> fix(ssr): fix expression scoping and other small fixes

packages/@lwc/perf-benchmarks-components/rollup.config.mjs, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/perf-benchmarks/rollup.config.mjs, packages/@lwc/perf-benchmarks/scripts/build.js, packages/@lwc/perf-benchmarks/scripts/fix-deps.sh, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-server/table-render-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/table-render-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/tablecmp-render-10k.benchmark.js
~~This will fail until #4702 is merged, but I wanted to get the PR ready.~~ (_Edit: merged!_)
This adds SSR Tachometer/Best benchmarks. For now I'm merely reusing the existing `engine-server` ones so we can compare them.
Interestingly we have some work to do! Running one iteration only (so not statistically significant), I got:
- `tablecmp-render-10k`: 70ms -> 101ms
- `table-render-10k`: 210ms -> 295ms
Probably this is mostly due to the `asyncYield`, but that's fine. We will be able to hopefully see the improvement later when we switch to a no-yield variant. Plus there are probably other optimizations to do.
**Edit:** yep it is due to `asyncYield`! `sync` is way faster:
- `tablecmp-render-10k`: 19ms
- `table-render-10k`: 47ms
-   🤞 No, …
=> test(ssr): add ssr benchmarks

.github/workflows/benchmark.yml, .github/workflows/integration.yml, .github/workflows/karma.yml, .github/workflows/unit.yml, packages/@lwc/integration-tests/package.json
Updating in case this is related to the WDIO failures in #4717
=> chore(ci): bump node/chrome/gha versions

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/stylesheets.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/compile-template/shared.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/for-of.ts, packages/@lwc/ssr-compiler/src/estree/builders.ts, packages/@lwc/ssr-compiler/src/estree/validators.ts
Doing unrelated work, I noticed that we have an import helper that we don't use! So I used it. I also gave it an easier to use signature.
=> refactor(ssr): use import helpers

packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/empty/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/empty/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/empty/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/empty/modules/x/comments-text/comments-text.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty-dynamic/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty-dynamic/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty-dynamic/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty-dynamic/modules/x/comments-text/comments-text.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/nonempty/modules/x/comments-text/comments-text.js
Adds tests for how we should render adjacent text nodes when the final value ends up being the empty string.
=> test(ssr): add tests for adjacent text nodes

packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/table-render-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/tablecmp-render-10k.benchmark.js, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-runtime/src/__tests__/render-component.spec.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/lightning-element.ts, packages/@lwc/ssr-runtime/src/render.ts
Fixes #4719 
Allows `renderComponent` in `@lwc/ssr-runtime` to accept the `default` export from a Component (i.e. the `Component` constructor) as well as the `generateMarkup` export.
The way I'm accomplishing this is by just attaching `generateMarkup` to the `Component` constructor as a symbol. This doesn't prevent all forms of monkeying but it does communicate "hey, don't mess with this."
Eventually I think we should remove the `generateMarkup` export entirely: #4726. For now I'm keeping it to avoid a breaking change.
=> feat: allow passing default export to `renderComponent`

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-empty-string/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-empty-string/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-empty-string/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-empty-string/modules/x/test/test.js, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/correct-tag-attr-pair/empty-string/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/incorrect-tag-attr-pair/static/expected.html, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/boolean-attribute/hidden-global-attr/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/boolean-attribute/required/expected.js, packages/@lwc/template-compiler/src/__tests__/fixtures/attributes/error-empty-value/expected.js, packages/@lwc/template-compiler/src/codegen/static-element-serializer.ts
Currently, we have an inconsistency between the static content optimization and non-static-content optimization in how the HTML is rendered for the empty string attribute value:
```html
<input required>    
<input required=""> 
```
We should emit the same thing in both cases, since they are [equivalent](https://html.spec.whatwg.org/multipage/introduction.html#a-quick-introduction-to-html:syntax-attributes):
> The value, along with the "=" character, can be omitted altogether if the value is the empty string.
Here I am preferring the shorter format (for slightly better HTML file size), which means changing the static-optimized variant.
Technically your Jest snapshots may break. But we …
=> fix(engine): do not render empty string attr values

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-and-class-modify/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-component-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-dynamic-with-scoped-css/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-static/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-styles-with-existing-class/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-styles-with-existing-class/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-styles-with-existing-class/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-styles-with-existing-class/modules/x/component/component.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-styles-with-existing-class/modules/x/component/component.scoped.css, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/scoped-and-unscoped-with-class/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/static-stylesheets/unscoped-with-scoped-template-styles-and-class/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/style-class-whitespace/expected.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/scoped-styles-with-existing-class/index.spec.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/scoped-styles-with-existing-class/x/main/main.html, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/scoped-styles-with-existing-class/x/main/main.js, packages/@lwc/integration-karma/test-hydration/mismatches/class-attr/scoped-styles-with-existing-class/x/main/main.scoped.css, packages/@lwc/integration-karma/test/rendering/scoped-styles-with-existing-class/index.spec.js, packages/@lwc/integration-karma/test/rendering/scoped-styles-with-existing-class/x/component/component.html, packages/@lwc/integration-karma/test/rendering/scoped-styles-with-existing-class/x/component/component.js, packages/@lwc/integration-karma/test/rendering/scoped-styles-with-existing-class/x/component/component.scoped.css, scripts/test-utils/format-html.ts
This does a few things:
1. Reorders the `class`es in our SSR fixture tests to be in alphabetical order
2. Adds some karma/SSR/hydration tests to ensure the classes are correct, even if they are in different orders
The hydration tests in particular are important because they demonstrate that the order of classes does not matter w.r.t. hydration mismatches.
The goal here is to eventually run our `engine-server` tests both with and without the static content optimization and have the same fixture result.
Related: #4714 
=> test: ignore rendered class order

packages/@lwc/ssr-compiler/src/compile-template/transformers/component.ts, packages/@lwc/ssr-runtime/src/lightning-element.ts
Would eventually like to remove the use of `any` [here](https://github.com/salesforce/lwc/blob/e3f50fcaff8630ec623626a4ec1cf1a34e45dd23/packages/%40lwc/ssr-runtime/src/reflection.ts#L132).
=> chore(ssr-compiler): aria loose ends

packages/@lwc/ssr-compiler/src/__tests__/estemplate.spec.ts, packages/@lwc/ssr-compiler/src/estemplate.ts
This reverts commit d47b442aa3fc4c1f9100d317b30311e3bb6def9c.
The `placeholderType` being used is always `Identifier`, because the placeholder is always an identifier that looks like `__ESTEMPLATE_123456_PLACEHOLDER__0`. That's not particularly interesting information to include in the error message.
=> Revert "fix(ssr-compiler): update estemplate spec (#4749)"

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts
Since some test fixtures contain assertions, the errors need to be rethrown in order to properly fail the test.
https://github.com/salesforce/lwc/blob/e520676f2ee66c89e151302458734168e978380b/packages/%40lwc/engine-server/src/__tests__/fixtures/getter-class-list/modules/x/getter-class-list/getter-class-list.js#L1-L13
=> test(engine-server): rethrow assertion errors

packages/@lwc/ssr-compiler/src/__tests__/estemplate.spec.ts, packages/@lwc/ssr-compiler/src/estemplate.ts, packages/@lwc/ssr-compiler/src/estree/validators.ts
Makes the errors more clear during development. Kinda hacky, but I figure we can remove it once we're stable enough.
=> chore(ssr): label validators

packages/@lwc/engine-server/src/__tests__/fixtures/inner-outer-html/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/inner-outer-html/ssr-error.txt, packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts, packages/@lwc/ssr-runtime/src/lightning-element.ts
This is technically divergent behavior from `@lwc/engine-server`, but we want to discourage use of these attributes.
=> feat(ssr): forbid scary attributes

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-boolean copy/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-boolean copy/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-boolean copy/modules/x/attribute-boolean/attribute-boolean.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-boolean copy/modules/x/attribute-boolean/attribute-boolean.js
This fixture snuck in in 849d5cae66e9e69e0d6c18841866b8a88bbb408e and appears to be an exact copy of the non-copy folder.
```shell
$ diff -r \
packages/@lwc/engine-server/src/__tests__/fixtures/attribute-boolean\ copy \
packages/@lwc/engine-server/src/__tests__/fixtures/attribute-boolean
```
=> chore: remove fixture copy

packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names-attr-value/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names-attr-value/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names-attr-value/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names-attr-value/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names-attr-value/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names-attr-value/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/deep-different-variable-names/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-var-name-in-child-and-scoped-slot/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-var-name-in-child-and-scoped-slot/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-var-name-in-child-and-scoped-slot/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-var-name-in-child-and-scoped-slot/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-var-name-in-child-and-scoped-slot/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-var-name-in-child-and-scoped-slot/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-variable-used-outside/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-variable-used-outside/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-variable-used-outside/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-variable-used-outside/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-variable-used-outside/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/same-variable-used-outside/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/undefined-var-name-in-child-and-scoped-slot/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/undefined-var-name-in-child-and-scoped-slot/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/undefined-var-name-in-child-and-scoped-slot/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/undefined-var-name-in-child-and-scoped-slot/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/undefined-var-name-in-child-and-scoped-slot/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/undefined-var-name-in-child-and-scoped-slot/modules/x/parent/parent.js
Even more tests for scoped slots, after discussion with @wjhsf about how variable shadowing is supposed to work.
=> test(ssr): add yet more tests for scoped slots

packages/@lwc/ssr-runtime/src/lightning-element.ts, packages/@lwc/ssr-runtime/src/reflection.ts
We don't need this anymore because we now handle attribute-to-property reflection through property get descriptors.
=> refactor(ssr-compiler): remove setter attribute reflection

packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/dynamic/error.txt, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/dynamic/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/dynamic/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/dynamic/modules/x/component/component.js
I didn't notice in #4730 that we introduced an `error.txt` caused by an attempt to convert a `Symbol` to a string. Since using `Symbols` in this case is a super-rare edge case, and because it reduces the value of the test to just have an error message, I say we remove the `Symbol`.
=> test: fix Symbol error in fixture

packages/@lwc/integration-karma/test/profiler/mutation-logging/index.spec.js
Quick-and-dirty attempt to fix #4781. I can only repro in CI, so will need to look at the logs in CI to see if this works. No clue why `Promise.resolve()` would not be enough.
=> test: fix flaky mutation logging test

packages/@lwc/engine-core/src/framework/freeze-template.ts, packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/integration-karma/scripts/karma-plugins/lwc.js, packages/@lwc/integration-karma/test/rendering/native-only-css/index.spec.js, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/chic.native-only.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/glamorous.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/hip.scoped.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/light.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/light.html, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/light.js, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/light.scoped.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/light/snazzy.native-only.scoped.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/chic.native-only.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/glamorous.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/hip.scoped.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/shadow.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/shadow.html, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/shadow.js, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/shadow.scoped.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/shadow/snazzy.native-only.scoped.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/styleLibrary/bar.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/styleLibrary/foo.native-only.css, packages/@lwc/integration-karma/test/rendering/native-only-css/x/styleLibrary/styleLibrary.css, packages/@lwc/shared/src/keys.ts, packages/@lwc/shared/src/style.ts, packages/@lwc/style-compiler/src/__tests__/fixtures/disable-synthetic-shadow-support-keyframes/expected.js, packages/@lwc/style-compiler/src/__tests__/fixtures/disable-synthetic-shadow-support/expected.js, packages/@lwc/style-compiler/src/serialize.ts
If you are using a custom Rollup plugin (or similar) to conditionally set `disableSyntheticShadowSupport` for certain files (e.g. `foo.native-only.css`), then those CSS files will get compiled in a way that is fundamentally incompatible with synthetic shadow: https://github.com/salesforce/lwc/pull/3229
If, for whatever reason, you then take those stylesheets and try to render them in synthetic shadow anyway, you'll get a broken experience because the styles will not be scoped, or have the proper `:host`/`:dir` transformations, and (worse) will be hoisted to the top-level `<head>` where they might affect other unrelated components.
To fix this, this PR adds a special expando, `stylesheet.$nativeOnly`, to the `style-compiler` to indicate that a stylesheet function is intended not to be used …
=> feat(engine-dom): native-only styles

vitest.shared.mjs
This delay actually makes it rather impossible to run the tests in debug mode, as in Node.js any delay exceeding the maximum signed 32 bit integer will be treated as `1ms` instead. In the browser it would overflow. 🦶🔫 .
- [Window: setTimeout() method - Web APIs | MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/setTimeout#maximum_delay_value)
- [Timers | Node.js Documentation](https://nodejs.org/docs/latest/api/timers.html#settimeoutcallback-delay-args:~:text=the%20time%20specified.-,When%20delay%20is%20larger%20than%202147483647%20or%20less%20than%201%20or%20NaN%2C%20the%20delay%20will%20be%20set%20to%201.%20Non%2Dinteger%20delays%20are%20truncated%20to%20an%20integer.,-If%20callback%20is)
It actually shows a red-colored warning in the console since Node.js 10:
``` …
```
=> fix(tests): timeout in debug should not exceed max signed 32 bit int

packages/@lwc/engine-core/src/framework/template.ts, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/modules/x/child/child.css, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/no-dup-styles/modules/x/parent/parent.js
Fixes #4790
Turns out we had a simple programming error here where we were using `MutableVNodes` when it should have been the immutable `VNodes`. Tricky bug!
Related: #4789
W-17151345
=> fix(ssr): fix duplicate styles in same template

packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-pseudo-attr/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-pseudo-attr/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-pseudo-attr/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-pseudo-attr/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-pseudo-attr/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/parent-child-read-only-pseudo-attr/modules/x/parent/parent.js, packages/@lwc/ssr-compiler/src/compile-template/transformers/component.ts, packages/@lwc/ssr-runtime/src/clone-and-deep-freeze.ts, packages/@lwc/ssr-runtime/src/index.ts
This fixes the `parent-child-read-only-prop` by making props read-only when passed from the parent to the child.
Long-term, we can debate if this is worth it or not – it probably adds a perf overhead, but it is technically consistent with the current engine.
I also added a test to ensure this works correctly for props-that-kinda-look-like-attributes (e.g. `title`/`spellcheck`).
W-17150218
=> fix(ssr): make child props immutable

packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/text.ts
Once #4776 is merged, this PR will get us down to 29 total snapshot test failures.
This fixes how we render a variety of dynamic and literal values, in both text content and attribute values. There are lots of special rules here for e.g. `spellcheck`, `tabindex`, and HTML global attributes.
[W-17094417](https://gus.lightning.force.com/a07EE000024NyElYAK)
=> fix(ssr): fix converting dynamic values to strings

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts
Partially addresses #4793
'htmlEscape'
```
Snapshots  77 failed
Test Files  1 failed | 3 passed (4)
Tests  84 failed | 136 passed (220)
```
```
Snapshots  38 failed
Test Files  1 failed | 3 passed (4)
Tests  45 failed | 175 passed (220)
```
=> fix(ssr-compiler): unused htmlEscape import

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, vitest.workspace.mjs
Rather than skipping all the ssr tests, I think it makes more sense to skip just the fixtures instead, since all the others are passing.
To run the fixtures, the approach hasn't changed: `TEST_SSR_COMPILER=1 yarn test`.
```
✓ |lwc-ssr-compiler| src/__tests__/compilation.spec.ts (3)
✓ |lwc-ssr-compiler| src/__tests__/estemplate.spec.ts (12)
↓ |lwc-ssr-compiler| src/__tests__/fixtures.spec.ts (199) [skipped]
✓ |lwc-ssr-compiler| src/__tests__/transmogrify.spec.ts (6)
Test Files  3 passed | 1 skipped (4)
Tests  21 passed | 199 skipped (220)
```
=> test(ssr-compiler): enable all tests and skip fixtures

packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/tsconfig.json
=> fix(ssr-compiler): conflicting type definitions for estree

packages/@lwc/perf-benchmarks-components/src/benchmark/cardComponentLight/cardComponentLight.html, packages/@lwc/perf-benchmarks-components/src/benchmark/cardComponentLight/cardComponentLight.js, packages/@lwc/perf-benchmarks-components/src/benchmark/slotUsageComponentLight/slotUsageComponentLight.html, packages/@lwc/perf-benchmarks-components/src/benchmark/slotUsageComponentLight/slotUsageComponentLight.js, packages/@lwc/perf-benchmarks-components/src/benchmark/tableComponentRowLight/tableComponentRowLight.html, packages/@lwc/perf-benchmarks-components/src/benchmark/tableComponentRowLight/tableComponentRowLight.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-slot-light/light-slot-create-container-5k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/engine-dom/benchmark-slot-light/light-slot-update-slotted-content-5k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/slots/light-slot-create-container-5k.benchmark.js
Adds benchmarks for light dom slots for both `engine-dom` and SSR.
Not familiar with the benchmarking here yet. I initially wrote a script to convert the components to light dom instead of copying, but thought it might be better to validate if I kept it simple.
Closes #4784
=> test: add benchmark for light dom slots

eslint.config.mjs, package.json, yarn.lock
This was only used for `eslint-plugin-import` which supports eslint v9 since [v2.31.0](https://github.com/import-js/eslint-plugin-import/releases/tag/v2.31.0)
Annoyingly, an older version of it still gets pulled in by `eslint-config-flat-gitignore`.
=> chore(deps): remove @eslint/compat

packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/slots/slot-create-container-5k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/table/table-render-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/__benchmarks__/ssr/table/tablecmp-render-10k.benchmark.js, packages/@lwc/perf-benchmarks/src/utils/styledComponentSsrBenchmark.js, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-runtime/package.json, packages/@lwc/ssr-runtime/src/render.ts
This reverts commit d47c56c7fbd6b4f891d3398109a8b975dab897b7 (#4820).
It turns out we broke the Best tests with this PR (due to `node:utils/types` not being Rollupified correctly), and plus it seems like it doesn't accurately detect `async` mode for some reason (it sometimes determines `sync`)?
This PR was not super important so let's just revert it for now.
=> fix: revert "fix(ssr): infer the SSR mode in `renderComponent`"

scripts/tasks/unsafe-external-contributor-ci-workaround.sh
Script to run CI for forks doesn't include triggering nucleus tests; now it does!
=> chore(forks): auto trigger nucleus tests

packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-js/remove-decorator-import.ts
=> feat: remove decorator imports visitor

packages/@lwc/babel-plugin-component/src/constants.ts, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/undeclared/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/undeclared/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/undeclared/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/with-@api/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/with-@api/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/with-@api/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/with-@api/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/without-@api/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/without-@api/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/without-@api/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/without-@api/modules/x/component/component.html, packages/@lwc/shared/src/html-attributes.ts
Remove support for `contextmenu` global html attribute that was only ever implemented in Firefox and has since been removed from Firefox.
Unlikely, as there isn't a single browser that does anything with this attribute. Even when it was implemented, it was only supported by Firefox.
=> chore: remove deprecated contextmenu html global attribute

packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
It seems this one is fixed after #4840 
=> chore(ssr): remove as-component-prop/with-@api from expected failures

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
Incrementally building towards #4793 (and validating #4840), this reduces the allowed unused imports to a hard-coded list. Also includes the change in #4854 (thx @cardoso <3).
=> test(ssr-compiler): narrow which unused imports are expected

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, scripts/test-utils/test-fixture-dir.ts
Follow up to #4816.
Uses vitest's built-in support for expected failures.
I also removed `description` from `TestFixtureConfig` since it's unused.
=> chore(ssr): use test options for expected failures

packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component.ts
=> fix(ssr): fix rendering of `spellcheck` attribute

packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static-on-component/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static-on-component/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static-on-component/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static-on-component/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static-on-component/modules/x/component/component.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
More tests for things we weren't covering before!
Adds tests for string/boolean literals of known global HTML attributes when applied to components (rather than elements).
=> test(ssr): test global html literals on components

packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts, packages/@lwc/ssr-compiler/src/optimize-imports.ts
Fixes #4793.
This solves the Gordion knot by cutting it. I added an extra AST transform to remove unused imports from `@lwc/ssr-runtime`. This means we don't need to manually track any imports during AST generation.
=> fix(ssr): remove unused imports

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-imports/basic/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-imports/basic/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-imports/basic/modules/x/dynamic/dynamic.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-imports/basic/modules/x/dynamic/dynamic.js, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-imports/basic/modules/x/fake/fake.js, packages/@lwc/engine-server/src/__tests__/utils/custom-loader.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
Add a test to demonstrate the issue with #4875
I would like to test more cases here (like `import()`ing a non-literal), but that causes the SSR tests to crash with an unhandled rejection.
=> test(ssr): add test for dynamic imports

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/stylesheet-scope-token.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts
Block statements are helpful when you have a repeated pattern and don't want to deal with tracking variable names.
```py
const arr = []
{
const tmp = 1
arr.push(tmp)
}
{
const tmp = 2
arr.push(tmp)
}
{
const tmp = 3
arr.push(tmp)
}
```
They're not necessary in other cases, as there aren't collisions to worry about.
```go
const arr = []
{
arr.push(1)
}
{
arr.push(2)
}
{
arr.push(3)
}
// 👆 is the same as 👇
const arr = []
arr.push(1)
arr.push(2)
arr.push(3)
```
This PR just tidies up some unnecessary block statements.
=> chore: remove unnecessary block statements

packages/@lwc/ssr-compiler/src/compile-template/ir-to-es.ts
=> fix(ssr): make `lwc:dynamic` a runtime error

packages/@lwc/ssr-compiler/package.json
- Surfaced while working on #4897 
- Explanation: [Creating a non-flat node_modules directory](https://pnpm.io/motivation#creating-a-non-flat-node_modules-directory)
File:
https://github.com/salesforce/lwc/blob/8e1b1cfe4b2636aa91947f98d293ef6cceac646e/packages/%40lwc/ssr-compiler/src/compile-template/index.ts#L11
=> fix(ssr-compiler): missing @lwc/errors dependency

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, scripts/test-utils/test-fixture-dir.ts
The current way fixtures are tested is a bit broken:
When a value is `undefined` we check if the file doesn't exist, otherwise we check the snapshot.
If the value changes to something else, it will create a new snapshot and succeed instead of failing, since there's no way to know it was previously undefined.
This is annoying when making changes that cause a new error or produces new output, as the indication is success and a bunch of new files which need to be deleted again. Snapshot creation is something intended to happen only when actually adding new tests.
This PR only adds new empty snapshots in `babel-plugin-component` and `style-compiler` since the others were already accounting for this behavior.
-   🤞 No, it does not introduce …
=> fix(fixtures): always match empty file for undefined snapshots

packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-runtime/src/styles.ts
Another small micro-optimization, this time in the 1-7% range:
The perf benefit here is basically just avoiding creating a lot of temporary arrays that get thrown away. I noticed we were spending a lot of time in GC.
Instead of creating arrays and `filter`ing them, we can just traverse the stylesheet arrays as-is.
=> perf(ssr): speed up rendering stylesheets

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/component.ts, packages/@lwc/ssr-runtime/src/__tests__/render-component.spec.ts, packages/@lwc/ssr-runtime/src/render.ts
Fixes #4726
I've confirmed this isn't used anymore by LWR or CLWR, so we can remove it.
The `generateMarkup` export from an SSR-compiled component is no longer supported. You can use the default export just like any other LWC component.
Technically this is breaking, but the new SSR compiler is marked as unstable so we don't consider this worthy of a major version bump.
=> fix(ssr): remove `generateMarkup` export

packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/error-ssr.txt, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/error.txt, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/modules/x/dynamic/dynamic.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/modules/x/dynamic/dynamic.js, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/slots/scoped-slots/modules/x/test/test.js
Scoped slots currently do not work with `lwc:component`/`lwc:is` (see #4871). This test merely asserts the current behavior.
When #4871 is fixed, this test should be updated.
=> test(ssr): add test for scoped slots with `lwc:is`

packages/@lwc/compiler/src/options.ts, packages/@lwc/rollup-plugin/src/index.ts, packages/@lwc/shared/src/ssr.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/index.ts, packages/@lwc/ssr-compiler/src/shared.ts
Rollup plugin currently has an undeclared dependency on `@lwc/ssr-compiler` only to use the type `CompilationMode`.
Rather than declaring the dependency and since `@lwc/shared` already exports the constant `DEFAULT_SSR_MODE`, I think it's best that this type is moved there.
=> fix(rollup-plugin): remove undeclared dependency on ssr-compiler

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Minor version bump for CLCO. 8.10.x series is now for `spring25`.
=> chore: release v8.11.0

packages/@lwc/perf-benchmarks/scripts/build.js
This is an error we discovered in https://github.com/salesforce/lwc/pull/4897. yarn v1 uses `--frozen-lockfile`, not `--immutable`.
=> chore(perf-benchmarks): avoid `yarn --immutable`

packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/mixed/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/mixed/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/mixed/modules/x/dynamic/dynamic.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/mixed/modules/x/dynamic/dynamic.js, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/mixed/modules/x/test/test.html, packages/@lwc/engine-server/src/__tests__/fixtures/dynamic-components/mixed/modules/x/test/test.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
SSR currently diverges with this error:
`__SYMBOL__GENERATE_MARKUP is not defined`
=> test: mixed lwc:component and tag

packages/@lwc/ssr-compiler/src/__tests__/utils/runner.ts, packages/@lwc/ssr-compiler/vitest.config.mjs
This avoids accidentally updating snapshots from the ssr fixtures.
Besides hitting the 'u' button accidentally, it can happen when adding new tests and rerunning everything ( eg: #4958 ).
Not sure it's worth it just for this, but in a future PR the custom runner could be used to verify changes in the expected failures to spot regressions or improvements.
=> chore(ssr): disable snapshot updates in fixtures

packages/@lwc/integration-karma/scripts/karma-plugins/hydration-tests.js, scripts/test-utils/test-fixture-dir.ts
Currently, we can put `.only` in a fixture directory to focus on that test. But we also sometimes group similar fixtures into directories, so it would be nice to be able to just put a single `.only` in that directory. Now we can!
=> chore(test-utils): check parent directories for .only

.github/dependabot.yml
Prettier can introduce formatting changes even in minor version bumps (see #4977); this PR updates the config to move breaking prettier changes out of the non-breaking group.
=> chore(dependabot): don't group prettier with non-breaking deps

packages/@lwc/engine-server/src/__tests__/fixtures.spec.ts
Turning the flag on and off for each test meant that the state becomes flaky when running concurrently.
=> test(ssr): fix sync mode flag to work with concurrency

packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/lwc-component.ts
Fixes 1 expected failure: `dynamic-components/mixed/index.js`
=> fix(ssr): correct import alias for generateMarkup symbol in lwc-component

packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each-with-rendered-item/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each-with-rendered-item/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each-with-rendered-item/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each-with-rendered-item/modules/x/comments-text/comments-text.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-for-each/modules/x/comments-text/comments-text.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-iterator/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-iterator/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-iterator/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-off/deep-iterator/modules/x/comments-text/comments-text.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/for-each.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/for-of.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/if.ts
=> fix(ssr): adjacent text in `<template>`s

packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-key/error.txt, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-key/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-key/modules/x/wire/adapter.js, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-key/modules/x/wire/wire.html, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-key/modules/x/wire/wire.js
=> test(ssr): add fixture for computed prop exploding

packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-on/empty copy/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-on/empty copy/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-on/empty copy/modules/x/comments-text/comments-text.html, packages/@lwc/engine-server/src/__tests__/fixtures/adjacent-text-nodes/preserve-comments-on/empty copy/modules/x/comments-text/comments-text.js
=> test(ssr): add fixture for lwc:if and comment with no text nodes

packages/@lwc/ssr-compiler/src/compile-template/transformers/text.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/render-text-content.ts
I got bugged by seeing so much repeated code in the generated JS. So I extracted some of it into a shared runtime helper.
Before:
```js
didBufferTextContent = true;
{
const value = instance.foo;
textContentBuffer += value == null ? '' : String(value);
}
didBufferTextContent = true;
{
const value = instance.bar;
textContentBuffer += value == null ? '' : String(value);
}
didBufferTextContent = true;
{
const value = instance.baz;
textContentBuffer += value == null ? '' : String(value);
}
```
After:
```js
didBufferTextContent = true;
textContentBuffer += renderTextContent(instance.foo);
didBufferTextContent = true;
textContentBuffer += renderTextContent(instance.bar);
didBufferTextContent = true;
textContentBuffer += renderTextContent(instance.baz);
```
No we just need to have …
=> refactor(ssr): reduce duplicated text rendering logic

.gitignore, package.json
Partially addresses #4911 . 
Linting currently takes almost 30s in my M1 Max 🤦 . I don't always run the lint command directly and lint-staged kinda does a similar job to caching, but when I have to this is definitely a help. 
```
% yarn lint
yarn run v1.22.22
$ eslint . --cache
✨  Done in 27.55s.
% yarn lint
yarn run v1.22.22
$ eslint . --cache
✨  Done in 1.72s.
```
Ref:
- https://eslint.org/docs/latest/use/command-line-interface#caching
This shouldn't affect CI.
=> chore: use eslint cache

scripts/test-utils/test-fixture-dir.ts
In #4985, I updated the fixtures to have a custom error when we go from having `expected.html` to `error.txt`, or vice versa. However, vitest tries to be clever and merges test output that has the same error message. This isn't helpful when the underlying errors are completely different, so I added the fixture name to the error message to avoid deduping.
**Before:**
```vitest
FAIL |lwc-ssr-compiler|  src/__tests__/fixtures.spec.ts > fixtures > scoped-slots/expression/index.js
FAIL |lwc-ssr-compiler|  src/__tests__/fixtures.spec.ts > fixtures > exports/component-as-default/index.js
AssertionError: Expected content in expected.html, but found content in error.txt.
- Expected
+ Received
- <x-parent>
-   <template shadowrootmode="open">
-     <x-child>
-       <div>
-         
-         
- …
```
=> chore: refine fixture error message

packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/scoped-slots/default-slot/modules/x/parent/parent.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
Add specific coverage for scoped default slots (currently, `engine-server` does not render all content, see #5020)
=> chore: test usage of default slot with scoped data

packages/@lwc/rollup-plugin/src/index.ts
Fixes a bug that caused dynamic component names to contain illegal characters on Windows platforms
=> always use / when splitting filename to get name and namespace

packages/@lwc/compiler/src/options.ts, packages/@lwc/compiler/src/transformers/javascript.ts, packages/@lwc/rollup-plugin/src/index.ts, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-compiler/src/__tests__/dynamic-imports.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/utils/custom-loader.js, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-js/types.ts, packages/@lwc/ssr-compiler/src/compile-js/wire.ts, packages/@lwc/ssr-compiler/src/compile-template/context.ts, packages/@lwc/ssr-compiler/src/imports.ts, packages/@lwc/ssr-compiler/src/index.ts, packages/@lwc/ssr-compiler/src/shared.ts
Fixes #5021
Related: #5031 #5032
=> fix(ssr): add `experimentalDynamicComponent` aka dynamic imports

packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/modules/x/deep/deep.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/modules/x/deep/deep.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/light/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/modules/x/deep/deep.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/modules/x/deep/deep.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/lwcIf-with-adjacent-text-nodes/shadow/modules/x/outer/outer.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
Adds some tests for tricky edge cases with slots, `lwc:if`, and adjacent text.
=> test(ssr): add test for bookends with text concat

packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/light/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/light/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/light/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/light/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/light/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/light/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/shadow/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/shadow/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/shadow/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/shadow/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/shadow/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/ifTrue/shadow/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/light/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/light/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/light/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/light/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/light/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/light/modules/x/outer/outer.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/shadow/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/shadow/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/shadow/modules/x/inner/inner.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/shadow/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/shadow/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slot-not-at-top-level/nested-elements/lwcIf/shadow/modules/x/outer/outer.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
This adds a test that demonstrates another issue with #5027. This was reproducible by taking the existing `advanced` tests and replacing `lwc:external`s with `<div>`s. In principle, both external components and elements should behave the same.
=> test(ssr): add tests for nested elements in slots

packages/@lwc/integration-karma/test/events/focus-event-composed/index.spec.js
`FocusEvent` is widely supported now: https://caniuse.com/mdn-api_focusevent
=> test(karma): remove unnecessary IE11-related code

packages/@lwc/integration-karma/test/rendering/issue-4889/index.spec.js, packages/@lwc/integration-karma/test/rendering/issue-4889/x/data/data.js, packages/@lwc/integration-karma/test/rendering/issue-4889/x/row/row.html, packages/@lwc/integration-karma/test/rendering/issue-4889/x/row/row.js, packages/@lwc/integration-karma/test/rendering/issue-4889/x/table/table.html, packages/@lwc/integration-karma/test/rendering/issue-4889/x/table/table.js
Adds a disabled test for #4889. Not a solution, but may help point us to a solution eventually!
=> test(karma): add test for for:each issue #4889

packages/@lwc/ssr-compiler/src/__tests__/estemplate.spec.ts, packages/@lwc/ssr-compiler/src/shared.ts
This is a type-only fix.
It was probably an unintended change introduced in #5033 which caused some type errors in tests:
=> fix(ssr-compiler): namespace & name are optional in CompilerTransformOptions

packages/@lwc/integration-karma/test/rendering/issue-4889/index.spec.js, packages/@lwc/integration-karma/test/rendering/issue-4889/x/data/data.js
Reduces #4889 even further. I still don't have a solution, but I wanted to get this in, in case I need to timebox this work.
=> test(karma): reduce #4889 even further

packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/element.ts, packages/@lwc/ssr-runtime/src/render.ts
Fixes two tests, for `style` rendering.
Relevant:
https://github.com/salesforce/lwc/blob/59e2c6cb57283e972a0c0da34ceab54d043aaace/packages/%40lwc/engine-core/src/framework/modules/computed-style-attr.ts#L40
=> fix(ssr): fix `style` attribute rendering

packages/@lwc/engine-server/src/__tests__/fixtures/superclass/with-props/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/with-props/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/with-props/modules/x/component/component.js, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/with-props/modules/x/fancyElement/fancyElement.html, packages/@lwc/engine-server/src/__tests__/fixtures/superclass/with-props/modules/x/fancyElement/fancyElement.js, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
If you have a superclass with arguments in its `constructor`, and if the subclass tries to pass in those arguments via `super`, then this currently fails in SSR compiler. The reason is that the SSR compiler overwrites the constructor's args with its own `propsAvailableAtConstruction` object.
This adds a test to repro this.
=> test(ssr): add test for superclass with args passed in

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-runtime/src/render.ts
I'm not sure what the original intention was here, but the `tmpl` function never uses the `props` or `attrs` parameters, so we don't need to pass them to it.
(Instead, the way it works is that the `tmpl` function calls `instance.foo`/`instance.bar` etc., and `props` are pre-applied to the `instance` via `SYMBOL__SET_INTERNALS`.)
=> refactor(ssr): do not pass props/attrs to `tmpl`

ARCHITECTURE.md
Fixes some typos and improves a link.
=> docs: fix mistakes in ARCHITECTURE.md

eslint.config.mjs
=> chore(eslint): disallow `fdescribe`/`fit`

packages/@lwc/engine-core/src/framework/mutation-tracker.ts, packages/@lwc/engine-core/src/framework/utils.ts, packages/@lwc/integration-karma/test/signal/protocol/index.spec.js, packages/@lwc/integration-karma/test/signal/protocol/x/throws/throws.html, packages/@lwc/integration-karma/test/signal/protocol/x/throws/throws.js
Fixes #5104
Avoids throwing an error when the `in` operator throws an error on an arbitrary object.
This should not cause any breaking changes, because we are trying to detect if an object "looks" like a signal, and if checking `'value' in object` throws, then we can conclusively say it's not a signal.
=> fix(signals): avoid throwing when `in` check throws

packages/@lwc/engine-server/src/__tests__/fixtures/reserved-keywords/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/reserved-keywords/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/reserved-keywords/modules/x/cmp/cmp.html, packages/@lwc/engine-server/src/__tests__/fixtures/reserved-keywords/modules/x/cmp/cmp.js, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts
If a component author happens to use the variable names `privateFields`/`publicFields` in their component, then they will conflict with the SSR compiler's usage of those same variables, and result in an error at compile time:
```
Identifier "privateFields" has already been declared
```
Note this was introduced by https://github.com/salesforce/lwc/pull/5092
This PR fixes that.
=> fix(ssr): avoid reserved keyword collision

packages/@lwc/engine-core/src/framework/mutation-tracker.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/signal/protocol/index.spec.js
=> chore: add a flag for signals try/catch fix

packages/@lwc/ssr-runtime/src/render.ts
For some reason, we had a custom attribute value serializer here rather than using `htmlEscape` like we do elsewhere. The two functions do the same thing.
=> chore(ssr): use `htmlEscape` consistently

packages/@lwc/ssr-compiler/src/__tests__/compilation.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/errors.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-js/wire.ts
Partially addresses #5032 
I borrowed some tests from `babel-plugin-component` to make sure the location matches.
Since it uses `generateCompilerError` from `@lwc/errors`, it should work with the LSP/VSCode extension. ([relevant code](https://github.com/forcedotcom/lightning-language-server/blob/46ec16e555ff23dfb90a3daea060d70a31830720/packages/lwc-language-server/src/javascript/compiler.ts#L99-L124)).
=> feat(ssr): compiler error location

packages/@lwc/ssr-compiler/src/compile-template/transformers/component/component.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/lwc-component.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/lightning-element.ts
Another relatively low-hanging 8-13% perf improvement. We don't need to create a read-only proxy for the entire child props object – the intention is for each individual object to be read-only, but the whole thing doesn't need to be.
This is especially nice for prop objects like `{ foo: 'string', bar: 123 }` where the values are primitives, and thus don't even need to be wrapped, so `readOnlyProxy` will just return the primitive.
=> perf(ssr): avoid proxying entire props object

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/decorator-expects-a-function-identifier-as-first-parameter/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/decorator-expects-a-function-identifier-as-first-parameter/error.json
This error was missing a test in babel-plugin-component. It can later be replicated for ssr.
=> test: @wire expects a function identifier as first parameter (LWC1097)

packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/decorator-rejects-computed-props/actual.js, packages/@lwc/babel-plugin-component/src/__tests__/fixtures/wire-decorator/decorator-rejects-computed-props/error.json
=> test: wire identifier cannot contain computed properties (LWC1131)

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/api/createElement/index.spec.js, packages/@lwc/integration-karma/test/integrations/locker/index.spec.js
[Flag name change requested](https://gitcore.soma.salesforce.com/core-2206/core-public/pull/76328#discussion_r943667)
[W-17528759](https://gus.lightning.force.com/a07EE000027V1pCYAS)
=> chore: change locker support flag for clarity

packages/@lwc/engine-core/src/framework/template.ts
=> fix: remove dot from style token regex @W-17528745

.github/workflows/unit.yml, packages/@lwc/ssr-compiler/src/__tests__/fixtures.spec.ts, vitest.config.mjs
Removes the `TEST_SSR_COMPILER` and runs the SSR compiler tests as part of the main `yarn test` suite. Also adds coverage thresholds.
The main benefit of this PR is that we now get coverage numbers for the SSR compiler, and plus the test infra is much simpler. The only downside is that there is a somewhat annoying and distracting red "9 failed" message for the mismatched snapshots:
These snapshot failures should ideally be driven down to zero soon. We are reaching the point where many of the differences between `engine-server` and `ssr-compiler` are expected or unimportant. E.g. for HTML global attributes, both systems are wrong (https://github.com/salesforce/lwc/issues/5123). So it may be time to just deprecate `engine-server` and move forward with fixing `ssr-compiler`.
Partially …
=> test(ssr): remove env var, test coverage

packages/@lwc/engine-core/src/framework/decorators/wire.ts, packages/@lwc/integration-types/src/decorators/wire.ts
Expand the allowed types for `wire` decorators to support objects that have an `adapter` prop holding the WireAdapterConstructor. Examples of this being Apex functions imported from the Salesforce platform. They are function objects that can be called imperatively and also have an `adapter` prop holding a compatible WireAdapterConstructor that can be passed to the `wire` decorator.
Expand the type compatibility for the `wire` decorator to allow a wire adapter constructor delivered as a prop. This should only expand the allowed types, not constrain them and shouldn't result in any breaks for consumers.
=> feat(engine): support imperative wire adapters

packages/@lwc/perf-benchmarks/README.md
=> docs(perf-benchmarks): say how long things take

packages/@lwc/perf-benchmarks/README.md, packages/@lwc/perf-benchmarks/scripts/format-results.mjs
Does what it says in the README.
=> chore(perf): save summary table to files and improve readme @W-17718770

packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/modules/x/child/child.html, packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/modules/x/child/child.js, packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/modules/x/parent/parent.html, packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/modules/x/parent/parent.js, packages/@lwc/engine-server/src/__tests__/fixtures/api/inherited/modules/x/superChild/superChild.js, packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list/modules/x/getter-class-list/getter-class-list.js, packages/@lwc/engine-server/src/__tests__/fixtures/if-block/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/if-block/modules/x/if-block/if-block.html, packages/@lwc/engine-server/src/__tests__/fixtures/if-block/modules/x/if-block/if-block.js, packages/@lwc/engine-server/src/__tests__/fixtures/non-lwc-class/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/non-lwc-class/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/non-lwc-class/modules/x/cmp/cmp.html, packages/@lwc/engine-server/src/__tests__/fixtures/non-lwc-class/modules/x/cmp/cmp.js, packages/@lwc/engine-server/src/__tests__/fixtures/non-lwc-class/modules/x/notLightningElement/notLightningElement.js, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/legacyIf.ts, packages/@lwc/ssr-runtime/src/class-list.ts
As we've rendered some internal components under the new SSR implementation, a handful of issues were identified. This PR introduces corresponding test cases and fixes.
Further closes the gap between SSRv1 and SSRv2.
W-17740271
=> feat(ssr): implement fixes for known issues

packages/@lwc/engine-core/src/framework/mutation-logger.ts, packages/@lwc/engine-server/src/__tests__/fixtures/track-revoked-proxy-fails/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/track-revoked-proxy-fails/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/track-revoked-proxy-fails/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/track-revoked-proxy-fails/modules/x/component/component.js
=> fix(track): don't throw on revoked proxies @W-17739481

packages/@lwc/engine-server/src/__tests__/fixtures/prohibited-variable-name/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/prohibited-variable-name/error-ssr.txt, packages/@lwc/engine-server/src/__tests__/fixtures/prohibited-variable-name/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/prohibited-variable-name/index.js, packages/@lwc/engine-server/src/__tests__/fixtures/prohibited-variable-name/modules/x/dontDoItStupid/dontDoItStupid.js, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts
In extreme edge cases, customers might try to get a handle on and manipulate variables we use in SSRv2 internals. This makes that much harder.
Barely observable, not a concern.
W-17561326
=> fix(ssr): prohibit variable names in customer code from colliding with SSR-internal variables

packages/@lwc/rollup-plugin/src/__tests__/index.spec.ts, packages/@lwc/rollup-plugin/src/index.ts
This PR exposes the rollup plugin version to facilitate interoperability with other plugins, which is required for supporting scenarios like #4628 in the long run.
See: https://github.com/rollup/rollup/pull/4771
=> feat(rollup-plugin): expose version

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/integration-karma/test/component/LightningElement/index.spec.js
=> revert: temporarily undo Locker-specific logic @W-17769475

packages/@lwc/ssr-runtime/src/lightning-element.ts
We had a fix for this in a branch but failed to introduce it into LWC proper. Some components will check `this.template.synthetic` to determine if the LWC instance is running in synthetic mode. It will never be running in synthetic mode in SSRv2, so the answer is to return `{ synthetic: false }` for any reference to `this.template`. In the future, we might want to make this frozen object constant that's referenced by `LightningElement`, but we can make those changes when we do the optimization work on SSRv2.
Described above.
=> fix: provide template prop on LightningElement in SSRv2

packages/@lwc/rollup-plugin/src/index.ts
[StackBlitz Repro](https://stackblitz.com/~/github.com/cardoso/salesforce-lwc-dshanxfr). (The only difference from the playground is using pnpm instead of npm)
This PR proposes removing:
https://github.com/salesforce/lwc/blob/a12a3cd9150c4b967e479f58a3a849ea502343db/packages/%40lwc/rollup-plugin/src/index.ts#L58-L62
All tests are passing locally and no breaking changes are intended. If nucleus catches any downstream breakages, this PR can be closed.
There are at least a few drawbacks related to declaring these default modules in advance.
1. if you don't use synthetic shadow you're still required to have it in your dependency graph, even if you configure `disableSyntheticShadowSupport: true` and don't import it at all.
2. If your setup doesn't handle transitive dependencies in the same way …
=> fix(rollup-plugin): remove default modules

packages/@lwc/ssr-compiler/src/__tests__/compilation.spec.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts
In #5186 we added the version comment to compiled component JS, but we forgot to also do it for compiled template files. This does it! The compiled output of a template now looks like the following:
```js
export default function tmpl($$emit, shadowSlottedContent, lightSlottedContent, scopedSlottedContent, Cmp, instance) {
...
/*LWC compiler v8.13.1*/
}
```
=> feat(ssr): add LWC version comment to end of compiled template

packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/estemplate.ts
We prevent component authors from using `__lwc` variables, so the temporary placeholder variable should use that prefix, to avoid any nasty surprises.
=> chore: rename ephemeral placeholder variable

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/integration-karma/test/component/LightningElement/index.spec.js
[W-17767282](https://gus.lightning.force.com/a07EE000029DvAhYAK)
=> chore: reintroduce locker logic

packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list-modify/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list-modify/error.txt, packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list-modify/expected-ssr.html, packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list-modify/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/getter-class-list-modify/modules/x/getter-class-list/getter-class-list.js, packages/@lwc/ssr-runtime/src/class-list.ts
We believed that these ClassList methods would not be needed in the new SSR implementation. However, it appears that there are some use cases that are unavoidable.
The overall implementation for ClassList was made more DRY with the introduction of `parseClassName`.
Feature addition.
W-17894489
=> feat: implement remaining ClassList methods

packages/@lwc/rollup-plugin/src/__tests__/resolver/resolver.spec.ts, packages/@lwc/rollup-plugin/src/index.ts
It reintroduces the default modules removed in #5203 , but in a way that can be opted out.
Fixes #5232
Fixes #5229 
=> fix(rollup-plugin): add default modules back

.nucleus.yaml
Outdated downstreams that always fail just create noise.
=> chore(nucleus): remove always failing downstreams

packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/component.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/lwc-component.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/lightning-element.ts, packages/@lwc/ssr-runtime/src/render.ts
With all the indirection between the generated code fragments (and their lack of types) and the transmogrifier, the types in `render.ts` got a bit out of date. I updated them to be accurate and tried to DRY it up a bit. But it's not _that_ repetitive, so the abstraction might be too much in the other direction? 🤷
Note that TypeScript knows to expand the rest params, so that the tooltips still look as if the functions had been defined the regular way.
=> chore(ssr): update `generateMarkup` type defs

packages/@lwc/engine-server/src/__tests__/fixtures/prohibited-variable-name/error-ssr.txt, packages/@lwc/errors/src/compiler/error-info/index.ts, packages/@lwc/errors/src/compiler/error-info/ssr.ts, packages/@lwc/ssr-compiler/src/__tests__/dynamic-imports.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/decorators/wire.ts, packages/@lwc/ssr-compiler/src/compile-js/index.ts
Updates `ssr-compiler` to use the shared error messages, for a more consistent user experience.
=> chore(ssr): use real error messages for errors @W-17408217

packages/@lwc/engine-server/src/__tests__/fixtures/slots-light-evil-template-as-prop/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/slots-light-evil-template-as-prop/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-light-evil-template-as-prop/modules/x/inner/inner.js, packages/@lwc/engine-server/src/__tests__/fixtures/slots-light-evil-template-as-prop/modules/x/outer/innerTemplateFn.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-light-evil-template-as-prop/modules/x/outer/outer.html, packages/@lwc/engine-server/src/__tests__/fixtures/slots-light-evil-template-as-prop/modules/x/outer/outer.js
This adds a passing test. I originally thought this was a repro for an issue we're seeing, but it must be something else. The test still has value though.
- 
=> test: template provided through @api-decorated prop

packages/@lwc/engine-core/src/framework/check-version-mismatch.ts
Playground is currently broken:
Repro:
https://stackblitz.com/edit/salesforce-lwc-gzz2fzxz?file=rollup.config.js
=> fix(engine-core): process is not defined

package.json, packages/@lwc/aria-reflection/package.json, packages/@lwc/babel-plugin-component/package.json, packages/@lwc/compiler/package.json, packages/@lwc/engine-core/package.json, packages/@lwc/engine-dom/package.json, packages/@lwc/engine-server/package.json, packages/@lwc/errors/package.json, packages/@lwc/features/package.json, packages/@lwc/integration-karma/package.json, packages/@lwc/integration-tests/package.json, packages/@lwc/integration-types/package.json, packages/@lwc/module-resolver/package.json, packages/@lwc/perf-benchmarks-components/package.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/rollup-plugin/package.json, packages/@lwc/shared/package.json, packages/@lwc/signals/package.json, packages/@lwc/ssr-client-utils/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/ssr-runtime/package.json, packages/@lwc/style-compiler/package.json, packages/@lwc/synthetic-shadow/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/types/package.json, packages/@lwc/wire-service/package.json, packages/lwc/package.json, playground/package.json
Release PR number one for 8.16.0 including style-dedupe functionality.
=> chore: release v8.16.0

packages/@lwc/rollup-plugin/src/index.ts
Fixes `ReferenceError: module is not defined in ES module scope` when running the esm build of rollup-plugin in pure es module environment. 
In certain use cases where the esm version of rollup-plugin is loaded, this can cause a failure:
```bash
examples/csr build: failed to load config from /home/runner/work/vite-plugin-lwc/vite-plugin-lwc/examples/csr/vite.config.ts
examples/csr build: error during build:
examples/csr build: ReferenceError: module is not defined in ES module scope
examples/csr build:     at file:///home/runner/work/vite-plugin-lwc/vite-plugin-lwc/node_modules/.pnpm/@lwc+rollup-plugin@8.15.1_rollup@4.34.9/node_modules/@lwc/rollup-plugin/dist/index.js:261:1
```
This fix should not break anything™ 
- 🤞 No, it does not …
=> fix(rollup-plugin): module is not defined in ES module scope

packages/@lwc/engine-core/src/framework/check-version-mismatch.ts
evidently some places have `process` but not `process.env`
=> chore: extra guards process.env @W-17994335

package.json, packages/@lwc/ssr-client-utils/package.json, scripts/tasks/check-and-rewrite-package-json.js
In #5264, we introduced a method to register the `lwc-style` custom element. We also tried to add a helper file, so that users can do a bare import (`import "@lwc/ssr-client-utils/register-lwc-style"`), rather than needing to import and call a function. But we didn't add it to the package.json `files` array! 😳 This PR adds it, so that users can receive it!
=> chore: expose `lwc-style` register util

packages/@lwc/ssr-compiler/src/__tests__/compilation.spec.ts, packages/@lwc/ssr-compiler/src/__tests__/transmogrify.spec.ts, packages/@lwc/ssr-compiler/src/compile-js/generate-markup.ts, packages/@lwc/ssr-compiler/src/compile-js/stylesheet-scope-token.ts, packages/@lwc/ssr-compiler/src/compile-template/index.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/slotted-content.ts, packages/@lwc/ssr-compiler/src/transmogrify.ts
When we transmogrify the SSR compiler's output, we only want to target functions created by the compiler, not the component's implementation. We check for specific function names, but technically a component could implement a function with the same name (or even _containing_ the same name, like `omgwtftmplbbq`, because we don't use `^$` in the regex check). However, we already prevent components from using names starting with `__lwc`, so we can prevent accidental transmogrification by using that namespace for the functions we own.
=> chore: use `__lwc` for transmogrified function names

packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-when-colliding-prop-then-method/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-when-colliding-prop-then-method/error-ssr.txt, packages/@lwc/ssr-compiler/src/__tests__/utils/expected-failures.ts
V1/2 have different errors but they are both expected so pathing required in the fixture.
W-18023007
=> fix: colliding error prop delta

packages/@lwc/engine-server/src/__tests__/fixtures/read-only-props/function/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/read-only-props/function/expected-ssr.html, packages/@lwc/engine-server/src/__tests__/fixtures/read-only-props/function/expected.html, packages/@lwc/engine-server/src/__tests__/fixtures/read-only-props/function/modules/x/component/component.html, packages/@lwc/engine-server/src/__tests__/fixtures/read-only-props/function/modules/x/component/component.js, packages/@lwc/ssr-runtime/src/get-read-only-proxy.ts, packages/@lwc/ssr-runtime/src/index.ts, packages/@lwc/ssr-runtime/src/stubs.ts
Add readonly implementation to SSR V2 for parity with CSR. We don't want to support it in SSR v2, but LBC and Commerce rely on it, so we will add it but mark it as deprecated.
W-18034153
=> fix: added readonly function and tests

packages/@lwc/integration-karma/helpers/test-hydrate.js
Nolan's comment says the workaround is for Firefox, which added support in version 128 (released 2024-07-09). So it shouldn't be necessary any more. (Unless we're still testing older versions.)
=> chore(integration-karma): remove programmatic DSD check

.github/dependabot.yml
Something's broken in a recent update. Not sure what and don't want to look into it, at the moment. Pulling the packages out separately means we can still get the other dependabot bumps.
=> chore(dependabot): separate out all @wdio packages

eslint.config.mjs, package.json, packages/@lwc/engine-server/src/__tests__/fixtures/scope-token/.skip, packages/@lwc/rollup-plugin/src/__tests__/resolver/fixtures/inherited-templates/src/typescript.ts
We noticed recently that `.only` files could be accidentally committed, which breaks test coverage. Turns out they've been broken since we switched to flat ESLint config!
This was more annoying than I'd like it to have been because it seems `typescript-eslint` doesn't play nice with mixing and matching.
=> chore(eslint): update config to catch .only and .skip files

packages/@lwc/ssr-compiler/src/compile-js/index.ts, packages/@lwc/ssr-compiler/src/compile-js/types.ts
1. Changed the `__load` identifier to `__lwcLoad` so that users can't sneaky hijack that. But that change gets caught by our `__lwc` check, so I added a way to check which `__lwc` identifiers we trust.
2. We only want to mutate things that belong to the actual LWC component. The existing `isLWC` logic potentially breaks if there's more than one class in a file (e.g. `class Cmp extends LightningElement { ... }; class Helper { ... };`), so I added a way of tracking whether we're actually inside the LWC component itself.
3. PR best viewed with whitespace diff ignored.
Closes #5189.
=> feat(ssr-compiler): only mutate things if we're in a component @W-17748892

packages/@lwc/ssr-compiler/src/compile-js/decorators/wire.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/component/slotted-content.ts, packages/@lwc/ssr-compiler/src/compile-template/transformers/slot.ts
We added a bunch of `FIXME`s while doing the initial implementation of SSR v2. Turns out we've fixed just about all of them. There's only one left, that we can probably address when we do perf optimizations.
https://github.com/salesforce/lwc/blob/9a75843839bea264dd579cbce33102ea59798022/packages/%40lwc/ssr-compiler/src/compile-template/transformers/slot.ts#L92
=> chore(ssr-compiler): remove fixed FIXMEs

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/component/LightningElement/index.spec.js
Re-introduce new constructor check with an additional gate to protect the rollout.
WHAT:
Adds the DISABLE_LIGHTNING_CONSTRUCTOR_CHECK gate to only do the component instanceof LightningElement check when this gate is false and LEGACY_LOCKER_ENABLED is false.
WHY?
Adding the gate allows us to disable the new constructor check if there are issues and it gives LWS a chance to correctly implement the LEGACY_LOCKER_ENABLED using the new logic.
W-18174268
=> chore: re-introduce new constructor validation with gate

packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/without-@api-values/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/as-component-prop/without-@api/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/draggable/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/hidden/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/attribute-global-html/spellcheck/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/inner-outer-html/inner-lwc/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/known-boolean-attributes/default-def-html-attributes/static-on-component/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/read-only-props/function/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/ssr-internals/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-getter/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-method/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-on-computed-setter/config.json, packages/@lwc/engine-server/src/__tests__/fixtures/wire/errors/throws-when-colliding-prop-then-method/config.json
If SSR v1 and v2 are both expected to pass or both expected to fail, then they can share the unused fixture file.
=> chore(fixtures): remove some empty files

packages/@lwc/engine-core/src/framework/invoker.ts, packages/@lwc/features/src/index.ts, packages/@lwc/features/src/types.ts, packages/@lwc/integration-karma/test/component/LightningElement/index.spec.js
Invert locker constructor check so default gate value is false.
[W-18174268](https://gus.lightning.force.com/a07EE00002C20XEYAZ)
=> fix: invert locker contructor gate

.github/workflows/karma.yml
`saucelabs/sauce-connect-action@v2` was end-of-lifed in 2024 Q4. This PR bumps to v3 (the latest). It won't be clear until after merging whether this fixes Sauce Labs integration or if additional changes are needed.
=> chore: fix sauce labs integration

.github/workflows/karma.yml
Follow-up from #5342. There is no `v3` tag in the repo where the action is defined, despite what the docs say. There is a `v3.0.0`, however.
=> chore: update SL action to reference `v3.0.0`

packages/@lwc/engine-core/src/framework/mutation-tracker.ts
Remove perf regression for signals re-enablement. Once removed, we can re-enable `ENABLE_EXPERIMENTAL_SIGNALS` in main
W-18381293
=> chore: remove perf regression for signals re-enablement

packages/@lwc/engine-core/src/framework/mutation-tracker.ts
Backport signals perf regression to 256 patch
[W-18328598](https://gus.lightning.force.com/a07EE00002DAb1vYAD)
=> fix: remove perf regression for signals re-enablement (256 patch)

.nucleus.yaml
update nucleus.yaml to summer25
[W-18328598](https://gus.lightning.force.com/a07EE00002DAb1vYAD)
=> chore: update nucleus to summer25 definitions

packages/@lwc/engine-dom/src/apis/create-element.ts, packages/@lwc/template-compiler/src/parser/expression-complex/html.ts
When rendering an LWC component, the component instance and element instance are two connected but distinct objects. The component instance inherits from `LightningElement`, while the element is an instance of `HTMLElement` with a few additional properties. Those properties are the `@api`-decorated properties from the component instance.
When the class in the following example gets used, the component instance would have two props, `exposed` and `internal`. The element instance only has one, `exposed`.
```js
class Example extends LightningElement {
@api exposed = 'hello'
internal = 'secret'
}
```
Because component authors create components, but largely consume elements, we added a new helper type in [LWC v7.0.0](https://github.com/salesforce/lwc/releases/tag/v7.0.0#user-content-improved-ty …
=> feat(types): add hidden helper to make inferring element types better @W-18442478

packages/lwc/package.json, playground/README.md, playground/package.json, playground/rollup.config.js, playground/tsconfig.json
We want the playground to be minimal, but we also want it to be easy to have a minimal TypeScript playground. This PR adds the necessary bits to support TS, but comments them out by default.
=> feat(ts): almost enable TypeScript in the playground

.github/dependabot.yml
We still haven't fixed the vite issues in #5355 and I'm pretty sure the webdriver deps also have issues? So separating them out will hopefully unblock the rest of the dependency treadmill. (Also I alphabetized the groups.)
=> chore(dependabot): separate all webdriverio versions and add group for vitest

package.json, packages/@lwc/engine-server/package.json, packages/@lwc/ssr-compiler/package.json, packages/@lwc/template-compiler/package.json, packages/@lwc/template-compiler/src/codegen/codegen.ts, packages/@lwc/template-compiler/src/codegen/expression.ts, packages/@lwc/template-compiler/src/codegen/optimize.ts, packages/@lwc/template-compiler/src/parser/expression-complex/validate.ts, packages/@lwc/template-compiler/src/parser/html.ts, yarn.lock
Dependabot PRs have been blocked for a while (see https://github.com/salesforce/lwc/pull/5355#issuecomment-2845441078, #5390). `@types/estree` and `parse5` have some minor type def changes that are a mild nuisance, so I pulled them out into their own PR.
=> chore(deps): bump @types/estree and parse5

packages/@lwc/engine-core/README.md, packages/@lwc/engine-core/src/framework/main.ts, packages/@lwc/engine-dom/src/index.ts, packages/@lwc/engine-server/src/index.ts, packages/@lwc/integration-karma/test-hydration/context/x/contextManager/contextManager.js, packages/@lwc/ssr-runtime/src/index.ts, packages/lwc/README.md, scripts/bundlesize/bundlesize.config.json
addTrustedContext should be exported for use by state managers
W-18783313
=> feat: export add trusted context

.github/workflows/benchmark-release.yml, nx.json, packages/@lwc/perf-benchmarks/package.json, packages/@lwc/perf-benchmarks/scripts/build.js, yarn.lock
See #5408 for details; this backports the configuration so that we can have perf tests run if we make changes to the current release.
=> chore(ci): backport perf testing config @W-18882666

packages/@lwc/engine-core/src/framework/stylesheet.ts, packages/@lwc/engine-core/src/framework/template.ts
`getStylesheetTokenHost` was removed in #4865
=> chore: remove dead code

package.json
=> chore(scripts): canary release script should use canary dist tag

packages/@lwc/ssr-client-utils/src/index.ts
The `process` object is not defined when imported and this scenario needs to be protected.
W-19292529
=> fix: check process is defined in ssr-client-utils

scripts/release/version.js
=> chore(release): validate new version is greater than current version @W-16628948

.github/workflows/release.yml
Use a PAT to commit since github actions bot seems to be unavailable to bypass rulesets.
W-16628948
=> feat(release): add PAT support

packages/@lwc/integration-not-karma/test/component/dynamic-imports/index.spec.js
All that nesting made the test file annoyingly hard to read, so I converted it to use async/await to make it flatter.
Diff best viewed with whitespace ignored.
=> test(wtr): convert test to async/await

packages/@lwc/integration-not-karma/configs/base.js, packages/@lwc/integration-not-karma/configs/integration.js, packages/@lwc/integration-not-karma/configs/plugins/serve-integration.js, packages/@lwc/integration-not-karma/helpers/matchers/jasmine.js, packages/@lwc/integration-not-karma/package.json, packages/@lwc/integration-not-karma/test/component/LightningElement.addEventListener/index.spec.js, packages/@lwc/integration-not-karma/test/profiler/mutation-logging/index.spec.js, packages/@lwc/integration-not-karma/test/rendering/iframe/index.spec.js, yarn.lock
This PR implements the fixes to enable the last two broken test files. With this PR, all integration and hydration tests have been migrated from Karma to Web Test Runner! 🎉 
=> test(wtr): fix all broken tests! @W-19098252

packages/@lwc/integration-not-karma/configs/plugins/serve-integration.js, packages/@lwc/integration-not-karma/test/api/sanitizeAttribute/index.spec.js, packages/@lwc/integration-not-karma/test/api/sanitizeAttribute/x/hrefDynamic/hrefDynamic.js, packages/@lwc/integration-not-karma/test/api/sanitizeAttribute/x/hrefStatic/hrefStatic.html, packages/@lwc/integration-not-karma/test/api/sanitizeAttribute/x/xlinkDynamic/xlinkDynamic.js, packages/@lwc/integration-not-karma/test/api/sanitizeAttribute/x/xlinkStatic/xlinkStatic.html
Without this change, every test run includes this log output:
```
test/api/sanitizeAttribute/index.spec.js:
🚧 404 network requests:
- foo
- bar
```
We don't care about the network requests, so that's just noise. This PR adds handling to make that noise go away. The extra logic can't be encapsulated within the single test, and it's kind of indirect "magic", so I changed the name of the endpoint to try to make the connection between the two a bit more obvious.
=> test(wtr): handle endpoint to make logs quieter @W-19098252

packages/@lwc/perf-benchmarks-components/src/benchmark/expression/expression.html, packages/@lwc/perf-benchmarks-components/src/benchmark/expression/expression.js
We were already testing expressions with complexTemplateExpressions enabled. This PR just adds a few actual CTEs to best perf testing to ensure they are also performant.
W-15073459
=> addtional cte perf testing
